### ISSUE TITLE
Outdated link to ARIA Authoring Practices

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/html#1003]
Second note under “[3.2.8.1. ARIA Authoring Requirements](https://w3c.github.io/html/dom.html#aria-authoring-requirements)” links to the previous GitHub version (which is still in the ARIA repo. The APG has since moved to [its own repo](http://w3c.github.io/aria-practices/).

**Comment by siusin** [comment]
Thanks for report the bug. It's been fixed by commit d7da0f7b5a18e9b7a0cd3033ada18eb86f64d14f.
