### ISSUE TITLE
Semantic? - Where is the content tagging?

### ISSUE THREAD

**Issue by schittli** [w3c/html#1006]
Good eveining,
it's sobering that html 5 still does not have a Tag to allow to Tag contents, e.g add keywords which are describing the content to the Document and Paragraphs.

OK, for the complete Document we have the hidden meta tags but there is no easy way to use css to display just the meta tags which describe the content tags.

**Therefore, this simple feature request would help a lot in handling knowledge:**
1. Please add a Tag which saves one or more content tagging keywords
2. This Tag should be assignable to at least the body, headings, and paragraphs. Images, Lists, and Tables would benefit, too.

**With this kind of content tagging we could:**
- get more precise search results
- allow the user to select a content tag and filter any website by this tag
- allow the user to select a content tag and highlight parts of any website by this tag
- ...

And, by the way, it would be great if you would change the rules and remove all optional html elements.
If a Browser supports html standard x, then it should just support all elements. It's still very annoying to have to write different code based on the Browser. It's really time to change the mind: browser should offer differences by real features and not by torturing developers, Designers, and Users :-)

Thanks a lot,
kind regards,
Thomas

**Comment by clapierre** [comment]
This semantic tagging is something that the ARIA Personalization TF will be looking into which may turn out to be something that needs to be at the HTML level and not only specific to AT/ARIA, but I agree something worth figuring out that will help not only for discovery but has a lot of accessibility benefits as well.
Thanks
Charles

**Comment by LJWatson** [comment]
Thanks @schittli.

Take a look at Schema.org. It's a collection of vocabularies that can be applied to HTML using RDFa, Microdata, or JSON-LD. The vocabularies are used to identify what content is (as opposed to what it does), and they're already in wide use across the web.
