### ISSUE TITLE
"inputmode" incorrectly flagged as "removed from HTML5.1" in HTML5.2

### ISSUE THREAD

**Issue by tidoust** [w3c/html#1015]
In the [list of changes since HTML5.1](http://www.w3.org/TR/html52/changes.html#changes-fpwd), the HTML5.2 specification states that the `inputmode` attribute "**was removed from HTML 5.1 for lack of implementation**, and may be removed from HTML 5.2 if not implemented".

I understand that there are on-going discussions (#269 and #893) to remove that attribute, but it [was not removed from HTML 5.1](http://www.w3.org/TR/html51/sec-forms.html#input-modalities-the-inputmode-attribute), AFAICT, and is still present in HTML 5.1 second edition as well.

(Also note the minor style hiccup for the text of the `datetime` in that change section due to the use of `<dt>` instead of `<dd>`)

**Comment by LJWatson** [comment]
Thanks @tidoust. Do you happen to have tests and/or know what the current implementation state is for this?

**Comment by chaals** [comment]
That seems like a straight error - as far as I know there isn't working implementation in a modern browser (although it has been implemented in multiple browsers in the past) and it should have been removed - as it should for HTML 5.2 PR.

**Comment by tidoust** [comment]
@LJWatson I do not have tests to offer, but trying the `numeric` value on different browsers indeed shows that the attribute is basically not supported anywhere.

**Comment by LJWatson** [comment]
Thanks @tidoust. @Cynthia can you remove this from the 5.2 spec? Ta.
