### ISSUE TITLE
input type=hidden has tabIndex 0?

### ISSUE THREAD

**Issue by cycomachead** [w3c/html#1017]
When I create a hidden input, it still has a tabIndex of 0. 

I.e. `<input type='hidden' name='text' value='1234' id='hidden-inp'>`
Tested with `document.getElementById('hidden-inp').tabIndex`

Shouldn't this be -1? I cannot focus on the element, and they never seem to be displayed.

**Comment by LJWatson** [comment]
When `type="hidden"` is used, the browser removes the `<input>``` from the tab order without modifying the `tabindex` property. The same is true when either the `hidden` attribute or `style:display:none;"` is used to hide the field.

For example, if you set `tabindex="2"` on the hidden field, the test returns the expected value for the `tabindex` property, but the ```<input>``` itself is still removed from the tab order.

**Comment by cycomachead** [comment]
Hey, thanks for responding! I'm very thankful for the many resources you've provided. :)

The browser's behavior of removing elements from the tab order makes sense, but it seems to complicate finding the next/first focusable element. In this case, it was dealing with finding focusable elements in a modal. We ended up using jQuery UI's `:tabbable` selector, but it seems like this request maybe is more about having an attribute or property that accurately reflects whether or not an element is in the tab order.  Is there something better than tabIndex for this?

**Comment by LJWatson** [comment]
The usual method is to use a query selector that excludes things that are hidden, and includes things with the relevant tabindex set.
