### ISSUE TITLE
Why reduce accesskey values to a single code point?

### ISSUE THREAD

**Issue by r12a** [w3c/html#1022]
5.5.2. The accesskey attribute
http://w3c.github.io/html/editing.html#the-accesskey-attribute

> The user agent may strip content from value to reduce the length of value to a single unicode code point. 

Why is this done? What benefit does it bring?  Note that Chrome and Safari are capable of matching an accesskey attribute against a keypress that produces more than one character (see https://www.w3.org/International/tests/repo/results/accesskey#multiple).

This also seems to contradict earlier text:

> Printable characters that may represent more than one Unicode code point, such as accesskey="श्र", are valid values.

**Comment by chaals** [comment]
@r12a wrote:

> > The user agent may strip content from value to reduce the length of value to a single unicode code point.

> Why is this done? What benefit does it bring?

IE/Edge do this.

If the author uses a value like `accesskey="a 1"` (which is not valid, except according to the WHATWG, HTML 5.0 and HTML 5.1) or `accesskey="hazlo"` (which nobody claims is valid) other browsers do not provide a shortcut at all.

It would be possible to do something much more intelligent, like recognise a voice command or provide a keyboard shortcut, but that is not **precluded** by allowing this behaviour.

IE/Edge provides a somewhat predictable shortcut based on more or less any value for the attribute, which is better than what most other browsers do.

**Comment by r12a** [comment]
> IE/Edge do this.

Yes, but Chrome and Safari don't. (see https://www.w3.org/International/tests/repo/results/accesskey#multiple and https://www.w3.org/International/tests/repo/results/accesskey#multiplea)

But equally important, the recent changes to the spec in the accesskey section contradict this (see the quote in my earlier comment).

**Comment by chaals** [comment]
I don't think this contradicts the text you quoted. It is a "may", meaning user agents may not do it, and most don't ever do it. In the case of a single printable character such as `accesskey="श्र"`, if Edge supported `accesskey` for such characters (it appears not to do so), there is no obligation to insist on only the first code point.

The multiple code point case is fairly unusual, but there is a body of historical advice out there ()and Whatwg's spec) suggesting you could use something like `accesskey="1 f t"`. In most browsers that simply means **no** shortcut activation is assigned at all, and allowing this behaviour means browsers **may** do something more user-friendly than Blink/Webkit/Firefox currently with invalid content they find.

**Comment by chaals** [comment]
@r12a can we close this issue?

**Comment by chaals** [comment]
@r12a closing the issue. Please re-open if you think that was wrong.
