### ISSUE TITLE
Clearly Mark Obsolete Guidance As Such

### ISSUE THREAD

**Issue by JaninaSajka** [w3c/html#1029]
We have a considerable amount of implementation guidance in the HTML specification itself. Some of this has changed radically as consensus developed over time, yet the older guidance continues to be available and can easily rise to the top of searches. Since we want to promote our best considered guidance, and not out of date guidance, out of date wiki pages, etc., should be clearly marked "Obsolete," preferably with pointers to current best practices guidance.
An example is the following which recently jumped to the top for me on a Google search:
https://www.w3.org/wiki/HTML/Elements/img#A_key_part_of_the_content

**Comment by chaals** [comment]
I don't think this is an issue on the HTML specification, although it is presuambly something the Web Platform WG should manage.

I will try to find out what old material is lying around - I imagine there is a lot of it - but it is entirely appropriate if you find a clearly superseded wiki page to edit it yourself, leaving a stub note explaining what happened to the content.

**Comment by stevefaulkner** [comment]
@chaals I deleted the out of date content and updated the link to point to latest.

**Comment by chaals** [comment]
Sweet, thank you. Only a few dozen more to do :)
