### ISSUE TITLE
Add a nested attribute to ol element

### ISSUE THREAD

**Issue by ghost** [w3c/html#1033]
Suggestion, add a nested attribute for the ol element to avoid all the CSS needed to do this. For example:

&lt;ol type="A"&gt;
&nbsp;&nbsp;&lt;li&gt;First main item
&nbsp;&nbsp;&nbsp;&nbsp;&lt;ol type="1" nested&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;First item first sub-topic&lt;/li&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;First item second sub-topic&lt;/li&gt;
&nbsp;&nbsp;&nbsp;&nbsp; &lt;/ol&gt;
&nbsp;&nbsp;&lt;/li&gt;
&nbsp;&nbsp;&lt;li&gt;Second main item
&nbsp;&nbsp;&nbsp;&nbsp;&lt;ol type="1" nested &gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Second item first sub-topic&lt;/li&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;Second item second sub-topic&lt;/li&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/ol&gt;
&nbsp;&nbsp;&lt;/li&gt;
&lt;ol&gt;

To render as:

A. First main item
&nbsp;&nbsp;A.1 First item first sub-topic
&nbsp;&nbsp;A.2 First item second sub-topic
B. Second main item
&nbsp;&nbsp;B.1 Second item first sub-topic
&nbsp;&nbsp;B.2 Second item second sub-topic

... and maybe also a delimiter attribute to specify what the separator character should be for nested lists, with the default being a "." For example in the above:

&lt;ol type="1" nested delimiter=""&gt; would generate A1, A2, etc.
&lt;ol type="1" nested delimiter="-"&gt; would generate A-1, A-2, etc.

**Comment by LJWatson** [comment]
Thanks for this suggestion. 

For new features to be considered for inclusion, there needs to be a proposal and evidence that there is a need for the solution in the wild. This usually comes in the form of a polyfill that has wide adoption (showing that there is interest from the developer community), and then commitment from at least two browser vendors to implement the proposed solution.

**Comment by prlbr** [comment]
The exact display sounds more like a topic for CSS which offers more flexibilty already, see https://www.w3.org/TR/css-counter-styles-3/ for example. It offers a mechanism to set a different suffix than the default dot for example.

If the current CSS options are not sufficient, you could discuss this with the [CSSWG](https://github.com/w3c/csswg-drafts/issues) or maybe get input from [WICG](https://discourse.wicg.io/) first.

Edit: Sorry – I missed that you wanted to avoid CSS. Why though? Anyway, the [WICG](https://discourse.wicg.io/) seems like a good place to start.

**Comment by ghost** [comment]
Many thanks for all the helpful comments.

To prlbr, regarding your question, the reason behind my comment about avoiding CSS was actually accessibility related. All my searching for ways to get a hierarchical ol list such as A.2.1 involved counters combined with using content: and my understanding (perhaps incorrect) was that content added using CSS content: presented accessibility problems with screen readers. Appreciate your suggestion that a more appropriate place for this topic this might be WICG, thanks.

**Comment by chaals** [comment]
This has now been opened as an [incubation idea](https://discourse.wicg.io/t/suggestion-an-ordered-list-nested-attribute/2393) (thank you)
