### ISSUE TITLE
Add as attribute to the link element

### ISSUE THREAD

**Issue by siusin** [w3c/html#1044]
Used by the `preload` request (for `rel="preload"`), which has been implemented by Blink and Webkit.

See also the [Preload spec](https://w3c.github.io/preload/#as-attribute).

**Comment by siusin** [comment]
This is going to be a substantive change, but the feature is interoperable, see [tests](https://wpt.fyi/preload/reflected-as-value.html).

**Comment by LJWatson** [comment]
From a chair's point of view, providing there is consent from the WG, I don't envisage any problem with the `as` attribute being in cluded in the next iteration of the HTML spec.
