### ISSUE TITLE
Consider referencing the  disableRemotePlayback attribute 

### ISSUE THREAD

**Issue by plehegar** [w3c/html#1047]
This HTML attribute is defined in https://w3c.github.io/remote-playback/#extensions-to-htmlmediaelement
This should be added in a future version of the spec once it gets enough traction. See also https://github.com/w3c/remote-playback/issues/105

**Comment by Donnalynch** [comment]
[rfc2026.txt.pdf](https://github.com/w3c/html/files/1573856/rfc2026.txt.pdf)

**Comment by LJWatson** [comment]
What is the interop story for [Remote Playback API](https://www.w3.org/TR/remote-playback/)? Will it exit CR anytime soon?

**Comment by siusin** [comment]
Implementation report of Remote Playback API: https://w3c.github.io/test-results/remote-playback/all.html

I think the attribute is ready to be added to the HTML spec.

**Comment by chaals** [comment]
Think it is ready to add, but without another implementation I think it should be marked as "at risk" for the moment.
