### ISSUE TITLE
Non contributors may get issue in link

### ISSUE THREAD

**Issue by anmol27katyani** [w3c/html#1049]
If I run Bikshed after I've fixed a bug in the spec, it will set the issue link in single-page.html to my GitHub repository. This prevents me to run all the steps in the contributing guide. Should I create pull requests without running Bikeshed?

To be more specific, Bikeshed generates this code:

<dt>Issue Tracking:
<dd><a href="https://github.com/MichielBijl/html/issues/">GitHub<

**Comment by siusin** [comment]
hi @octamois ,

single-page.html is listed in the [.gitignore file](https://github.com/w3c/html/blob/master/.gitignore)... I'd suggest running Bikeshed locally after fixing the bug, but please don't commit the single-page.html to the pull request.

Thanks!
