### ISSUE TITLE
Screenshot API

### ISSUE THREAD

**Issue by salvan13** [w3c/html#1062]
Proposal for an API that let user to get an image from an HTML element

`[ImageData img] = window.screenshot([HTMLElement element])`

**Comment by edent** [comment]
That's an interesting idea. I suggest incubating it first in e.g. the W3C incubator group and getting some browser buy-in.

For consistency, it might make sense to model it after the existing [`HTMLCanvasElement.toDataURL()
`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL). That allows a browser to turn a canvas element into a PNG.

**Comment by chaals** [comment]
I wrote an API to do this, a few years ago.

I am not sure it is a good idea to expose a function like this to Web applications - there are privacy and security issues (most particularly based on fingerprinting vectors) if a website can make a screenshot and get access to the content without significant user interaction.

There are use cases within browsers, and it is a handy function **IFF** you can solve the privacy problems.

But it would be helpful to understand why we need a Web API for this - what problems does it solve, what problems does it create? Is there are reason why it should be a common standard and not just a feature of individual browsers (which it is today)? 

I agree with @edent that this should be incubated. I would suggest answering the questions above in the [WICG](https://discourse.wicg.io) as a first step - and maybe sketching out some design questions like sync/async and so on, and trying to get some broader agreement on the need and some possible shapes for the API.

**Comment by salvan13** [comment]
I created a topic on WICG https://discourse.wicg.io/t/proposal-screenshot-api/2412

**Comment by chaals** [comment]
Closing in favour of the WICG incubation discussion
