### ISSUE TITLE
Merge Web Workers into HTML?

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#1075]
During the [WebPlat TPAC meeting](https://www.w3.org/2017/11/09-webplat-minutes.html#item02) it was suggested that [Web Workers](https://w3c.github.io/workers/) be merged into the HTML spec. The reason is that it would make it easier to maintain, and therefore more likely for the spec to be kept up to date.

Does this seem like a good idea?

**Comment by cynthia** [comment]
As discussed during TPAC, I can fold the bikeshed spec into html after the CSP dependencies are solved.

**Comment by LJWatson** [comment]
Thanks @Cynthia. What are the CSP dependencies?

**Comment by cynthia** [comment]
I took a first whack at this and was welcomed with a build error. Trying to figure out how to fix this.

**Comment by chaals** [comment]
Following discussion at HTML meeting we will run a CfC to re-examine the question of merging Web Workers. It doesn't seem that Web Workers has much linkage to HTML...

**Comment by chaals** [comment]
There is a new CfC on this: #1468. Moving to the next milestone.

**Comment by chaals** [comment]
The CfC closed and we will **not** merge workers into HTML.
