### ISSUE TITLE
Proposed HTML5.3 timeline

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#1076]
During the [WebPlat TPAC meeting](https://www.w3.org/2017/11/09-webplat-minutes.html#item02), a proposed timeline for HTML5.3 was discussed. Based on the discussions, a refined timeline has now been proposed:
* Thu 14th Dec 2017: publish the First Public Working Draft (FPWD)
* Tue 6th Feb 2018: publish an updated Working Draft (WD)
* Tue 13th Mar: publish an updated WD
* Thu 24th May: publish Candidate Recommendation (CR)
* Thu 12th Jul: publish Proposed Recommendation (PR)
* Thu 23rd Aug: publish Recommendation

The intent is to ship within the current [WebPlat charter](https://www.w3.org/2017/08/webplatform-charter.html) (which ends on 30th September 2018.

Comments welcome.

**Comment by SHAGO7932** [comment]
Hello World ....HTML.5....on 
WEB 3
