### ISSUE TITLE
Specify HTML numeric character reference fallback encoding for multipart upload filename characters not representable in form charset

### ISSUE THREAD

**Issue by bsittler** [w3c/html#1077]
Filed here by accident. Please see https://github.com/whatwg/html/issues/3223

**Comment by bsittler** [comment]
Accidentally filed here, now re-filed as https://github.com/whatwg/html/issues/3223

**Comment by edent** [comment]
We want to add this to the 5.3 spec.  I'd like to ask a couple of clarifying questions to make sure I've understood things.

The *filename* of the submitted file (not the contents) should be in the same `charset` as requested in the form. So if the filename is `你好.jpg` and the charset is `windows-1252` then the filename should be escaped into HTML decimal entities like `&#20320;&#22909;.jpg`

Is that correct?

This refers to:
> https://www.w3.org/TR/html5/forms.html#attr-form-accept-charset
> The accept-charset attribute gives the character encodings that are to be used for the submission. If specified, the value must be an ordered set of unique space-separated tokens that are ASCII case-insensitive, and each token must be an ASCII case-insensitive match for one of the labels of an ASCII-compatible character encoding. [ENCODING]

**Comment by bsittler** [comment]
That is correct. And if the filename were `ABC~‾¥≈¤･・•∙·☼★星🌟星★☼·∙•・･¤≈¥‾~XYZ.txt` and the form charset were ISO-2022-JP the expected encoded name would be `ABC~⊖(J~\&#8776;&#164;⊖$B!&!&⊖(B&#8226;&#8729;&#183;&#9788;⊖$B!z@1⊖(B&#127775;⊖$B@1!z⊖(B&#9788;&#183;&#8729;&#8226;⊖$B!&!&⊖(B&#164;&#8776;⊖(J\~⊖(B~XYZ` a.k.a. `ABC~␛(J~\&#8776;&#164;␛$B!&!&␛(B&#8226;&#8729;&#183;&#9788;␛$B!z@1␛(B&#127775;␛$B@1!z␛(B&#9788;&#183;&#8729;&#8226;␛$B!&!&␛(B&#164;&#8776;␛(J\~␛(B~XYZ` (here `⊖` or `␛` pictorially represents the ESC C0 control x1B)

**Comment by LJWatson** [comment]
Please leave this issue open whilst we look into it. Thanks @bsittler
