### ISSUE TITLE
Clarify use of headings in legends with phrasing content

### ISSUE THREAD

**Issue by selfthinker** [w3c/html#1081]
The [`legend` element](https://w3c.github.io/html/sec-forms.html#the-legend-element)'s content model is:
> Phrasing content and headings (h1-h6 elements).

But when you add both to a legend the validator gives an error and says:
> Text not allowed in element legend in this context.

Here is the simplest example I used for that error to appear:
```
<fieldset>
  <legend>
    <h1>Heading in legend</h1>
    with other phrasing content
  </legend>
</fieldset>
```

The error does not appear when there is only a heading or only phrasing content in the legend. Is that an issue in the validator? Or is the spec not very clear here?
I did not expect that to happen after reading the spec. If the validator is correct, I would think a better way to phrase it would be:
> Either phrasing content or headings

But I would also question whether that makes sense.

**Comment by chaals** [comment]
I agree with your interpetation. And I took [a couple of variations on your example](https://chaals.github.io/testcases/legend-heading-text-manual.html) and played with them in Firefox, Edge, and Yandex browser, and they all seemed to behave as though this was a reasonable thing to do. And I cannot see a scernario in which it is not. 

So it seems to me that the spec matches reality. I haven't checked what happens in accessibility APIs yet, although it seems to me they **should** behave similarly... @stevefaulkner @LJWatson ping?

I suggest filing a bug on the validator.

Unless someone screams in the next couple of days, I propose to close this issue.

**Comment by stevefaulkner** [comment]
agree it seems like a validator bug. /cc @sideshowbarker

**Comment by selfthinker** [comment]
Thanks for the quick responses!
I just opened an issue with the validator (validator/validator#575).

**Comment by chaals** [comment]
OK, seems like we can close this.
