### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by sirx** [w3c/html#1083]
The loop argument for audio and video does not loop very good this should be fixed

**Comment by shwetank** [comment]
@sirx Could you add more specifics as to how it doesn't 'loop very good'. Would be helpful to evaluate fixing it.

**Comment by chaals** [comment]
It is not clear what this issue is requesting. Unless someone can clarify it, I will close it soon.

**Comment by chaals** [comment]
It is not clear that there is anything to change in the specification.
