### ISSUE TITLE
The description of "label" is confusing

### ISSUE THREAD

**Issue by chaals** [w3c/html#109]
As per https://www.w3.org/Bugs/Public/show_bug.cgi?id=13553

It would be good to rewrite this.

**Comment by stevefaulkner** [comment]
removal of form attribute being discussed further here: https://github.com/whatwg/html/issues/787 @chaals can you take a look?

**Comment by chaals** [comment]
There are still some vestiges of `label` as a reassociatable element that should be hunted out and fixed

**Comment by chaals** [comment]
whatwg/html#787 took this up, and made forms non-reassociatable. (They also removed the concept, since everything in that class is also in their "listed" class of elements, but that's editorial).

In fact label _can_ be associated with a different form, but it doesn't have any practical impact. It doesn't change what gets submitted, or how the control behaves in any ther discoverable way, including in user interfaces - I tested Yandex/Firefox/Safari, VoiceOver and @LJWatson told me JAWS doesn't expose this in any way either. 

Keeping the IDL attribute should cover any real use case that relies on a label not being in the same form as its control, and it looks as if browsers may move to explicitly force `label.form` to alias `label.control.form` which it doesn't at the moment.

For compatibility with WHATWG, and because we can't find any meaningful implementation, we should indeed remove `label` from reassociatable things for 5.1

**Comment by chaals** [comment]
I have a [sort-of testcase](http://chaals.github.io/testcases/MixedFormsTest.html) to work out what happens with various situations. Playing with that and a JS console gives more insight again.

**Comment by chaals** [comment]
#540 needs to be taken into the master branch as well…

**Comment by chaals** [comment]
Kept this open for the merge into the master branch - was done in the HTML 5.1 branch
