### ISSUE TITLE
What should autocapitalize default be

### ISSUE THREAD

**Issue by chaals** [w3c/html#1092]
The `autocapitalize` attribute for `input` and `textarea` is implemented in Safari for iOS and some blink browsers for Android. They use a deault of `sentences` for plain-text input types such as `textarea`, `input type="text"`, but a default of `none` for things like `input type="password"` (which seems pretty important).

All the non-implementations effectively have a default of `none`.

So the latter is far more interoperabel in practice. Defaulting to `sentence` could be helpful, but it depends how it is defined. In particular, most langauges have special rules for capitalising some things inside a sentence (language adjectives like "English" in English, but not in many other latin-script european languages, nouns in German, different approaches for abbreviations, ...).

And for historical reasons a couple of languages would like a different default as @r12a [pointed out](https://github.com/w3c/html/issues/208#issuecomment-347270249) @r12a.

**Comment by prlbr** [comment]
Do I understand correctly that some browsers default to altering text in textareas now? I.e. I type a lowercase "a" and get an "A"? I kind of understand why some browsers do something like that on some devices (cell phones) with limited means for entering text. But I think it would be a really bad idea to bake such a default into HTML and hence for all browsers. That would be a big break in backwards compatibility and really weird, e.g. when you need to enter computer code where the lower/upper case matters.

**Comment by chaals** [comment]
@prlbr 

> Do I understand correctly that some browsers default to altering text in textareas now

Yes. Mobile browsers - seemingly Safari for iOS and Chromium for Android do it for `textarea` and some `input` types.

There is a requirement in the spec text (where we currently also suggest defaulting to no autocapitalization - in part because in mobile scenarios users can set up preferences on their keyboard) that the user can over-ride this behaviour, but it is not clear how it **should** happen in practice. I have personally only tested the Safari version, and rather than allowing an override of the element at user level it seems to rely on the user re-configuring the keyboard.

How common the various usecases for overriding are is probably really guesswork (I am not sure how easy it is to get statistics that are really meaningful), but it is helpful to at least collect them...

And yes, the rationale for setting the default as "none" is partly that this matches the overwhelming majority of **current** browsers.

ping @hober, @dtapuska, @travisleithead, @johanneswilm ...

**Comment by rniwa** [comment]
@whsieh

**Comment by edent** [comment]
This is a problem with some login boxes on mobile. My software keyboard autocapitalises my username `Edent` - but the server doesn't recognise this as being the same as `edent`. Poor design from the website owner - but having `autocapitalize="lower"` or similar may help there.

**Comment by r12a** [comment]
> Do I understand correctly that some browsers default to altering text in textareas now? I.e. I type a lowercase "a" and get an "A"?

@prlbr @chaals I was under the impression that this is NOT correct, inasmuch as what the `autocapitalize` attribute does is set a convenience hint for the display of the visual keyboard - not to alter what the user types at all.  Ie. for `autocapitalize=sentence` the keyboard switches to show uppercase letters, but the user is quite at liberty to switch the keyboard back to lowercase before typing anything.  Am i misunderstanding?

**Comment by chaals** [comment]
@r12a wrote:

> ... what the autocapitalize attribute does is set a convenience hint for the display of the visual keyboard - not to alter what the user types at all.

Yes, this is what Safari does on iOS, and while I don't have a test device so cannot say for Android I presume it is the same.

That is a bit different to what we have specified now, and might well be a better way of describing it. It would significantly reduce the range of potential benefit, but it simplify the question of ensuring the user can override where necessary...

**Comment by r12a** [comment]
It also makes life much much easier because you don't need to worry about language-specific rules for upper and lowercasing, such as whether the i needs to be a Turkish capital letter I with dot or not, which is a nest of snakes (i assume you're familiar with that, otherwise see http://rishida.net/blog/201512.html#20160907). If this is a prompt to the keyboard display, the turkish user is likely to be using a turkish keyboard and will be presented with the appropriate character.

**Comment by prlbr** [comment]
> > Do I understand correctly that some browsers default to altering text in textareas now? I.e. I type a lowercase "a" and get an "A"?
>
> @prlbr @chaals I was under the impression that this is NOT correct, inasmuch as what the autocapitalize attribute does is set a convenience hint for the display of the visual keyboard - not to alter what the user types at all. Ie. for autocapitalize=sentence the keyboard switches to show uppercase letters, but the user is quite at liberty to switch the keyboard back to lowercase before typing anything.

This is much more sensible, I think.
It’s just a pity they called the attribute `autocapitalize` and not something less confusing.
