### ISSUE TITLE
Influence of the base tag on links to elements with id

### ISSUE THREAD

**Issue by musteresel** [w3c/html#1102]
I was surprised that a `<base href="FOOBAR">` tag also affects links of the form `<a href="#target"></a>` to no longer point to an element within the current page but to the destination referenced by the `<base>` tag.

**Was this behavior intentionally specified as it is?** This way there seems to be no way to reference an object in the current document without resorting to specifying its full absolute path.

I guess - though without any significant examples nor experience on this subject - that most uses of the `<base>` tag will be either

 - shortcuts to avoid specifying long links into deeply nested directory structures, e.g. `<base href="./builds/current/test/html/">` with `<a href="test1.html">Result of test 1</a>`, or
 - a way to use relative URLS that are always relative to some "top" URL, e.g. `<base href="www.foo.bar/">`

Both seem to have "external" links (leaving the current page) rather than "internal" links (within the document) in mind, IMO.

**Comment by LJWatson** [comment]
I believe this is always how ```<base>``` has worked. Chrome, Edge, Firefox, and IE all resolve the relative fragment identifier to the base URL.
