### ISSUE TITLE
Remove magical alignment for dialog

### ISSUE THREAD

**Issue by chaals** [w3c/html#1108]
The [magical alignment for `dialog` elements](https://w3c.github.io/html/interactive-elements.html#magically-aligned) doesn't seem to work anywhere, and appears to be a holdover from the old 5.0 version of `dialog` relying on the `anchor-point` pseudo-CSS that doesn't seem to exist in reality either.

Unless someone has a reason to believe it should and does exist, I suggest we just remove it.

**Comment by shwetank** [comment]
Fixed (see above referred issue)
