### ISSUE TITLE
Confusing statement regarding the content model of <p> in the "Changes" section in HTML5.2

### ISSUE THREAD

**Issue by SelenIT** [w3c/html#1112]
The ["Fixing bugs and matching reality better" subsection](https://www.w3.org/TR/html52/changes.html#fixing-bugs-and-matching-reality-better) of the "Changes" section in the HTML5.2 spec has the following statament:

> The following constructions are no longer valid HTML:
> * Inline blocks, inline tables, or floated and positioned block-level elements as children of a `<p>` element.

As far as I understand, it refers to the clarification issue #763 (and the related PR #838).

This statement looks very confusing to me because it seems to imply that in previous editions of HTML these elements _were_ valid as children of a `<p>` element when formatted that way, which hardly could be the case because CSS doesn't affect the content model (and the rules of parsing, which occurs long before any CSS is applied). Also, it seems to imply that the concept of "block-level elements" exists in HTML (not CSS), which also can lead to wrong conclusions and confusion since too many educational resources still operate the HTML 4 concept of "block vs. inline elements" and not all modern HTML elements can fall into one of these categories.

Wouldn't it be better to change the wording so that it would be clear that 1) the appearance of the element is controlled by CSS and doesn't affect its kind and content model, and 2) therefore, elements not allowed to be children of `<p>` can't be nested in it _regardless their styling,_ even if they are _formatted_ as "inline" or "inline-something"?

**Comment by chaals** [comment]
Hmm. I will record this as an erratum, and propose a fix for the changelog along the lines of your suggestions, although I am not sure if we will publish a revised version of HTML 5.2 ...

I'll propose a fix for the spec itself too.

**Comment by chaals** [comment]
I committed the change to the HTML branch on the off-chance that we use it to produce an errata update (Revised Rec).

I would consider this issue fixed by #1113 - if you disagree please say so...

**Comment by SelenIT** [comment]
Thanks, the change you propose in #1113 is much better. However, I'm not sure that mentioning the _rendering_ of the elements, especially after "In general", removes the confusion completely. If I were a novice taught on "block vs. inline" dichotomy and not taught about the "Content model" concept (which seems to happen quite often), I could still come to conclusion that _the general rule_ that defines whether these elements can be children of `<p>` element or not has something to do with the rendering itself, and that changing the rendering could create exceptions from this rule, at least potentially.

Wouldn't it be better to mention that `<p>` element has the optional end tag instead, and that [it gets implicitly closed](https://www.w3.org/TR/html52/syntax.html#ref-for-syntax-end-tags④⑤) before certain non-phrasing elements start tag, making it physically impossible for them to become its children (regardless the rendering etc.)? IMO, this would prevent both the confusion caused by the ambiguity of the term "block", and the surprise from how the DOM created for the markup supposed to be "a block element inside the paragraph" is actually constructed.

Also, shouldn't the similar editorial change be made for the main branch?

**Comment by SelenIT** [comment]
Sorry, I forgot that there is already the "Tag omission in text/html" block in the element definition that effectively lists these elements. Given that, repeating this info in prose might probably be not necessary.
