### ISSUE TITLE
no tarball?

### ISSUE THREAD

**Issue by dchmelik** [w3c/html#1115]
When will there be a tarball of documentation files for off-line reading like the old html40.tgz?

**Comment by ylafon** [comment]
It should be available from https://www.w3.org/TR/2017/REC-html52-20171214/html52.tar.gz
HTH

**Comment by dchmelik** [comment]
Thanks.  The problem seemed to be the new documention doesn't mention the .tar.gz, like HTML4 did.  I had been searching such as for html5.tar.gz, etc., years, just thought you discontinued it.  So, I might have the same question for html53.tar.gz later.

**Comment by chaals** [comment]
To be honest, we had stopped doing it, which is why there wasn't a link. Given it is pretty easy, we will do it for 5.3 - but the link will get into HTML 5.2 sometime next year in an errata update I guess
