### ISSUE TITLE
Don't use a wiki to define canvas context types

### ISSUE THREAD

**Issue by chaals** [w3c/html#1118]
The spec currently [refers (non-normatively)](https://w3c.github.io/html/semantics-scripting.html#the-canvas-element) to [a WHATWG wiki page to define the context types for canvas](https://wiki.whatwg.org/wiki/CanvasContexts#content). These should just be defined in the spec, or written as HTML extensions.

(WHATWG themselevs don't rely on their wiki as a source).

**Comment by edent** [comment]
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext), the valid contexts are:

* `2d`
* `webgl`
* `webgl2`
* `bitmaprenderer`

The [WHATWG spec](https://html.spec.whatwg.org/multipage/canvas.html#dom-canvas-getcontext) doesn't mention `webgl2`.

I can't find any mention of `webgl2` or `bitmaprenderer`  on the W3 site.

**Comment by edent** [comment]
`bitmaprender` appears to have become [OffscreenCanvas](https://wiki.whatwg.org/wiki/OffscreenCanvas), so I think it can be excluded.

I'll update the current pages to include WebGL2.
