### ISSUE TITLE
4.10.5.1.16. Radio Button state (type=radio) Is flawed

### ISSUE THREAD

**Issue by jbosse** [w3c/html#1134]
The specification *should either* require at least one radio element in a group be selected by default in order to be valid html *or* require browsers to allow a radio element to be deselected. 

The notion that a *radio button is the only form element* that cannot be restored to its originally presented state is a significant flaw in the HTML specification that should not be allowed to continue.

**Comment by chaals** [comment]
I agree that this was a mistake made in the distant past that we should not repeat. The question now for radio buttons is whether changing their behaviour would match deployed reality better, or cause a lot of things to break...

**Comment by jbosse** [comment]
I think I agree that allowing deselection might not be feasible at this point, but the spec used to state that a browser should select the first by default if the markup did not select one. I think this requirement should be added back to the spec for browser implementation (I realize there is no guarantee any browser will implement) and any markup missing a default selection should be considered invalid.

**Comment by chaals** [comment]
See also issue #1073 (having an "indeterminate" state) - ping @notabene

There is not much point putting stuff in the spec if browsers are not going to implement - we have worked hard for some time to make the spec a better reflection of what actually works rather than what would be nice (or even just "more sensible than the current reality"). 

Changing the way HTML works is problematic because it takes a long time to update documentation and tools that are pretty disconnected from the whole process of developing a standard, e.g. in some secure slow-moving environment, in a community relying on a translation, etc.

**Comment by notabene** [comment]
@chaals 

> There is not much point putting stuff in the spec if browsers are not going to implement

Agreed, although from what I understand [when reported to Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1413193), we're in a chicken-and-egg situation for said issue #1073. Mozilla would wait for a change in the spec, and the spec would need to be able to point out to browsers who implement desired behaviour, if I understand correctly. Stalemate for this issue, I think.

**Comment by jbosse** [comment]
> There is not much point putting stuff in the spec if browsers are not going to implement

I would hope that adding something to the spec would at least encourage browsers to consider implementation. 
> we have worked hard for some time to make the spec a better reflection of what actually works rather than what would be nice

This sounds more like documentation than specification, which I understand as a reasonable goal. But then maybe change the name from "Specification" to "Major Browser Accord" 🙃 

Feel free to close this issue. I just wanted people to realize that this item of the specification continues a bad user experience. Someone has to push for a better user experience, and I would think the best platform for that push would be the specification itself.

**Comment by chaals** [comment]
Closing this issue - #1073 (which is still open) would resolve it for this case, and the design pattern was a bad move. Hopefully we will remember and not make the mistake again...
