### ISSUE TITLE
future:add scrollbar tag

### ISSUE THREAD

**Issue by annopnod** [w3c/html#1135]
&lt;scrollbar value=&quot;0&quot; max=&quot;100&quot; min=&quot;0&quot; type=&quot;vertical&quot;&gt;&lt;/scrollbar&gt;
&lt;scrollbar value=&quot;0&quot; max=&quot;100&quot; min=&quot;0&quot; type=&quot;horizontal&quot;&gt;&lt;/scrollbar&gt;

**Comment by annopnod** [comment]
onscroll Event

**Comment by sumitsg10** [comment]
<element onscroll="myScript">
Try this code
