### ISSUE TITLE
Should option/optgroup be listed in disabled attribute desc?

### ISSUE THREAD

**Issue by scottaohara** [w3c/html#1138]
In reviewing the conditions for disabling a form control, I noticed that `option` and `optgroup` [were not listed as valid elements](https://www.w3.org/TR/html/sec-forms.html#enabling-and-disabling-form-controls-the-disabled-attribute) to receive the disabled attribute.

However, in the specific entries for [option](https://www.w3.org/TR/html/sec-forms.html#the-option-element) and [optgroup](https://www.w3.org/TR/html/sec-forms.html#the-optgroup-element), `disabled` is listed under allowed content attributes.

From reviewing past versions of the HTML5 specification, it appears that the individual listings of valid elements was dropped from [HTML4](https://www.w3.org/TR/html4/interact/forms.html#adef-disabled) to 5, with the [March 17, 2015 draft](https://www.w3.org/TR/2015/WD-html51-20150317/semantics.html#enabling-and-disabling-form-controls:-the-disabled-attribute) reinstating the list of valid elements.

As `option` and `optgroup` can receive the `disabled` attribute, should they be re-added to the valid element listing as well?

**Comment by SelenIT** [comment]
The same inconsistency is there in the WHATWG spec. Probably it should be fixed in both places?
