### ISSUE TITLE
header and footer element context as banner and contentinfo landmarks

### ISSUE THREAD

**Issue by jongund** [w3c/html#114]
Where is the current definition of the context where header and footer element context have default roles of banner and contentinfo landmarks?

**Comment by stevefaulkner** [comment]
in https://www.w3.org/TR/html-aam-1.0/
https://www.w3.org/TR/html-aam-1.0/#el-header
https://www.w3.org/TR/html-aam-1.0/#el-footer

**Comment by chaals** [comment]
Not in HTML spec.
