### ISSUE TITLE
The range of years is incorrect in note of 2.4.5. Dates and times.

### ISSUE THREAD

**Issue by rh-KIMATA** [w3c/html#1141]
https://www.w3.org/TR/html53/infrastructure.html#dates-and-times

>Dates are expressed in the proleptic Gregorian calendar between the proleptic year 0000, and the year 9999. Other years cannot be encoded. 

But, valid years string is "Four or more ASCII digits, representing year, where year > 0".

"0000-01" is inside the range in note of 2.4.5., but it is invalid.

And, "10000-01" is outside the range in note of 2.4.5., but it is valid.

**"between the proleptic year 0000, and the year 9999. Other years cannot be encoded" should be removed from  note of "2.4.5. Dates and times".**

**Comment by edent** [comment]
I agree that this is confusing.

This is based on [ISO8601](http://dotat.at/tmp/ISO_8601-2004_E.pdf) - which says this about years greater than 9999:

> By mutual agreement of the partners in information interchange, it is permitted to expand the component identifying the calendar year, which is otherwise limited to four digits. This enables reference to dates and times in calendar years outside the range supported by complete representations, i.e. before the start of the year [0000] or after the end of the year [9999].

HTML5 doesn't have a mutual agreement.

I think the word should be revised.  My suggestion is

> Four ASCII digits, representing year, where year >= 0000.

**Comment by edent** [comment]
This has raised an interesting bug in the HTML validator!

Consider the 1st of January in the year 1.
`<time>0001-01-01</time>`
Gives the error
> Warning: The text content of element time was not in the required format: Year may be mistyped.

The validator *only* accepts years >= 1000.

The spec says
> A string is a valid month string representing a year *year* and month *month* if it consists of the following components in the given order:
> Four or more ASCII digits, representing year, where year > 0
> https://www.w3.org/TR/2017/REC-html52-20171214/infrastructure.html#valid-month-string

The spec later goes on to say:

> If *year* is not a number greater than zero, then fail.

I propose two things.

1. I'll revise the wording to make clear that the year `0000` is valid.
2. Someone else can fix the validator :-)

**Comment by rh-KIMATA** [comment]
Thanks for your comment.

But, I still think as follows:

**"between the proleptic year 0000, and the year 9999. Other years cannot be encoded" should be removed from note of "2.4.5. Dates and times".**

Because...

1. Year [0000] is BC 1 year (AD 0 year is not exist).

1. Compatibility with HTML Living Standard will be break.

<table>
    <thead>
        <tr>
            <th>Spec</th>
            <th><code>&lt;time&gt;0000-01&lt;/time&gt;</code></th>
            <th><code>&lt;time&gt;0001-01&lt;/time&gt;</code></th>
            <th><code>&lt;time&gt;10000-01&lt;/time&gt;</code></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>HTML 5.2: note of 2.4.5. <a lang='en' hreflang='en' href='https://www.w3.org/TR/2017/REC-html52-20171214/infrastructure.html#dates-and-times'>Dates and times</a></td>
            <td>valid</td>
            <td>valid</td>
            <td>invalid</td>
        </tr>
        <tr>
            <td>HTML 5.2: 2.4.5.1. <a lang='en' hreflang='en' href='https://www.w3.org/TR/2017/REC-html52-20171214/infrastructure.html#months'>Months</a></td>
            <td>invalid</td>
            <td>valid</td>
            <td>valid</td>
        </tr>
        <tr>
            <td>HTML Living Standard <small>Last Updated <time datetime='2018-01-17'>17 January 2018</time></small>: 2.3.5.1. <a lang='en' hreflang='en' href='https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#months'>Months</a></td>
            <td>invalid</td>
            <td>valid</td>
            <td>valid</td>
        </tr>
    </tbody>
</table>

<hr>

> Consider the 1st of January in the year 1.<br><code>&lt;time&gt;0001-01-01&lt;/time&gt;</code><br>Gives the error

This is "warning", not "Error".

<table>
    <thead>
        <tr>
            <th>Checker</th>
            <th><code>&lt;time&gt;0000-01&lt;/time&gt;</code></th>
            <th><code>&lt;time&gt;0001-01&lt;/time&gt;</code></th>
            <th><code>&lt;time&gt;10000-01&lt;/time&gt;</code></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><a href='https://validator.w3.org/nu/'>Ready to check - Nu Html Checker</a> <small>Version: 18.1.17</small></td>
            <td>Error: Year cannot be less than 1.</td>
            <td>Warning: Year may be mistyped.</td>
            <td>Warning: Year may be mistyped.</td>
        </tr>
    </tbody>
</table>

**Comment by chaals** [comment]
I am happy to leave out the proleptic year 0000 - it isn't that useful, for reasons I outlined in a comment on the commit.

I think the question in adding years after 9999 is whether it breaks anything important. I suspect not - the date system in HTML is pretty primitive, whereas people who have a use case for talking about 8 millennia hence are probably not.

Is any evidence around that would help to decide based on something better than educated guesses?

**Comment by edent** [comment]
OK! Thanks for the info. I'll update it to make Year `0001` the first. This diverges slightly from ISO8601.

**Comment by edent** [comment]
Updated at https://github.com/w3c/html/commit/4aafc74f7ad2bc0e98a849e7c4f11a86ff2f16e6

**Comment by rh-KIMATA** [comment]
Thank you all comments and Update.

I am only anxious about losing compatibility with HTML Living Standard. I don't have any other problems.

And ...

> I suspect not - the date system in HTML is pretty primitive, whereas people who have a use case for talking about 8 millennia hence are probably not.

I think so, too.
