### ISSUE TITLE
Support CSS supports as <link> attribute

### ISSUE THREAD

**Issue by ryanve** [w3c/html#1150]
Is this the best place to suggest an HTML feature? I think it'd be useful if `<link>` supported a `supports` attribute similar to how it supports `media` as an attribute for media queries. Like so you could conditionally load stylesheets based on CSS supports

```html
<link rel="stylesheet" supports="not (display: grid)" href="legacy.css">
<link rel="stylesheet" supports="(display: grid)" href="modern.css">
```

Has anything like this been considered? I'm not sure how it could be made backward compatible. Like is there a way to create something like this in a way that avoids loading both where the attribute isn't supported? Maybe overload `[media]` to handle both `@media` and `@supports`

**Comment by LJWatson** [comment]
Thanks for this suggestion. New ideas are proposed and discussed in the [Web Platform Incubator Community Group](https://discourse.wicg.io/).

If you post your idea there for discussion, you'll get a sense from authors and implementors as to whether there is interest and whether it might work or not.

**Comment by ryanve** [comment]
Cool thanks @LJWatson :smile:
