### ISSUE TITLE
Duplicated character references?

### ISSUE THREAD

**Issue by borela** [w3c/html#1157]
[The character reference table appears to have duplicated entries.](https://w3c.github.io/html/syntax.html#named-character-references)

**Comment by chaals** [comment]
No, each of the entities defined is different either by case or having a semi-colon (;) at the end.

But thanks for asking.

**Comment by borela** [comment]
Thank you :D

**Comment by maffe** [comment]
I was going to report the same. What is the reason to include names without semicolon in the table? The section [Character references](https://w3c.github.io/html/syntax.html#syntax-charref) states
> The name must be one that is terminated by a U+003B SEMICOLON character (;).

It is also unclear why only some names occur without semicolon.

**Comment by chaals** [comment]
Although it is an error to use a name without a semicolon in the source of a document, user agents are required to parse some (the ones that are in the table) anyway.
