### ISSUE TITLE
Can caption end tag be ommitted?

### ISSUE THREAD

**Issue by borela** [w3c/html#1158]
> A caption element’s end tag may be omitted if the caption element is not immediately followed by a space character or a comment.

Does that mean that:

```html
<caption>This won't need to be closed

<caption> This will because of the space before "this"</caption>
```
Did I get it right?

**Comment by chaals** [comment]
I don't think so.

If you have another element immediately, as in 
`<caption>This is the caption<tr><th>...` you don't need the end tag.

If you have a comment following, like 
`<caption>This is the caption<!-- you need an end tag>...` then you do.

If you have space following the **element** (not the tag), e.g. 
`<caption>This is the caption       <tr><th>...` then it claims you do, but in practice the spaces are part of the caption.

A [simple, maybe simplistic test](http://chaals.github.io/testcases/caption-unclosed-manual.html) shows that at least in Firefox, Edge, and Opera (blink) there is interoperable behaviour if you do leave out the end tag, with the element being closed when there is another table element and everything up to that point part of the `caption`.

So I think we could happily remove the restriction and stop requiring a closing tag at all. Note to self, check the parsing to see if it matches that...

**Comment by borela** [comment]
Thank you @chaals :D

**Comment by LJWatson** [comment]
Suggest taking a look at #922 on this repo, and the related validator/validator#593 issue.

**Comment by chaals** [comment]
@LJWatson saw that. But it turns out implemented reality - and what the parser section seems to suggest should happen - is even simpler than that.
