### ISSUE TITLE
Proposed revised content attribute description for a[download]  

### ISSUE THREAD

**Issue by scottaohara** [w3c/html#1162]
The description of the `download` attribute, [under the `a` element, Content attributes section](https://w3c.github.io/html/textlevel-semantics.html#the-a-element), reads as the following:

> `download` - Whether to download the resource instead of navigating to it, and its file name if so

The second part of this description is not entirely clear, and I would like to open a pull request to revise to the following:

> `download` - Whether to download a resource instead of navigating to it. If a value is set, change the resource's <var>proposed filename</var> to match.

Does anyone have any additional thoughts / suggestions on how to better describe this attribute, or if the current text should stay as is?  

Thanks

**Comment by chaals** [comment]
Something in this direction seems like a great clarification - thank you.

**Comment by chaals** [comment]
Closed by #1164 - thanks

**Comment by devarshipant** [comment]
@scottaohara 
> If a value is set, change the resource's proposed filename to match.

Some questions:

1. Are these boolean vaues?

2. Should the attribute value help assistive tech users to know before activating the resource if its downloadable?
