### ISSUE TITLE
Is the question mark intended? - editorial

### ISSUE THREAD

**Issue by agcolom** [w3c/html#1174]
https://github.com/w3c/html/blob/9780b1c2be68efbe49455fe3b621fcc55d7abbeb/sections/semantics-document-metadata.include#L352

Is the question mark intended on the line above, or should the line be changed from 
```[CEReactions] attribute DOMString? crossOrigin;``` 
to 
```[CEReactions] attribute DOMString? crossOrigin;```

**Comment by chaals** [comment]
Intended - it means the attribute can be null, even though that is not normally a DOMString value.
