### ISSUE TITLE
Cleanup Embedded content section

### ISSUE THREAD

**Issue by agcolom** [w3c/html#1176]
https://github.com/w3c/html/blob/48acf8ced4fad4bd9bde23c02fea74d4402626f4/sections/semantics-embedded-content.include#L3251-L3267

I'm finding this example hard to read... and I think there might be an extra ```<tr>``` at the start (L3253) which should be removed?

Would it be ok to either add the omitted closing tags and/or indent the code and avoid having an opening ```<tr>``` at the end of a line ((L3253)?

I'd be happy to submit a PR if you let me know 
1. whether the extra ```<tr>``` at the start should be removed
2. whether we add the omitted closing tags (I'm ok either way)
3. whether it is ok to indent the code
4. whether it is ok to move the end of line ```<tr>``` on a new line.

Thank you

**Comment by chaals** [comment]
It would be nice to make the formatting more regular so people can understand the example more easily. So the answer to all your questions is "yes". (For this and almost any other example, except where they are explicitly to show that different syntax makes the same result)

I think this whole section is pretty problematic, and would suggest basically starting from scratch, which you may want to do instead...

**Comment by agcolom** [comment]
@chaals brilliant! I'll get started and I'll send a PR when ready. We can then add to the PR after review etc. I will assign to myself for now, and I'll add comments here if I have further questions on this section :-)

**Comment by agcolom** [comment]
Changed the issue name to better reflect the task.

**Comment by chaals** [comment]
@agcolom does #1199 cover this, or do you want to leave it open?

I think if you do leave it open, a more specific explanation of the issue would be helpful.

**Comment by agcolom** [comment]
@chaals It looks like @edent 's work has addressed this issue 👍  Thank you! I'll close the issue.
