### ISSUE TITLE
Consider deprectation of secondary browser contexts

### ISSUE THREAD

**Issue by jonathanKingston** [w3c/html#118]
See:
- https://github.com/whatwg/html/issues/582
- https://bugzilla.mozilla.org/show_bug.cgi?id=1250906

The w3c doesn't seem to specify the supported tokens like the WHATWG spec does? So no removal of the `rel="sidebar"` https://html.spec.whatwg.org/multipage/semantics.html#attr-hyperlink-rel

**Comment by travisleithead** [comment]
OK, it looks like we only need to remove the short section on secondary browsing contexts...
