### ISSUE TITLE
Use <xmp> for examples in .include files?

### ISSUE THREAD

**Issue by edent** [w3c/html#1182]
As noted in #1176, many of the examples are confusing to read when editing.  This is, in part, because using the `<pre>` element means that elements must be escaped using `&lt;`.

```
<pre highlight="html"> 
 &lt;table&gt; 
   &lt;tr&gt;&lt;tr&gt; &lt;th&gt; Image &lt;th&gt; Description&lt;tr&gt; 
...
```

I *think* that Bikeshed allows us to use `<xmp>` in the `.includes` files https://tabatkins.github.io/bikeshed/#xmp

This would mean we could write:

```
<xmp highlight="html"> 
 <table> 
   <tr><tr> <th> Image <th> Description<tr> 
...
```

Does anyone object to me creating an experimental branch to see if it makes the examples easier to read?

(I appreciate [`xmp` is obsolete in HTML5](https://www.w3.org/TR/html5/obsolete.html#elementdef-xmp).)

**Comment by chaals** [comment]
Go for it. We don't use HTML5 to write the spec anyway :)

**Comment by edent** [comment]
A quick test shows that this works!

Roughly 560 HTML example to fix.... :-)

**Comment by edent** [comment]
Notes to myself...

Running `grep -rinc "pre highlight=\"html" | grep -v :0` to find all / most instances.

```
sections/semantics-forms.include:100
sections/semantics-document-metadata.include:18
sections/semantics-embedded-content.include:87
sections/infrastructure.include:4
sections/introduction.include:12
sections/editing.include:8
sections/semantics-common-idioms.include:15
sections/semantics-edits.include:11
sections/semantics-root.include:1
sections/semantics-tabular-data.include:10
sections/semantics-links.include:11
sections/browsers.include:5
sections/semantics-interactive-elements.include:4
sections/semantics-sections.include:37
sections/dom.include:19
sections/semantics-grouping-content.include:53
sections/semantics-scriptings.include:12
sections/syntax.include:41
sections/semantics-textlevel.include:97
```

(I've fixed some already)

**Comment by chaals** [comment]
When you say "works" do you mean that it converts the `<xmp>`s in the input to proper HTML 5 when it builds? Because we do publish the spec in HTML...

**Comment by agcolom** [comment]
@edent I'm currently working on sections/semantics-embedded-content.include to clean up the whole section... so I can take care of this one if you like at the same time for this section, if you haven't done it yet, otherwise I could wait for your editions and make my changes afterwards....

**Comment by edent** [comment]
@chaals yes, it outputs proper HTML5.

So:
```
    <xmp highlight="html">
      <p>Only <img src="euro.png" alt="euro ">5.99!
    </xmp>
```

Becomes:
```
<pre class="highlight"><span class="p">&lt;</span><span class="nt">p</span><span class="p">></span>Only <span class="p">&lt;</span><span class="nt">img</span> <span class="na">src</span><span class="o">=</span><span class="s">"euro.png"</span> <span class="na">alt</span><span class="o">=</span><span class="s">"euro "</span><span class="p">></span>5.99!
</pre>
```

@agcolom if you're happy to wait until Monday, I should have a cleaned up version ready for you to work your magic on.

**Comment by edent** [comment]
@agcolom Here's a diff showing what I've done to the file.

https://github.com/w3c/html/compare/master...1182-edent-xmp#diff-49ee012831f68736a21421145a6ce3db

I've run bikeshed over it and manually compared it to the original - but I'm sure there's room for improvement.  Some highlights....

* All examples now use `<xmp>` and have "pure" HTML in them.
  * Well... Except ~6 examples which use `<mark>` to highlight specific passages within the example.
* Examples have been simplified.
* Splelling and grammer corrections.
* Tables have better layout (although can be improved).
* MathML example doesn't have invisible characters any more.

**Comment by agcolom** [comment]
@edent perfect! I'll wait until it's all in :-) I was wondering whether it might make sense to have a style guide for the examples? i.e. we can improve consistency and also highlight separately that html can be written in many different ways (i.e. attributes in no quotes/single/double quotes, upper case, lower case, indentation, omissible closing tags), but that for clarity, we will follow a specific style for clarity?

**Comment by chaals** [comment]
@agcolom yes please :)

See also #487

**Comment by agcolom** [comment]
Excellent! I'll create a new issue and assign to myself :)
