### ISSUE TITLE
Incorrect Syntax highlighting 

### ISSUE THREAD

**Issue by agcolom** [w3c/html#1185]
It appears that there are some issues with the syntax highlighting of some of our examples, in particular in CSS media queries when  ```@media``` is followed by parenthesis, see https://www.w3.org/TR/html53/semantics-embedded-content.html#example-ed8956bf 

However, media queries that only have _mediatype_ and no parenthesis have correct syntax highlighting, see the first example under https://www.w3.org/TR/html53/common-idioms-without-dedicated-elements.html#sec-tag-clouds .

Examples with both have incorrect syntax highlighting, see first example under https://www.w3.org/TR/html53/rendering.html#non-replaced-elements-flow-content (towards the end of the example).

I'm not sure what syntax highlighter is used so couldn't look further.

**Comment by hnrindani** [comment]
There are many related issues on our platform. Please refer to the following
[Problem with syntax highlighting (HTML/PHP) #34204](https://github.com/Microsoft/vscode/issues/34204)
[HTML not recognized inside php conditional bracket #34309](https://github.com/Microsoft/vscode/issues/34309)

**Comment by agcolom** [comment]
@hnrindani These issues are with Visual Studio. I am not sure we're using the same syntax highlighter. Are we?

**Comment by agcolom** [comment]
Just found that Bikeshed is using Pygment for syntax highlighting (https://tabatkins.github.io/bikeshed/#syntax-highlighting) ... I'll have a closer look to see what we can do to overcome this issue.

**Comment by agcolom** [comment]
Pygments seem to highlight media queries correctly when I tried on their site: http://pygments.org/demo/6712743/ ... This is a good sign :) I'm wondering whether bikeshed needs an updated version of Pygments... or that this file https://github.com/tabatkins/bikeshed/blob/master/bikeshed/lexers.py needs a new entry for ```@media```?

**Comment by agcolom** [comment]
Ok, so It seems that changing the example from 
```<pre highlight="css">
img { 
  width: 300px; height: 300px; 
}

@media (min-width: 32em) { img { width: 500px; height: 300px; } }
@media (min-width: 45em) { img { width: 700px; height: 400px; } }
</pre>
```

to

```<pre highlight="html">
&lt;style>
img { 
  width: 300px; height: 300px; 
}

@media (min-width: 32em) { img { width: 500px; height: 300px; } }
@media (min-width: 45em) { img { width: 700px; height: 400px; } }
&lt;/style>
</pre>
```

fixed this! 

Also worked with 

```
<xmp highlight="html">
<style>
img { 
  width: 300px; height: 300px; 
}

@media (min-width: 32em) { img { width: 500px; height: 300px; } }
@media (min-width: 45em) { img { width: 700px; height: 400px; } }
</style>
</xmp>
```
The only issue is we get the extra ```<style>``` element on the example... There must be a way to fis this, but at least we now have a workaround :)

**Comment by edent** [comment]
Try `<xmp highlight="css">`

**Comment by agcolom** [comment]
@edent just tried and it gives the same result as what we currently have with ```<pre highlight="css">``` which is that syntax highlighting stops after ```@media (min-width: 32em) {```

**Comment by chaals** [comment]
@agcolom would that be related to [a noted issue in pygments](https://bitbucket.org/birkenfeld/pygments-main/issues/1321/scss-highlighting-variables)?

Is it a feasible workaround to break the `xmp` at the point pygments breaks down and put a new one in immediately? Or does that have no benefit over the html/style hack you already found?

**Comment by siusin** [comment]
Thanks @agcolom .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
