### ISSUE TITLE
prefetch is defined in resource hints

### ISSUE THREAD

**Issue by plehegar** [w3c/html#119]
The prefetch definition in
 https://w3c.github.io/html/links.html#link-type-prefetch

is now getting refined in the webperf group:
 https://www.w3.org/TR/resource-hints/#dfn-prefetch

The HTML spec should simply reference Resource Hints.

**Comment by plehegar** [comment]
https://github.com/whatwg/html/commit/0f54b54307647ca15ace16ef03c570db1b918193

**Comment by plehegar** [comment]
I'm delegating this one to Resource-Hints rather copying some definitions in the HTML spec. Also, dropping suport for a/@prefetch and not including support for hints on a and area.

**Comment by travisleithead** [comment]
Closed per #417
