### ISSUE TITLE
<ins> example - why is crossing a boundary "poor form"?

### ISSUE THREAD

**Issue by edent** [w3c/html#1191]
I'd like some clarification on this example. Emphasis added:

> The following example represents the addition of two paragraphs, the second of which was
    inserted in two parts. The first <{ins}> element in this example thus crosses a
    paragraph boundary, **which is considered poor form**.
> https://github.com/w3c/html/blob/master/sections/semantics-edits.include#L65

By whom? And why?

**Comment by chaals** [comment]
By HTML, because as an author it is invalid to use overlapping elements.

**Comment by chaals** [comment]
(If you do this the parser will handle them in predictable ways. But doing it is still wrong - because unless you know **how** the parsing algorithm works, what will happen may or may not surprise you from reading the source code)

**Comment by chaals** [comment]
Closing this.
