### ISSUE TITLE
No description alternate and preferred style sheets 

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1194]
Hi. There is no description alternate style sheets and preferred style sheets in HTML 5.2 
Go to paragraph 4.8.6.1  https://www.w3.org/TR/html/links.html#element-statedef-link-alternate.
When you see example 5 comments, there are no description what is alternate style sheets and preferred alternate style sheet. I think It must be description or link, where you can read it (description have too old specification HTML4)

**Comment by edent** [comment]
This should probably use text from https://www.w3.org/Style/Examples/007/alternatives.en.html

**Comment by programmer3000** [comment]
@edent And where you can see there description what is alternate style sheets and preferred alternate style sheet? That link have no description. Description have only old specification HTML 4.01   https://www.w3.org/TR/html401/present/styles.html#h-14.3 
So HTML writers must give description alternate and preferred style sheets, because they have differents dehaviour or remove anything mentions about preferred style sheets (incl. example5 about stylesheets https://www.w3.org/TR/html/links.html#element-statedef-link-alternate ) or give link to older specification where people can read about it (but i think it is bad idea when new standard have link to old specification).

**Comment by edent** [comment]
Agreed. It is badly worded. The description for preferred is given in https://www.w3.org/TR/cssom-1/#preferred-css-style-sheet-set-name
