### ISSUE TITLE
Definition of class attribute does not specify order

### ISSUE THREAD

**Issue by martinth** [w3c/html#1195]
In the current HTML 5.2 specification defines:

> When specified on HTML elements, the class attribute must have a value that is a **set of space-separated tokens** representing the various classes that the element belongs to.

It's commonly excepted that for a "set" order usually does not matter and indeed the section about "set of space-separated tokens" also defines a  ordered subvariant:

> An ordered set of unique space-separated tokens is a set of space-separated tokens where none of the tokens are duplicated but **where the order of the tokens is meaningful**.

So I think it's fair to assume that by the above definition the order of the `class` tokens is indeed not specified.

Consider the following example:
```
<style>
. foo { color: red; }
. bar { color: green; }
</style>

<div class="foo bar">A</div>
<div class="bar foo">B</div>
```
The "A" will be green and "B" will be red. 

Granted, the fact that this behaves this way actually stems from the CSS specification. But without the definition in the HTML spec, wouldn't a user agent _technically_ be allowed to reorder the tokens in the `class` attribute in whatever way he likes _before_  applying any CSS rules? If that us the case I would argue that the order _should_ be specified in the HTML spec.

**Comment by chaals** [comment]
No, in at least blink, mozilla and MS Edge both A and B are green, because the ordering isn't relevant and the styles are applied according to the CSS spec, making the last rule the one that wins in both cases.

(I used a test case based on your example. I would be very surprised if Safari behaved differently, so closing for now).

**Comment by scottaohara** [comment]
Can confirm Safari also behaves as @chaals outlined above.

The ordering of classes in HTML has no effect on how the styling of an element is rendered.  The ordering of the class selectors in the cascade determines the styling and if one selector will be overwritten by another of the same specificity. 

Even an example like: 
```
<style>
.doo.dar {color: orange;}
.dar.doo {color: pink;}
</style>

<div class="doo dar">C</div>
<div class="dar doo">D</div>
```

Still renders both C and D as pink.
