### ISSUE TITLE
Make changes to HTMLAllCollection to track recent discussion about making the WebIDL match reality

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#120]
See Issue: https://github.com/whatwg/html/commit/4315a98056c60637546f739c2870b6945136af6d

**Comment by travisleithead** [comment]
Oops. Looks like I was working in the w3c repo and not my own fork... well shoot. If folks would still please review this commit, I'm happy to adjust it... 738b31570455b41d9c83bbe0c613bd95a32241fa

**Comment by foolip** [comment]
Did you mean to push 738b315 to master? https://github.com/whatwg/html/pull/780 has evolved since.

**Comment by domenic** [comment]
You may instead just want to add a normative reference to WHATWG HTML since that is where this HTMLAllCollection spec is actually being maintained.

**Comment by travisleithead** [comment]
> Did you mean to push  738b315  to master? whatwg/html#780 has evolved since.

No, but I'm tracking whatwg/html#780 and will catch-up when I have some time today...
