### ISSUE TITLE
ASCII art in source files is not helpful

### ISSUE THREAD

**Issue by chaals** [w3c/html#1201]
The source files generally start with a giant ASCII art version of the name, in a comment.

It is not always legible, and in any event it doesn't provide much in the way of value. It would be more helpful to describe the source file, what it contains, and where it ends up in the spec, for example

```
<!--
This is the source file for https://w3c.github.io/html/introduction.html

All the content is "non-normative". It contains
- a background / potted history of HTML
- a few design notes
- a note on HTML and XML syntax
- information on how the spec is written and how to read it
- some privacy considerations
- an introduction to HTML itself, how to write it, etc.
- non-normative conformance requirements for content
- links to some other specs: charmod, unicode security, and some accessibility specs
-->
```

* [x] acknowledgements.include
* [x] attributes.include
* [x] browsers.include
* [x] changes.include
* [x] dom.include
* [x] editing.include
* [x] element-content-categories.include
* [x] element-interfaces.include
* [x] elements.include
* [x] events.include
* [x] iana.include
* [x] infrastructure.include
* [x] introduction.include
* [x] obsolete.include
* [x] rendering.include
* [x] semantics-common-idioms.include
* [x] semantics-document-metadata.include
* [x] semantics-edits.include
* [x] semantics-embedded-content.include
* [x] semantics-forms.include
* [x] semantics-grouping-content.include
* [x] semantics.include
* [x] semantics-interactive-elements.include
* [x] semantics-links.include
* [x] semantics-root.include
* [x] semantics-scriptings.include
* [x] semantics-sections.include
* [x] semantics-tabular-data.include
* [x] semantics-textlevel.include
* [x] syntax.include
* [x] webappapis.include
* [x] xhtml.include

**Comment by arpit7714** [comment]
what to do ??

**Comment by chaals** [comment]
I filed one PR that covers the introduction chapter - #1202 

I am trying to get another one through my temporarily blocked up machine, covering the other items I ticked off the list.

Anyone should feel free to tick something off and file a PR to cover it...

**Comment by scottaohara** [comment]
@chaals I was going to try to take care of a few of these over the weekend.  Would you rather I piggy back off your existing PR, or create a PR of my own changes?

Thanks

**Comment by chaals** [comment]
Easier if you make your own I think, although I am not that fussed. I started ticking off items as I was about to do them, which might help.
