### ISSUE TITLE
CfC: Incorporate Custom Elements into HTML spec

### ISSUE THREAD

**Issue by chaals** [w3c/html#1209]
This is a formal call for consensus on the proposition:

The HTML spec should directly incorporate Custom Elements.

Replies should be made before the end of the day (i.e. midnight Hawaii time) 20 February 2018 to be taken into consideration,

Positive response as a thumbs-up, or negative response explaining rationale are preferred. Silence will be taken as agreeing to the outcome of the CfC.

Please see also issue #955. The rationale for the proposal is that there has been no work done on the Custom Elements specification in well over a year, and it makes more sense to include relevant parts in the HTML specification itself than to maintain a series of patches. The HTML editorial team have committed to ensure the relevant work is done within the HTML 5.3 timeline.

**Comment by edent** [comment]
For those new to this issue (like me!) - here are some helpful resources:

* [MDN Guide to Custom Elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements)
* [Google's Guide to Custom Elements](https://developers.google.com/web/fundamentals/web-components/customelements)
* [W3C Specification on Custom Elements](https://www.w3.org/TR/custom-elements/)

**Comment by chaals** [comment]
With thanks to those who replied to this as well as the previous issue, this CfC passes. We will retire the (already orphaned) stand-alone Custom Elements spec, and incorporate its content here.
