### ISSUE TITLE
Question: license of W3C HTML

### ISSUE THREAD

**Issue by takenspc** [w3c/html#121]
It seems that there are two different license notices for W3C HTML:
- [LICENSE.md](https://github.com/w3c/html/blob/master/LICENSE.md) links to [W3C Software and Document Notice and License](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document),
- On the other hand, https://w3c.github.io/html/ links to [W3C Document License](https://www.w3.org/Consortium/Legal/2015/doc-license)

I wonder which is the right one.

**Comment by chaals** [comment]
The software and document license.

**Comment by plehegar** [comment]
That's a bikeshed issue actually.
See
https://github.com/tabatkins/bikeshed/issues/626

**Comment by plehegar** [comment]
We need to upgrade bikeshed at least to https://github.com/tabatkins/bikeshed/commit/fa51152ebb4305cf1ee353d091a88c87c7934cf1

**Comment by plehegar** [comment]
See #152

**Comment by takenspc** [comment]
I would like to thank you for every work in this issue.

I would like to close this issue because there is another issue (https://github.com/w3c/html/issues/121).

**Comment by plehegar** [comment]
This issue is still unresolved as far as I can tell, so I don't think we should close it yet.
