### ISSUE TITLE
parsing: xmp should trigger RCDATA-like parsing

### ISSUE THREAD

**Issue by chaals** [w3c/html#1211]
In the parsing chapter, [`xmp` triggers normal text parsing](http://w3c.github.io/html/syntax.html#the-in-body-insertion-mode), but it is actually using [RCDATA parsing]() (or something very like it and unlike text parsing), like `title` and `textarea`.

**Comment by chaals** [comment]
@patricia-gallardo @bzbarsky @cynthia @travisleithead might know more about this than me - or just be able to confirm/deny.

**Comment by bzbarsky** [comment]
Simple testcase:

    data:text/html,<xmp>&amp;

Sure looks like "raw text" parsing to me in Firefox, Chrome, and Safari.   And quite different from:

    data:text/html,<textarea>&amp;

Hard to tell more without context for what's actually being claimed here.

**Comment by chaals** [comment]
cf.

* `data:text/html,<p>&<mark>f`
* `data:text/html,<xmp>&<mark>f`
* `data:text/html,<textarea>&<mark>f`

Basically, `xmp` (like `textarea` and `title`) handle markup in a "special" way... and `xmp` **additionally** seems to have special handling of &amp;

**Comment by bzbarsky** [comment]
textarea/title use http://w3c.github.io/html/syntax.html#tokenizer-rcdata-state and xmp uses http://w3c.github.io/html/syntax.html#tokenizer-rawtext-state

Please don't confuse "raw text" and "text".  They are NOT the same thing.

**Comment by bzbarsky** [comment]
And to be clear, http://w3c.github.io/html/syntax.html#the-in-body-insertion-mode in the "xmp" section says: "Follow the generic raw text element parsing algorithm" which links to http://w3c.github.io/html/syntax.html#generic-raw-text-element-parsing-algorithm which puts the tokenizer in http://w3c.github.io/html/syntax.html#tokenizer-rawtext-state which is not the same thing at all as http://w3c.github.io/html/syntax.html#data-state (which is the "normal text" state).

**Comment by chaals** [comment]
Erp. Yup. Nothing to see here.

Sorry. (And thanks @bzbarsky)
