### ISSUE TITLE
Remove "Other Pragma Directives"

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1212]
Pragma directives have 2 problems.
1) If you go to link https://wiki.whatwg.org/wiki/PragmaExtensions#content - you can read "that model has been abandoned, and further pragma directives must go through the normal standards process for new features instead." That mean now not exist "other pragma directive". That mean HTML creators must delete section "4.2.5.4. Other pragma directives"
2)  Attribute `http-equiv` have not normal decsription. Just "When the `http-equiv`
attribute is specified on a meta element, the element is a pragma directive." What idiot wrote the specification? No normal description. How people can understand what mean pragma directive? -  no description how it works. If older specification have some decription about it like equivalent HTTP header. But now in 2017 description just "When the `http-equiv`
attribute is specified on a meta element, the element is a pragma directive."

**Comment by chaals** [comment]
I edited the title to be clearer - this should be done in the next Working Draft.

Note: [Section 4.2.5.4](http://w3c.github.io/html/document-metadata.html#other-pragma-directives) is generated by [sections/semantics-document-metadata.include](https://github.com/w3c/html/blob/master/sections/semantics-document-metadata.include)

(To be honest I thought we had, but I looked and the issue I half-remembered was a different bad idea that needed to be removed).

By the way, it is not acceptable behaviour in this group to call people idiots. Many people worked on the specifications in the last 25 years, some of them are acknowledged in this version. See the [Code of conduct](https://github.com/w3c/html/blob/master/docs/conduct.md), point 4, in particular

**Comment by ericwbailey** [comment]
I'd like to try tossing my hat into the ring, if you don't mind.

@chaals: Am I correct in my understanding that this ticket is asking for an upstream removal of all references to Other Pragma Directives in `sections/semantics-document-metadata.include`?

**Comment by programmer3000** [comment]
@chaals Yes, mabye some not acceptable behaviour. 

But when reading HTML specification it seems that people who wrote it nothing understand what they do or far from web design. 
How can professional who understand what he do write so description for peoples "When the http-equiv
attribute is specified on a meta element, the element is a pragma directive." which absolutely not informative (before versions HTML was more informative about that attribute)? Looks like people who worked on the specification not understand how work attribute http-equiv. 

And so almost every element have problems. For example if you go to link and see <title> element parents. 
https://www.w3.org/TR/html/fullindex.html#index-elements    <title> element parents is <head> and <template>. But if you go to link <title> element description https://www.w3.org/TR/html/document-metadata.html#the-title-element you can see there "Contexts in which this element can be used: In a head element containing no other title elements. " - mean only in <head>. And why differently called "Contexts in which this element can be used" and table header "Parents"? - It would be carefully for reader if the same things woud have have same names.

Or if you go to link https://www.w3.org/TR/html/fullindex.html#attributes-table and look value for rel - "Set of space-separated tokens". But it's not Set of space-separated tokens because space space-separated token could be every words. It must be list of alternate dns-prefetch author service worker ... and so on . Also specification have no description dns-prefetch at all )) .. and many other thing too have no description

**Comment by chaals** [comment]
@ericwbailey, please read the [documentation on contributing](https://github.com/w3c/html/blob/master/CONTRIBUTING.md), and then go ahead if you would like to. (Note also that the documentation needs editing. We are looking at that now, but your comments on what should be noted would be very gratefully received. Likewise, feel free to shout out to me for some help).

The ticket is basically to remove the section noted, and any references to it from elsewhere in the document - but I don't think there are any.

This does not add anything, and therefore doesn't need a patent commitment to do - if you make a Pull Request we'll clear the IPR check in review.

**Comment by chaals** [comment]
@programmer3000 for every thing you find that doesn't have a description, and should, it would be helpful to raise an issue. The spec was written over many years, and some bits have probably not been looked at carefully - or someone never got back to fix what they saw - since 10 years ago. A lot of people have worked on it, and some write better than others. One of the tasks we would like to do is make it easier to understand - having all algorithms for how browsers process stuff doesn't help developers much.

(@edent recently added a [description of `dns-prefetch`](http://w3c.github.io/html/links.html#element-statedef-link-dns-prefetch) to the editors' draft... but there is still a lot more work to do ...)

**Comment by ericwbailey** [comment]
Thanks for the direction, @chaals! I've removed the section in question. 

A quick global search for "pragma directives" reveals two additional references on lines [817](https://github.com/w3c/html/blob/master/sections/semantics-document-metadata.include#L817) and [1133](https://github.com/w3c/html/blob/master/sections/semantics-document-metadata.include#L1133), but they appear to speak to, er, non-other pragma directives and have not been removed.

I've [submitted a PR for the changes](https://github.com/w3c/html/pull/1220), and have a few notes for `CONTRIBUTING.md`. Would you prefer an issue to be raised before submitting for review? Or just submitting the PR and having the conversation there?
