### ISSUE TITLE
Missing "fetching a module worker script tree"

### ISSUE THREAD

**Issue by edent** [w3c/html#1222]
We have an missing definition for [fetching a module **worker** script tree](https://github.com/w3c/html/blob/master/sections/webappapis.include#L257).

We have a definition for [fetching a module script tree](https://github.com/w3c/html/blob/master/sections/webappapis.include#L353)

WHATWG have [fetch a module script graph](https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-module-script-tree) *and* [fetch a module **worker** script graph](https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-module-worker-script-tree).

I don't know enough about this to fix it.

Discovered in #1215

**Comment by chaals** [comment]
@cynthia, do you "want" to take this?

**Comment by chaals** [comment]
It seems Chrome implemented "fetching a module worker script" [a few days ago](https://bugs.chromium.org/p/chromium/issues/detail?id=680046) behind a flag, but it is not clear if they have got graphs (used to be called trees) running.

**Comment by chaals** [comment]
Mozilla think [it's something that would be nice one day](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687)

**Comment by chaals** [comment]
It seems like this should be marked "at risk"... or just removed. @cynthia, WDYT?

**Comment by chaals** [comment]
Changing the title on this - there are various differences, in various states of matching reality. Should do a proper side-by-side review and check...

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
