### ISSUE TITLE
HTML structure <article> and <section> needs to be redone

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1224]
**Structure of document HTML 5.2 very strange and implicitly and must be rewrite**. It's about elements `<article>` and `<section>`. What we have now. - example of structure what html creators think is perfect:

```
<article>
	<header>
		<h2>Apples</h2>
		<p>Tasty, delicious fruit!</p>
	</header>
	<p>The apple is the pomaceous fruit of the apple tree.</p>
	<section aria-label="Red apples.">
		<h3>Red Delicious</h3>
		<p>These bright red apples are the most common found in many
		supermarkets.</p>
	</section>
	<section aria-label="Green apples.">
		<h3>Granny Smith</h3>
		<p>These juicy, green apples make a great filling for
		apple pies.</p>
	</section>
</article>
```

And same example as it should be (content(article) "Apples" inside big category(section) and sub-categories(section) "Red Delicious" and "Granny Smith" inside big category(section)):
```
<section>
	<article>
		<header>
			<h2>Apples</h2>
			<p>Tasty, delicious fruit!</p>
		</header>
		<p>The apple is the pomaceous fruit of the apple tree.</p>
	</article>
	<section aria-label="Red apples.">
		<h3>Red Delicious</h3>
		<p>These bright red apples are the most common found in many
		supermarkets.</p>
	</section>
	<section aria-label="Green apples.">
		<h3>Granny Smith</h3>
		<p>These juicy, green apples make a great filling for
		apple pies.</p>
	</section>
</section>
```

 
or this (big category(section) "Apples" and sub-categories(section) "Red Delicious" and "Granny Smith" inside big category(section)):

```
<section>
	<header>
		<h2>Apples</h2>
		<p>Tasty, delicious fruit!</p>
	</header>
	<p>The apple is the pomaceous fruit of the apple tree.</p>
	<section aria-label="Red apples.">
		<h3 aria-label="Red apples.">Red Delicious</h3>
		<p>These bright red apples are the most common found in many
		supermarkets.</p>
	</section>
	<section aria-label="Green apples.">
		<h3 aria-label="Green apples.">Granny Smith</h3>
		<p>These juicy, green apples make a great filling for
		apple pies.</p>
	</section>
</section>
```

Main problem that write HTML creators about `<article>` and `<section>` does not conform to the logic and common sense. Because always everywhere content placed inside category and not category inside content. I think **it must be strongly deprecated placed `<section>` inside `<artice>`**

**Comment by LJWatson** [comment]
Why would you want to put a ```<section>``` element around an ```<article>``` element? The ```<section>``` element has no semantic meaning in that context.

**Comment by programmer3000** [comment]
@LJWatson why not? -because it most classical 100% semantic explicit structure without pervertions: 
```
-Category
	-SubCategory1
	-Subcategory2
	...
	-SubcategoryN
		-Element1
		-Element2
		...
		-ElementN
```

**Comment by edent** [comment]
> because it most classical 100% semantic explicit structure without pervertions:

Please could you give us some citations where this style is used.

**Comment by chaals** [comment]
(Giving a thumbs up to your own comment is pretty pointless) 

The semantics provided by HTML are not very strong, and usage in reality varies a lot. 

There are `article`s which are far too small to have `section`s, and `article`s which most definitely should use them. Even in blogs, but also in more substantial publications. Trying to make this construction invalid doesn't seem to serve any useful purpose.

**Comment by LJWatson** [comment]
Worth noting that the ```<section>``` element only has (accessibility) semantics when it has an accessible name. Otherwise it's the semantic equivalent of a ```<div>``` element.

So:
```
<section>
<article>...</article>
</section>
```

Has the same semantics as:
```
<div>
<article>...</article>
</div>
```


Even if this was not the case, a ```<section>``` represents content that has a common theme. An ```<article>``` represents content that has the common theme of being article content. So wrapping an ```<article>``` inside a ```<section>``` makes no semantic sense in that regard either.

Suggest we close this.

**Comment by programmer3000** [comment]
@LJWatson  @edent  No no no. you everybody wrong about structure. 
Yes, that example is bad, same bad as example6 to link https://www.w3.org/TR/html/sections.html#the-section-element ( **example must be redone** because it have not semantical structure) .

`<section>` not same as `<div>` because specification said: "The authors strongly recommend that the element `div` be considered as an element of last resort." - that mean `<div>` can be use if other tags non-conforming, for example for styling or for non-important information without any structure. 

But if you add `<h1>` - it will have semantic.
```
<section>
	<h1>Section name</h1>
	<article>...</article>
</section>

```

And where you can find real useful section with such description "represents content that has a common theme"? What does it mean in practice? And why so strange with anti-logic semantic structure examples for `<section>` and `<article>` in HTML 5.2 specification? Mabye because peoples not fully understand how to apply it in practice. 

"An `<article>` represents content that has the common theme of being article content." - where are you reading this? And what does that mean? How peoples can interpretate this and put into practice?
No, specification tell about `<article>` this:

"`article` element represents a complete, or self-contained, composition in a document, page, application, or site. This could be a magazine, newspaper, technical or scholarly article... " - and that description is really good. But description about `<section>` in HTML 5.2 specification looks like mean "hashtags" in vkontake or instagram. But it's not. It's nonsense, how can be practical to use with this description. Because absense normal alternate developers still use `<div>`, because `<section>` instead of category mean non-userfriendly something mystery "generic section of a document".

Situations where this style is used:
Example24 (`<li>` always inside `<ul>` - element inside container but not container inside element, same for `<table>` --> `<tr>` --> `<td>`). If you open any news site - there is Header --> Subheader --> Article and hashtags (or tags(link to category)), but most often still uses `<div>`, mabye because peoples not understand how right to use `<section>`, because specification have not normal explain where it could be used in practicie with normal examples with semantic structure.

Example where style can be use:
page with catalog of news (highly understanding and explicit structure)

```
<section>
	<h1>News></h1>
	<section>
		<h2>About Moscow</h2>
	</section>
	<section>
		<h2>About New York</h2>
	</section>
	<section>
		<h2>About stars</h2>
	</section>
</section>
```

same if author want put ahead news as most interesting (about Britney Spears )


```
<section>
	<h1>News></h1>
	<section>
		<h2>About Moscow</h2>
	</section>
	<section>
		<h2>About New York</h2>
	</section>
	<section>
		<h2>About stars</h2>
		<article>
			<h2>Britney Spears didn't watch Winter Olympics men’s downhill  super-gigant downhill because it was postponed due to high winds </h2>
			<p>
			Britney Spears come to Pyeongchang watch for skiing but strongly wind no further her plans to be realized.
			The men’s downhill, the blue riband event of the Winter Olympics, has been cancelled after 50mph gusts made it impossible for the gondolas taking the skiers up the mountain to be safely operated.
			With weather at the Jeongseon Alpine Center expected to worsen over the coming hours, the organisers said they had no choice but to move the event, which was due to take place on Sunday lunchtime, to 11am on Thursday.
			That will have the knock-on effect of pushing the men’s super-G to Friday, February 16.
			Korea’s united Olympic squad: symbol of hope or mere political stunt?
			Read more
			When there were fears earlier in the week that the race may have to be postponed, the 2014 Olympic Super G champion Kjetil Jansrud insisted that maintaining the integrity of the competition was paramount. “The message we got is that they want to do the downhill from the top in fair conditions,” he said. “I‘m thankful to hear that because that’s the way it should be in the Olympics. We do have reserve days and if the gondola’s not going to run we have a major problem.”
			International Ski Federation (FIS) chief race director Markus Waldner said at Friday’s team captains’ meeting that organisers were prepared for a lot more disruption over the next four days and were planning accordingly.
			Waldner said organisers would proceed with planning to race on Sunday with the first alternative being to move it to Monday at noon local time, between the two runs of the women’s giant slalom at the Yongpyong Alpine Centre.
			If they were unable to run the downhill before Thursday, then it would replace the Super G in the schedule with the other speed race shifting to Friday, currently a rest day.
			“We have some challenging days ahead,” admitted Waldner.
			Weather disruptions are commonplace in Alpine skiing both on the World Cup circuit and at the Olympics, and organisers always give themselves plenty of room for adjustments.
			Canada’s Manuel Osborne-Paradis said dealing with the weather went part and parcel with competing in an outdoor sport. ‚“The weather happens - in and out of clouds, the wind, snow picks up, whatever,” he said. “You push out of the gate, you do your best for two minutes and all the stars have to align anyway. The only factor you’re in charge of is how you ski.”
			World champion Beat Feuz of Switzerland and past Olympic downhill medalists Aksel Lund Svindal and Kjetil Jansrud - both from Norway – are the favourites for the competition.
			</p>
		</article>
	</section>
</section>
```

**Comment by programmer3000** [comment]
@chaals about thumb up - it's a joke, though mabye I think my comment too helpful))
"semantics provided by HTML are not very strong, and usage in reality varies a lot" - that is right. But strong and explicit are different meaning. 
Current definition `<section>`:
"The section element represents a generic section of a document or application. A section, in this context, is a thematic grouping of content."  - though not so bad, just for my examples.

I watch example 4 https://www.w3.org/TR/html/sections.html#the-article-element really no bad. Agreed, sometimes `<section>` inside `<article>` could have no bad semantic structure.

But **example6** https://www.w3.org/TR/html/sections.html#the-section-element much pointless and **must be redone**. 
I think **specification must have example**, **where `<article>` inside `<section>`** as most semantic explicit structure... for peoples to see different cases and mabye see something new for their projects.

I think **example 7** https://www.w3.org/TR/html/sections.html#the-section-element **must be remove** as too weak and poor as semantic structure. Possible add my example instead it.

I think **example 8** https://www.w3.org/TR/html/sections.html#the-section-element **must be redone**. Because there is no real article, just little introductory content.
I remade example8 for most right structure (I think it must be in specification):

```
<style>
	section { border: double medium; margin: 2em; }
	section.chapter h3 { font: 2em Roboto, Helvetica Neue, sans-serif; }
	section.appendix h3 { font: small-caps 2em Roboto, Helvetica Neue, sans-serif; }
</style>
...
<section class="book">
	<header>
		<h2>My Book</h2>
		<p>A sample with not much content</p>
		<p><small>Published by Dummy Publicorp Ltd.</small></p>
	</header>
	<section class="chapter">
		<h3>My First Chapter</h3>
		<p>This is the first of my chapters. It doesn’t say much.</p>
		<p>But it has two paragraphs!</p>
	</section>
	<section class="chapter">
	<h3>It Continues: The Second Chapter</h3>
	<p>Bla dee bla, dee bla dee bla. Boom.</p>
	</section>
	<section class="chapter">
	<h3>Chapter Three: A Further Example</h3>
	<p>It’s not like a battle between brightness and earthtones would go
	unnoticed.</p>
	<p>But it might ruin my story.</p>
	</section>
	<section class="appendix">
	<h3>Appendix A: Overview of Examples</h3>
	<p>These are demonstrations.</p>
	</section>
	<section class="appendix">
	<h3>Appendix B: Some Closing Remarks</h3>
	<p>Hopefully this long example shows that you <em>can</em> style
	sections, so long as they are used to indicate actual sections.</p>
	</section>
</section>
```

**Comment by Comandeer** [comment]
I'd like to put my 2 cents in.

> `<section>` not same as `<div>` because specification said: "The authors strongly recommend that the element div be considered as an element of last resort." - that mean `<div>` can be use if other tags non-conforming, for example for styling or for non-important information without any structure.

In terms of specification – yes. But in reality `section` without a heading is just a `div`. It's even written in specification:

> Each section should be identified, typically by including a heading (`h1`-`h6` element) as a child of the section element.

and:

> A general rule is that the `section` element is appropriate only if the element’s contents would be listed explicitly in the document’s outline.

Therefore `section` without a heading is _de facto_ non-conforming. In fact [that's how it's been understood for years](http://html5doctor.com/downloads/h5d-sectioning-flowchart.pdf) (this chart is from 2011).

> And where you can find real useful section with such description "represents content that has a common theme"?

Actually every content that is delimited by a heading could be considered having a common theme, e.g. chapters in book or parts of webpage's article. IMO `section` is redundant to headings, yet it strengthen their semantics (now chapters are not implicitly delimited by headings, but explicitly by `section`s).

> And why so strange with anti-logic semantic structure examples for <section> and <article> in HTML 5.2 specification?

I don't see them as anti-logic. In fact they follow "headings-first principle" (HFP): content is already parted by headings and then we just add appropriate semantic element to make this parting explicit. Let's look at examples that you think should be redone/removed.

Example 6 is the direct implementation of HFP. The whole thing is an `article` (as it's self-contained, independent content; rule of thumb: could be put into RSS, it's probably an `article`) and every thematic _section_ is marked up as `section` with appropriate heading. Therefore every content with a common theme is explicitly delimited.

Example 7 – the same, direct implementation of HFP. Every part of content describes different aspect of ceremony , so they should be delimited somehow. We can't use `article` here as these parts of content don't make sense on their own (without the whole concept of ceremony, user would lack necessary context to fully understand meaning of the content). Therefore we're left with `section` – a part of content that has a common theme.

Example 8 – the use of `article` seems to be appropriate as every single book could be a separate entry in RSS/Atom feed. To understand meaning of the specific book, we don't need any additional context (especially about other books), so such part of content is self-contained and independent – in terms of HTML 5.3 it's an `article`.

**Comment by programmer3000** [comment]
@Comandeer 

> But in reality section without a heading is just a div. It's even written in specification:
> Each section should be identified, **TYPICALLY** by including a heading (h1-h6 element) as a child of the section element.

You incorrectly interpretate HTML 5.2 specification. TYPICALLY not equivalent MUST. Each section also coud be identified by descendant element (because TYPICALLY not MUST), for example inheriting what inside `<header>`. For example, if `<p>` inside `<header>` and author full sure what just full paragraph could right identifited `<section>` - why not?! :
```
<section>
	<header>
		<p>Some text some text some text some text some text. 
		Some text some text some text some text some text. 
		Some text some text some text some text some text. Some 
		text some text some text some text some text. 
		Some text some text some text some text some text.</p>
	</header>
</section>

```

> Therefore section without a heading is de facto non-conforming

If you watch example28 for outline https://www.w3.org/TR/html/sections.html#outline you can see about outline "User agents should provide default headings for sections that do not have explicit section headings."

> Actually every content that is delimited by a heading could be considered having a common theme, e.g. chapters in book or parts of webpage's article. 

"every content that is delimited by a heading could be considered having a common theme" - there is nothing like this in the specification HTML 5.2. 
Specification HTML 5.2 tell about section: `<section>` represents common theme of content.

> I don't see them as anti-logic. In fact they follow "headings-first principle" (HFP): content is already parted by headings and then we just add appropriate semantic element to make this parting explicit. 

heading first or heading not-first or without heading - it doesn't matter, author can do how it sees it right.

> Example 6 is the direct implementation of HFP. The whole thing is an article (as it's self-contained, independent content; rule of thumb: could be put into RSS, it's probably an article) and every thematic section is marked up as section with appropriate heading. Therefore every content with a common theme is explicitly delimited.

What rss does it matter? Specification HTML 5.2 tell about article:  "The article represents a complete or self-contained, composition in a document. This could be a magazine, newspaper, technical or scholarly article, an essay or report, a blog or other social media post.". It's mean `<article>` like news article. Article (example 6) if it is real article must have more massive content and not so small. Sometimes in theory if author so want it could be too small, but it is not typical case. This specification is global and main specification of global web as main language of internet. But it is strange when main specification have strange and poor examples (Example 6) instead have rich most useful most explicit examples.

It would be more typical case if example6 was like this (more massive `<p>` (content) inside `<article>`):
```
<article>
  <header>
    <h2>Apples</h2>
    <p>An apple is a sweet, edible fruit produced by an apple 
	tree (Malus pumila). Apple trees are cultivated worldwide 
	as a fruit tree, and is the most widely grown species in the
	genus Malus. The tree originated in Central Asia, where 
	its wild ancestor, Malus sieversii, is still found today. 
	Apples have been grown for thousands of years in Asia and 
	urope, and were brought to North America by European 
	colonists. Apples have religious and mythological significance
	in many cultures, including Norse, Greek and European Christian 
	traditions.</p>
  </header>
  <p>The apple is the pomaceous fruit of the apple tree.</p>
  <section aria-label="Red apples.">
    <h3>Red Delicious</h3>
    <p>These bright red apples are the most common found in many
    supermarkets.</p>
  </section>
  <section aria-label="Green apples.">
    <h3>Granny Smith</h3>
    <p>These juicy, green apples make a great filling for
    apple pies.</p>
  </section>
</article>
```

> Example 7 – the same, direct implementation of HFP. Every part of content describes different aspect of ceremony , so they should be delimited somehow. 

Though agreed, example 7 has possible structure.

> Example 8 – the use of article seems to be appropriate as every single book could be a separate entry in RSS/Atom feed. 

Why about rss, it is topic not about rss. 

It would be most right structure for example8 it it will be like this (more massive `<p>` (content) section which inside `<article>`):

```
<style>
  section { border: double medium; margin: 2em; }
  section.chapter h3 { font: 2em Roboto, Helvetica Neue, sans-serif; }
  section.appendix h3 { font: small-caps 2em Roboto, Helvetica Neue, sans-serif; }
</style>
...
<article class="book">
  <header>
    <h2>My Book</h2>
    <p>A sample with not much content. More text. More text.
	 More text. More text. More text. More text. More text.
	 More text. More text. More text. More text. More text.
	 More text. More text. More text. More text.
	 More text. More text. More text. More text. More text.
	More text. More text.</p>
    <p><small>Published by Dummy Publicorp Ltd.</small></p>
  </header>
  <section class="chapter">
    <h3>My First Chapter</h3>
    <p>This is the first of my chapters. It doesn’t say much.</p>
    <p>But it has two paragraphs!  More text. More text. More text.
	 More text. More text. More text. More text. More text.
	  More text. More text. More text. More text. More text.</p>
  </section>
  <section class="chapter">
    <h3>It Continues: The Second Chapter</h3>
    <p>Bla dee bla, dee bla dee bla. Boom.  More text. More text.
	 More text. More text. More text. More text. More text.
	  More text. More text. More text. More text. More text.
	   More text. More text. More text. More text. More text.
	 More text. More text. More text. More text. More text.</p>
  </section>
  <section class="chapter">
    <h3>Chapter Three: A Further Example</h3>
    <p>It’s not like a battle between brightness and earthtones would go
    unnoticed.  More text. More text. More text. More text. More text.
	 More text. More text. More text. More text. More text. More text.
	 More text. More text. More text. More text. More text. More text.
	  More text. More text. More text. More text. More text. More text.</p>
    <p>But it might ruin my story.</p>
  </section>
  <section class="appendix">
    <h3>Appendix A: Overview of Examples</h3>
    <p>These are demonstrations. More text. More text. More text.
	 More text. More text. More text. More text. More text.
	  More text. More text. More text. More text.</p>
  </section>
  <section class="appendix">
    <h3>Appendix B: Some Closing Remarks</h3>
    <p>Hopefully this long example shows that you <em>can</em> style
    sections, so long as they are used to indicate actual sections. 
	 More text. More text. More text. More text. More text.
	 More text. More text. More text. More text. More text.
	  More text. More text. More text. More text. More text.
	   More text. More text. More text. More text. More text.</p>
  </section>
</article>

```

or like this, where `<header>` represents `<article>` as content and below `<section>` like categories (massive `<p>` just inside `<header>` )
```
<style>
  section { border: double medium; margin: 2em; }
  section.chapter h3 { font: 2em Roboto, Helvetica Neue, sans-serif; }
  section.appendix h3 { font: small-caps 2em Roboto, Helvetica Neue, sans-serif; }
</style>
...
<article class="book">
  <header>
    <h2>My Book</h2>
    <p>A sample with not much content. More text. More text.
	 More text. More text. More text. More text. More text.
	 More text. More text. More text. More text. More text.
	 More text. More text. More text. More text.
	 More text. More text. More text. More text. More text.
	More text. More text.</p>
    <p><small>Published by Dummy Publicorp Ltd.</small></p>
  </header>
  <section class="chapter">
    <h3>My First Chapter</h3>
    <p>This is the first of my chapters. It doesn’t say much.</p>
    <p>But it has two paragraphs!</p>
  </section>
  <section class="chapter">
    <h3>It Continues: The Second Chapter</h3>
    <p>Bla dee bla, dee bla dee bla. Boom.</p>
  </section>
  <section class="chapter">
    <h3>Chapter Three: A Further Example</h3>
    <p>It’s not like a battle between brightness and earthtones would go
    unnoticed.</p>
    <p>But it might ruin my story.</p>
  </section>
  <section class="appendix">
    <h3>Appendix A: Overview of Examples</h3>
    <p>These are demonstrations.</p>
  </section>
  <section class="appendix">
    <h3>Appendix B: Some Closing Remarks</h3>
    <p>Hopefully this long example shows that you <em>can</em> style
    sections, so long as they are used to indicate actual sections.</p>
  </section>
</article>
```
or example which above (sub-categories inside big category):
```
<style>
  section { border: double medium; margin: 2em; }
  section.chapter h3 { font: 2em Roboto, Helvetica Neue, sans-serif; }
  section.appendix h3 { font: small-caps 2em Roboto, Helvetica Neue, sans-serif; }
</style>
...
<section class="book">
  <header>
    <h2>My Book</h2>
    <p>A sample with not much content</p>
    <p><small>Published by Dummy Publicorp Ltd.</small></p>
  </header>
  <section class="chapter">
    <h3>My First Chapter</h3>
    <p>This is the first of my chapters. It doesn’t say much.</p>
    <p>But it has two paragraphs!</p>
  </section>
  <section class="chapter">
    <h3>It Continues: The Second Chapter</h3>
    <p>Bla dee bla, dee bla dee bla. Boom.</p>
  </section>
  <section class="chapter">
    <h3>Chapter Three: A Further Example</h3>
    <p>It’s not like a battle between brightness and earthtones would go
    unnoticed.</p>
    <p>But it might ruin my story.</p>
  </section>
  <section class="appendix">
    <h3>Appendix A: Overview of Examples</h3>
    <p>These are demonstrations.</p>
  </section>
  <section class="appendix">
    <h3>Appendix B: Some Closing Remarks</h3>
    <p>Hopefully this long example shows that you <em>can</em> style
    sections, so long as they are used to indicate actual sections.</p>
  </section>
</section>
```

So specification HTML 5.2 must have explicit note about "`<article>` could placed inside `<section>` and `<section>` could placed inside `<article>`" and must have example where `<article>` inside `<section>`. Because no examples where `<article>` inside `<section>` structure... like this deprecated but it is not and most cleary structure.

Example where `<article>` inside `<section>` like this (Sub-categories inside big category "News" and author explicit showed article content about Britney Spears):
```
<section>
	<h1>News></h1>
	<section>
		<h2>About Moscow</h2>
	</section>
	<section>
		<h2>About New York</h2>
	</section>
	<section>
		<h2>About stars</h2>
		<article>
			<h2>Britney Spears didn't watch Winter Olympics men’s downhill  
			super-gigant downhill because it was postponed due to high winds </h2>
			<p>
			Britney Spears come to Pyeongchang watch for skiing but strongly 
			wind no further her plans to be realized.
			The men’s downhill, the blue riband event of the Winter 
			Olympics, has been cancelled after 50mph gusts made it 
			impossible for the gondolas taking the skiers up the mountain 
			to be safely operated.
			With weather at the Jeongseon Alpine Center expected to worsen 
			over the coming hours, the organisers said they had no choice 
			but to move the event, which was due to take place on Sunday 
			lunchtime, to 11am on Thursday.</p>
			<p>That will have the knock-on effect of pushing the men’s 
			super-G to Friday, February 16.
			Korea’s united Olympic squad: symbol of hope or mere 
			political stunt?
			Read more</p>
			<p>When there were fears earlier in the week that 
			the race may have to be postponed, the 2014 Olympic 
			Super G champion Kjetil Jansrud insisted that 
			maintaining the integrity of the competition was 
			paramount. “The message we got is that they want to 
			do the downhill from the top in fair conditions,” 
			he said. “I‘m thankful to hear that because 
			that’s the way it should be in the Olympics. 
			We do have reserve days and if the gondola’s not 
			going to run we have a major problem.”</p
			</p>
		</article>
	</section>
</section>
```

**Comment by scottaohara** [comment]
Just wanted to jump in here and mention that I'll be giving these elements a review.  

It seems to me that there might be some areas where we can be a bit more explicit about usage, to help clear up some of how these elements should be interpreted by developers.

**Comment by js-choi** [comment]
See also recent activity at whatwg/html#83, starting from https://github.com/whatwg/html/issues/83#issuecomment-359871505.

**Comment by programmer3000** [comment]
You still don't add in HTML 5.3 case where `<article>` placed inside `<section>` ?
