### ISSUE TITLE
Allow SVG path data string to be used in CanvasRenderingContext2D fill/stroke

### ISSUE THREAD

**Issue by jacobp100** [w3c/html#1230]
We can currently use SVG path data to construct a `Path2D` object.

```js
const path = new Path2D("M10 10 h 80 v 80 h -80 Z");
```

We can also use this path in `ctx.fill` and `ctx.stroke`.

```js
ctx.stroke(new Path2D("M10 10 h 80 v 80 h -80 Z"));
```

Would it be consistent to allow path data to be used directly in `fill` and `stroke`? This would remove indirection. It make this feature more visible to users.

```js
ctx.stroke("M10 10 h 80 v 80 h -80 Z");
```

**Comment by chaals** [comment]
This is a feature request on a different specification. I opened an [issue in the canvas repository](https://github.com/w3c/2dcontext/issues/12)...
