### ISSUE TITLE
There is something wrong in character reference

### ISSUE THREAD

**Issue by dvorapa** [w3c/html#1231]
See [screenshot](https://ctrlv.cz/LTzY)

**Comment by chaals** [comment]
This is in the HTML 5.2 Recommendation? I fixed this as you can see in the [latest Working Draft](www.w3.org/TR/2017/html53/syntax.html#named-character-references). I have marked it as an erratum to consider fixing in the Recommendation.

**Comment by chaals** [comment]
Credit where it is due. **Wolfgang** [fixed it](https://github.com/w3c/html/commit/484452a5c02bd1a333db50f79cab384efe9c7cb8#diff-18abfc9c77aab42a715be1fd1e530dc2), I just committed the fix

**Comment by dvorapa** [comment]
I see
