### ISSUE TITLE
"div" inside "dl" for what? - no description

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1232]
HTML 5.2 specification have no description for what could be used `<div>` inside `<dl>` https://www.w3.org/TR/html/grouping-content.html#the-dl-element and no example, where `<div>` inside `<dl>`

**Comment by scottaohara** [comment]
This issue is already covered by [issue 1116: The prose for the dl element is not very clear, and examples are lacking](https://github.com/w3c/html/issues/1116).

Thank you for reporting, but I'm going to close this issue as it's a duplicate.
