### ISSUE TITLE
menu* roles missing from ARIA roles, states and properties table

### ISSUE THREAD

**Issue by carmacleod** [w3c/html#1234]
The ARIA roles `menu`, `menuitem`, `menuitemradio`, and `menuitemcheckbox` are missing from the [Allowed ARIA roles, states and properties table](http://w3c.github.io/html/dom.html#allowed-aria-roles-states-and-properties).

**Comment by chaals** [comment]
Note that this will fix a bunch of the outstanding linking errors in #1215

**Comment by carmacleod** [comment]
For some reason, the links aren't working for me when I go to [the table](http://w3c.github.io/html/dom.html#allowed-aria-roles-states-and-properties).
The code for each link looks ok, for example:
`<a attr-value for="aria/role"><code>menu</code></a>`
but it's not showing up as a link in the doc.
Does some other process need to be run to connect up all the links?

**Comment by scottaohara** [comment]
ah yes, looks like that's the case.  Will reopen and take care of that.

**Comment by chaals** [comment]
Specifically, looks like the terms still need to be listed in single-page.bs

**Comment by carmacleod** [comment]
Nice - thanks! :+1:
