### ISSUE TITLE
HTML 5.2 have no author element

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1239]
I think HTML 5.2 should be added new element `<author>`... where author represents author of creative work. Because for now nearest value for `<author>` have `<cite>` element. But `<cite>` it not fully represent semantic for most often cases.

For example how would it be (think it would be perfect):

```
<p><author>Sergei Smirnov</author> who wrote <cite>Yesterday, Tomorrow</cite> was
 winner <abbr>Palme d'Or</abbr> festival</p> 
```

More example how would it be (think it would be perfect):

```
<p><author>Mazda</author> build new turbo engine called <cite>Bird3000</cite> with perfect 
fuel consumption</p>
```
New element `<author>` could be help differentiate `<cite>` element. Because what we have now uses only `<cite>`:

```
<p><cite>Sergei Smirnov</cite> who wrote <cite>Yesterday, Tomorrow</cite> was winner 
<abbr>Palme d’Or</abbr> festival</p>
```
-last example imho, really strange

**Comment by chaals** [comment]
I suspect that there is little appetite to support an `author` element. Experience from e.g. Schema.org, and for much longer Dublin Core, suggests that it doesn't help people as much as we expect it to. So for plain HTML, `cite`is probably enough. For people who really want to get the detail there, RDFa, Microdata, JSON-LD, `meta` elements and Dublin Core are all established ways to do so with a *lot* of real use.

For what it's worth, I think your examples match the [description of the `cite` element](https://w3c.github.io/html/textlevel-semantics.html#the-cite-element), but that the description is not very helpful.

Rather, the element means something like a link, but without providing any clear mechanism to follow the link - its destination is represented by the content of the element, and is intended to make sense to at least some people...

So while I disagree that there should be an `author` element, looking at this issue has convinced me that we should describe the `cite element` better.

If you still think we should create a new element you should probably look for buy-in for your proposal in the [Web Incubator group](https://disourse.wicg.io) and bring back a more detailed proposal that has some clear support.
