### ISSUE TITLE
No example for data element

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1241]
HTML 5.2 specification have no example for `<data>` element https://www.w3.org/TR/html/textlevel-semantics.html#the-data-element

**Comment by chaals** [comment]
Assigned myself. This will also remind me that I need to finish the microdata specification with @danbri ...

(@programmer3000 if you want to make a Pull Request, e.g. using an example from microdata, that would be most welcome).

**Comment by programmer3000** [comment]
@chaals what is Pull Rerquest? For what?

**Comment by chaals** [comment]
It's how you create and propose a change to the actual code of the spec.

Feel free to contact me privately if you want me to show you how to do this - I am on skype and twitter and have a yandex email address. Or follow the link about contributing at the top of the page when you open an issue, and maybe the documentation will be clear already. (Probably not, but I will work on that a little too...)
