### ISSUE TITLE
Same functionality data- and RDF attributes?

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1242]
I'm not sure, but I think data-attributes https://www.w3.org/TR/html/dom.html#embedding-custom-non-visible-data-with-the-data-attributes  and RDF attributes (like in example 99) https://www.w3.org/TR/html/textlevel-semantics.html#the-time-element have same functionality. And if it so, one of attributes (mabye RDF) need to be remove from specification.

**Comment by chaals** [comment]
No. The difference is that `data-` attributes have locally defined meaning - two different authors might choose to call an attribute in their content `data-time` but each have very different meanings for the attribute. RDFa attributes, and many others, have a standardised meaning that is common to all usage of the attribute.

It is possible, and generallly bad practice, that an author might decide to use a `data-...` attribute where they could have used a standardised attribute. But making that impossible is extremely difficult, and very unlikely to be worth the effort. In part, making it too hard to use `data-...` is unhelpful; the "private-use" namespace stops people from inventing attributes that are even less clear than the ones we might try to standardise later, by always calling them `data-...` which we will never use for a standardised attribute.

Suggest we close this.

**Comment by programmer3000** [comment]
ok, close it
