### ISSUE TITLE
No example for "u" element

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1245]
HTML 5.2 specification have no example for `<u>` element https://www.w3.org/TR/html/textlevel-semantics.html#the-u-element
Though, I think it must be delete from HTML specification because it similar as `<b>` and `<i>` and it is not easy to differentiate between them (especially with `<i>`).
But if don't, it must have example and more cleary and explicit description, because for now too difficult understand what about this element

**Comment by programmer3000** [comment]
@prlbr It's bad example use for styling element
Good example for error:
`<p>The <u>see</u> is full of fish.</p>`

**Comment by chaals** [comment]
Yes, that is a better example. I don't think we should remove `u`, but it is tempting to deprecate it.

**Comment by programmer3000** [comment]
Thougn for mistakes no other elements. But <i> and <em> have too similar semantic and one of it should be removed

**Comment by prlbr** [comment]
`<u>` used to be deprecated in HTML4 and was re-introduced as an adequate member of HTML after much discussion, similar to what happend with `<s>`. Please don’t change this again quickly without serious and broad consideration and input.

> It's bad example use for styling element. For styling could use other elements.

My example is **not** about styling. The `<u>` element explains where the letters in the abbreviation come from. This information is usually transmitted via styling in visual media, but that’s simply the nature of visual media.

> and "Chinese proper name mark" - it's bad idea use element for miskakes and "Chinese proper name mark" which is not mistake.

It is important to be able to mark Chinese proper names though!

Personally I think the use case of marking up real mistakes (i.e. something that went other than intended) is negliable. We usually don’t use markup on mistakes in published documents. We rather correct them or  add a note such as `[sic]` when mistakes need to be preserved in quotes.

We use markup on "mistakes" when we explicitly talk about and demonstrate mistakes, e.g. in a grammar guide. But in these cases the mistakes are not really mistakes (i.e. something that went other than intended) anymore.

The description “an unarticulated, though explicitly rendered, non-textual annotation” may not be very clear at first and there may be room for improvement, but I suppose it’s actually quite well in line with what `<u>` is used for.

I suggest gathering data from the wild how `<u>` is used before any attempt to change the element into something different than it is now.

**Comment by programmer3000** [comment]
@prlbr 
> The <u> element explains where the letters in the abbreviation come from.
This really bad example. And for what? Same for your case you could use any other tag, for example, `<b>`, `<i>` or `<abbr>`

**Comment by Comandeer** [comment]
Actually I find it a good example.

`i`, in this context` is not appropriate as pointing at certain letters is not "alternate mood" or some kind of technical term.
`abbr` is also not appropriate as it's used to mark up whole abbreviations in very different manner.

`b` seems to be suitable, but `u` seems _more_ suitable. Underlining letters that form an abbreviation is actually a "non-textual annotation", yet "explicitly rendered". On the other side `b` is used for marking spans of text without adding any context, which is not exactly the case here.

**Comment by programmer3000** [comment]
@Comandeer as you can see all those examples sucked out of a finger

**Comment by chaals** [comment]
@programmer3000 your last comment is inappropriate.
