### ISSUE TITLE
Mark element need moree explicit description.

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1246]
For now description for <mark> element too bad. What exactly mean "represents a run of text in one document marked or highlighted for reference purposes, due to its relevance in another context"? For what this element using?

**Comment by chaals** [comment]
The `mark` element is implemented, but I am also unsure exactly how to describe it.

The closest I can get is to note that it highlights a piece of content that is being described elsewhere. How this differs from `em` is unclear to me - that is how I used to do the same task.

**Comment by programmer3000** [comment]
@chaals It's main problem. With this description I don't understand what about this element. And many ask if forums about it, because peoples don't understand what does it mean. 
This is an impression like HTML creators themselves not understand what does it mean. 
So if nodoy knows what it mean I think it will good idea for delete him from HTML specification.

**Comment by programmer3000** [comment]
I think <mark> was created long time ago for yellow highlighting and now when HTML not designed for styling content it must be remove as non actual element. Because it have not cleare explaining for what it today.

**Comment by chaals** [comment]
@programmer3000 about ten years ago I too thought it did not need to be in the specification. It is there, it is widely implemented, and people use it quite a lot, so I don't think we should delete it.

I do think we should explain it in the same context as `em`, `strong`, `b`, `i` and `u`. 

Reading and thinking more... the spec suggests that where `mark` is used in a quotation, the emphasis is provided by the one quoting the original reference - whereas using `em` would presumably imply that the original quotation itself included the emphasis.

SImilarly (and see your issue #1245) the suggestion in example 122 that `mark` might be used to highlight an error seems to create confusion with the `u` element, where one explicit use case is to highlight errors.

I'm suggest we group some of these bugs about elements that make something stand out - `b`, `em`, `i`, `mark`, `strong`, `u` - and ask for broader input.

**Comment by chaals** [comment]
(Note that when `mark` was created there was already a clear sense among the people working on the specification that HTML should not provide elements just for styling effects.)

**Comment by prlbr** [comment]
The use case I have in mind when I think about the `<mark>` element is this:

I use a website’s search engine to look for a term, say "book". The website returns a list of links to the pages that contain the term, but adds something like `?highlight=book` to the regular page URLs, so that the website software will still know I had searched for the term once I visit a page from the search results. When I click on one of those links, the page opens and in it all the occurrences of the word "book" will be highlighted with injected `<mark>` elements. The term is only relevant because I have searched for it (it is not especially relevant in the context of the page, but in the context of my search), hence `<mark>` is used. Someone opening the page with its regular URL won’t have any `<mark>` elements inside the page.

**Comment by programmer3000** [comment]
@prlbr but you can also use any element and search for that element or add class for element like `<span class="search">`

**Comment by Comandeer** [comment]
But the semantics would be totally different. What's more, `mark` element is [explicitly represented in browser's accessibility tree](https://w3c.github.io/html-aam/#el-mark), which is not the case with e.g. `span.search`.

**Comment by programmer3000** [comment]
@Comandeer and what idea for your own search must be full element. So possibly add 10 thousand new elements in HTML specification for different cases .

**Comment by chaals** [comment]
I suggest we close this issue in favour of #1247 which includes solving the problem...

**Comment by scottaohara** [comment]
I agree @chaals.  Closing.
