### ISSUE TITLE
i and em element have too similar semantic 

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1249]
I think `<i>` and `<em>` have too similar semantic and one of them must be deleted from HTML specification.
"The `<i>` element represents a span of text in an alternate voice or mood, or otherwise offset from the normal prose "
"The `<em>` element represents stress emphasis of its contents."
They really too similar.

**Comment by chaals** [comment]
These two are very similar, but I am not sure if we can deprecate either of them - they each have  wide use as well as implementation.

In any event, this issue is covered by #1247 so I am closing it. I will note there that deprecating elements is one possible pathway.
