### ISSUE TITLE
No description for slot attribute

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1256]
HTML 5.2 have no description for `slot` attribute https://www.w3.org/TR/html/dom.html#element-attrdef-global-slot and it not inside list of global attributes https://www.w3.org/TR/html/dom.html#global-attributes

**Comment by chaals** [comment]
This is something that is part of Shadow DOM, but yes it needs to be specified. Since it is something of a "super-global", going beyond the HTML spec, HTML probably isn't the ideal home for the "authoritative" specification, but IMHO it should at least be described there.

**Comment by chaals** [comment]
see also #1229
