### ISSUE TITLE
No example for picture element 

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1258]
HTML 5.3 specification have no example for `<picture>` element https://www.w3.org/TR/html53/semantics-embedded-content.html#the-picture-element

**Comment by scottaohara** [comment]
@programmer3000 examples 14, 15, 16 and 65 all utilize the `picture` element.

**Comment by programmer3000** [comment]
@scottaohara so probably it would be right placed example for picture also inside <picture> section

**Comment by shwetank** [comment]
CC'ing @brucelawson as well.

**Comment by scottaohara** [comment]
Do we want to:
1. move a previously outlined example into this section?
2. create a new example, though it may similar to other examples on the page?

Additionally, do we want to add a call out that there are other picture examples on this page?

**Comment by chaals** [comment]
either move an example, or create a new one.

In either case, linking to further examples seems helpful.

**Comment by srikanthalluri** [comment]
fsvfsv
