### ISSUE TITLE
Picture element haven't note about img element inside picture element

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1263]
There must be note in description of `<picture>` element about `<img>` element (after `<source>` element) **MUST** be placed inside `<picture>` element.
https://www.w3.org/TR/html/semantics-embedded-content.html#the-picture-element

**Comment by programmer3000** [comment]
So when this will be fixed?

**Comment by shwetank** [comment]
@brucelawson Want to have a crack at this?

**Comment by programmer3000** [comment]
Description of `<picture>` element nothing tell about this. So peoples could placed just `<source>` element inside `<picture>` without `<img>`

**Comment by Comandeer** [comment]
IMO there is such note, in description of content model (bold's mine):

> Zero or more `source` elements, **followed by one `img` element** […]

What's more, description of `picture` element also is quite clear at stating that `img` is required:

> The `picture` element is a container which provides multiples sources to its **contained `img` element** […]

That info is in fact repeated twice:

> By itself the `picture` element itself does not display anything; it merely provides a context for its **contained `img` element** that enables it to choose from multiple URLs.

Note also that description of `picture` element is different in ED than in latest published version.

**Comment by programmer3000** [comment]
@Comandeer although really content model have it

**Comment by scottaohara** [comment]
Agreed, @Comandeer 

As you mentioned, there are notes about `picture` containing an `img`, so I agree that is not an issue here.

The only thing I think could be updated is possibly a more explicit line about "why" the `img` must follow other `source` elements in `picture`.

**Comment by chaals** [comment]
Having an example in the element description would be helpful in itself, and would provide an opportunity to explain that the element must have the contained `img` in the prose, rather than relying on people reading the stuff that looks to a lot of ordinary people like complex boilerplate.

Explaining the example naturally make it clear *why* the element behaves that way, as Scott suggests.

**Comment by brucelawson** [comment]
I'll take a look, @chaals, but I personally see no ambiguity in the spec, as @Comandeer points out.
