### ISSUE TITLE
Picture element haven't note about priority source and img element

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1264]
https://www.w3.org/TR/html/semantics-embedded-content.html#the-picture-element
`<picture>` element haven't note about priority `<source>` and `<img>` element. It must be something like this: "first preferred for choose is `<source>` element and if no one source is relevant for choose then browser choose `<img>` element"

**Comment by programmer3000** [comment]
So when this will be fixed?

**Comment by shwetank** [comment]
@brucelawson Maybe take this up too?

**Comment by programmer3000** [comment]
For now description of `<picture>` element: "The picture element is a container which provides multiples sources to its contained img element to allow authors to declaratively control or give hints to the user agent about which image resource to use, based on the screen pixel density, viewport size, image format, and other factors. It represents its children.". 
And that is all? But nothing tell about how it work. 
Must be like this: "first preferred for choose is `<source>` element and if no one source is relevant for choose then browser choose `<img>` element" 
Otherwise where from peoples could know about first choose exactly `<source>` element and not `<img>` element

**Comment by scottaohara** [comment]
seems [PR 1379](https://github.com/w3c/html/pull/1379) has taken care of this issue? 

going to close.  if anyone thinks otherwise, let's discuss.
