### ISSUE TITLE
Update Content Models to account for Cus

### ISSUE THREAD

**Issue by brucelawson** [w3c/html#1276]
(Part of https://github.com/w3c/html/issues/1229 metabug)

HTML has several sections that need to be updated when introducing a new element, or in this case class of elements. The necessary changes are:

<ul>
        <li>
          <p><a href="https://html.spec.whatwg.org/multipage/dom.html#content-categories">The categories venn diagram</a>'s interactive list must include <a href="#autonomous-custom-element">autonomous custom elements</a> in phrasing and flow content.</p>
        </li>
        <li>
          <a href="https://html.spec.whatwg.org/multipage/dom.html#flow-content-2">Flow content</a> must include <a href="#autonomous-custom-element">autonomous custom elements</a>
        </li>
        <li>
          <a href="https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2">Phrasing content</a> must include <a href="#autonomous-custom-element">autonomous custom elements</a>
        </li>
        <li>
          <a href="https://html.spec.whatwg.org/multipage/dom.html#palpable-content-2">Palpable content</a> must include <a href="#autonomous-custom-element">autonomous custom elements</a>
        </li>
        <li>
          <a href="https://html.spec.whatwg.org/multipage/indices.html#elements-3">The elements index</a> must include a row at the bottom for <a href="#autonomous-custom-element">autonomous custom elements</a>
        </li>
        <li>
          <a href="https://html.spec.whatwg.org/multipage/indices.html#element-content-categories">The element content categories index</a> must include <a href="#autonomous-custom-element">autonomous custom elements</a> in the flow content, phrasing content, and palpable content sections
        </li>
        <li>
          <a href="https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission">Tag omission</a> must note that <a href="https://html.spec.whatwg.org/multipage/semantics.html#the-p-element"><code>p</code></a> element end tags cannot be omitted if the element's parent is an <a href="#autonomous-custom-element">autonomous custom element</a>
        </li>
      </ul>

**Comment by chaals** [comment]
fixed by #1294
