### ISSUE TITLE
Clean up 4.10 Form examples

### ISSUE THREAD

**Issue by scottaohara** [w3c/html#1290]
I'd like to take on the task of updating the code examples in 4.10 and start implementing some of the [formatting rules outlined in the style guide (WIP)](https://github.com/agcolom/html/wiki/Style-Guide---WIP).

As part of this update, I plan to review each of the examples to see if any should be revised or expanded.  For instance:

```
The following example shows the use of a for attribute, 
to associate labels which do not contain the element they label.

<form>
  <table>
    <caption>Example, <label>'s for attribute</caption>
    <tr>
      <th><label for="name">Customer name: </label></th>
      <td><input name="name" id="name"></td>
    </tr>
  </table>
</form>
```

A revision to this example would be a simplification by removing the `table` elements, and instead possibly using a `div` as a single container.  This would create a tighter focus on what the example is supposed to be representing (the `for` attribute's usage) while also moving the example away from what could be perceived as using `table`s for "layout purposes".

If anyone has any additional thoughts on this task, please let me know.

Thanks

**Comment by prlbr** [comment]
Concerning the particular example you gave, there’s the string `name` three times in

```
<input name="name" id="name">
```

So the example may not really make clear which `name` the `for="name"` refers to. I’d suggest using a string as ID that does not occur anywhere other than in the `id` and corresponding `for` attributes.

**Comment by scottaohara** [comment]
right, @prlbr.  Making some tweaks to things like that could definitely make things more clear, especially to those that might be unfamiliar to these attributes.
