### ISSUE TITLE
Proposal: allow <span> elements in <title> element

### ISSUE THREAD

**Issue by accessabilly** [w3c/html#1292]
Dear W3C-Team,

After conducting some tests with screen readers I encountered, that it's not possible to markup correct multi language `<title>` elements.

Let's assume, my markup looks like this:

```html
<html lang="en">
  <head>
    <title>La vie en rose - a love song by Edith Piaf</title>
  </head>
  ...
</html>
```

A screen reader (tested with NVDA and JAWS) or maybe any other assitive technology reads the `<title>` in English as proclaimed in `<html>` lang attribute. I assume, that this can be confusing for screen reader users.

As it is possible in the `<body>` element to assign different languages to different sections or even smaller parts of inline text via e.g. `<span lang="fr">`, it should be possible to have mixed language in `<title>` element. 

For users of assitive technology the `<title>` is very important and if this is read in a confusing way, the whole perception of the site starts with confusion.

By writing this, I suggest to **allow `<span>`  elements in the `<title>`** element like this:

```html
<html lang="en">
  <head>
    <title>
      <span lang="fr">La vie en rose</span> - a love song by Edith Piaf
    </title>
  </head>
  ...
</html>
```

Thank you and greets from Switzerland,
Martin

**Comment by edent** [comment]
That's a very interesting idea.  I should note that `<title>` can have a `lang` attribute which is different from the page's title.

```
<html lang="en">
  <head>
    <title lang="fr">Liberté, égalité, fraternité</title>
  </head>
```
https://www.w3.org/TR/html5/single-page.html#elementdef-title

At the moment, the Text Model is Escapable Raw Text https://www.w3.org/TR/html5/single-page.html#escapable-raw-text

This means there are lots of pages out there which use this as a feature.

`<title>This page is about the <span> element</title>`

So we'd need to find a way to allow that use case as well.

**Comment by accessabilly** [comment]
Aha, thank you for your reply. I didn't know about the Escapable Raw Text. This might make it complicated.

**Comment by edent** [comment]
The `<title>` is one of those fundamental things which hasn't changed much since the beginning of the web. I'd worry that expanding it might break all sorts of things.

You can use multiple languages on `<h1>` and other headings - but I appreciate that's not necessarily a good solution for screen readers.

I wonder if a `<meta>` might be a better solution? But I think I'll let other people chime in on that.

**Comment by LJWatson** [comment]
The use case is valid I think. That said, I tend to agree with @edent, that the ```<title>``` element would be a difficult thing to change.

**Comment by edent** [comment]
As a thought, does this problem also occur with `alt` text for images?

**Comment by accessabilly** [comment]
Yes it does, as far as I have tested it in the past. But I'm not a "real" screen reader user. I just use them for testing. Maybe @LJWatson has better facts on that. 

But if we could solve that `alt` text issue in the same way as we do for the `<title>`, this would be really nice, I think. Great thought.

**Comment by prlbr** [comment]
… then it also applies to the `title` attribute as well.

How much of a problem is this in practice though – is this something that screen reader users struggle with regularly?

If there was a solution, would authors actually bother to apply such detailed language markup? For instance, [Wikipedia](https://en.wikipedia.org/wiki/La_vie_en_rose) and [IMDB](http://www.imdb.com/title/tt0450188/) and [Youtube](https://www.youtube.com/watch?v=rzeLynj1GYM) do not mark occurrences of “La vie en rose” in the body with French language tags, although it would be possible with `<span>`s.

**Comment by accessabilly** [comment]
Yes, it applies to all attributes, that can contain language content. Maybe even `data` attributes should be considered here.

I can't tell for sure if this is a real problem to screen reader users. But I know of personal experiences, that the info in `<title>` is extremly important to users assitive technology. That some sites don't handle language correctly, I would rather see as a result of the technical challenge behind it, which is not properly addressed in most CMS or other web authoring tools.

On the other hand, the impossibility to handle mixed language in `<title>` and several attributes in HTML itself kind of contradicts [Success Criterion 3.1.2 of WCAG 2.1](https://www.w3.org/TR/WCAG21/#language-of-parts), if I'm correct here.

**Comment by accessiblewebuk** [comment]
Whether or not this is a problem for screenreaders, allowing change of language within a title element, or alt attribute, or for that matter other areas that don't allow a span (ARIA-live perhaps?), it would make the web better and more usable for screenreader users. 

Other than technical difficulties of implementation I can't think of any logical reasons not to make the change.

**Comment by chaals** [comment]
Changing the parsing is going to be complicated indeed, There is also an underlying assumption in HTML that a single page has a single language - although I think that especially with "single page applications" that assumption is now a constraint that doesn't match what people are trying to do.

An alternative approach that might be feasible to implement would be to allow multiple title elements, varying by page language. This would still be complex if it is possible, but it seems more likely than changing the parsing of the contents of the `title` element itself.

Marking this as i18n-comment and hoping for some feedback from the i18n group. I don't anticipate we can do this in the timeline of HTML 5.3, since that will start locking down soon, but I think it is worth considering the impact and value...

**Comment by chaals** [comment]
For what it is worth, trying to do this for attributes is a massive architectural change that seems very unlikely to occur.

**Comment by prlbr** [comment]
> Whether or not this is a problem for screenreaders […] it would make the web better and more usable for screenreader users.

I am not convinced. ;-)

> Other than technical difficulties of implementation I can't think of any logical reasons not to make the change.

I think that there should be a practical benefit to outweigh added complexity.

I’d like to add two and a half more thoughts to the discussion. Firstly, there are related features that should be considered in context: If a method for specifying the language where it is not yet possible would be added, then what about translatebility in the sense of the `translate` attribute? And should it also be possible to define text directionality as with the `dir` attribute?

Secondly, there could be alternatives to solve the problem. For example, software could recognize “la vie en rose” as being French automatically, without markup. This could have much more benefit than markup, as it would work for all sites, including legacy sites, sites of authors who don’t bother to add language tags and sites that are crafted with tools that don’t support this. This is not really an argument against markup as automatic recognition will surely fail in some cases and markup would help then, but it’s something to consider if you’re interested in solving the problem for users.

Dicussing the problem at the [Web Platform Incubator Group](https://discourse.wicg.io/) could be beneficial to find solutions to the problem. (The link does not work for me now, but it should work again soon. It is the correct URL.)

**Comment by accessabilly** [comment]
Before I opened this issue, I thought about exactly the same stuff: will Artificial Intelligence help out here? But the answer must be: NO! Because then, we leave it up to the makers of screen reader software. And we could start leaving out all the assistive content features like `alt` attributes and let AI define, what you see in an `<img>`. I agree, that maybe in the future this is an option, but not now.

And as long as there is [Success Criterion 3.1.2 of WCAG 2.1](https://www.w3.org/TR/WCAG21/#language-of-parts), as a developer or maintainer of an accessible site, I would want to have a solution to that.

What about something like this:

```html
<html lang="en">
  <head>
    <title aria-multilanguage="title">La vie en rose - a love song by Edith Piaf</title>
  </head>
  ...
 <h1 id="title"><span lang="fr">La vie en rose</span> - a love song by Edith Piaf</h1>
</html>
```

Just a quick thought. Why not do the multi language elsewhere and make a relation between two elements via id, like we do in other cases?

**Comment by prlbr** [comment]
> Because then, we leave it up to the makers of screen reader software.

You need to get them into the boat anyway. New markup won’t make sense if there’s no implementor interest.

---

<s>I think having a new title element that overrides the classical `<title>` element in supporting user agents would be the most simple markup solution:</s>

```html
<html lang="en">
  <head>
    <title>La vie en rose - a love song by Edith Piaf</title>
    <newtitle><span lang="fr">La vie en rose</span> - a love song by Edith Piaf</newtitle>
  </head>
</html>
```

Edit: Not a good idea actually. Legacy browsers would print the `<newtitle>` on the page.

**Comment by edent** [comment]
As a late night thought - something like this passes validation, and structured data testing.

```
<!doctype html>
<html lang="en">
  <head itemscope itemtype="http://schema.org/CreativeWork">
    <meta itemprop="alternativeHeadline" content="<span lang='fr'>La vie en rose</span> - a love song by Edith Piaf"/>
    <title>La vie en rose - a love song by Edith Piaf</title>
  </head>
</html>
```

Or, similarly:
```
<head itemscope itemtype="http://schema.org/Property">
    <meta itemprop="alternateName" ...
```

With regards to getting Screen Readers on board - yes. But there's use beyond accessibility features as well.

**Comment by accessabilly** [comment]
Yep, I would be fine with something like that. But isn't this too schema.org specific and not "native" HTML? Just feels a little "away" from it.

**Comment by fantasai** [comment]
Hm, what if you defined the page title as all the `<title>` elements concatenated together, and then allowed multiple `<title>` elements in the `<head>`?

**Comment by edent** [comment]
@fantasai you can't. Older browsers expect exactly one `<title>`. They place any extras they find into the body text.

**Comment by aphillips** [comment]
This is a long-standing I18N problem (the `alt` attribute--and other language bearing attributes--mentioned elsewhere in the thread are also and for the same reason if not worse because they don't have separate language identification for the most part). 

It's not just screen readers: processing and display of strings sometimes depends on good language information. The inability to correctly tag substrings with language (or, for that matter, direction) is a Problem.

That said, we've never been able to fix it in 25 years because of compatibility.

**Comment by prlbr** [comment]
@edent Currently, Firefox, Safari and Lynx don’t place multiple `<title>` elements into the body. All but the last `<title>` elment seem to be ignored. I haven’t tested other browsers.

But I think that your [idea](https://github.com/w3c/html/issues/1292#issuecomment-375820383) would be nicer in terms of graceful degradation than composing a single title from multiple `<title>` elements, where legacy browsers only take the first `<title>` element as complete title.

**Comment by ntounsi** [comment]
RTL users have similar problem to tag an opposite direction in titles
One still need to use control characters (fortunately represented by numeric entities for some).

```
<head>
	<meta charset="utf-8">
	<title>Title is "&#x202B;نشاط التدويل، W3C&#x202C;"</title>
 </head>
 <body>
	<p>Title is "<span dir="rtl">نشاط التدويل، W3C</span>"</p>
 </body>
```

to have the title appear as in the body text :

![rtltitle](https://user-images.githubusercontent.com/15004708/37875613-e4acba38-3039-11e8-86fa-f9c9b3d797f8.png)

instead of :

![ltrtitle](https://user-images.githubusercontent.com/15004708/37875625-f074ec6e-3039-11e8-8b5f-fd750f92734d.png)

**Comment by r12a** [comment]
> That said, we've never been able to fix it in 25 years because of compatibility.

Actually, we did manage to fix most of it for XHTML2, but of course that didn't get us very far, and when i asked the HTML5 folks in the early days to look at title attribute and element and alt they didn't feel able/motivated to address the issue.

(fwiw, especially if we are planning to add new features to HTML, please follow the advice at https://www.w3.org/International/techniques/developing-specs.en?open=markup&open=markup_elements_attributes)

**Comment by j9t** [comment]
Historical note, we’ve discussed similar on www-html at some point (cf. my own partially uninformed suggestion [1]) and a bit later (2007), Lachlan Hunt explained regarding why changes were unlikely to be made [2]:

> For compatibility reasons in HTML, title cannot contain elements because of the way it is parsed. It would be possible to do so in XHTML, but then that would be another incompatibility between the 2 languages and there is also limited usefulness in doing so anyway, since many of the use cases for title are plain text. e.g. the window's title bar, bookmarks, search results, etc.

[1] https://meiert.com/en/blog/html-semantics-of-title-element-content/
[2] https://lists.w3.org/Archives/Public/www-html/2007Feb/0003.html

**Comment by chaals** [comment]
As far as I can tell at a glance, the HTML5 parsing algorithm puts all title elements into the head. The rendering chapter says nothing at all about them.

The spec for the element itself just says "there can be only one" without explaining what to do if there **are** more.

I did a back-of-a-scratch file test and Edge, Firefox and Opera all used the first of three for the relevant tab. Lynx used the last one. None of them rendered the others on the page.

It seems feasible (in terms of changes to the spec) to allow alternate `title` elements that are marked with different `lang` attributes, stating that user agents should render the one that matches the user's UI, or the first one as a fallback.

The question is whether there are any user agents who would implement this any time soon.

@patricia-gallardo ? Thoughts?

**Comment by aphillips** [comment]
@chaals but that's not actually solving the problem at hand though. I suppose multiple title elements might be occasionally (rarely) useful. The problem is tagging spans of text within a title--this helps with font selection, accessibility, etc. Direction info would also be helpful.

Having multiple titles strikes me mainly as a way to smuggle more SEO keywords into the text. After all the content of the page won't have multilanguage alternatives..

**Comment by chaals** [comment]
@aphillips sorry, you are right. Jetlag seems to be kicking into my brain.

Although the content of SPA pages in particular might well have multilingual alternatives.

**Comment by edent** [comment]
As this has thread is quite long, I will summarise...

Multilingual titles are important for usability and accessibility. 

Ideally, we'd like something like `<title><span lang="en">A review of</span> <span lang="la">Tractatus Logico-Philosophicus</span></title>`

* Currently, the `<title>` element cannot contain anything other than raw text.
* Changing the way `<title>` behaves would have negative effect on older browsers.
* Adding new elements into the `<head>` is not possible. Browsers treat their contents as body text.
* It is possible to put multiple `<title>`s in the `<head>` - but rendering behaviour is inconsistent.

It seems that the options are...

1. Allow child elements in `<title>` and accept that older browsers may get confused, and that newer browsers may render older pages incorrectly.
1. Use [schema.org markup](https://github.com/w3c/html/issues/1292#issuecomment-375820383) to provide an `alternativeHeadline` and accept there's no way to achieve this in "pure" HTML.
1. Create a new attribute which could be used on `<title>` to provide multilingual text. 

It strikes me that [`longdesc`](https://www.w3.org/TR/html-longdesc/) may be suitable here.  If the title is the same as a heading which is correctly localised, then `<title longdesc="#example">...`

Or, if not, it can be done inline.

```
<title 
 longdesc="%3Cspan%20lang%3D%22en%22%3EA%20review%20of%3C%2Fspan%3E%20%3Cspan%20lang%3D%22la%22%3ETractatus%20Logico-Philosophicus%3C%2Fspan%3E">
```

**Comment by r12a** [comment]
To continue in brainstorming mode:

4. Add a new element that browsers can use instead of or alongside title, such as <docSummary>, and get browsers to transition to that so that it's eventually possible to deprecate <title>. The new element would allow spans internally, and browsers would be allowed to initially turn those to plain strings for representation in  tabs or bookmarks, etc, but eventually should take account of language and directional information in those locations.

I think that whatever solution is chosen, it has to be very quick and easy for authors to use, so i worry about items 2 and 3 on that score.

**Comment by prlbr** [comment]
@r12a: The problem with a new element is that browsers display it in the body, even if it’s written inside `<head>`. But maybe adding a `hidden` attribute or `style='display:none'` for a transitional time would help?

**Comment by devarshipant** [comment]
Just a thought--since a screen reader speaks the page title on page load (or made to via a shortcut key), could this work if aria-labelledby / aria-describedby attribute were supported in title?


e.g.:


```
<title aria-describedby="idPointingToHeading">I am learning french</title>
<h1 id="idPointingToHeading" lang="fr">J’apprends le français </h1>
```

**Comment by accessiblewebuk** [comment]
@edent I would have thought that in most cases the main part of the title will be in the language of the page so an initial span wouldn't be necessary, but I don't suppose that would make any difference to difficulties of implementation. 

Given that older browsers wouldn't support this, wouldn't users be no worse off when using them than if the title was in multiple languages without spans? In other words, wouldn't adding the ability to include spans just be a progressive enhancement?

**Comment by aphillips** [comment]
In the [I18N teleconference](https://www.w3.org/2018/03/29-i18n-minutes.html#x10) today (sorry our notes are sketchy), I suggested that we might adopt a new use for the `meta` element. Currently `meta` doesn't support content, but it is an existing element. Something like:

> &lt;meta name="title" lang="en">Learning &lt;span lang="de">Deutsch&lt;/span>&lt;/meta>

I drew an action item to mention it here.

**Comment by Malvoz** [comment]
Referencing issue [#553](https://github.com/w3c/html/issues/553) on multilingual `<meta name="description">`, I believe it is relevant.

**Comment by thepian** [comment]
Would multiple title tags with lang attributes not solve the need? I think allowing a page to have alternate titles by language would be quite helpful. Is it about pronunciation of different parts of the title?

**Comment by aphillips** [comment]
Having multiple titles in different languages would maybe be useful for multiple language documents, but it doesn't solve the problem of substrings in another language (where the TTS engine needs to change dictionaries or voices, for example, or where the font selection and fallback needs to change).

**Comment by chaals** [comment]
This is recorded with our new label "[if only we could](https://github.com/w3c/html/labels/if%20only%20we%20could)" - meaning we recognise the use case as valid, but don't think we can solve it in this group. It is therefore archived (although people can continue to discuss it) and can be found and referred to in the future.
