### ISSUE TITLE
Allow mapping between ARIA role=button/listbox/combobox/etc. AND HTML labelable element

### ISSUE THREAD

**Issue by devarshipant** [w3c/html#1295]
In the example below, the `<div> `with ARIA role listbox would be a valid (and an acceptable) labelable element. Objective is to create:
1.  for / ID attribute programmatic association.
2. Larger click area.
3. Less code to associate labels with their controls.

```
<label id="listbox_option" for="listbox_option_list">Search for Cases by</label>

<div tabindex="0" class="ui selection dropdown" id="listbox_option_list" 
role="listbox" aria-expanded="false" aria-activedescendant="listbox_option_0" ...
```

See related issue -- https://github.com/w3c/aria/issues/707

**Comment by devarshipant** [comment]
#https://github.com/w3c/aria/issues/707

**Comment by scottaohara** [comment]
Hi @devarshipant,

While I think the idea of a `label` providing the accessible name for an ARIA widget has merit, [Steve's comment about implementation](https://github.com/w3c/aria/issues/707#issuecomment-371825420) indicates that this is an issue that should be (re)proposed with browsers for implementation interest.
 
That said, I do have questions about expectations for this request beyond providing an accessible name.  Would it be expected that this sort of functionality should work regardless of if the author appropriately implemented the ARIA component, or if the JavaScript to power the ARIA widget were blocked or disabled?

e.g. in your example the `listbox` has a `tabindex='0'`.  If a user were to click the `label`, would browsers be expected to move keyboard focus to the `listbox` if the `tabindex` were missing?  What if the widget had an `aria-disabled` set, but the author had not implemented the appropriate JavaScript to disabled keyboard focus in the presence of that attribute? This would cross the line of ARIA expanding on / altering the semantics of an element and into the territory of ARIA changing the native functionality of an element (see also [Bryan's comment](https://github.com/w3c/aria/issues/707#issuecomment-373116989)).

Reading through the referenced [raised ARIA issue](https://github.com/w3c/aria/issues/707), I think discussion could continue there for now.

Thank you
