### ISSUE TITLE
Adopt new WebIDL mixin sytax

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/html#1298]
The [WebIDL spec has introduced a dedicated `mixin` syntax](https://heycam.github.io/webidl/#idl-interface-mixins) for interface partials that are never directly exposed. The [`NoInterfaceObject` attribute](https://heycam.github.io/webidl/#NoInterfaceObject) has been marked as an undesirable legacy feature.

WHATWG HTML has already moved to the new syntax, and other specs are being asked to switch over.

In reviewing [edits to SVG](https://github.com/w3c/svgwg/pull/376), I noted that we include/implement HTML interfaces by reference to the W3C spec, and that you have not changed your syntax.

We've filed an issue on WebIDL (https://github.com/heycam/webidl/issues/536), asking them to define transitionary behavior for different specs updating at different times.

But it would probably help overall consistency of web standards if W3C HTML also adopted the new syntax.

PS. I'm certainly not the person to answer any detailed questions about the syntax or the reasons for the change. Consult the WebIDL editors for that.

**Comment by chaals** [comment]
@AmeliaBR if this stuff is never exposed, I am currently assuming that it therefore doesn't affect conformance, and is just a better way of writing the spec.

Given that we are trying to get a spec out that is sufficiently complete for review as a potential Candidate Recommendation, I am assuming that we can do this when we're more or less feature-frozen, and therefore letting it slip the current milestone (due about now, but likely to slip a few days), and instead make it part of our long list of "editorial" cleanups to do once that milestone ships.

If I got that wrong, please push back fast...

**Comment by AmeliaBR** [comment]
@chaals

No, it's not exposed to end users. I think the main concern is for validators and other tools that are trying to consume specs in order to help build other specs.

**Comment by chaals** [comment]
@AmeliaBR by "not exposed" I understood "doesn't directly change implementation conformance", which may be what you are saying, or not.

I *think* we agree here - so if something I have said doesn't ring true, I'd be grateful for correction or raising a flag to make sure... :)

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
