### ISSUE TITLE
Define HTMLOrSVGElement mixin interface

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/html#1299]
SVG 2 adopts a number of features previously only defined on HTML elements: `dataset` and `data-*` attributes, the `tabindex` attribute and `tabIndex` DOM property, the `focus()` and `blur()` methods.

[In the September 2016 CR version of SVG 2](https://www.w3.org/TR/SVG2/types.html#InterfaceSVGElement), the new DOM interface features were defined independently on the `SVGElement` interface, with prose saying that they should be implemented in the same way as HTML.  This is not as "DRY" a definition as we'd like, and risks having the specs get out of alignment.

_For example, `HTMLElement` includes two different interfaces defining `on*` event handlers; `SVGElement` only included one of them (`GlobalEventHandlers`); for the other (`DocumentAndElementEventHandlers`), some user agents expose the properties on SVG elements but others don't._

An implementer raised an issue (https://github.com/w3c/svgwg/issues/60) asking why these couldn't be defined on the parent `Element` interface. They can't because they depend on attributes and behavior that aren't common to all XML. But I suggested that it might be nice to define a single interface for the shared behavior, which could then be implemented by both `HTMLElement` and `SVGElement`.

Follow-up discussion happened at WHATWG/DOM (https://github.com/whatwg/dom/issues/280) and then WHATWG/HTML (https://github.com/whatwg/html/issues/3471 and https://github.com/whatwg/html/pull/3543), with the decision to define the mixin interface in the HTML spec, as this was consistent with the current behavior of SVG linking to HTML for the definitions of these features.

The changes have just been committed to WHATWG HTML:
https://github.com/whatwg/html/commit/81e82437a7ef1ee37d4ce2b5a982bc297d5b58b1

Corresponding edits are in process for SVG. But we currently use W3C HTML as our normative reference, so it would be helpful if those changes could get incorporated into 5.3.

To be extra clear:
We're not suggesting any changes to any HTML behavior! We'd just like you to carve out some of the existing `HTMLElement` interface into a mixin that SVG can formally include by reference.

Directly copying the WHATWG changes would be dependent on #1298, re WebIDL syntax changes. 
 (Although if https://github.com/heycam/webidl/issues/536 is fixed, then it's possible you could add the mixin using the old syntax, and we could still include it with the new syntax. But that seems complicated.)

cc @dstorey

**Comment by dstorey** [comment]
an example of where this bit us was we (Edge) updated focus() to the new html definition with optional scroll parameter. The dev only updated it on HTMLElement, and the spec only defined it in SVG as the old signature without parameter. I've just implemented the new mixin (as defined in WHATWG HTML), which caused me to spot this mistake and update the implementation for SVG.
