### ISSUE TITLE
how does the HTML files in repo get updated?

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#13]
is the single-page.html file auto updated when changes are made to the .bs files?

**Comment by travisleithead** [comment]
Apparently not. Does anyone know how to set that up?

**Comment by LJWatson** [comment]
You need to install Bikeshed (instructions linked from the readme.md).

You edit single-page.bs (or one of the include  files it references), then run Bikeshed on the .bs file. This generates the single-page.html file. With that done you should be ok to issue a PR.

We're working on documentation for this.

**Comment by ZoeBijl** [comment]
@LjWatson some of us—@iandevlin and I—have issues when we run Bikeshed, see [comments on issue number one](https://github.com/w3c/html/issues/1#issuecomment-173195765). @tabatkins said in the Bikshed gitter channel that [those are linking issues](https://gitter.im/tabatkins/bikeshed?at=56a0222da03e28ad1adfed0d). Is this something you're aware of and are working on?

**Comment by adrianba** [comment]
Fixed by 8fd90967b036bb97c26013ba8c5c667e7935773e
