### ISSUE TITLE
ismap attribute have no example and description how it works

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1303]
1) `ismap` attribute have not good description about how it works. 
Only description:
"The ismap attribute, when used on an element that is a descendant of an a element with an href attribute, indicates by its presence that the element provides access to a server-side image map. This affects how events are handled on the corresponding a element."
But also must have description about content model: "ismap attribute of `<img>` element could be used only with `<a>` element with href attribute, where href - link to cgi-program"
2) Also ismap attribute have no example

**Comment by programmer3000** [comment]
So when this will be fixed?

**Comment by chaals** [comment]
When someone does the necessary work.

This attribute is rarely used on the web, and has been around for most of the history of the Web, so there are many examples and explanations available. We will fix this issue, but it is probably not high priority for many people.

**Comment by programmer3000** [comment]
@chaals So it must have note about that is old attribute and ot recommend for use

**Comment by prlbr** [comment]
@programmer3000 There is nothing wrong with the attribute – it’s old, but not obsolete.
