### ISSUE TITLE
Element <video> have no example vithout <script>

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1316]
Element `<video>` have no example without `<script>`. It should have most typical native (without script, because it is not script language, but HTML) example
https://www.w3.org/TR/html53/semantics-embedded-content.html#elementdef-video

**Comment by scottaohara** [comment]
I’ve self assigned to keep it on my radar but anyone should feel free to take this issue.

**Comment by iandevlin** [comment]
The `<audio>` element suffers from the same problem.
I have been looking to stop being lazy and get back to tackling some issues here again, so perhaps I will find the time to do this one.

**Comment by iandevlin** [comment]
https://github.com/w3c/html/pull/1378
