### ISSUE TITLE
Description of html element is not available

### ISSUE THREAD

**Issue by Comandeer** [w3c/html#1317]
Link to the `html` element in table of contents leads to an empty document without any content → http://w3c.github.io/html/semantics.html#the-root-element

**Comment by chaals** [comment]
Oh. I thought that bug had been fixed already. Maybe it recurred - it's to do with the build scripts.

**Comment by siusin** [comment]
The latest build has fetched [the missing content](https://w3c.github.io/html/semantics.html#the-root-element).

Thanks for reporting the bug, @Comandeer !
