### ISSUE TITLE
clarify 4.10.6 button tag for keyword or state

### ISSUE THREAD

**Issue by Nick-Levinson** [w3c/html#1319]
Please clarify section 4.10.6, on the button element, as to whether the type attribute's value should be the keyword or the state. I tested both possibilities (for a button intended to do nothing) without other attributes in relatively recent versions of the Firefox and Chrome browsers and saw no difference in either default appearance or in feedback. Both W3Schools and Mozilla document in favor of the keyword (https://www.w3schools.com/tags/tag_button.asp and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button (both as accessed Mar. 23-24, 2018)).

**Comment by chaals** [comment]
It should be the keyword - other values are invalid, because it is an enumerated attribute.
