### ISSUE TITLE
Update chapter 6 "Loading Web Pages"

### ISSUE THREAD

**Issue by takenspc** [w3c/html#132]
W3C HTML seems to not have intended to change "6. Loading Web pages". The section of W3C HTML is identical to WHATWG HTML Standard in theory.
https://www.w3.org/TR/2015/WD-html51-20151008/introduction.html#landscape

However there are number of differences. It can be said that W3C HTML is hard to gather implementation experiences of this section.

https://w3c.github.io/html/browsers.html#browsers
https://html.spec.whatwg.org/multipage/browsers.html

While updating the section requires a lot of specialized resources, the section has relatively small number of audience (browser vendors).

To ease the situation, I would like to propose:
- Dropping "6. Loading Web pages" from W3C HTML
- Referencing corresponding definitions of WHATWG HTML Standard

Note: W3C HTML has already referenced WHATWG HTML Standard.

2.7.5. Transferable objects
https://w3c.github.io/html/infrastructure.html#transferable-objects

> MessagePort

**Comment by plehegar** [comment]
I'm curious about the feedback for this one. The fact is this is one of the least tested part of the HTML spec and one of the wishful thinking part of it...

**Comment by chaals** [comment]
I considered the proposal... specifically, I compared chapter 6 line-by-line to the analogous parts of the LS spec.

While there are a number of differences, many of them are trivial or very easily fixed (assuming there are tests). There are also some parts that are just poorly understood or not properly specified anywhere, as @plehegar noted above.

I'm keeping this open for the next milestone. I plan to fix the simple differences, and create more detailed issues for the things that are substantial, most of which should be fixable within the next milestone or so.

**Comment by chaals** [comment]
See also #277
