### ISSUE TITLE
Logical sizing attributes

### ISSUE THREAD

**Issue by Malvoz** [w3c/html#1333]
Edit, see WICG incubation: https://discourse.wicg.io/t/logical-sizing-attributes-internationalization/2971

<hr>

Should logical sizing attributes [`inline-size | block-size`](https://www.w3.org/TR/css-logical/#dimension-properties) exist in addition to the `width` and `height` html attributes?

**Comment by chaals** [comment]
In my personal opinion, no - although that isn't an opinion I hold very strongly.

I presume the use case is like the one for `width` and `height` to allow preliminary layout to be done before CSS is fully loaded. (If not, please explain what it is, and if it is please confirm).

**Comment by scottaohara** [comment]
I could see those attributes being added for the few element that `width` and `height` haven't been deprecated for.  e.g., `canvas`, `img`, `video` and a few others.

But i'd submit that even the allowed usage on these elements is not always ideal for a responsive web.  Best to [incubate the proposal](https://discourse.wicg.io/) to see if it gains legs.

**Comment by Malvoz** [comment]
@chaals 

> I presume the use case is like the one for width and height to allow preliminary layout to be done before CSS is fully loaded. (If not, please explain what it is, and if it is please confirm).

Yes, that is the use case I had in mind. And because the `width`/`height` attributes aren't being deprecated, I thought moving forward with logical sizing would be the sensible thing to do.

@scottaohara 

> ... even the allowed usage on these elements is not always ideal for a responsive web.

You could set the height/width attributes for your "mobile first"/responsive web and override the set dimensions using CSS at larger viewports.

With that said, this is not something I personally need. Authors using other writing modes may though.

**Comment by prlbr** [comment]
Their [CSS definition](https://www.w3.org/TR/css-logical/#dimension-properties) says,

> These properties correspond to the width and height properties. The mapping depends on the element’s [writing-mode](https://drafts.csswg.org/css-writing-modes-4/#propdef-writing-mode).

The mentioned writing-mode is set by CSS. Does that mean that CSS needs to be loaded to compute these properties correctly? Does the use case still hold then?

**Comment by Malvoz** [comment]
@prlbr 
That is a good point, which makes me wonder why there is no `writing-mode` attribute.

**Comment by chaals** [comment]
Closing - this should be taken up in [WICG](https://discourse.wicg.io) for incubation first

**Comment by Malvoz** [comment]
https://discourse.wicg.io/t/logical-sizing-attributes-internationalization/2971
