### ISSUE TITLE
Clarify that bdi is not needed if there's already an element in place

### ISSUE THREAD

**Issue by r12a** [w3c/html#1339]
https://www.w3.org/TR/html/textlevel-semantics.html#the-bdi-element

Example 125 has an example of how the text would be incorrectly displayed if the `b` element were used rather than `bdi`. That's a useful illustration.

However, many people think that when they use a `b` tag they need to also use a `bdi` tag, eg. 

`<li>User <b><bdi>إيان</bdi></b>: 3 posts.`

Actually, it's better practise to just use a `dir` attribute on the `b` tag, ie.

`<li>User <b dir="auto">إيان</b>: 3 posts.`

I see the former so often, that i think it's worth extending the example to say the above. (`bdi` is really just useful as a short form for `<span dir="auto">`.)

**Comment by r12a** [comment]
```
<ul>
+        <li>User <bdi>jcranmer</bdi>: 12 posts.</li>
+        <li>User <bdi>hober</bdi>: 5 posts.</li>
+        <li>User <b dir="auto">إيان<</b>: 3 posts.</li>
+      </ul>
```
I don't think we've got this right yet, since there's no obvious reason why the last line should have a b tag and the others not (and it would produce an odd looking display).  I would expect all three to be the same:
- either all just use `<bdi>`
- all all use `<b>` with `dir`

Perhaps we're trying to crowd too much into one example.

**Comment by r12a** [comment]
Btw, there's a typo: `<</b>`

**Comment by ntounsi** [comment]
https://www.w3.org/TR/html/textlevel-semantics.html#the-bdi-element
Example 125, I don't see any issue here. 

Figure 2. "If the bdi element were to be replaced by a b element". Why replace `<bdi>`  by `<b>`?  To my understanding, these two elements are orthogonal, and may be applied independently of each other.

Given the need of `<bdi>` in figure 1, if one wishes to emphasis, say, the names in the list, one can use `<b>` in addition to `<bdi>`,  as @r12a noted, 
`<li>User <b><bdi>إيان</bdi></b>: 3 posts.`
Or, beter, as @r12a also noted, 
`<li>User <b dir="auto">إيان</b>: 3 posts.</li>`
for all the three list items.

I see Figure 2 confusing the example 125 (this is an issue). The example is intended to show that `<bdi>`  element "is especially useful when embedding user-generated content with an unknown directionality. "

Possibly, I would add a note or another example to warn, if any, to not confuse `<b>` with `<bdi>`.

**Comment by r12a** [comment]
> Given the need of `<bdi>` in figure 1, if one wishes to emphasis, say, the names in the list, one can use `<b>` in addition to `<bdi>`, as @r12a noted,

@ntounsi that's what i'm recommending should NOT be done. Please reread the initial comment and the proposed fix. My reaction two days ago was to https://github.com/w3c/html/pull/1354.

**Comment by ntounsi** [comment]
May be I'm missing something. But I agree with you in my second reference to your comment.

Also my question was why confuse <b> with <bdi>?

**Comment by ntounsi** [comment]
Actually it is why confuse b with bdi.

**Comment by LJWatson** [comment]
@R12a #1364 adds the ```<b>``` tags as suggested. Shout if there is more still to be done. Thanks.

**Comment by r12a** [comment]
[copying this comment here, since the PR was closed while i was writing this over there]

Ok, it's now consistent wrt tags, but not wrt attributes.  If one knows that the third item needed a dir=auto, one would use a  dir=rtl instead.  I think that the scenario represented here is that the  names of the restaurants and number of stars are obtained from a  database or feed elsewhere and injected into the page using a standard  template. You don't know which line will turn out to be the rtl one, and  that's why you use `dir=auto` for display of all the lines.  (It does no harm to non-rtl text.) 

So, the upshot is that all three lines should have the same dir="auto" markup. 

Does that help?

**Comment by r12a** [comment]
And btw the `<</b>` typo is still there.
