### ISSUE TITLE
bikeshed error when building spec

### ISSUE THREAD

**Issue by iandevlin** [w3c/html#1371]
When I try to build the spec via `bikeshed spec` I get the following error message:
```
LINE 589: Line jumps 2 indent levels:
path: includes/cldr.include
```

I did run `bikeshed update` before  this, and I merged `master` into my fork, so everything is up to date.

Does anyone have an ideas?

**Comment by siusin** [comment]
hi @iandevlin -

This problem didn't present when I ran `bikeshed spec` in our latest version so I'm afraid I don't have a solution for this. If `$ git pull --rebase` / `$ bikeshed update` doesn't help, could you try re-install bikeshed? It works for @chaals last time.

**Comment by chaals** [comment]
My guess is that you have an indent-based syntax error in single-page.bs at that line number...

(I haven't got bikeshed working for me again, and I still have no idea why it seemed to just suddenly stop. But I will remove it and re-install it some time today).

**Comment by iandevlin** [comment]
Thanks for all your comments. I had some time again this morning and did one extra thing that i forgot to do yesterday, and that was to update my bikeshed repository via `git pull`.  Then I ran `bikeshed update` again, and then `bikeshed spec` worked fine.

Should have tried that yesterday, sorry, but perhaps this informations helps someone else who may be having the same issue.

**Comment by iandevlin** [comment]
I know I shouldn't comment on closed issues, but I had a similar problem today, couldn't remember what fixed it the last time, and ended up here again :D
