### ISSUE TITLE
"body ok" of <link> element

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1386]
https://w3c.github.io/html/links.html#body-ok
> The body-ok keywords defined by this specification are dns-prefetch, external, preconnect, prefetch, preload, prerender and stylesheet. 

→ `external` should be removed. Because `rel=external` not be allowed in `<link>` element.

Ref: https://w3c.github.io/html/links.html#ref-for-body-ok%E2%91%A2

→ Row of `external` is destroyed.

**Comment by prlbr** [comment]
Or do it the other way around and add `external` to the table with the descriptions of link types?

By the way, WHATWG has it the other way around than it is in the W3C spec now. `external` is explained in their table with keyword meanings, but it is not allowed on `<link>` elements and is hence not _body-ok_ for `<link>` elements.

In general, `external` isn’t really helpful, is it? On the one hand it can usually be determined from the URI whether a linked resource is external and on the other hand a lack of `rel=external` does not imply that the link is not external. But `external` is a reality nevertheless. I suppose it’s used as styling hook by some software.

**Comment by chaals** [comment]
I agree that `external` isn't obviously helpful, beyond being more explicit. As well as a styling hook, it can be used where content is passed around copy-paste style, so a republished document on an aggregation site like the 'wayback machine' can be clear.
