### ISSUE TITLE
clarify usage of autocomplete attribute on <input type=hidden>

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1389]
https://w3c.github.io/html/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute

> On an input element whose type attribute is in the Hidden state, the autocomplete attribute wears the autofill anchor mantle.

→ This sentence should be removed. Because autocomplete attribute is not allowed in `<input type=hidden>`

> The groups correspond to controls as follows:
> - Text
>     - input elements with a type attribute in the Hidden state
>     - input elements with a type attribute in the Text state
>     - input elements with a type attribute in the Search state
>     - textarea elements
>     - select elements
> - Multiline
>     - input elements with a type attribute in the Hidden state
>     - textarea elements
>     - select elements
> - Password
>     - input elements with a type attribute in the Hidden state
>     - input elements with a type attribute in the Text state
>     - input elements with a type attribute in the Search state
>     - input elements with a type attribute in the Password state
>     - textarea elements
>     - select elements
> - URL
>     - input elements with a type attribute in the Hidden state
>     - input elements with a type attribute in the Text state
>     - input elements with a type attribute in the Search state
>     - input elements with a type attribute in the URL state
>     - textarea elements
>     - select elements
> - E-mail
>     - input elements with a type attribute in the Hidden state
>     - input elements with a type attribute in the Text state
>     - input elements with a type attribute in the Search state
>     - input elements with a type attribute in the E-mail state
>     - textarea elements
>     - select elements
> - Tel
>     - input elements with a type attribute in the Hidden state
>     - input elements with a type attribute in the Text state
>     - input elements with a type attribute in the Search state
>     - input elements with a type attribute in the Telephone state
>     - textarea elements
>     - select elements
> - Numeric
>     - input elements with a type attribute in the Hidden state
>     - input elements with a type attribute in the Text state
>     - input elements with a type attribute in the Search state
>     - input elements with a type attribute in the Number state
>     - textarea elements
>     - select elements
> - Month
>     - input elements with a type attribute in the Hidden state
>     - input elements with a type attribute in the Text state
>     - input elements with a type attribute in the Search state
>     - input elements with a type attribute in the Month state
>     - textarea elements
>     - select elements
> - Date
>     - input elements with a type attribute in the Hidden state
>     - input elements with a type attribute in the Text state
>     - input elements with a type attribute in the Search state
>     - input elements with a type attribute in the Date state
>     - textarea elements
>     - select elements

→ All "input elements with a type attribute in the Hidden state" should be removed. Because autocomplete attribute is not allowed in `<input type=hidden>`

Ref: https://w3c.github.io/html/sec-forms.html#element-statedef-input-hidden
> The following content attributes must not be specified and do not apply to the element: accept, alt, autocapitalize, **autocomplete**, capture, checked, dirname, formaction, formenctype, formmethod, formnovalidate, formtarget, height, list, max, maxlength, min, minlength, multiple, pattern, placeholder, readonly, required, size, src, step, and width.

**Comment by chaals** [comment]
I think the **bug** here is in the list of attributes not allowed.

The current explanation of autocomplete uses a complex indirection with the "autocomplete anchor mantle" - which only applies when the attribute is used on an input in the hidden state - to explain that autocomplete must have not be applied to suggest or change the value of a hidden input.

The fact that an autocomplete is specified *can* be useful metadata for inspection - see for example [WCAG 2.1 checkpoint 1.3.5](https://www.w3.org/TR/WCAG21/#identify-input-purpose) where an **accurate** autocomplete on a hidden input would enable a user agent to explain to remind people what information had been gathered for submission already.

I propose:
* remove the concept of "autocomplete anchor mantle" (and mantles for autocomplete generally). 
* state clearly and simply that `autocomplete` must not be used to change values of a hidden input.
* fix the bug that says `autocomplete` is **not allowed** on hidden elements.

**Comment by StommePoes** [comment]
> The fact that an autocomplete is specified can be useful metadata for inspection - see for example WCAG 2.1 checkpoint 1.3.5 where an accurate autocomplete on a hidden input would enable a user agent to explain to remind people what information had been gathered for submission already.

You mean, people fill in inputs and then those inputs become hidden? I'm trying to think of when a user could or would inspect a hidden element.

I would think having autocomplete gone (or invalid/not working) on hidden elements makes sense for security reasons, and I thought this was why.

**Comment by LJWatson** [comment]
I don't think @mtrootyy was suggesting that hidden field should have autocomplete, only that the following sentence should be removed from the spec because it's untrue: 

>On an input element whose type attribute is in the Hidden state, the autocomplete attribute wears the autofill anchor mantle.>

If a field is hidden it cannot have the autocomplete attribute, and therefore it cannot have the autofill mantle.

**Comment by chaals** [comment]
@LJWatson right. In fact, I think the mantle stuff is an unnecessary complication that we can just remove, as outlined above. I hope to do this in the next few days, if @patricia-gallardo doesn't beat me to it.

**Comment by scottaohara** [comment]
@chaals  & @patricia-gallardo, [created a branch](https://github.com/w3c/html/commit/bf64a84983bd21e8dd33c6975f7ac59b5ef331cd) to help move this issue along.

Feel free to add/edit as you see fit.

**Comment by mtrootyy** [comment]
@scottaohara

https://w3c.github.io/html/sec-forms.html#ref-for-element-statedef-input-hidden%E2%91%A7
→The cell(Hidden, autocomplete) should be fix to "Yes".

**Comment by scottaohara** [comment]
thanks @mtrootyy, figured i didn't get everything in my partial commit.

added this to the branch

**Comment by scottaohara** [comment]
note: revised issue title to align with where the discussion has gone
