### ISSUE TITLE
rel=canonical in <link> element

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1392]
https://w3c.github.io/html/document-metadata.html#ref-for-supported-tokens%E2%91%A0
> The possible supported tokens are alternate, dns-prefetch, icon, next, pingback, preconnect, prefetch, preload, prerender, search, serviceworker, and stylesheet.

→ `canonical` should be added.

**Comment by prlbr** [comment]
That list also lacks `author`, `help`, `license`, `prev`. Maybe it would be better not to have a redundant list there at all and only keep the link to https://w3c.github.io/html/links.html#allowed-keywords-and-their-meanings ? It will be easier to maintain a single place that defines the allowed tokens.

That said, https://w3c.github.io/html/links.html#allowed-keywords-and-their-meanings does not contain `canonical` either, so should it be added there?

**Comment by mtrootyy** [comment]
[commit/07e9d9aaeb52920e9cd993c9d04c5996a30219c0](https://github.com/w3c/html/commit/07e9d9aaeb52920e9cd993c9d04c5996a30219c0)（committed on 7 Apr 2017）
→`canonical` was added to "4.2.4. The link element" section.


[commit/4e4d714c6560022b647aea1b8ab435a65bc27875](https://github.com/w3c/html/commit/4e4d714c6560022b647aea1b8ab435a65bc27875) （committed on 19 May 2017）
→`canonical` was removed from "4.2.4. The link element" section.


It is considered to be a mistake that `canonical` was removed in 19 May 2017.
Therefore `canonical` should be re-added.

**Comment by Malvoz** [comment]
Remove `serviceworker` from that list? (see https://github.com/w3c/html/issues/821).

Add [`manifest`](https://www.w3.org/TR/appmanifest/#using-a-link-element-to-link-to-a-manifest).

**Comment by Malvoz** [comment]
@scottaohara 



https://w3c.github.io/html/links.html#allowed-keywords-and-their-meanings does not include [`manifest`](https://www.w3.org/TR/appmanifest/#using-a-link-element-to-link-to-a-manifest) as noted in my comment above. Was there a decision not to add it?

**Comment by scottaohara** [comment]
Hi @Malvoz,
No decision was made, but it fell off my radar as I was focused on the topic of the issue, and didn't address other add-on comments.

I will open a new issue to reference your comment and an additional request that was made in the PR for this issue.

**Comment by chaals** [comment]
(Note, #1506 is the issue mentioned).
