### ISSUE TITLE
main cannot be a child of address

### ISSUE THREAD

**Issue by scottaohara** [w3c/html#1397]
The content model for `address` states:
>Flow content, but with no heading content descendants, no sectioning content descendants, and no `header`, `footer`, or `address` element descendants. 

However `main` is also an invalid child of `address`.

**Comment by slemini2033** [comment]
@scottaohara are you sure it's not a mistake about main element? 
> The main element represents the dominant contents of the document.

so main element could be child of any tag

**Comment by scottaohara** [comment]
No, it cannot be a child of any tag.

But, per this specific issue, that doesn’t mean that the reverse is untrue. E.g. if the primary content of a document is an address 
<code>&lt;main>&lt;address>...&lt;/address>&lt;/main></code>would be appropriate.
