### ISSUE TITLE
Inbound link 404

### ISSUE THREAD

**Issue by alexpls** [w3c/html#143]
Hi, the w3c page https://www.w3.org/TR/html-srcset/ has a prominent link to http://www.w3.org/html/wg/drafts/html/master/embedded-content.html#attr-img-srcset, which at this stage returns a 404:

![broken-link](https://cloud.githubusercontent.com/assets/301630/13566991/2722b388-e4a4-11e5-90de-7e1ee5912d53.jpg)

Since the target page is built from this repo I figure this is the best place to raise the 404 issue? If not please delete it!

**Comment by plehegar** [comment]
This is the right place to raise the issue. The switch to bikeshed did a rewrite of the links and the multipage version uses the IDs of the sections to generate filenames. I think we should attempt to match the filenames but the fragment would remain broken in any case. We'll have to update the link in html-srcset.

**Comment by plehegar** [comment]
I sent a request to update the link to
 http://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset

**Comment by plehegar** [comment]
https://www.w3.org/TR/html-srcset/ got fixed.
