### ISSUE TITLE
No description of the attribute method

### ISSUE THREAD

**Issue by slemini2033** [w3c/html#1447]
No description of the attribute **method** of form element what is and how works is:
GET
POST
And when should use GET and when POST and difference between them.

**Comment by scottaohara** [comment]
Hi @slemini2033 

Here's the section on [method and formmethod](http://w3c.github.io/html/sec-forms.html#element-attrdef-form-method) and information/examples about the values `get`, `post` and `dialog` are outlined there.

Is there something beyond the information provided in this section that you were wondering about, or feel could be expanded on?

Thanks

**Comment by slemini2033** [comment]
@scottaohara hi. yes, but what is **GET** and **POST** state there is not describe. There should be at least a minimal descriptionat about HTTP GET and POST method: GET for getting document and POST for sending data. And how it works together with **enctype** attrubite it should be described too.

**Comment by brothersprod** [comment]
> On May 21, 2018, at 3:10 AM, slemini2033 <notifications@github.com> wrote:
> 
(#1447)
