### ISSUE TITLE
clarify text around <label>

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#145]
moved from: 
https://www.w3.org/Bugs/Public/show_bug.cgi?id=13553

> The label element's exact default presentation and behavior, in particular what its behavior might be, if anything, should match the platform's label behavior. The activation behavior of a label element for events targetted at interactive content descendants of a label element, and any descendants of those interactive content descendants, must be to do nothing.
> 
> The second sentence here seems to contradict the first and the following example.  This text is in the editor's draft.  The second sentence does not appear in the last call draft, and the meaning is more clear without it.

relates to http://w3c.github.io/html/sec-forms.html#the-label-element

**Comment by chaals** [comment]
The text was already changed in #113

**Comment by stevefaulkner** [comment]
thanks!
