### ISSUE TITLE
Is (h1, h2, h3, h4, h5, h6) content model the Phrasing content?

### ISSUE THREAD

**Issue by ishendyweb** [w3c/html#1460]
This is my first to find something that I consider as a mistake in W3C specifications. Am I wrong? is there something I am missing? It clearly says that the heading elements are of the Phrasing content!

![screenshot-www w3 org-2018 05 29-17-01-16](https://user-images.githubusercontent.com/10582418/40667358-4cb18e8c-6362-11e8-9252-5d0bf2aac33a.png)

**Comment by stevefaulkner** [comment]
@ishendyweb headings are not phrasing content, what the [content model](http://w3c.github.io/html/dom.html#content-model) specifies is what a particular element can contain. In the case of headings, they can only contain [phrasing content](http://w3c.github.io/html/dom.html#phrasing-content-2)
