### ISSUE TITLE
Ambiguity in section 8.1.4 Character References

### ISSUE THREAD

**Issue by douglasheld** [w3c/html#1461]
The draft says:
> The numeric character reference forms described above are allowed to reference any Unicode code point other than U+0000, U+000D, permanently undefined Unicode characters (noncharacters), surrogates (U+D800—U+DFFF), and control characters other than space characters.

This section should be reworded for clarity. Is it `any A other than ( B, C, D, E, F that are not G)` or is it `(any A other than B) ∪ C ∪ D ∪ E ∪ F that are not G` ?

I assumed the former, until I got to "...other than space characters" where U+000D Carriage Return is already classified as a space character, and I got confused.

**Comment by edent** [comment]
Thanks Douglas, that's a great question.

https://w3c.github.io/html/syntax.html#character-references

I think this would be better expressed as a list. So:

> The numeric character reference forms described above are allowed to reference any Unicode code point other than:
> * U+0000 
> * U+000D
> * permanently undefined Unicode characters (noncharacters)
> * surrogates (U+D800—U+DFFF)
> * control characters other than space characters

Does that make it clearer?  For example `&#12;` is allowed because it is a space character within the control characters.

Hmmm. Perhaps it might be better to explicitly list the control characters which are unacceptable?

**Comment by douglasheld** [comment]
Since there are 65 control characters, it would be better to list the allowable control characters. Among the 65 control characters with General Category=Cc in https://www.unicode.org/Public/10.0.0/ucd/UnicodeData.txt there are only five space characters as defined in the HTML spec (ref: https://w3c.github.io/html/infrastructure.html#space-characters). 

If `(other than (other than X))` means `X is allowed` then that should imply a whitelist of only three control characters, because U+0020 is not even a control character. You **_could_** then simplify the text as:

> The numeric character reference forms described above are allowed to reference any Unicode code point other than:
> - control characters, with the exception of U+0009 CHARACTER TABULATION (tab), U+000A LINE FEED (LF), and U+000C FORM FEED (FF)
> - permanently undefined Unicode characters (noncharacters)
> - surrogates (U+D800—U+DFFF)

From a security design perspective, I think the draft is asking for future trouble by attempting to blacklist certain characters from expression though. It would be much more powerful to specify that the numeric character reference can only be used for:

- Code points with the General Category beginning with L, M, N, P, S, Z _(etc.)_
- The additional control characters U+0009 CHARACTER TABULATION (tab), U+000A LINE FEED (LF), and U+000C FORM FEED (FF)

(or whatever is the correct whitelist of control characters)

Maybe it's the subject of a different thread but I do have to wonder what is the reasoning behind allowing form feeds to be expressed in HTML, while disallowing carriage returns?

**Comment by edent** [comment]
How does this read?

The numeric character reference forms described above are allowed to reference any Unicode code point but not:
* permanently undefined Unicode characters ([noncharacters](https://www.unicode.org/faq/private_use.html#nonchar1))
* [surrogates](https://unicode.org/glossary/#high_surrogate_code_point) (U+D800—U+DFFF)
* [control codes](https://unicode.org/glossary/#control_codes)
  * the following control codes are allowed - [space characters](https://w3c.github.io/html/infrastructure.html#space-characters) :
     * U+0009 CHARACTER TABULATION (␉)
     * U+000A LINE FEED (␊)
     * U+000C FORM FEED (␌)
     *  U+000D CARRIAGE RETURN (␍)
     *  U+0020 SPACE (␠)

I agree that we ought to write a formal whitelist. @douglasheld are you able to do that?

**Comment by douglasheld** [comment]
I really think we should go back to the original authors who specified this, and find out whether their original intention is reflected in what we have written. Like I said, there is no clear justification for allowing certain control characters to be expressed numerically and others, not.

Here is a formal whitelist based on interpreting the current reading:

> The numeric character reference forms described above are allowed to reference any Unicode code point but not:
> permanently undefined Unicode characters (noncharacters)
> surrogates (U+D800—U+DFFF)
> control codes, with the exception of the following numeric character references which are allowed:
> &amp;#x9; or &amp;#9; (Representing U+0009 CHARACTER TABULATION (␉) )
> &amp;#xA; or &amp;#10; (Representing U+000A LINE FEED (␊) )
> &amp;#xC; or &amp;#12; (Representing U+000C FORM FEED (␌) )
> (You have included CR but it is supposed to be excluded)
> (You have included SPACE but it is not a control character and is already allowed)

**Comment by edent** [comment]
Ah, my reason for `&#13;` is that it is listed as a space character in https://w3c.github.io/html/infrastructure.html#space-characters - but you're right, it *is* invalid.

I've also seen that U+007F—U+009F are also to be excluded.
