### ISSUE TITLE
Title Attribute 

### ISSUE THREAD

**Issue by devarshipant** [w3c/html#1463]
[3.2.9.1 warning says](https://w3c.github.io/html/dom.html#the-title-attribute) --

"Relying on the title attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g., requiring a pointing device such as a mouse to cause a tooltip to appear, which excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet)."

IE 11 / Win 10 renders the title as a visible tooltip on keyboard focus besides mouse hover. The implementation is helpful for keyboard users, but Chrome and Firefox do not support it. Should the warning mention that the title should (or not) appear as a tooltip on keyboard focus?

**Comment by scottaohara** [comment]
I don't think this needs to be called out at this time, as doing so would cover keyboard focus, but it would not cover other manners in which a user might be interacting with an element (e.g. by touch, or potentially voice), nor would it take into account user agents that expose the title in a manner that is not a "tooltip", e.g. images with titles can have that content exposed when a user performs a long press on an image, causing an action sheet to load in iOS + Safari.

There are other issues that we might then want to cover with tooltips as well, but that would potentially create a verbose warning, which is pretty straight forward in its present state.

Thank you.
