### ISSUE TITLE
event 'mousewheel' type is no longer in UIEvents

### ISSUE THREAD

**Issue by plehegar** [w3c/html#148]
Not part of
 https://w3c.github.io/uievents/#event-types-list

**Comment by garykac** [comment]
It was replaced with `wheel` in 2010. The last UIEvents spec that mentions `wheelevent` is:
https://www.w3.org/TR/2010/WD-DOM-Level-3-Events-20100907/

**Comment by plehegar** [comment]
Will wait for #150 to move before adding a PR for this.

**Comment by travisleithead** [comment]
Fixed by #403.
