### ISSUE TITLE
Link to https://w3c.github.io/html/ from project description

### ISSUE THREAD

**Issue by tripu** [w3c/html#15]
Projects using `gh-pages` usually put that URL [at the top of the front page](https://github.com/w3c/html/#repo_homepage).
It just saves a few seconds to anyone visiting who wants to take a look at the generated document :)

**Comment by chaals** [comment]
Your Pull Request would have been welcome ;)

Anyway, agreed. https://github.com/w3c/html/commit/095a83aa711240f50430eb53172157dd968e19a4 puts it in the README and I'll add it to the description.

**Comment by tripu** [comment]
Ah, the README too, @chaals. Thanks :)

But my suggestion isn't pull-request-able: I mean the two project fields (_description_ and _website_) that you see at the top of the main page of the repo (follow my link above)&hellip;

I could have done that myself, but I wouldn't dare without asking the maintainers of the repo first! :)

**Comment by tripu** [comment]
Description and URL added to the front page after talking with @chaals.
