### ISSUE TITLE
Add <inputgroup> element

### ISSUE THREAD

**Issue by desandro** [w3c/html#1508]
I propose the `<inputgroup>` element be added to the HTML spec.

`<inputgroup>` functions as a parent wrapper element to group together descendant radio or checkbox inputs, rather than grouping by `name` attribute value.

``` html
<!-- current: use name attribute to group radio inputs -->
<label><input type="radio" name="flavor">Chocolate</label>
<label><input type="radio" name="flavor">Vanilla</label>
<label><input type="radio" name="flavor">Strawberry</label>
<label><input type="radio" name="flavor">Coffee</label>

<!-- proposed: use inputgroup parent element -->
<inputgroup name="flavor">
  <label><input type="radio">Chocolate</label>
  <label><input type="radio">Vanilla</label>
  <label><input type="radio">Strawberry</label>
  <label><input type="radio">Coffee</label>
</inputgroup>
```

Using a parent-child structure to group together radio inputs is more legible and easier to understand. At a glance you can see that `input`s within `inputgroup` act together as a whole. The structure is similar to `<select>` and `<option>`.
  
``` html
<select name="flavor">
  <option>Chocolate</option>
  <option>Vanilla</option>
  <option>Strawberry</option>
  <option>Coffee</option>
</select>
```

95% of the radio inputs I code follow this structure. Writing `name` for each one feels counter-intuitive for HTML's tree model.  After a decade of writing HTML, I still have to look up how to group together radio inputs ("Is it by `id`?").

---

I haven't thought out all the edge cases (What happens to a `<inputgroup>` within a `<inputgroup>`?). But I think `<inputgroup>` would be a welcome addition to the spec.

**Comment by jgarber623** [comment]
@desandro Interesting proposal, Dave!

A couple of thoughts/questions:

- The `<radiogroup>` element is [actually a thing in XUL](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/radiogroup) (so there's some precedent for this proposal).
- There was _almost_ [a `<command>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/command) with a `radiogroup` attribute, but it didn't make the cut.
- How would user agents that don't support `<inputgroup>` properly handle a series of radio inputs lacking a `name` attribute and value? The proposal as-is might not degrade gracefully.

**Comment by Comandeer** [comment]
There is no need to introduce new element as we already have `fieldset`. Your example could be written as:

```html
<fieldset name="flavor">
	<label><input type="radio">Chocolate</label>
	<label><input type="radio">Vanilla</label>
	<label><input type="radio">Strawberry</label>
	<label><input type="radio">Coffee</label>
</fieldset>
```

However currently `fieldset[name]` is not used to group radio buttons and it's not considered by form submitting algorithm. So the proposal could be simplified to "change behaviour of `[name]` attribute on `fieldset` element":

> If elements inside `fieldset` don't have their own `[name]` attributes, use the one of parent's `fieldset` element.

Yet there are two big issues with that:

1. This behaviour makes sense only for radio buttons and – in some cases – checkboxes. Every other field will remain the same. It'd be totally inconsistent.
2. Such behaviour won't degrade gracefully.

**Comment by desandro** [comment]
Yeah, I'd be open to adding my requested functionality to `fieldset`. If it's an easier path to shipping the general feature of "use a parent element to group together radio inputs", then I'm all for it.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
