### ISSUE TITLE
fix "Contexts in which this element can be used:" of <source> element

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1510]
https://w3c.github.io/html/semantics-embedded-content.html#the-source-element
> Contexts in which this element can be used:
> - As a child of a picture element, before the img element. 
> - As a child of a media element, before any flow content or track elements. 

↓
The above should be fixed following;
> Contexts in which this element can be used:
> - As a child of a picture element, before the img element. 
> - As a child of a media element **that doesn't have a src attribute**, before any flow content or track elements. 

Ref: https://w3c.github.io/html/semantics-embedded-content.html#the-audio-element
> Content model:
> - If the element has a src attribute: zero or more track elements, then transparent, but with no media element descendants. 
> - If the element **does not have a src attribute**: zero or more **source elements**, then zero or more track elements, then transparent, but with no media element descendants. 

Ref: https://w3c.github.io/html/semantics-embedded-content.html#the-video-element
> Content model:
> - If the element has a src attribute: zero or more track elements, then transparent, but with no media element descendants. 
> - If the element **does not have a src attribute**: zero or more **source elements**, then zero or more track elements, then transparent, but with no media element descendants.

**Comment by siusin** [comment]
I'm curious about the background for this change...

I did a simple test and it seems the source elements can be rendered properly as a child of the media element with a src attribute in Chrome and Firefox:

```
<video controls
    width="300"
    height="200"
    muted="true" 
    src="https://interactive-examples.mdn.mozilla.net/media/examples/stream_of_water.webm">
    <source src="https://interactive-examples.mdn.mozilla.net/media/examples/stream_of_water.mp4"
            type="video/mp4">
    This browser does not support the HTML5 video element.
</video>
```

Let me know if I misunderstand the problem here. @scottaohara

**Comment by scottaohara** [comment]
Hi @siusin,
testing with an unsupported format in the `src`, the fallback `<source>` isn't loaded in firefox or chrome.

Running the code snippet through https://validator.w3.org/nu/ returns an error when `source` is a child element when a `src` is set

**Comment by siusin** [comment]
Ok, then it makes sense to me. Thanks @scottaohara !
