### ISSUE TITLE
<dialog> element should trap focus

### ISSUE THREAD

**Issue by Dan503** [w3c/html#1514]
This is a major accessibility issue with the `<dialog>` element in the HTML spec.

The W3C [officially endorses focus trapping inside of `<dialog>` elements](https://www.w3.org/TR/wai-aria-practices/#dialog_modal) as a best practice for accessibility. However, in the HTML spec for the `<dialog>` element, it makes no mention of needing to focus trap inside dialog elements.

Focus trapping is complicated for authors to implement without the help of plugins specifically designed for this task like [focus-trap](https://github.com/davidtheclark/focus-trap). Relying on author js is also less performant than what a browser user agent could do.

Another point is that the `<dialog>` element makes it impossible for screen reader users to navigate out of the dialog while it is open (a good thing). A screen reader user navigating by using the [tab] key _is_ able to escape the dialog in the current implementation though. This would be a very confusing experience for screen reader users.

**Comment by Dan503** [comment]
This is somewhat related to issue https://github.com/w3c/html/issues/773

**Comment by stevefaulkner** [comment]
@Dan503 The ARIA practices document you reference pertains to modal dialogs. The HTML spec defines a showModal() method:

> The showModal() method of the HTMLDialogElement interface displays the dialog as a modal, over the top of any other dialogs that might be present. It displays into the top layer, along with a ::backdrop pseudo-element. Interaction outside the dialog is blocked and the content outside it is rendered inert.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal

**Comment by Dan503** [comment]
Oh awesome!

I'll test it out before I close the issue.

I've only ever seen people use the `.open()` method. I didn't know about `.showModal()` 😀

**Comment by stevefaulkner** [comment]
@Dan503 note in the chrome implementation the browser address bar is in the tab order, same as for JS alert() type dialogs
