### ISSUE TITLE
No explain what for headers attribute of td element [was: Issue #1359]

### ISSUE THREAD

**Issue by siusin** [w3c/html#1527]
Re-file [Issue #1359](https://api.github.com/repos/w3c/html/issues/1359) from [programmer3000](https://github.com/programmer3000).

from [programmer3000](https://github.com/programmer3000):

> No explain what is `headers` attribute of `<td>` element
> https://www.w3.org/TR/html53/tabular-data.html#elementdef-td

**Comment by scottaohara** [comment]
this was closed by [PR 1427](https://github.com/w3c/html/pull/1427)

**Comment by siusin** [comment]
Thanks @scottaohara !
