### ISSUE TITLE
HTML no described of pingback, preload and serviseworker attributes [was: Issue #1344]

### ISSUE THREAD

**Issue by siusin** [w3c/html#1538]
Re-file [Issue #1344](https://api.github.com/repos/w3c/html/issues/1344) from [programmer3000](https://github.com/programmer3000).

from [programmer3000](https://github.com/programmer3000):

> HTML specification have no description of `pingback`, `preload` and `serviseworker`  attribute.
> https://www.w3.org/TR/html53/document-metadata.html#element-attrdef-link-rel
> Also inside table placed 2 same `prerender` attribute
> https://www.w3.org/TR/html53/links.html#body-ok
> And what is body-ok and body-not-ok? Why body-not-ok `alternate`, `author`, `bookmark`, `dns-prefetch`, `help`, `icon`, `next`, `nofollow`, `noopener`, `noreferrer`, `prev`, `search` and  `tag` attributes?

**Comment by scottaohara** [comment]
[Related issue 1506](https://github.com/w3c/html/issues/1506)

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
