### ISSUE TITLE
srcObject MediaProvider for media element has been lost

### ISSUE THREAD

**Issue by stefhak** [w3c/html#154]
It is missing in the latest draft, but present in 
https://www.w3.org/TR/2015/WD-html51-20151008/semantics.html#htmlmediaelement
As the "Media Capture and Streams" specification relies on srcObject it should be re-inserted.

**Comment by dontcallmedom** [comment]
See also https://lists.w3.org/Archives/Public/public-html/2016Mar/0011.html and follow up thread.

**Comment by travisleithead** [comment]
Will add srcObject, MediaProvider and required dependencies.

**Comment by travisleithead** [comment]
I think I got all the tendrils (which were surprisingly few...?) @dontcallmedom feel free to take a look.
