### ISSUE TITLE
Add call to new MediaSource detachment algorithm for Media Elements

### ISSUE THREAD

**Issue by jdsmith3000** [w3c/html#155]
We have a pull request in to change how a MediaSource is detached in MSE.  The [steps for detachment](http://w3c.github.io/media-source/#mediasource-detach) in the current spec require doing it for a single condition (media element transition to NETWORK_EMPTY).  We have two active bugs requesting this be changed to an algorithm that can be called generally from HTML.
- [MSE Issue #17: Should the media element load algorithm trigger detaching from a media element?](https://github.com/w3c/media-source/issues/17)
- [MSE Issue #18:  Should fetch algorithm failure trigger detaching from a media element?](https://github.com/w3c/media-source/issues/18)

The issues identify gaps where the MediaSource should be detached, but isn't per the current spec.  

[MSE Pull Request #56](https://github.com/w3c/media-source/pull/56) removes the NETWORK_EMPTY condition, and defines a general purpose "**Detaching from a media element**" algorithm.  This change was requested for WHATWG/HTML, and so creates a need to reference the detachment criteria in W3C/HTML if the PR is to be approved.  It would require referencing [Detaching from a media element](https://w3c.github.io/media-source/#mediasource-detach) and calling it when the Media Element is being reset.  A call after step 4.2 in **media element load algorithm** seems appropriate.  This would encompass the previous case involving transition to NETWORK_EMPTY.

Is this possible?

**Comment by chaals** [comment]
Fixed by #157

**Comment by wolenetz** [comment]
@travisleithead @plehegar We ideally need more detachment call-outs. Please see the specifics documented in https://github.com/w3c/media-source/issues/18#issuecomment-221938304. MSE spec has a non-normative note which unblocks it for V1. Can this be done before you lock down for HTML 5.1?
