### ISSUE TITLE
Validator gives an error for header element  [was: Issue #1221]

### ISSUE THREAD

**Issue by siusin** [w3c/html#1567]
Re-file [Issue #1221](https://api.github.com/repos/w3c/html/issues/1221) from [programmer3000](https://github.com/programmer3000).

from [programmer3000](https://github.com/programmer3000):

> **Content model for `<header>` element not valid for validator w3c.**
> \"Flow content, but with no main element descendants, or header, footer elements that are not descendants of sectioning content which is a descendant of the header.\" not valid for w3c validator when `<header>` put inside `<header>` even if it \"descendants of sectioning content\".\r\nSo **for clear** that **mistake** most **right would be rewrite content model** to like this: \"**Content model: Flow content, but with no main, header or footer elements descendants**\"
> If you want to check you can go to link https://www.w3.org/TR/html/sections.html#the-header-element  copy \"Example 20\" and paste in validator it will return error: \"The element header must not appear as a descendant of the header element.\"
> I think it's very bad idea let `<header>` placed incide `<header>` (same for `<footer>` inside `<footer>`). Because `<header>` element represents introductory content. And if document will have two `<header>`, document will more unreadable with strange semantic structure.

from [chaals](https://github.com/chaals):

> @programmer3000 this structure was allowed - although it is probably usually a bad idea - in resolving #273. I think the use case that makes the most sense is when mixing components together, so a component which contains a `header` is OK to be inside a `header`.
> Unless we want to revert that change, this should be a bug on the validator rather than the spec.
> ping @stevefaulkner

from [programmer3000](https://github.com/programmer3000):

> @chaals  Yes, now it's bug of validator. But main problem in the structure.
> It very bad idea let be ok header inside header. So possible let everytag be everywhere and what will be in the end? - different understanding of the structure by different developers. Such situation now - too much topics about structure - because structure is not explicitly.

from [chaals](https://github.com/chaals):

> @programmer3000 we will look at the issue. If something matches a real-world need, and works, unless we have a better solution and a clear explanation of how to change what people do, we will probably make it valid in the spec.
> We might add advice saying \"don't do this if you don't have to\", and explanations of why. It is probably a good idea to add such explanations in the case of `header` inside a `header`.
> I suggest the resolution of this should be to explain how a `header` inside a `header` might appear (e.g. by including components made separately in a template), and why it is probably not a good idea in cases where you can avoid it. That would be editorial and we can probably get it done in the current milestone.

from [programmer3000](https://github.com/programmer3000):

> @chaals  I think it no good idea \"header inside a header might appear (e.g. by including components made separately in a template)\" - so can everytag be inside everytag \"(e.g. by including components made separately in a template)\". 
> I think it must be phrase like: \"Possible, but not recommend use `<header>` inside `<header>` even if descendant\" , because it born implicit structure\" and `<header>` represents introductory content for full page and not for only one element - same for `<footer>`.

**Comment by scottaohara** [comment]
hey, @sideshowbarker.  @chaals mentioned we should ping you regarding why the HTML validator isn't passing the following markup, per this issue / the resolution of [#273](https://github.com/w3c/html/issues/273).

```
<header>
  ...
  <section>
     <header>...</header>
  </section>
</header>
```

Appreciate any thoughts on this.  Thank you.

**Comment by sideshowbarker** [comment]
> hey, @sideshowbarker.  @chaals mentioned we should ping you regarding why the HTML validator isn't passing the following markup, per this issue / the resolution of [#273](https://github.com/w3c/html/issues/273)

I wasn’t aware of it. You probably want to raise an issue for it at https://github.com/validator/validator/

**Comment by scottaohara** [comment]
thank you!

**update:**
after talking with chaals, i'm going to run a test on how common this sort of `header` nesting is used in the wild.  Results will determine if we move forward with a validator issue and updating editorial of the spec. vs other action.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
