### ISSUE TITLE
picture element: Fallback to src of img element, if srcset of source element can not be loaded.

### ISSUE THREAD

**Issue by Meteor0id** [w3c/html#1577]
```
<picture>
  <source srcset="https://example.com/does-not-exist.jpg" />
  <img src="https://upload.wikimedia.org/wikipedia/commons/e/ed/W3C%C2%AE_Icon.svg" alt="This is alt text instead of a fallback image." />
</picture>
```

What I was hoping to see was a fallback to the img element and loading its src, when the source element could not be loaded.
Instead the img src is not loaded either, and the browser (I tested this with Firefox) immidialty skips to the alt text.

**Would it be possible to clearly state in the html draft that this sort of fallback should be supported as part of the picture element?**

Ideally, the browser 
1. tries each source element in sequence, loading the first image which can be loaded.
2. If none can be loaded, it attempts to load the img src.
3. If the img src can not be loaded either, it displays the alt text.

**Comment by brothersprod** [comment]
<picture>
  <source srcset="https://example.com/does-not-exist.jpg" />
  <img src="https://upload.wikimedia.org/wikipedia/commons/e/ed/W3C%C2%AE_Icon.svg" alt="This is alt text instead of a fallback image." />
</picture>

**Comment by Meteor0id** [comment]
@brothersprod please put that in a code snippet, in its current form your reply is not helpful.

**Comment by chaals** [comment]
@Meteor0id actually it is really useful as a test. And it works for me as expected in Firefox as well as other browsers. I can only conclude that there was some issue with loading the image when you ran the test, that caused the alt text to be shown instead.

The thing you are asking for is described in the text of the picture element:

> The user agent first tries to match an image source contained within the source attribute and use that, but if none is found, it falls back to what is contained within the img element, which must be present.

Do you think we need to make a change to this text?

**Comment by Meteor0id** [comment]
That text does seem to cover most of it, I will test it again, see if I missed anything.

But now that you ask, it does not state the sequential attempts on each following source element. If there are other source elements left which do not have a media querry preventing it from being shown in the client, it should try those one by one before arriving at the img element.

**Comment by chaals** [comment]
I think the rest of what you are asking for is covered in the section on the `source` element.

Thank you for the review - if there is something missing or unclear, please note it :)
