### ISSUE TITLE
Typo in section 1.4

### ISSUE THREAD

**Issue by cinephile85** [w3c/html#1593]
The last sentence in the second to last paragraph of section 1.4. History reads, "The W3C HTML editors have also added patches that resulted from discussions and decisions made by the W3C Web Platform WG as well a bug fixes from bugs not shared by the WHATWG." I believe it should read, "The W3C HTML editors have also added patches that resulted from discussions and decisions made by the W3C Web Platform WG as well as bug fixes from bugs not shared by the WHATWG."

**Comment by scottaohara** [comment]
Thank you!
