### ISSUE TITLE
fix "Contexts in which this element can be used:" of <table> element

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1594]
https://w3c.github.io/html/tabular-data.html#the-table-element
> Contexts in which this element can be used:
> - Where flow content is expected.

↓
The above should be fixed following;
> Contexts in which this element can be used:
> - Where flow content is expected, **but with no caption element ancestors**.

Ref: https://w3c.github.io/html/tabular-data.html#the-caption-element
> Content model:
> - Flow content, but with no main, or **table** element descendants.

**Comment by RizBizKits** [comment]
I'll get this fixed!
