### ISSUE TITLE
fix "Contexts in which this element can be used:" of <video> and <audio> element

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1595]
https://w3c.github.io/html/semantics-embedded-content.html#the-video-element
> Contexts in which this element can be used:
> - Where embedded content is expected.

↓
The above should be fixed following;
> Contexts in which this element can be used:
> - Where embedded content is expected, **but with no media element ancestors**.

https://w3c.github.io/html/semantics-embedded-content.html#the-audio-element
> Contexts in which this element can be used:
> - Where embedded content is expected.

↓
The above should be fixed following;
> Contexts in which this element can be used:
> - Where embedded content is expected, **but with no media element ancestors**.

　
　
　
Ref: https://w3c.github.io/html/semantics-embedded-content.html#the-video-element
> Content model:
> - If the element has a src attribute: zero or more track elements, then transparent, **but with no media element descendants**.
> - If the element does not have a src attribute: zero or more source elements, then zero or more track elements, then transparent, **but with no media element descendants**.

Ref: https://w3c.github.io/html/semantics-embedded-content.html#the-audio-element
> Content model:
> - If the element has a src attribute: zero or more track elements, then transparent, **but with no media element descendants**.
> - If the element does not have a src attribute: zero or more source elements, then zero or more track elements, then transparent, **but with no media element descendants**.

**Comment by carolgilabert** [comment]
I can look into this 🙋‍♀️
