### ISSUE TITLE
No tutorial

### ISSUE THREAD

**Issue by Lancer4** [w3c/html#1597]
Hi all,

I want to learn HTML 5.2. After beginning to learn it, the specification indicated I am not the audience it is intended for and to use a more approachable tutorial.

The product seems to be broken as there is no tutorial for HTML 5.2. Please fix this as I am keen to learn the product.

Thanks

**Comment by siusin** [comment]
Hi @Lancer4 ! Lots of people from the community have been helping to make the spec more readable, but if you are learning HTML from scratch, MDN may be a better place, as it provides more detail information about the usage of each elements. There are also a few HTML courses on [W3Cx](https://www.edx.org/school/w3cx). Hope it helps.

**Comment by Lancer4** [comment]
Thanks for your information siusin. Its good to here a tutorial is being made.

I do know there are plenty of third party tutorials, but I like to learn from official documentation as that way you know you are learning the right way for sure. :)
