### ISSUE TITLE
Why is the force attribute required in the Bikeshed command?

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/html#16]
We al like to use the force, but is it really necessary to bikeshed the spec with it? If there are no issues, `bikeshed spec` should work too, right?

**Comment by adrianba** [comment]
There are currently two errors because of an [issue with PutForwards](https://github.com/tabatkins/bikeshed/issues/559).

**Comment by tabatkins** [comment]
And that's fixed now. Let me know if there's anything left.

**Comment by ZoeBijl** [comment]
No that seems to have done it, thank you!
