### ISSUE TITLE
Create a wrapper for `dd`/`dt` elements that's valid inside a `dl`

### ISSUE THREAD

**Issue by calebdwilliams** [w3c/html#1604]
I looked through open and closed issues, but haven't seen this proposal which honestly surprises me, so if this is a duplicate, I apologize.

I believe there should be a new valid child for the `dl` element that could serve as a wrapper for `dd` and `dt` elements. I would propose something like `dg` for definition group. That would allow developers to group terms and definitions and allow for styling those groups easier.

**Comment by scottaohara** [comment]
Hi @calebdwilliams 
The `div` element can be used to wrap these elements.  
> The div element may be used as a child of the dl element (as a way to organize term-description groups consisting of one or more dt elements, and one or more dd elements).

Or were you specifically looking for a `dg` element to provide additional semantics?

**Comment by calebdwilliams** [comment]
I think there is added value in adding something like `dg` for semantic purposes, but the primary motivation was for styling.

**Comment by LJWatson** [comment]
The [```<div>``` element](https://www.w3.org/TR/html53/grouping-content.html#the-dl-element) is already permitted for use in the way you describe. Does that meet your use case?

**Comment by calebdwilliams** [comment]
That meets part of it, for sure, I didn't realize that HTML5.2 had allowed `div` to be a child of `dl`. As far as styling is concerned, it definitely does meet my use case, however, it might behoove us to add some semantics to that division.

**Comment by scottaohara** [comment]
A `dt` + `dd` (one or more) already form a term description group.  From the spec:
> Each term-description group consists of one or more terms (represented by dt elements) and one or more descriptions (represented by dd elements.

With that in mind, what additional semantics do you think would necessitate the adding of a new element, @calebdwilliams?

**Comment by calebdwilliams** [comment]
With that in mind, the only benefit would be making the relationship more explicit. If you don't believe that to be a worthwhile cause, that's fine, I can close this request although it does make more sense to me as a grouping mechanism than a `<div>`. It could also give you the ability to identify multiple `dd` elements as almost list items that could be styled as a group. That's just spitballing though and I don't know how widespread that need and/or desire is.

**Comment by chaals** [comment]
@calebdwilliams said

> ...It could also give you the ability to identify multiple `dd` elements as almost list items that could be styled as a group.

It's sound spitballing, and I think the case is pretty common, but I think having the `div` there means that you can do that, no?

Creating a new element really is a big deal, so expect a lot of reluctance and requests for **really** good justification if you propose it. That's not to say it never happens...

**Comment by scottaohara** [comment]
Agree with @chaals.  my comment wasn't to imply that it's not a bad idea, but that it needs to be fleshed out more.

If you'd like to incubate the idea further, you should post it over at [WICG](https://discourse.wicg.io/).

**Comment by calebdwilliams** [comment]
Thanks all. I’ll consider moving this over there. Should I close this issue in the mean time?

**Comment by scottaohara** [comment]
I'll close it for now.  Thanks
