### ISSUE TITLE
Thanks guys.

### ISSUE THREAD

**Issue by alove1008** [w3c/html#1628]
Your website was very misleading and I have a terminal brain disease. You should be ashamed.

**Comment by LJWatson** [comment]
If you found something misleading in the [HTML specification](https://w3c.github.io/html), please let us know what it was by filing a [specific issue](https://github.com/w3c/html/issues/new). Thank you.

**Comment by alove1008** [comment]
I didn't go to code. I went to what I thought was a legitimate website so that I could get judicial help to see my son beforw I die. I don't know what coding is and what you did was beyond misleading and you me me hack q site. I'll be reporting this. Thanks for letting me stay up for hours just for a chance that what I thought this website was and did would help. I'm so embarrassed and experiments arent ethical without consent.
