### ISSUE TITLE
Micro-tasks don't define insertion point semantics & all browsers disagree

### ISSUE THREAD

**Issue by DigiTec** [w3c/html#165]
https://jsfiddle.net/h0446dky/

FireFox prints `thirdfourth` as they reopen the document after the script exits, but yet they define an insertion point for the lifetime of third and fourth (two separate promises)

Chrome prints `firstsecondthirdfourth` as they keep an insertion point the entire time

Edge either crashes or prints `third` as script execution stops after the first call to `document.write`

**Comment by DigiTec** [comment]
@domenic @annevk Would either of you want to take a stab at this? Seems pretty critical. We believe, but have no data yet, that some sites may be hitting this issue. We are likely to put in use counters/trackers of some sort to figure out how often these edge cases are being hit.

**Comment by domenic** [comment]
Sure, can you reopen over on the HTML Standard?

**Comment by annevk** [comment]
As far as I can tell this is a bug in Firefox. There's a microtask checkpoint that's part of script execution so I don't see how insertion point could get undefined before that point.

**Comment by annevk** [comment]
This is probably https://bugzilla.mozilla.org/show_bug.cgi?id=1193394.

**Comment by DigiTec** [comment]
So for inline script execution we have:
8. Execute the script.
9. Decrement the parser’s script nesting level by one. If the parser’s script nesting level is zero (which it always should be at this point), then set the parser pause flag to false.
10. Let the insertion point be undefined again.

And https://w3c.github.io/html/single-page.html#execute-a-script-block doesn't have an explicit micro-task checkpoint.

The only micro-task checkpoint I see is BEFORE we execute the script, but that has nothing to do with the Promise's that get inserted during.

@annevk Can you help me out with how you arrived at the "microtask checkpoint that's part of script execution?"

**Comment by annevk** [comment]
@DigiTec I don't know anything about that specification as I (and others) explained here: https://annevankesteren.nl/2016/01/film-at-11. It's completely secret what kind of modifications were made, how, and why.

Now, https://html.spec.whatwg.org/multipage/scripting.html#execute-the-script-block, in step 8, invokes https://html.spec.whatwg.org/multipage/webappapis.html#run-a-classic-script, which in step 10 invokes https://html.spec.whatwg.org/multipage/webappapis.html#clean-up-after-running-script, which in step 5 handles microtasks.

**Comment by DigiTec** [comment]
Thank you, I consulted the incorrect spec at this time and that is an issue for me to work out. Thank you for the explanation. I'll review the relevant sections and see if there is anything we can do here to help align Edge with the other browsers in this regard.

@travisleithead Seems like a big chunk of text to push back into the W3C version of the spec.

**Comment by annevk** [comment]
The W3C version, apart from it being unclear what changes were made before the initial commit (apart from breaking many links), is easily hundreds of commits behind. Coupled with the W3C having switched formats, which apparently took four-person months or so to do, I very much doubt it's going to be usable ever.

**Comment by travisleithead** [comment]
With thanks to our friends at WHATWG, I believe I've ported over all of these dependencies in https://github.com/w3c/html/commit/1b70bac646e9ae3f7f7ac495032782f82685556b. Closing this issue now.
