### ISSUE TITLE
ethra

### ISSUE THREAD

**Issue by grannywolf** [w3c/html#1651]
i am in dialysis and have to ride ethra to and from. it takes me an hour to get there and to get home. the problem is they schedule me to be picked up later than i get out. i have already sat two hours waiting then have three or four others to be left off before me. i live in sunbright so am always last. i have tried to get this fixed. my dialysis care-corodinator has sent the form seven times since January. and they still haven't changed the time for me to be picked up after i'm done. i am on by 10, run 3 hours forty five minutes and am done by 2 or 2:30. they have my pickup time at 3 and i have to give them an hour. it is ridiculous that i have to wait so long and not get home until 5:30 or 6 every day i go to dialysis. i really wish you could help with this. most of the schedulers have never been drivers and don't know the distance or time it takes therefore cannot do their job properly. i suggest they either have to spend a week riding with a driver to realize how ridiculous they are or have to travel it on their own. how can one do their job properly looking at a scaled map and not knowing actual distance. and why am i the one who sits and waits in fustration? i admit i have anxiety and often cry. i do not blame the drivers nor the disppatchers who can't do anything to change it. can you help me get my time changed to 2:30? this is really getting me down. i am in a wheelchair. am diabetic, and need to get home and eat. by the time i do get home i am not able to cook or eat properly.

**Comment by chaals** [comment]
spam
