### ISSUE TITLE
Bogus comments

### ISSUE THREAD

**Issue by lazarljubenovic** [w3c/html#1663]
Sorry if this is a wrong place to ask about this. I've only recently started checking out the specification, mostly around tokenization as I'm building a parser for an HTML-based templating language.

I'm having trouble understanding the point of bogus state. One way to get there is [recognizing characters `<?`](https://w3c.github.io/html/syntax.html#ref-for-tokenizer-bogus-comment-state), when we "[c]reate a comment token whose data is the empty string". While in [the bogus state](https://w3c.github.io/html/syntax.html#bogus-comment-state), we pretty much only append to the created comment token and then "[e]mit the comment token".

What I do not understand is **how is this** (the fact that we were in the bogus state) **reflected in the emitted stream of tokens**. There is no flag on the token; the spec is clear on what a comment token has: "Comment and character tokens have data."

It certainly seems like it shouldn't result into a regular comment based on the description in [§ 8.1.6. Comments](https://w3c.github.io/html/syntax.html#comments), where it's clearly stated that a comment must start with `<!--`.

I've searched for the word "bogus" across the whole chapter and some other chapters, but it was always in the context of which _state_ to switch to. (I couldn't find a way to search across the whole document, just did browser's search.) The only other place where I found this mentioned is [this example](https://w3c.github.io/html/dom.html#example-906d284c) but I don't think it's relevant.

Maybe I'm missing something obvious but I was really confused. Also very few things to find online regarding bogus comment states as browsers probably just swallow them all.

**Comment by chaals** [comment]
@lazarljubenovic this is probably going to take some archeology. The `<?` pattern comes from XML if I recall correctly, and I think the story is that since browsers don't handle these instructions, you just swallow the relevant bit of syntax and emit a blank....

You might also want to raise this issue on the [WHATWG HTML repo](https://github.com/whatwg/html/issues) as people there may have faster answers on this issue.
