### ISSUE TITLE
Examples of Application Cache are missing or broken

### ISSUE THREAD

**Issue by takenspc** [w3c/html#167]
In current Editor's Draft, examples of Application Cache are file names. They should be content of HTML, CSS, JavaScript and cache manifest.

http://w3c.github.io/html/browsers.html#offline-web-applications-introduction

> Before adding the manifest, these three files might look like this:
> 
> EXAMPLE offline/clock/clock1.html
> EXAMPLE offline/clock/clock1.css
> EXAMPLE offline/clock/clock1.js
> 
> The author can instead provide a manifest of the three files, say "clock.appcache":
> 
> EXAMPLE offline/clock/clock2.appcache
> 
> With a small change to the HTML file, the manifest (served as text/cache-manifest) is linked to the application:
> 
> EXAMPLE offline/clock/clock2.html

https://github.com/w3c/html/blob/master/sections/browsers.include#L5449-L5466

**Comment by travisleithead** [comment]
Closed as part of #348.
