### ISSUE TITLE
type table in 4.10.7 should indicate control type 

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#174]
Migrated from Bugzilla 13550:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=13550 

adding the list attribute to the input states that support it changes the control from a text box to a combo box.  The table of types should reflect this.

**Comment by chaals** [comment]
As noted in the original bugzilla bug, the table of input types is already very difficult to understand, so maybe cleaning that at the same time would be a good thing…

cc @cyns
