### ISSUE TITLE
Allow blank option elements?

### ISSUE THREAD

**Issue by chaals** [w3c/html#176]
From Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29563

> According to the HTML spec per the content model for the option element,
> neither <option></option> nor <option label=""></option> are valid.
> 
> I believe they should be valid, because:
> 
> 1) there is widespread use of <option></option> on the internet, and
> 
> 2) A (granted, non-normative) section of the select element describes setting
> the length attribute of a select element to add "new blank option elements to
> the select".  There is no other definition of "blank option" and all current
> web browsers will generate "<option></option>" in response to increasing a
> select's length.

**Comment by travisleithead** [comment]
One test: https://jsfiddle.net/1wtf1pLy/

Chrome/Edge/Safari: creates new options with no attributes and no children
Firefox: creates new options with no attributes and one child node (#text of "")

It appears that per the Content model rules for option, this is a case of the platform behavior creating content automatically that is a violation of the spec. This appears to match the bug-opener's concerns.

**Comment by travisleithead** [comment]
The [HTMLSelectElement](http://w3c.github.io/html/sec-forms.html#the-select-element) and [HTMLOptionsCollection](http://w3c.github.io/html/infrastructure.html#htmloptionscollection-htmloptionscollection) both have a normative section for creating empty options. For example, in HTMLOptionsCollection.length:

> If the new value is greater, then n new option elements with no attributes and no child nodes must be appended to the select element on which the HTMLOptionsCollection is rooted, where n is the difference between the two numbers (new value minus old value).

**Comment by travisleithead** [comment]
Personally, I'm not sure we need a spec change for this. These operations may introduce (perhaps momentarily) content models that are non-conforming for option elements, but I believe there is an expectation that authors subsequently modify the freshly created options to make them conforming. 

Here's some possible options to address this issue:
1. Do nothing and close this issue.
2. Add a note to the spec that mentions that the options created by these operations have contents models that are non-conforming, and encourage authors to make them conforming by adding `label`, `value` or Text to the options...
3. Add the empty option element as a conforming content model. I'd like to see evidence that there is indeed widespread legitimate use of empty options on the web.
4. Change the spec to produce conforming options, such as auto-generating a `label` or `value` attribute value, and hope that implementers are willing to change to support this.

Thoughts?

**Comment by chaals** [comment]
My instinct is to go for option 3. In part because I don't see what the problem is if we do - although my paranoia is trying to make me think harder about it and hinting there might be something, I'm thinking about other stuff at the moment.

I recall lots of select things that used blank options as a spacer to make menus easier to understand, which I think is a legitimate use. But that's just anecdata…

**Comment by chaals** [comment]
What happens if you _submit_ a blank value? Is there interoperability?

**Comment by Boldewyn** [comment]
I tested with recent Firefox, Chrome and IE11 this: https://jsfiddle.net/boldewyn/0yzqh2dx/

All submit a name `foo` with empty value.

**Comment by chaals** [comment]
Thanks! Same result for Safari 9.1 on that.

**Comment by chaals** [comment]
[public-html discussion](https://lists.w3.org/Archives/Public/public-html/2016Apr/0056.html)

**Comment by ZoeBijl** [comment]
This is a handy way to mark a `select` as empty. Or clear it in case a default is selected. I am for option 3.

**Comment by travisleithead** [comment]
OK, content model restrictions will now allow "nothing". Please review pull #397.
- Note, I kept the other pre-existing conditions, because they seemed useful, and I didn't know how to refactor them well, preserving the original alternative content models. If anyone has alternative suggestions for the text, I'd love to hear it.
