### ISSUE TITLE
CSP: Reference.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#191]
Since you're pulling in algorithms from CSP, it ought to be a normative, not informative reference. Also, it would be preferable to refer to https://w3c.github.io/webapsec-csp/ rather than the (very old) CSP1 NOTE.

**Comment by travisleithead** [comment]
Looks like the latest in specref is [[!CSP3]] which is the latest published WD of CSP3, and includes a link to the ED on GitHub. Should work as upgraded ref :)

**Comment by travisleithead** [comment]
(Sorry, was wrong about the ED reference...)
