### ISSUE TITLE
In the HTML5.1 spec, there is a typo in the code example for "The algorithm for deleting names".

### ISSUE THREAD

**Issue by elliottregan** [w3c/html#192]
It looks like this code example has a typo:

``` html
<div class="spaceship">x="30">
  <button class="fire" onclick="spaceships[this.parentNode.dataset.shipId].fire()">
    Fire
  </button>
</div>
```

should be:

``` html
<div class="spaceship" data-ship-id="30">
  <button class="fire" onclick="spaceships[this.parentNode.dataset.shipId].fire()">
    Fire
  </button>
</div>
```

https://w3c.github.io/html/dom.html#embedding-custom-non-visible-data-with-the-data-attributes

**Comment by chaals** [comment]
Yep. Fixed in https://github.com/w3c/html/commit/3aa360986266b7ada63eb07e16ae0d2513021d45

thanks

**Comment by elliottregan** [comment]
It seems like the `x="30"` attribute is supposed to be in the `data-*` form. Am I reading that section wrong?

**Comment by chaals** [comment]
No, I am. I'll finish the fix…
