### ISSUE TITLE
clarify input type="date" change event behavior

### ISSUE THREAD

**Issue by paulpalaszewski** [w3c/html#194]
It would be great if html 5.1 would clarify when a browser should fire change-/blur-event when editing dates. firefox and internet explorer work intuitively: when the date is changed and the date input looses focus, the same thing in chrome is firing events on every date-part - so even when typing day, month, year you get events between day and month and month and year.

**Comment by travisleithead** [comment]
Indeed. Will need to do some interop testing here... unless you have some already?

**Comment by patrickhlauke** [comment]
Related, the same incompatibility happens for `<select>` - worth filing a separate issue or generalising this to clarify when `onchange` should be fired for all types of form controls/widgets? xref https://bugzilla.mozilla.org/show_bug.cgi?id=126379

**Comment by chaals** [comment]
@patrickhlauke is #263 what you're asking for?

**Comment by patrickhlauke** [comment]
@chaals indeed, thanks for pointing to that one. i've added a comment over there

**Comment by shwetank** [comment]
There are weird inconsistencies within browsers (sometimes even within different input methods) when it comes to this. I've made a quick-and-dirty test case here https://html-input-onchange.surge.sh

* Edge seems to have a UI where the date-picker comes up and the value only changes when you finally click on the 'tick' checkmark. If you change values in between, then it doesn't reflect it. 
* With Chrome/Opera, the event fires whenever you change values (without defocussing from it) .... kind of. If you keep pressing the increase/decrease counter using the mouse, then it will not fire events if the values change too fast (so will only fire for the first and last instance). However, if you use the keyboard, then it always fires as long as you keep pressing your keyboard to increase/decrease the values. 
* Firefox always fires the event whenever it changes, no matter how fast and no matter which method (mouse, keyboard etc). 
* Not supported on Safari Desktop and IE. 

I'm vearing towards firefox's behaviour as the proper one. I don't have iOS, so if someone has, please let me know what the behaviour is exactly on mobile safari.

**Comment by scottaohara** [comment]
@shwetank when the picker opens, and each time the picker stops on a new value, an onchange event fires.  so if you spin the picker quickly, it will only fire the onchange when the picker lands on the new value.
