### ISSUE TITLE
create an alternative for input type="checkbox" to fix submit of unchecked value

### ISSUE THREAD

**Issue by paulpalaszewski** [w3c/html#195]
This is a very old thing: <input type="checkbox"> is only submitted with the form when the checkbox is checked. When submitted to a server the server has to check which field were on the page ... counter-intuitive and different than the behavoir of all other input widgets.

To stay compatible and to offer a cleanup-path for the future I suggest to introduce a <input type="switch" which looks and works almost exaclty like the type="checkbox" but has a slightly changed semantics that require browsers to submit the unchecked value "false".

**Comment by RyanSquared** [comment]
[Source](https://www.w3.org/TR/html401/interact/forms.html) for previous interactions where checkboxes were unticked.

**Comment by Deltachaos** [comment]
You already can add the same field as hidden Field before. But having a method build in would be grate as well.

If you add a new type for this we have two types that are very similar. On the other hand older browsers would display the input as text field if the type is unknown. I would prefer to add a attribute to controll the behaivor.

**Comment by RyanSquared** [comment]
An attribute would also be helpful. Something such as `<input type="checkbox" switch>`?

**Comment by cheshrkat** [comment]
Perhaps add the logically-missing `unchecked` attr and submit when present: `<input type="checkbox" unchecked="unchecked">` - consistent with the existing spec and backwards compat handled by omission ie. if none of `checked|unchecked|indeterminate` are found, continue non-submission. Presence of the new attr would indicate explicit opt-in to the new behaviour.

**Comment by stevefaulkner** [comment]
Closing here as this needs incubation and therefore should be raised in the WICG https://discourse.wicg.io/
