### ISSUE TITLE
CSP: Parser metadata.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#197]
Please port over https://github.com/whatwg/html/pull/1048 from WHATWG's HTML. It enables Content Security Policy to correctly implement the `'unsafe-dynamic'` source expression by passing a script's `parser-inserted` state to Fetch.

**Comment by travisleithead** [comment]
Already fixed in our doc with my other changes (1b70bac646e9ae3f7f7ac495032782f82685556b)
