### ISSUE TITLE
CSP: Correctly process the frozen base URL.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#201]
Please port the changes to https://www.w3.org/TR/html/document-metadata.html#set-the-frozen-base-url from https://github.com/whatwg/html/pull/1053 so that CSP's `base-uri` directive will be correctly explained.

Thanks!

**Comment by travisleithead** [comment]
Thanks Mike. Just to set expectations, I'm currently importing legacy Bugzilla bugs into our repo before I start working on these--but they'll be high on the list after that task is complete.

**Comment by mikewest** [comment]
Yeah. I'm filing these just so they're on y'all's radar, not because I expect you to fix them all ASAP. I know that there are quite a few things outstanding that you'll need to work through.
