### ISSUE TITLE
Explain meaning of dl / dt / dd better?

### ISSUE THREAD

**Issue by chaals** [w3c/html#202]
Imported from bugzilla https://www.w3.org/Bugs/Public/show_bug.cgi?id=13726

**Comment by cheshrkat** [comment]
For what it's worth, I think a suitable analogy/description is defining a key/value relationship. Not always, but usually, key/value pairs. A common use case is document metadata; plus I have in fact marked up dialogue using dl/dt/dd :)

**Comment by LJWatson** [comment]
Closed with  #415
