### ISSUE TITLE
Bugzilla bug triage (import or close)

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#205]
This issue for tracking progress on this task...

**Comment by travisleithead** [comment]
https://www.w3.org/Bugs/Public/buglist.cgi?component=HTML5%20spec&list_id=62853&order=bug_id&product=HTML%20WG&query_format=advanced&resolution=---

216 bugs

**Comment by travisleithead** [comment]
210 bugs. Got to run and grab my car from the shop now.

**Comment by travisleithead** [comment]
196 bugs remaining after today's work.

**Comment by travisleithead** [comment]
187 bugs.

**Comment by travisleithead** [comment]
159 today! Thanks @arronei

**Comment by travisleithead** [comment]
Now at 135. Several PRs in flight with editorial fixes from today's work.

**Comment by travisleithead** [comment]
Have reviewed the list for editorial bugs prior to 24853 and following 27292.

**Comment by travisleithead** [comment]
59 bugs.

**Comment by travisleithead** [comment]
37 bugs.

**Comment by travisleithead** [comment]
10!

**Comment by travisleithead** [comment]
9!

**Comment by arronei** [comment]
8!

**Comment by arronei** [comment]
7!

**Comment by travisleithead** [comment]
6!

**Comment by arronei** [comment]
5!!

**Comment by travisleithead** [comment]
4!!

**Comment by travisleithead** [comment]
3!!!

**Comment by travisleithead** [comment]
2!!!

**Comment by travisleithead** [comment]
1!!!

**Comment by travisleithead** [comment]
0!!!! 🎆

**Comment by travisleithead** [comment]
No more bugs to port. Closing this issue.
