### ISSUE TITLE
User agents should respect user preferences for assigning `accesskey` values, not guess at the keyboard

### ISSUE THREAD

**Issue by chaals** [w3c/html#21]
The current specification does not mention user preferences, but does suggest user agents make determinations based on the user's keyboard - something that in practice they do not, and cannot do.

**Comment by chaals** [comment]
See also https://www.w3.org/Bugs/Public/show_bug.cgi?id=27654

**Comment by travisleithead** [comment]
This makes sense-- keyboard alone may not be enough context.

**Comment by chaals** [comment]
More to the point, 
1. user agents normally not know what keys the user's keyboard has, and
2. in practice no user agent I can find follows the suggestion in the spec.

**Comment by chaals** [comment]
Hmm. This is closed by #22 I think.

**Comment by foolip** [comment]
You reverted this change again in b5ed70739158bd2b13a99cdac8e3f4a2faa5e751, presumably by mistake.

**Comment by chaals** [comment]
Well, I made a mess of the Pull Requests, and applying them in reverse order was the simplest (but not "best" way to fix it.

**Comment by chaals** [comment]
(Yeah, @foolip is right that the PRs got applied in the wrong order. I'll make another one to fix this again)

See also [accesskey-cyrillic-latin-link-manual.html](https://chaals.github.io/accesskey/tests/accesskey-cyrillic-latin-link-manual.html) and [accesskeylabel-manual.html](https://chaals.github.io/accesskey/tests/accesskeylabel-manual.html) for tests that show that this change matches reality better.
