### ISSUE TITLE
We already have a tabindex attribute, but we really need a tabatkins attribute

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#212]
The question is... what would it do @tabatkins?

**Comment by tabatkins** [comment]
It'd force me to convert the element's contents to Bikeshed.

**Comment by garykac** [comment]
Low-carb tabs?

**Comment by chaals** [comment]
I'm finding problems with Travis in trying to build something that resolves this.

**Comment by travisleithead** [comment]
tabatkins attribute proposal dies an ignominious death.

**Comment by tabatkins** [comment]
this is effing BULLS***

**Comment by arronei** [comment]
@tabatkins you just want to have your own attribute named after you. But don't we all really want that.

I think we closed this because we couldn't think of all the rainbow and unicorn pieces of functionality that this needed to cover.

**Comment by mitchellevan** [comment]
tabatkins is synonymous with tabat. So tabat[kins]="[URI]" retrieves the sequential focus order from the specified network resource. Unlike tabindex values, the content retrieved from [URI] may contain HTML semantics.

@tabatkins; @chaals
