### ISSUE TITLE
Include hooks for :read-only and :read-write

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#215]
Clone from bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=15428

@tabatkins, @fantasai (following up on an old old bug)

It looks like we have :read-only and :read-write in Selectors 4 (https://drafts.csswg.org/selectors-4/#rw-pseudos). That definition seems to require the document language to describe "user-alterable".

In the current HTML spec, we use the term "mutable" to describe input (and related) elements. However, I'm not sure if we have a common entry point for these selectors to use for all elements. We may need to add some prose to describe the relationship in general in http://w3c.github.io/html/rendering.html#bindings or elsewhere.

On the other hand, rumors from bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=17812 indicate that these pseudos might be going away? In that case, maybe we shouldn't be adding anything.

We also need to test implementations.

Feedback?

**Comment by chaals** [comment]
related to #235

**Comment by arronei** [comment]
Text from the Selectors 4 spec:

For example, in [HTML5] a non-disabled non-readonly <input> element is :read-write, as is any element with the contenteditable attribute set to the true state.

**Comment by arronei** [comment]
Moving out since this is already covered in Selectors 4. We may want to also clarify in the HTML spec would like editors to chime in here.

**Comment by chaals** [comment]
Agree that this is sufficiently defined in the Selectors spec.
