### ISSUE TITLE
Sync up usages of "compatibilty caseless" comparisons used in the spec

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#216]
Cloned from bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=16970

Apparently compatibility caseless matching is used due to legacy IE behavior, though browsers are pretty inconsistent in to what extent this matching is implemented. The current spec leaves it relatively undefined to avoid the problem. There is general consensus that having compatibility caseless matching is a can of worms, and we would prefer to remove it from the spec. Can implementations align on something else? What is the impact to web content? These are some of the question that should be resolved.

Used in:
- `<map name="...">` - the name value of a map
- radio button name groups

**Comment by chaals** [comment]
This might get match reality…

**Comment by r12a** [comment]
Just for the sake of tidiness i'm added a link here to some online notes that Addison made.
https://www.w3.org/International/wiki/CaseForCaselessHTML

**Comment by travisleithead** [comment]
FYI; Discussion ongoing at https://github.com/whatwg/html/issues/1666

**Comment by edent** [comment]
Looking at this for 5.3 - just to help me out, which sections of the spec refer to this?

Is it just a case of removing it, or do we need to update the language?
