### ISSUE TITLE
Mistake in EXAMPLE 12 of Introduction

### ISSUE THREAD

**Issue by zomp** [w3c/html#217]
In [EXAMPLE 12](https://www.w3.org/TR/html51/introduction.html#example-1ef96626) there seems to be a mistake, according to its description it should be rather:

> `<h1>Contact details</h2>` (`<h1>` instead of the original `<h2>`)

... because its description says:

> For example, it is unclear whether the author intended the following to be an `<h1>` heading or an `<h2>` heading.

Bonus: The _EXAMPLE 12_ heading is bold whereas the other example headings are normal. This might be another bug.

**Comment by stevefaulkner** [comment]
@zomp thanks! will fix

**Comment by zomp** [comment]
I have just noticed another small bug just behind – in [EXAMPLE 13](https://www.w3.org/TR/html51/introduction.html#example-3eebe0bd) there is `<<caption>>` instead of `<caption>` – should I create its own report?

**Comment by stevefaulkner** [comment]
Hi @zomp, no need will fix along with other issues - thanks again!
