### ISSUE TITLE
add warning/advice about lang attribute use

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#218]

**Comment by stevefaulkner** [comment]
https://github.com/w3c/html/commit/f1406b61f899bbd3689af39ad8a4a87eb36367ae

**Comment by stevefaulkner** [comment]
published in spec http://w3c.github.io/html/dom.html#lang-warning

**Comment by chaals** [comment]
Expand the examples a bit for braille output, alphabetical sorting, dictionary support?

In plenty of cases screen reader output _is_ comprehensible with incorrect language tagging.

**Comment by aardrian** [comment]
I've only recently discovered that it's also important for font selection in CJK languages, otherwise hurt feelings and grumpiness.

**Comment by ZoeBijl** [comment]
The current warning is quite long and repeats some stuff. Can we simplify it? This is what @handcoding and I came up with:

> User agents use the lang attribute to figure out the language of an element or—when it’s set on the HTML element—the language of a page. User agents can then load dictionaries or libraries for that language. That includes pronunciation rules for screen readers and other assistive technologies.
> 
> **If the lang attribute doesn’t match the language of the page or the element that it’s on, some users won’t be able to understand the content.**

Could add this to the end of the first paragraph to support @aardrian's point—if it's the right wording:

> The `lang` attribute is also used for font selection where different alphabets are mixed.

**Comment by r12a** [comment]
I like @MichielBijl version, because it opens up the issue slightly.  Note however that in addition to voice browsers and fonts, it is also used to determine quotation marks for q elements, and for styling such as hyphenation, case conversion, and line-breaking, as well as for spell-checking in some editors, etc. Incorrect language labels can cause those things to also produce unexpected results.

Perhaps we could tag those things to the end of the last paragraph as additional examples of what is included, then change the second para to say something like:

If the lang attribute doesn’t match the language of the page or the element that it’s on, some users won’t be able to understand the content or will see unexpected results.

**Comment by stevefaulkner** [comment]
closing fixed

**Comment by aphillips** [comment]
Except that the text about fonts is wrong. The most common font selection problem is when the same characters in a script (notably the Han ideographic script) have different shapes (represented in different fonts or using OpenType features) in different languages. For example, Japanese, Simplified Chinese, and Traditional Chinese. The text in the updated warning says for when alphabets are mixed.

**Comment by chaals** [comment]
So s/where different alphabets are mixed/where different languages share characters that use the same code point for different glyphs/ ?

Or something like that? @aphillips @r12a ? Do you want to re-open this?

**Comment by aphillips** [comment]
I will reopen this. We have some documentation [here](http://w3c.github.io/i18n-discuss/notes/language-detection.html#Why_language_metadata_is_needed) that discusses this, but not quite in the format here. Perhaps:

>  It provides an explicit indication to user agents about the language of content in order to enable language specific behavior. For example, use of an appropriate language dictionary;  selection of an appropriate font or glyphs for characters shared between different languages; or in the case of screen readers and similar assistive technologies with voice output, pronunciation of content using the correct voice / language library.

**Comment by aphillips** [comment]
@chaals  Hmmm, I don't have permission to reopen...

**Comment by stevefaulkner** [comment]
@aphillips done

**Comment by aphillips** [comment]
I'm satisfied by this change. Thanks!
