### ISSUE TITLE
Consider dropping showModalDialog API

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#223]
If no, then we have the following (interop?) fix to make: 
#### Add 3rd parameter (options) to control the window position and size

from bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=18154

Edge, Chrome have dropped support
Firefox: still supports (in their public branch)

WHATWG spec has removed it.

**Comment by chaals** [comment]
A [simple test](http://www.crmanswers.net/p/test-page-for-showmodaldialog-api.html#) shows support in Firefox 45.02 and Safari 9.1 on Mac OS 10.10 …

Maybe we should just mark this as likely to be deprecated in future.

**Comment by chaals** [comment]
[Email thread in public-html](https://lists.w3.org/Archives/Public/public-html/2016Apr/0054.html)
