### ISSUE TITLE
value on button in submit state is translateable

### ISSUE THREAD

**Issue by chaals** [w3c/html#230]
Missing in https://w3c.github.io/html/dom.html#the-translate-attribute

**Comment by chaals** [comment]
[basic test from english](http://chaals.github.io/testcases/button-translate-manual.html)
[Yandex.translate](http://translate.yandex.com) respects the `translate` attribute on `input type="submit"`.
[Bing translator](http://translate.bing.com) does not translate the value, regardless of the value of the `translate` attribute.
[Google translate](http://translate.google.com) translates the value regardless of the value of the `translate` attribute
None of those three translate the default value as required by the specification. Anyone got more results?

**Comment by r12a** [comment]
fwiw, there are some other tests related to (other) attributes here.  (I'll add tests for the submit type input element if this makes it into the standard.) https://www.w3.org/International/tests/repo/results/translation-services#attributes

**Comment by chaals** [comment]
So the technical question is
Should the `value` attribute and the browser default value for an `input type=submit` be translateable?

It seems the answer is yes, but behaviour is unclear...

**Comment by r12a** [comment]
Unless someone knows of a reason that this was omitted from the original list, i'd assume that the behaviour is unclear principally because the spec doesn't make it so, and no-one thought about it because it wasn't in the spec.

Fwiw, it seems logical to me that the value attribute should be translatable by default.

I'm not sure what it means to make the default value translatable.  How is that value produced?

**Comment by chaals** [comment]
The default value is produced by the browser itself, by magic. So how it behaves is probably not well defined - it is suggested that in the local language it provide something that makes sense, so "does it do something apparently logical given a translate attribute" is probably the test to apply.

We might want to raise this as a further issue, since this one just talks about the explicit content of the optional `value` attribute on `<input type="submit" value="hwætwega">`. But for example whether the default value matches the page language or the browser UI is probably the crux of the question.
