### ISSUE TITLE
remove style scoped ?

### ISSUE THREAD

**Issue by chaals** [w3c/html#231]
According to [a simple test](http://chaals.github.io/testcases/scoped-style-manual.html) and [caniuse.com](http://caniuse.com/#search=scoped) it's only supported by Firefox, having been removed some time ago from blink.

**Comment by ZoeBijl** [comment]
It's not planned in WebKit: https://webkit.org/status/

**Comment by cheshrkat** [comment]
Meanwhile the new hottness is CSS Modules (https://github.com/css-modules/css-modules), suggesting a fond wish to stop CSS cascading. There's demand for a usable feature to scope CSS amongst authors at least.

**Comment by ZoeBijl** [comment]
> @cheshrkat wrote:
> …suggesting a fond wish to stop CSS cascading.

They're not seriously suggesting to turn it into SS right?

**Comment by cheshrkat** [comment]
My answer was obviously a little flippant, but my understanding is it's all about locally scoping CSS so styles written for a component do not apply elsewhere. It generates ID-like class names which are tightly coupled to the HTML rendering. The author can then choose to push styles up to global scope as the _exception_. So, essentially it's an attempt to stop the cascade.

**Comment by ZoeBijl** [comment]
So it's a dirty way of using `scoped`? I feel like people don't understand the cascade and thus are trying to work around it.

**Comment by cheshrkat** [comment]
I'm not advocating CSS Modules, just noting there is developer demand for scoped CSS.

**Comment by prlbr** [comment]
Yep, I'm a developer and I have demand for scoped CSS.

It's somewhat annoying to see it in the spec and not being implemented (except by Firefox). I wish it would be implemented. On the other hand, I would support the motion to remove it from the spec, if it was clear that other browser vendors definitely won't implement it. I really would like to hear the reasons for not implementing it though.

**Comment by RyanSquared** [comment]
I believe the problem with scoped CSS is the inability to modify <html> and <body> tags.
