### ISSUE TITLE
Are registerContentHandler and registerProtocolHandler interoperable?

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#233]
Moved from Bugzilla bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=18975

If there is not good interop here already, I think this may be a candidate to remove (and incubate further in WICG as needed)

@masinter

> The 6.5.1.2 Custom scheme and content handlers features of registerProtocolHandler and registerContentHandler open huge security and privacy holes which are not described in the specification and for which there is no reliable mitigation such that users of these features could count on.
> 
> It's understandable that these are attractive features from the point of view of the power they put in the hands of developers of new protocols and content-types.
> 
> The bug is that these features are inadequately specified and the security of them inadequately analyzed and mitigated.
> 
> Here is an incomplete analysis:
> 
> These features expand the attack surface for introduction of malware, for leakage of private information in unanticipated and undisclosed ways. While the security section alludes to a few of the problems, the mitigations given are not implementable in a way that a browser-independent web application that wished to use the features could do so reliably. 
> 
> For one small example, registerContentHandler for a new image type might merely prompt the user for permission to install a new content-type handler, without clearly identifying that now, all images of that type will be sent to the handler site as soon as the image is received.  This gives the site that registers the content handler far more information about the user's activities. It exacerbates the current difficulties of multiple applications overwriting the default content handler for various media types, provides for no 'undo' mechanism for putting back pointers to local interpreters, etc.
> 
> As these are intended to be permanent changes to the underlying systems and not bounded by interpretation within the browser, a web site is now allowed to affect the permanent operation of the receiver's system. While this might be thought of as no different from typical installation dialogs, installing new software on a system usually involves virus and malware scanning, checking digital signatures of the the installed code and so forth. After a new handler has been installed, the server of the handler is now part of an attack surface.
> 
> Attempting to strengthen the mechanism for preventing malicious overwriting of legitimate handlers could merely encourage malicious preemptive registration of handlers.

---

> Also:
> 
> The current specification attempts to mitigate some of the risks of registerProtocolHandler by maintaining a "white list" of protocols for which handlers are "safe" and disallowing registering all other handlers except those starting with "web+". However, this  mechanism doesn't help with most of the security and privacy problems that arise when allowing dynamically assigned and overwritten handlers.
> 
> There is another bug and decision which focused on "web+" prefix and the authority under which such schemes are registered, but this was a distraction from the more fundamental problems. 
> 
> For example, even if registerProtocolHandler only allowed registering "mailto" and nothing else, the risks of web sites trying to steal "mailto" from each other, or the information leakage that the handler's site now can learn whenever a user STARTS to type a message, even when the user abandons the interaction, has not been disclosed or mitigated. 
> 
> For example, one mitigation might be that handlers not be URI patterns of remote services but rather pages or content bodies or previously downloaded Javascript libraries.

---

> See also threads on public-ietf-w3c starting
> http://lists.w3.org/Archives/Public/public-ietf-w3c/2012Aug/0000.html
> "web+: enabling websites to expose services with custom URI schemes to registerProtocolHandler."
> 
> and
> http://lists.w3.org/Archives/Public/public-ietf-w3c/2012Sep/0004.html
> "web+ and registerProtocolHandler"
> 
> and Chris Weber's blog post
> http://web.lookout.net/2012/01/testing-registerprotocolhandler-and-web.html

**Comment by chaals** [comment]
registerProtocolHandler seems widely used, registerContentHandler not so much...

**Comment by dstorey** [comment]
Content is FF only. Protocol is Gecko and Blink: http://html5test.com/compare/feature/offline-registerContentHandler/offline-registerProtocolHandler.html

**Comment by adanilo** [comment]
Confirmed, registerContentHandler has only one implementation, should move to incubation. We have 2 for registerProtocolHandler that appear to work.

**Comment by chaals** [comment]
fixed by #526
