### ISSUE TITLE
@title should allow LF to render consistently, especially given textarea[title] attribute values.

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#234]
Moved from Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=19899

This might be worth considering, especially if implementations do allow LF in the title attribute. Marked for testing.

> The specification currently states that the attribute, if specified, must have a value that contains no "LF" (U+000A) or "CR" (U+000D) characters.
> 
> I would like to request that this restricition is reconsidered for Textarea input fields which, by their nature, are designed to span multiple lines and a placeholder hint to show a user an example of the data to enter should also be able to span multiple lines.
> 
> An example of this requirement is where a textarea is used to create a list of items e.g.
> 
> ```
> Please enter areas of work:
>    Area A
>    Area B
>    Area C
> ```
> 
> The specification suggests the alternative use of Title but in most browsers this does not display in as helpful a manner and is, anyway, currently discouraged by the W3C, see:
> 
> http://dev.w3.org/html5/spec/global-attributes.html#attr-title
> Relying on the title attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification 
> 
> The use of this feature is becoming increasingly common, there is a clear demand for this feature to be supported (as can be seen by a quick Google search) and the decision to disallow line breaks imposes a decision that should really be left to individual website developers as to what best suits their own requirements.

**Comment by chaals** [comment]
There might be support, otherwise this would need incubation.

**Comment by siusin** [comment]
The textarea element section in the spec has changed since 2012. The current definition matches this request. See [test](https://github.com/w3c/web-platform-tests/pull/5272).

Suggest we close this issue.

**Comment by chaals** [comment]
OK, closing
