### ISSUE TITLE
Invalidation of :target selector when new candidate elements with matching ids appear in the DOM

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#235]
Moved from Bugzilla bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=19994

@mathroc

> I [posted a bug on the mozilla tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=773020) for what I thought was a bug : Firefox does not apply :target css style when an element id is set to the current address hashtag via javascript
> 
> eg, URI is `http://test.com#foobar`
> the page does not contains an element with the id `'foobar'`, when an element id is set to `'foobar'`, should css style with `:target` pseudo-class become active?
> 
> testcase : https://bug773020.bugzilla.mozilla.org/attachment.cgi?id=641202

This is interesting... application of CSS selectors, and the timing of such (especially in dynamic scenarios) is not something HTML defines to my knowledge. I'm skeptical that CSS defines this timing either, but I could be wrong...

@tabatkins, @dbaron, @atanassov

**Comment by tabatkins** [comment]
Right, CSS purposely doesn't define this at all; it's up to the host language to tell CSS what element(s) are target elements.  It just says that the assignment is determined by the URL fragment.

**Comment by chaals** [comment]
Find out what reality does, and whether this is simple or hard - which may impact whether it makes 5.1 or not.

**Comment by arronei** [comment]
This is already covered in the HTML spec. If we think we need to be more explicit I think we need to create a new term "targetable element" or something like that. I don't want to explicitly use the ":target" name of the selector.

----------------
An element’s unique identifier can be used for a variety of purposes, most notably as a way to link to specific parts of a document using fragment, as a way to target an element when scripting, and as a way to style a specific element from CSS.

**Comment by bzbarsky** [comment]
Given https://github.com/whatwg/html/issues/190 is this one of the places where whatwg and W3C HTML diverge?

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
