### ISSUE TITLE
<img> : Inference not conclusive

### ISSUE THREAD

**Issue by SetTrend** [w3c/html#237]
> For example, if the current pixel density is 3.125, that means that there are 300 device pixels per CSS inch, and thus if the image data is 300x600, it has intrinsic dimensions of 96 CSS pixels by 192 CSS pixels.

http://w3c.github.io/html/semantics-embedded-content.html#example-fe16f76e

<br/>
This annotation is very confusing. It reads:

(a) The current pixel density is 3.125
=> (b) there are 300 device pixels per CSS inch ![smiley_emoticons_skeptisch](https://cloud.githubusercontent.com/assets/9283914/14717910/e95177d8-07f3-11e6-87a3-6cc68223d01f.gif)

(c) if the image data is 300x600
=> (d) it has intrinsic dimensions of 96 CSS pixels by 192 CSS pixels. ![smiley_emoticons_mazzn_wtf](https://cloud.githubusercontent.com/assets/9283914/14717961/2d75d526-07f4-11e6-9a13-c43cb9cea3c5.gif)

To me this list of consequences makes no sense. Is it just me?

**Comment by travisleithead** [comment]
Yeah, I don't get this either. @ChumpChief or @marcoscaceres can you explain? Perhaps I can then edit this to make it clearer...

**Comment by ChumpChief** [comment]
96 CSS pixels per CSS inch, so 3.125 \* 96 = 300.  The example is technically correct :-P

However I agree these values chosen sound like someone just made a math mistake, and no real device I know of ships at a default scale of 3.125.  It would be better to use other values, e.g. pixel density of 2.0, 192 physical pixels per CSS inch.

Or add a reminder in the annotation that it's 96px/in.

**Comment by travisleithead** [comment]
OK, checkout PR #316 and let me know if that updated text helps.

**Comment by arronei** [comment]
Merged.
