### ISSUE TITLE
HTML 5.1 should reference WCAG 2.0 instead of WCAG 1.0

### ISSUE THREAD

**Issue by takenspc** [w3c/html#241]
[1.11. Suggested reading](http://w3c.github.io/html/introduction.html#suggested-reading) references WCAG 2.0.

> Web Content Accessibility Guidelines (WCAG) 2.0 [[WCAG]](http://w3c.github.io/html/references.html#biblio-wcag)

However "[[WCAG]](http://w3c.github.io/html/references.html#biblio-wcag)" in [References](http://w3c.github.io/html/references.html) links to [WCAG 1.0](http://www.w3.org/TR/WAI-WEBCONTENT).

> [WCAG]
> Wendy Chisholm; Gregg Vanderheiden; Ian Jacobs. <a href="http://www.w3.org/TR/WAI-WEBCONTENT">Web Content Accessibility Guidelines 1.0</a>. 5 May 1999. REC. URL: <a href="http://www.w3.org/TR/WAI-WEBCONTENT">http://www.w3.org/TR/WAI-WEBCONTENT</a>

This should link to [WCAG 2.0](https://www.w3.org/TR/WCAG20/)

**Comment by travisleithead** [comment]
This is closed per the merged PR. Thanks!
