### ISSUE TITLE
Section numbers in Terms defined by this specification are invisible

### ISSUE THREAD

**Issue by takenspc** [w3c/html#242]
Section numbers (in §X.Y.Z) in  [Terms defined by this specification](http://w3c.github.io/html/fullindex.html#index-defined-here) are invisible.

For example, the first two links of [Terms defined by this specification](http://w3c.github.io/html/fullindex.html#index-defined-here) are "enum-value for CanPlayTypeResult" and "enum-value for AutocompleteErrorReason".

![](https://cloud.githubusercontent.com/assets/270905/14745523/a903d754-08e6-11e6-970d-9a9cecb3d814.png)

However true link texts are "enum-value for CanPlayTypeResult, in §4.7.14" and "enum-value for AutocompleteErrorReason, in §4.10.19.8.4" respectively. In other words, ", in §4.7.14" and ", in §4.10.19.8.4" are invisible.

They should be visible by default.

**Comment by chaals** [comment]
Fixed by #350
