### ISSUE TITLE
Websocket in worker

### ISSUE THREAD

**Issue by publicocean0** [w3c/html#245]
We need the possibility to make work websocket in process worker. Now there is no warranty it works and we can find it working after page is reloaded

**Comment by publicocean0** [comment]
If a websocket is stopped and rebuild every time the is a new connection so the advantages of ws are destroyed . In addition every time I reconnect I have lost the events in the while the connection is redone. It is not a stupid feature to add but a bug in websocket design or a theoretical error

**Comment by travisleithead** [comment]
Well... websockets are not a feature that is described by our HTML5.1 spec. I'm not sure you'll be able to get help in this forum. Have you tried filing bugs against the browser implementers that have the issue?

**Comment by chaals** [comment]
This should be filed against the websockets and workers specs. It's not defined by HTML.

**Comment by publicocean0** [comment]
If it is not defined it is a bug in design. Websocket is not related to page navigation. The life cycle is different. When you change page The events in this while are lost. This is a grave conceptual error.
