### ISSUE TITLE
Remove Media Controller?

### ISSUE THREAD

**Issue by chaals** [w3c/html#246]
Media Controllers seem to have fallen out of favour. There is an implementation in Safari, but blink removed its implementation some time ago, and no other browser seems to have plans to implement this.

Note that if we decide to remove Media Controller we would (need to) automatically resolve #151 as well.

**Comment by chaals** [comment]
[public-html discussion](https://lists.w3.org/Archives/Public/public-html/2016Apr/0057.html)

**Comment by travisleithead** [comment]
Discussed at May 10 Editors F2F: Should be removed--only one implementation.
See discussion at: http://www.w3.org/2016/05/10-html-editors-irc#T17-55-46
