### ISSUE TITLE
Add acknowledgements for contributions

### ISSUE THREAD

**Issue by chaals** [w3c/html#247]
The acknowledgements section is something of a mess. There are individuals thanked whose contribution was to the HTML 5.0 spec, some years ago.

I don't see that as a problem, but making an effort to go back through the contributions to HTML 5.1 and thank everyone we can find who contributed would be a good thing to do.

And then we can reset for the next version, with a clear acknowledgement to all who have contributed to the many foregoing versions of HTML. 

Since this is editorial, I figure it makes a good thing to do straight after we freeze off a CR draft for a CfC - setting milestone accordingly.

**Comment by travisleithead** [comment]
I really like that idea. An ever-growing ack section for a living-standard can become unwieldy. +1 to reset with each published revision.

**Comment by chaals** [comment]
I can take on the adding people in, but I am not sure if I will get to doing the HTML 5.0 - 5.1 reset completely - not that I think that is critical.

**Comment by stuartlangridge** [comment]
Removing a whole bunch of names as though they didn't contribute at all seems pretty likely to mildly annoy a bunch of people, including me :) If it's very important that the acknowledgements list be short for some reason, maybe have an explicit "contributions to this version" and a separate explicit "contributions to previous versions", or similar? The things that were contributed have, after all, not gone away.

**Comment by yatil** [comment]
The reasoning makes somewhat sense. Let's make an explicit reference that this is acknowledgement section is for changes to this specific version and link back to the acknowledgement page of previous versions.

**Comment by marcoscaceres** [comment]
You also changed the WHATWG license text, which is not ok. The license applies to the whole document, not arbitrary parts.

**Comment by chaals** [comment]
> Let's make an explicit reference that this is acknowledgement section is for changes to this specific version and link back to the acknowledgement page of previous versions.

That's what I tried to do with #484, mentioning various kinds of earlier work. I didn't add actual links, but I'd be fine with having them.

> maybe have an explicit "contributions to this version" and a separate explicit "contributions to previous versions", or similar? The things that were contributed have, after all, not gone away.

Of course contributions don't go away. Nor did the contributions of many people who worked on earlier version of HTML, whether or not their efforts are reflected in the current spec. Many were never acknowledged in HTML 5, and going through two decades of work to paste them in now seemed, to me when I was poring over old issues in bugzilla for #486, to value the acknowledgements section higher than its possible quality can justify.

Every HTML spec available is full of holes. While a real effort to acknowledge the many people who have tried to improve that seems absolutely essential, beyond a certain point the opportunity cost gets scarily high.

And as a more general principle, burying someone's name in 5000 others, some of whom were listed among 500 because they contributed in 2004 not 2024 seems at least as unfair as whatever other arbitrary decision we end up with, hence the suggestion to make acknowledgements by version.

**Comment by chaals** [comment]
> You also changed the WHATWG license text, which is not ok. The license applies to the whole document, not arbitrary parts.

This is not relevant to this issue - feel free to open one or comment on the relevant part of #484

As I understand the license it does not apply to the current document, but effectively applies to parts of it, that exist in another document to which the license applies. I may be wrong - what did I miss?

**Comment by stevefaulkner** [comment]
As the names aspect is an editorial change that is controversial and does not improve HTML for implementers or users can we please revert it for now, until we have agreement on how it should be done.

**Comment by Spaxe** [comment]
Maybe you should also remove Tim Berners-Lee, @chaals. Go for broke.

**Comment by chaals** [comment]
@stevefaulkner @brucelawson there's nothing to revert…

**Comment by LJWatson** [comment]
@Spaxe
"Maybe you should also remove Tim Berners-Lee..."

Perhaps you were trying to inject some humour into a difficult thread, perhaps not. Either way, it will help everyone if comments can be kept constructive. thanks.

**Comment by Spaxe** [comment]
@LJWatson My comment was, I hope, clearly satire. Noted. I'll delete it.

**Comment by LJWatson** [comment]
@Spaxe thanks.

**Comment by chaals** [comment]
This has been overtaken by a new issue.
