### ISSUE TITLE
Typo in 4.7.1.1.18 Icon Images

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#25]
Originally posted by @valerii-zinchenko [1]

Current text:
"... As the information conveyed by the icon is redundant the img element is given an an empty alt attribute."
I think it should be:
"... As the information conveyed by the icon is redundant the img element is given an empty alt attribute."

[1] https://lists.w3.org/Archives/Public/public-html/2015Oct/0003.html

**Comment by arronei** [comment]
Fixed merged
