### ISSUE TITLE
Determine rendering for @srcdoc docs with quirks-mode doctype

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#254]
This issue is related to issue #253. @komputist

Moved from Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25233

> SITUATION: 
> 
> For docs inside @srcdoc, spec says that the DOCTYPE is optional:
> http://www.w3.org/html/wg/drafts/html/master/single-page.html#attr-iframe-srcdoc
> Thus, DOCTYPE is not required for @srcdoc documents.
> 
> But what should the parser do if there is a _quirky_ DOCTYPE inside the @srcdoc? Should it ignore the DOCTYPE? Or should it render the document in quirks mode?
> 
> PROPOSAL:
> 
> We should take same attitude to this as we have taken to UTF-8. Thus, qurks mode should _not_ be spread to new contexts. Therefore, spec should point out that "Optionally, a DOCTYPE" means that the DOCTYPE is to be ignored and thus, that the iframe document is to be rendered in no-quirks mode.
> 
> IMPLEMENTATIONS:
> - Firefox implements the proposed behavior
> - Webkit and Blink (at least current release of Safari and Chrome) places the docuent in no-quirks mode if the DOCTYPE is lacking. However, if there is a quirky doctype, then they put the document in quirks mode.

**Comment by arronei** [comment]
I'll add some details on interop

**Comment by patricia-gallardo** [comment]
We will have to make a test and run it in the different browsers, but according to the comments above and this https://www.w3.org/Bugs/Public/show_bug.cgi?id=25233#c2 it seems that at least Firefox and Webkit might support the proposed behaviour.

**Comment by chaals** [comment]
Firefox and Blink now show consistent behaviour for [my dopey test](https://chaals.github.io/testcases/quirky-srcdoc-manual.html) and [zcorpan's rather smarter one](http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=4303#)

@patricia-gallardo  can you test on webkit?

**Comment by patricia-gallardo** [comment]
I can test on Monday - I'm working from home today and I only have Linux here

**Comment by chaals** [comment]
OK, bumped it to the next milestone since we expect to finish this one by then.
