### ISSUE TITLE
Please list longdesc in the table of HTML5 attributes and link to its spec (was Bug 26059)

### ISSUE THREAD

**Issue by johnfoliot** [w3c/html#258]
(In reply to Arron Eicholz from comment #12)

> HTML5.1 Bugzilla Bug Triage: Won't fix. Per HTML5 the longdesc attribute is
> obsolete. However, there is a new document that now extends HTML5 for
> longdesc (https://www.w3.org/TR/html-longdesc/).
> 
> If this resolution is not satisfactory, please copy the relevant bug
> details/proposal into a new issue at the W3C HTML5 Issue tracker:
> https://github.com/w3c/html/issues/new where it will be re-triaged. Thanks!

Hi Arron,

I believe you are mistaken - the HTML5 Image Description Extension (longdesc) at: https://www.w3.org/TR/html-longdesc/ makes the @longdesc attribute a now fully conformant attribute in HTML5 (as per Plan 2014: https://dev.w3.org/html5/decision-policy/html5-2014-plan.html) and thus, also as part of HTML5.1

This is/was a compromise position taken with the then HTML5 WG and the Chairs, and as HTML5.1 is intended to supersede HTML5.0 then all new extensions released since then are in scope. (This also includes MSE/EME if they are finalized in time for the HTML5.1 release)

I am reopening this as still requiring resolution based on historical context and promises made. If HTML5 _still_ states that @longdesc is obsolete, then a bug needs to be filed _ON THAT_.

Reference: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26059#c13

**Comment by johnfoliot** [comment]
Quote from Plan 2014:
Extension specifications are first-class citizens

Some believe that extension specifications are second-class citizens, or somehow “lesser” than the core HTML5 specification. On the contrary, the specifications in the list above are vibrant, active pieces of the Web platform, with significant implementation traction and community credibility. Many extensions recognized as having wide consensus are recognized as part of the default settings of the W3C Validator, so they have an equal footing in validation. In addition, we will work to find ways to promote these extensions as a part of a family of HTML5 specifications.

https://dev.w3.org/html5/decision-policy/html5-2014-plan.html

**Comment by cwilso** [comment]
Note that Longdesc on img was NOT marked as obsolete anymore - a commit was done (with no issue) to that effect:  https://github.com/w3c/html/commit/4aeba8660c000c50af3ee35a93835fa4b65a1216, prior to this issue being filed.  However, this change seems to belie the whole point of having modular specs, by putting the image attribute back into the core specification.  Given the politics of this particular item, I'm somewhat taken aback that in essence longdesc was was simply re-placed in the spec, given that an express goal was to encourage modularization. I think this change (NOT the removal-of-longdesc-as-obsolete change, that should stay) should be reverted, until such point as we can establish a better pattern of modular pieces being incorporated; this sets a bad precedent, and thumbs its nose at the previous controversy.  Not really something to go in right under the wire.
