### ISSUE TITLE
Integrate public identifiers extensions spec?

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#259]
At the end of: https://www.w3.org/Bugs/Public/show_bug.cgi?id=13409 which was cloned from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=20769, the proposal was taken to a [very short] extension specification that adds a new DTD to the list of DTDs for the purpose of getting adoption for XHTML documents.

http://www.w3.org/2003/entities/2007doc/xhtmlpubid.html

Is there interest in merging this into HTML5.1, or does it need incubation (at WICG) first?

**Comment by davidcarlisle** [comment]
See also

https://github.com/whatwg/html/issues/500

**Comment by chaals** [comment]
Without someone to test implementations, this is at risk for the 5.1 CR

**Comment by travisleithead** [comment]
Add pointer to this doc from HTML.

**Comment by travisleithead** [comment]
After investigation, it looks like the latest proposal that has some agreement in whatwg/html#500 is not inline with the published version of the extension spec: http://www.w3.org/2003/entities/2007doc/xhtmlpubid.html, so a pointer to that document is likely insufficient.

As I understand it, the latest proposal is to add new SYSTEM identifier processing logic (note: the [existing list](http://w3c.github.io/html/xhtml.html#parsing-xhtml-documents) is for PUBLIC identifiers) to handle the case-sensitive term `mathml.dtd` or a FPI with suffix `/mathml.dtd` and use that to trigger the spec's existing entity list (the embedded data:uri), which brings unity to the force, err, unity for entity handling anyway.

I'll create some tests to see how this will behave...

**Comment by travisleithead** [comment]
Wrote tests for all the DTD defs for XHTML docs in the spec: https://github.com/w3c/web-platform-tests/pull/3081

**Comment by travisleithead** [comment]
Also tested (and commented out) the proposed syntax. The tests show that:
- Edge: tends to eat the entity references when parsed in XHTML ???
- Chrome: only seems to have trouble with `&AMP;` `&LT;` `&nvlt;` and the `-//W3C//DTD MathML 2.0//EN` string isn't recognized.
- Firefox: had trouble only with `&DotDot;` `&DownBreve;` `&tdot;` `&TripleDot;` and that was it!

Didn't test Safari.

Of course, the proposed new syntax doesn't work in any current browser at the moment. Given this, rather than take this change (which is probably good) now for 5.1 I propose moving this fix to "After 5.1" so that we can get some interoperable support behind it after it is put into the 5.2 editor's draft (it may go into the WHATWG spec first, which is fine).

**Comment by travisleithead** [comment]
Per short IRC discussion, this does not appear to be a blocking issue for 5.1, so moving to 5.2.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
