### ISSUE TITLE
What should go in the Alt text for images of text that are linked

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#260]
Moved from Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22576
@DavidMacDonald

> We provide advice when an image of text is a link, and there is a sentence or so (say about 10 words)... we should explain what image text do we leave out of the ALT and under what conditions. Describing the purpose of the link (WCAG 2.4.4) balanced against anything the image might be contributing to the context where it resides. (WCAG 1.1.1) and sometimes meeting both.
> 
> How about something like this?
> 
> In cases where the image of text is a link, then the primary consideration for the ALT text is to describe the link destination, followed by any text in the image that is important to context of the page where the image resides.
> 
> Example 1
> An image with about 10 words, where we should leave out some words
> 
> Example 2
> An example with more than 4 words where we should keep all of the words that are in the image

Curious what some other folks think?
@stevefaulkner @michielbijl @unor @iandevlin

**Comment by LJWatson** [comment]
I think the advice given in <a href="http://w3c.github.io/html/semantics-embedded-content.html#a-link-or-button-containing-nothing-but-an-image">4.7.5.1.3 A link or button containing nothing but an image</a>, <a href="<a href="http://w3c.github.io/html/semantics-embedded-content.html#images-of-text">4.7.5.1.5 Images of text</a>, and <a href="<a href="http://w3c.github.io/html/semantics-embedded-content.html#images-that-include-text">4.7.5.1.6 Images that include text</a> already provides appropriate guidance>

As an aside, the guidance for providing alternative texts in <a href="http://w3c.github.io/html/semantics-embedded-content.html#the-img-element">4.7.5 The img element</a> is already weighty - to the extent the page is unresponsive in several browsers.

**Comment by travisleithead** [comment]
Would love to hear from @DavidMacDonald is the above is satisfactory resolution.

**Comment by chaals** [comment]
We hope this was satisfactory…
