### ISSUE TITLE
Define formal activation behavior for <select>

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#263]
Moved from Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22957

from: Giuseppe Pascale

> Shouldn't there be an "activation behavior" defined for the `<select>` element? Some of the text in the spec looks like an "activation behavior" to me, it's just that is not explicitly labeled as such.
> 
> Explicitly defining some of that text as "activation behavior" IMO is not only an editorial change but would be needed when looking at the requirements and definition of activation behavior as a "user agent should allow the user to manually trigger elements that have an activation behavior".

---

> from Robin Berjon
> 
> This is related to http://rodneyrehm.github.io/select-events/

**Comment by patrickhlauke** [comment]
related (as pointed out by @chaals) it would be good to explicitly define as part of this when `onchange` should fire, as there's currently an incompatibility between firefox and other browsers (which for some dynamic forms, where fields are shown/hidden based on what the user selects in the `<select>`, causes real-world problems for keyboard users - see https://bugzilla.mozilla.org/show_bug.cgi?id=126379)

**Comment by stevefaulkner** [comment]
may be useful https://diffofhtmls.herokuapp.com/diff/The%20elements%20of%20HTML/Forms/The%20select%20element

**Comment by shwetank** [comment]
@patrickhlauke can you check if the incompatibility still exists with the newest version of firefox? (I tested in v57). Seems like firefox is behaving like other browsers here now, or am I mistaken? 

(I just want to have more clarity about current state of browser (in)compatibility before we decide to take action on it, so would be good if you could confirm/deny what im seeing here with firefox).

**Comment by chaals** [comment]
@shwetank skimming the 15-year history of the Firefox bug that points out that they are inconsistent with everything else, it seems like whether or not Firefox has fixed it we should do so in the spec to match the rest... (But yeah, a test and implementation results would be handy...)

**Comment by shwetank** [comment]
@chaals I agree. Just wanted to confirm if that particular Firefox issue is fixed, because it seems to me like it is. I hope to discuss a bit more about it in upcoming team call regarding activation behaviour.

**Comment by patrickhlauke** [comment]
using https://jsfiddle.net/zgqvzz7w/ i can confirm that, to my understanding, Firefox (Quantum) now behaves in line with all other common browsers (including iOS/Safari, Android/Chrome, Opera, Brave, IE11, Edge...). in short, onchange is fired as soon as a new option is selected and the focus is still on the `<select>` (e.g. on windows, TABbing to it, using arrow key up/down to change the selection), whereas previously Firefox only fired the event once the user TABbed away from the `<select>`)

**Comment by shwetank** [comment]
So looking at the spec and the truckload of firefox bug comments, it seems the spec has this wording for the `<select>` element in there 

>Upon this option element being picked (either through a click, or through unfocusing the element after changing its value, or through any other mechanism) ...

This is what caused the confusion and probably the implementation in Firefox back in the first place. The part about when the change event must be fired is actually pretty clear in the spec, and IMO does not need any further changes there. 

Whats needed is to remove that part of where is said that *unfocussing* the element after changing its value is an example of it being picked. 

Will be sending in PR to remove that part.
