### ISSUE TITLE
Provide code example and best practice advice for <dialog>

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#264]
@stevefaulkner 

> "4.11.7 The dialog element"
> http://www.w3.org/html/wg/drafts/html/master/interactive-elements.html#the-dialog-element
> 
> there is not currently a code example, add on with advice on placement of DIALOG in DOM scoped to body, so in case where called as a modal dialog all content except dialog is marked as inert.
> also provide advice on desired keyboard behaviour:
> move focus to dialog on open
> move focus back to trigger control on close.

**Comment by LJWatson** [comment]
Closed per #529
