### ISSUE TITLE
Situation when using "hidden" is not appropriate

### ISSUE THREAD

**Issue by arronei** [w3c/html#265]
@stevefaulkner 

Imported from https://www.w3.org/Bugs/Public/show_bug.cgi?id=28702

In "7.1 The hidden attribute" (W3C Recommendation 28 October 2014 ), refer to
"The  hidden  attribute must not be used to hide content that could legitimately be shown in another presentation. 
For example, it is incorrect to use hidden  to hide panels in a tabbed dialog, because the tabbed interface is merely a kind of overflow presentation — one could equally well just show all the form controls in one big page with a scrollbar". 

How is this different from the "skeletal example, the attribute is used to hide the Web game's main screen until the user logs in:"
<section id="game" hidden>
   ...
  </section>

Just as certain content cannot be made available till one logs in, it may not be possible or logical functionality-wise to display content of subsequent tabs in a tabbed dialog because there may be dependencies. 
The hidden attribute may be removed programmatically when content is to be rendered just like display:none may be changed to display:block or the like.  
Please can you clarify why it is not suitable in a tabbed dialog?
Thanks,
Sailesh Panchang
[1] http://www.w3.org/TR/html5/editing.html#the-hidden-attribute

**Comment by stevefaulkner** [comment]
resolved via https://github.com/w3c/html/issues/203
