### ISSUE TITLE
Drop the relList IDL attribute?

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#267]
Moved from bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23579
@yucca42

> The `relList` IDL attribute defined for `<a>` and `<area>` has not been been implemented (Firefox, Chrome, IE all say it’s undefined). There is no appropriate definition for it, as it just described as follows: 
> 
> > “The IDL attribute `relList` must reflect the `rel` content attribute.” 
> 
> The meaning of “reflect” is defined in terms of using the same value, but the `rel` attribute is a string, whereas `relList` is declared to be a DOMTokenList object.
> 
> The intent is probably that `relList` should have the `rel` attribute value as parsed to a list, but this is not specified. This feature would be some usefulness, but since it has not been implemented and since the parsing `<a rel>` attribute value can be handled rather easily, `relList` should be removed at least for now.

Since this was filed, I note that Firefox 45 does support `relList`. Should check Safari too.

**Comment by arronei** [comment]
relList is supported in Firefox, Safari (`<a>, <area>`) and Chrome (only `<link>` element)

**Comment by travisleithead** [comment]
Given this, it's not unreasonable to expect implementation convergence on the current spec text. I suggest we leave it in for now.
