### ISSUE TITLE
Expand note on not using Tables as layout aids

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#271]
steve faulkner     2014-01-30 09:43:17 UTC  

Copied from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24447
@stevefaulkner 

> "Tables should not be used as layout aids. Historically, many Web authors have tables in HTML as a way to control their page layout making it difficult to extract tabular data from such documents. In particular, users of accessibility tools, like screen readers, are likely to find it very difficult to navigate pages with tables used for layout. If a table is to be used for layout it must be marked with the attribute role="presentation" for a user agent to properly represent the table to an assistive technology and to properly convey the intent of the author to tools that wish to extract tabular data from the document."
> http://www.w3.org/html/wg/drafts/html/master/tabular-data.html#the-table-element
> 
> original wg decision on issue http://lists.w3.org/Archives/Public/public-html/2011Mar/0245.html

**Comment by stevefaulkner** [comment]
Closing this for now as I can't think of any text that would improve what is currently there, if anybody has any bright ideas, feel free to re-open
