### ISSUE TITLE
Should <menuitem> really be a void element?

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#274]
Moved from Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24972
@AndySky21

> Is it possible to receive an answer in either way?

The question is:

> I hope that now editors will really consider the following:
> 1. `<menuitem>` should not be a void element, so that a normal open-closing tag syntax will help legacy UAs to treat it properly without nesting subsequent `<menuitem>`s
> 2. additionally, once it were made a normal element, its content model could also change from "empty" to "text", allowing authors to specify the label of the command as textContent avoiding as an alternative to `@label`.

---

> 1. The spec is considered to be correct, backward compatibility is not an issue, the element itself is not rendered unless user agents support it (even if its function can be achieved no matter the actual support) and the label cannot be given by the element's content. [this is poor coding language IMO]
>    If all above considerations are true, then the validator fails (it does not consider menuitem as void)
>    OR
> 2. The spec is not correct:
>    1. `<menuitem>` MUST have a closing tag in order to prevent a messy DOM
>    2. and possibly the content model for `<menuitem>` is "text", so that the label for the control can be given by the element's textContent. Consider that menu commands rely on script because as of now no standard commands have been defined. So, the menu can (and should) be made visible somehow also to legacy UA.
> 
> Please consider.

**Comment by stevefaulkner** [comment]
see https://github.com/whatwg/html/issues/234

**Comment by travisleithead** [comment]
Created https://jsfiddle.net/gnwv5076/.
In Firefox, Chrome and Edge, these appear to **not** be treated as void elements.

**Comment by RByers** [comment]
Except if you enable "experimental web platform features" in chromium (where our `<menuitem>` implementation still lives), then you'll see we do treat it as void.  This is [a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=412945) we should fix in blink IMHO. /cc @tkent-google.

**Comment by travisleithead** [comment]
Ah, thanks Rick. Wonder if Mozilla has any changes planned? @hsivonen

**Comment by chaals** [comment]
In the absence of pressure from changing implementations, we'll probably go with current reality.

**Comment by chaals** [comment]
[Working group discussion](http://www.w3.org/mid/op.yhyns70js7agh9@widsith.local)

**Comment by dylanb** [comment]
Without any ability to style these, it does not matter what happens because no-one with a serious web site/application would ever use them anyway.

**Comment by chaals** [comment]
@dylanb I'm inclined to agree that the use case for on-page menus isn't going to be huge, especially given that we have the longstanding `select` element to do that for the simple case.

But it might be more useful for adding to context menus - **if** it gets enough implementation...

**Comment by stevefaulkner** [comment]
> But it might be more useful for adding to context menus - if it gets enough implementation...

after years of the souped up menu specification being in the spec, the only vendor interest has been in regards to context menus

**Comment by dstorey** [comment]
@stevefaulkner We're using button with menu attribute in our CSS library for the Edge dev site, with a polyfill we're writing, because we need such functionality in a bunch of our pages, and it was nicer than writing a bunch of tag soup. Select wasn't good enough as we needed the current button text to stay visible when selected, multi-select without changing to a different type of control, etc. Filter/mile stone/etc. drop down menus on GitHub are a good example.

**Comment by chaals** [comment]
@dstorey did you keep using that? Got a pointer to a production page?

**Comment by dstorey** [comment]
@chaals yes, except we polyfill by converting to markup that works accessibly out of the box. For example "status" button drop down on https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/ (and additional ones when logged in). If you view source you will see the original markup the author writes, while DOM explorer will give you the converted source (menu attribute and type are still there in generated code as there was no reason to remove it)

Original code authors write is:

```
<button type="menu" menu="menu1">Radio Button Menu</button>
<menu type="context" id="menu1">
	<menuitem type="radio" id="radio1" radiogroup="foo" label="KeXP"></menuitem>
	<menuitem type="radio" id="radio2" radiogroup="foo" label="KCRW"></menuitem>
	<menuitem type="radio" id="radio3" radiogroup="foo" label="X Radio"></menuitem>
</menu>
```
We went with non-void menuitem as that looked like way it was moving at the time (and the way FF implemented if I recall)

**Comment by chaals** [comment]
@dstorey thanks.

Note that in PR #854 I removed the radio type - since as far as I can tell it isn't implemented. Is there any reason that you guys thought it would make more sense than just using commands?

(Yes, FF implemented with non-void `menuitem`)
