### ISSUE TITLE
initial focus precedence: autofocus or fragment identifier 

### ISSUE THREAD

**Issue by arronei** [w3c/html#277]
@rodneyrehm

Imported from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27912

There are currently at least 2 ways to set initial focus upon document load. The document itself can define an element to (scroll to and) focus by using the autofocus attribute [1](limited to form elements). The user can define the element to (scroll to and) focus by using a URL fragment identifier [2]. The specification does not define order of processing autofocus and fragment identifiers. 

Blink [3] prefers the autofocus attribute. Gecko [4] and WebKit [5] prefer :target but show bugs in doing so. Trident (IE11) prefers :target without bugs.

In my opinion Microsoft got this one right. A URL fragment identifier can be argued to be user-input, where autofocus is a document's default state. User input should be more important. I propose to add a note to the autofocus [1] spec saying that fragment identifiers [2] have precedence.

[1] http://www.w3.org/html/wg/drafts/html/master/forms.html#autofocusing-a-form-control:-the-autofocus-attribute
[2] http://www.w3.org/html/wg/drafts/html/master/browsers.html#scroll-to-fragid
[3] https://code.google.com/p/chromium/issues/detail?id=382901
[4] https://bugzilla.mozilla.org/show_bug.cgi?id=840187
[5] https://bugs.webkit.org/show_bug.cgi?id=140963

**Comment by IanPouncey** [comment]
Confirming the behaviour described by @arronei with a little more detail, based on a [test case](http://ianpouncey.jsbin.com/kirizuz/) I put together. IE11 and Edge behave slightly differently depending on whether it is a new tab or not, perhaps someone can confirm this as I was working from a virtual machine - I can't think of a reason why this would matter, but it is rather odd.

**Chrome (version 63):**

autofocus takes precedence in all cases

**Safari (version 10.1.2):**

autofocus takes precedence when the fragment target is not keybaord focusable (div with no tabindex).

In other cases (including div with tabindex -1 or 0) focus is set to both the fragment target and the input field with autofocus; starting to type sets focus to input exlusively, navigating with tab key sets focus to fragment target exclusively, with keyboard navigation starting from that point.

**Firefox (version 58):**

Fragment target takes precedence in all cases; focus style is not set.

**Internet Explorer 11:**

When loading content in a new tab, fragment target takes precedence except when the fragment target is not keyboard focusable (div with no tabindex) in which case no focus is set.

After a hard refresh of an existing tab with a fragment url, autofocus takes precedence in all cases.

**Edge (version 20):**

Same behaviour as IE

**Comment by chaals** [comment]
Edge behaves as you describe on my native windows machine too...

Hmm. Tab navigation does start from the unfocusable element in a new tab.

**Comment by chaals** [comment]
UPD. Fix URL... I **think** this issue needs to update http://w3c.github.io/html/browsers.html#updating-the-session-history-with-the-new-page step 6...

And should note the outcome for the autofocus element definition too.
