### ISSUE TITLE
Add focusin and focusout to the focus model

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#278]
See bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25877

> Presumably, focusin fires immediately before focus in the algorithm, and focusout fires immediately before blur in the algorithm (neither are cancelable).

**Comment by chaals** [comment]
Looks like it works - http://caniuse.com/#search=focusin

**Comment by travisleithead** [comment]
Note @smaug---- commented on https://www.w3.org/Bugs/Public/show_bug.cgi?id=25897, noting that we have implementations, but they don't match the spec...

**Comment by chaals** [comment]
@adanilo there is some effort in the editing task force to look at the order of events like this. @garykac might know more…

**Comment by patricia-gallardo** [comment]
I have taken a look, and it seems that most browsers support 'focusin' and 'focusout' events, as @chaals pointed out earlier.

In Chromium and Firefox they seem to fire just after focus/blur - that is:

* an element gaining focus will receive 'focus' first and 'focusin' right after
* an element losing focus will reveive 'blur' first and 'focusout' right after

Using 'focusin' and 'focusout' in a bubbling fashion conforms the best to GUI development in other frameworks so I think it makes sense to include them.

**Comment by patricia-gallardo** [comment]
The section involved is the so called "focus update steps" where the fireing order of the focus events are described: https://w3c.github.io/html/editing.html#loses-focus

**Comment by patricia-gallardo** [comment]
My very simple test is here : https://gist.github.com/patricia-gallardo/0b87e090c242e1ad12dbaa53a9a0f20f

It just makes a ul with two input fields and sets 'click', 'focus', 'blur', 'focusin' and 'focusout' event listeners on all three. Then prints to the console when they are called.

**Comment by patricia-gallardo** [comment]
There are two cases to consider 
1) The added event listener is added in "bubble" mode - this should imo be the "normal" thing to do
2) The added event listener is added in "capturing" mode

Suggestions

1) For the "bubble" mode a two points are needed 
Under point 2 we will need a point 5 for 'focusout'
Under point 4 we will need a point 6 for 'focusin'
We also need to make it clear that the event will "bubble"

2) For the "capturing" mode these are still sent down after focus/blur in both Firefox and Vivaldi (Chromium) but reaching the ul first
It might be possible to formulate something in the points mentioned above to make both of these cases (bubble/capturing) clear.

**Comment by patricia-gallardo** [comment]
The UI Events specification seems relevant to this issue https://w3c.github.io/uievents/#events-focusevent-event-order

This part specifically confuses me because it does not seem to reflect the behaviour I'm seeing. I will do some more testing.

**Comment by patricia-gallardo** [comment]
Made a bubble test that is a bit easier to use (still super naive) : https://gist.github.com/patricia-gallardo/e2380ee60e0893c0f71344d258b93a6c

**Comment by LJWatson** [comment]
@patricia-gallardo can you document the results of the new test in different browsers? If it confirms we have interop across at least two different browser/engines, we'll be in a good position to get this issue resolved.

**Comment by patricia-gallardo** [comment]
My Results for the bubble test

Chromium (Vivaldi/Opera/Chrome) : test passes
Firefox 56 : test passes
Firefox 57 : test passes
Safari 11 : test passes

Edge (EdgeHTML 16) : test failes - but only in the second part and only about when the blur event happens (it comes _after_ focus out in Edge)
IE 11 (Trident 7) : test fails - in many different ways:
- First click : FocusIn fires before Focus
- Second click : Blur and the second Focus fire after FocusIn

**Comment by LJWatson** [comment]
LGTM :)  If you have a proposed change to the spec text, feel free to post it here as a draft.

**Comment by LJWatson** [comment]
Ping @TravisLeithead for thoughts on if/where UI Events fits in here?

**Comment by patricia-gallardo** [comment]
Similar test for the capture case for FocusIn/FocusOut 

https://gist.github.com/patricia-gallardo/19862e5e0cad8e9f991cf5aabff94731

**Comment by patricia-gallardo** [comment]
My Results for the capture test ( similar results - but without Firefox 56 since I uninstalled it :D )

Chromium (Vivaldi/Opera/Chrome) : test passes
Firefox 57 : test passes
Safari 11 : test passes

Edge (EdgeHTML 16) : test failes - but only in the second part and only about when the blur event happens (it comes _after_ focus out in Edge)
IE 11 (Trident 7) : test fails - in many different ways:
- First click : FocusIn fires before Focus
- Second click : Blur and the second Focus fire after FocusIn

**Comment by patricia-gallardo** [comment]
Rough idea of change in https://w3c.github.io/html/editing.html#loses-focus

Add a sub-point under 2 : "5. If blur event target is not null, fire a FocusOut event named focusout along the old chain to the blur event target."

Add a sub-point under 4 : "6. If focus event target is not null, fire a FocusIn event named focusin along the new chain to the focus event target."

**Comment by patricia-gallardo** [comment]
I am assuming here that old/new chain here is defined as the same as the regular chain for events (if not please give me the proper term for the regular event chain and I will reword it)

**Comment by patricia-gallardo** [comment]
Alternative text:

Add a sub-point under 2 : "5. If blur event target is not null, fire an event named focusout at the blur event target."

Add a sub-point under 4 : "6. If focus event target is not null, fire an event named focusin at the focus event target."

With "fire" referencing : https://w3c.github.io/html/webappapis.html#event-firing

I am not sure if it is sufficiently clear that this is a regular event that can both be captured and bubble

**Comment by patricia-gallardo** [comment]
My first draft for the above change is in https://github.com/w3c/html/pull/1142

**Comment by patricia-gallardo** [comment]
Relates to web-platform-test
http://w3c-test.org/uievents/order-of-events/focus-events/focus-manual.html

**Comment by patricia-gallardo** [comment]
Made pull request in web-platform-tests: https://github.com/w3c/web-platform-tests/pull/9049

**Comment by patricia-gallardo** [comment]
@siusin can you take a look? (to make sure I haven't totally broken protocol :D)

**Comment by chaals** [comment]
@travisleithead / @garykac  can you take a look at @patricia-gallardo 's comments? Is there any apparent resolution to https://github.com/w3c/uievents/issues/88 which seems to be the same problem?

**Comment by travisleithead** [comment]
So, Edge just changed to more closely match Chrome (even if it's not the right theoretical ordering). In our daily builds, we're now passing: https://github.com/w3c/web-platform-tests/blob/master/uievents/order-of-events/focus-events/focus-automated-blink-webkit.html

However, we (and Chrome) are failing: http://w3c-test.org/uievents/order-of-events/focus-events/focus-manual.html

It's still unclear to me what the spec'd order should be. I'm trying to dig-into the 'why' Edge made the change in hopes of understanding if there was a web-compat reason for it...

**Comment by patricia-gallardo** [comment]
@travisleithead my tests showed that Edge almost matched Chrome, Safari and Firefox

Edge (EdgeHTML 16) : test failes - but only in the second part and only about when the blur event happens (it comes after focus out in Edge)

**Comment by patricia-gallardo** [comment]
Notes from help from @chaals on things I need to add:
1) add a note to the changes section saying that focusing fires the in/out events
2) add the events to the events table (connected to focus/blur)
3) look into if there should be anything about related target
4) check that the intro section still makes sense
5) who should be acknowledged for this change who aren't yet listed as contributing for this version
7) update the attributes index
