### ISSUE TITLE
Add advice about use of sectioning content in lists

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#279]
...this is to match the note already available about headings in lists...

> "While it is conforming to include heading elements (e.g. h1) inside li elements, it likely does not convey the semantics that the author intended. A heading starts a new section, so a heading in a list implicitly splits the list into spanning multiple sections"
> 
> example of article use inside ordered list
> http://blog.teamtreehouse.com/use-html5-sectioning-elements

@stevefaulkner

**Comment by plehegar** [comment]
See also https://github.com/w3c/html/issues/33
