### ISSUE TITLE
Need a change log for humans

### ISSUE THREAD

**Issue by chaals** [w3c/html#28]
There needs to be a proper changelog, that normal people can understand, similar to https://www.w3.org/TR/html5-diff/ to clarify what has changed since HTML 5 - and ideally between milestone working drafts, to assist review.

**Comment by arronei** [comment]
@chaals I am creating a complete html diff file for you. This will at least help in figuring out all the changes between tr/HTML5 and the current version as of 2/3

**Comment by arronei** [comment]
@chaals you now have a diff file to look at for creating the change log. I have added it to the diff folder for now. We can determine later if we want to do more with this diff file.

**Comment by chaals** [comment]
This is now in the spec.
