### ISSUE TITLE
colspan="0" option for TD elements was dropped, yet the "no one uses" rowspan="0" remains

### ISSUE THREAD

**Issue by arronei** [w3c/html#284]
@scunliffe

Imported from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27099

"The td and th elements may have a colspan content attribute specified, whose value must be a valid non-negative integer greater than zero."

Back in HTML 4.x http://www.w3.org/TR/html401/struct/tables.html#adef-colspan the colspan"0" attribute on a TD element was spec'd to tell the user agent to span the column across all columns in the colgroup.  This appears to have been dropped.

This is rather frustrating as it seems to conflict with developers' interests.

Only Mozilla/Firefox (AFAIK) correctly implemented this attribute value behavior yet it is highly desired: http://stackoverflow.com/questions/398734/colspan-all-columns (134 upvotes, and 21 stars!)

The resolution for developers is to specify a wildly inaccurate bogus high number that exceeds the tables rendered column count.

Although effective in some scenarios it wreaks of sloppy coding and won't work when the table-layout is set to fixed.

There's a bit more discussion about the colspan="0" and rowspan="0" attributes in this bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=13770

It seems that rowspan="0" remained because both Opera and Firefox implemented it but because Opera didn't implement colspan="0" this item was "cut".

Whilst I understand the (if 2 browsers implement) rule for keeping items in the spec this seems really messed up. I hate to be a spoil sport on this but if we can't bring back colspan="0" and have browsers properly implement it, I'd rather drop both attributes' (zero-value-scenario) as it will only cause confusion to developers that both attributes exist, but only 1 has the magic zero value that spans... and it is specifically **_NOT**_ on the attribute developers actually want it on.

**Comment by chaals** [comment]
As mentioned, while it is desired by developers browsers haven't done anything so won't be in HTML 5.1... please incubate e.g. in [WICG](http://discourse.wicg.io) to get traction if you want it in a future HTML specification
