### ISSUE TITLE
object element usemap should be deprecated

### ISSUE THREAD

**Issue by arronei** [w3c/html#285]
@rodneyrehm

Imported from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27756

I'd like to discuss options to deprecate the usemap attribute on the object element.

> The usemap attribute, if present while the object element represents an image, can indicate that the object has an associated image map. The attribute must be ignored if the object element doesn't represent an image.

This limits maps to the case where the object element references an image, i.e. a file format that <img> already handles just fine. With the exception of SVG, which features does the object element provide an img element does not?

The move to deprecate this stems from testing [1] the current user agent landscape. While map support for `<img>` works in every browser, Chrome will ignore usemap completely on object elements. Firefox makes a map on an object element available to script and mouse, but not add it to the sequential navigation list ("tabbing sequence"), so it is not accessible via keyboard. Internet Explorer will make the map available only to the mouse. usemap is ignored in Firefox for SVGs.

[1] http://medialize.github.io/ally.js/tests/browser-bugs/object-map.html

**Comment by chaals** [comment]
Safari seems to behave the same as Chrome, ignoring the map completely.

Sadly, I think we should indeed deprecate this. Only working with a mouse is pretty unacceptable.

**Comment by chaals** [comment]
Not enough workable implementation, we'll do this.

**Comment by arronei** [comment]
The useMap property/attribute is supported in all browsers. However actual implementation is poor and inconsistent. I recommend we move this to obsolete section.
