### ISSUE TITLE
Dropzone operation and effectAllowed

### ISSUE THREAD

**Issue by arronei** [w3c/html#287]
@stevendwood

Imported from:https://www.w3.org/Bugs/Public/show_bug.cgi?id=26686

Since the dropzone can only support only one kind of operation (copy, move, link), does that mean that you cannot use a dropzone to do a copy OR a move based on a modifier key ?  The relation between dropEffect and the dropzones operation is not clear. Is the operation only for feedback - or does it work like dropEffect which causes the drop option to be unavailable if it does not match one of the effectAllowed values ?

**Comment by chaals** [comment]
pull request to remove it #356

**Comment by chaals** [comment]
Not enough implementation. We''ll apply the PR.

**Comment by chaals** [comment]
Duplicate of #64. NB the resolution may be not to merge #356.
