### ISSUE TITLE
make element.focus() consider body element's focusable state for improved real-world interop

### ISSUE THREAD

**Issue by arronei** [w3c/html#290]
@travisleithead 

Imported from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26725

Test case files:
- https://www.w3.org/Bugs/Public/attachment.cgi?id=1508
- https://www.w3.org/Bugs/Public/attachment.cgi?id=1509

Example showing the expectations of the new behavior; this is the primary repro file.

A few months ago, IE made a platform change to improve our Mobile interop to match a webkit behavior which a variety of sites required in order to display properly. The change involved the behavior of focusing the body element. IE [previously], Firefox, and the spec all define the behavior that when element.focus() is called on the body element, it forwards the focus command on to the window which causes the viewport to be in a focused state (this scenario is usually done from a parent browsing context calling focus() on the body element of a child browsing context). However, in Webkit-based browsers, the ability of the body/viewport to accept focus is conditional on whether the body element can actually accept focus (e.g., if the body element has a valid tabindex attribute set). So, in a webkit-based browser and now in IE (on mobile, soon to come to desktop) unless the body element is focusable the call to focus() the body will do nothing.

I recommend updating the spec to contain this condition in order to better match an interoperable pattern that many [mobile] sites expect. The change would be from:

> Section: Focus management APIs
>  element . focus()
>   Moves the focus to the element.
>   If the element is the body element, moves the focus to the viewport instead.

to:

> Section: Focus management APIs
>  element . focus()
>   Moves the focus to the element.
>   If the element is the body element, and the body element is focusable, moves the focus to the viewport instead. Otherwise, does nothing.

(and update the relevant details in the algorithm for the "focusing steps")

**Comment by chaals** [comment]
Note to self: Looking at the test cases given, it seemed that there is poor interop, but it might be that I am misreading them. Should probably make some more tests...

**Comment by travisleithead** [comment]
Reviewed the test-case and spec, and don't see a remaining interop difference. Looks like the spec has been dramatically updated for focus handling, and browsers seem to have figured out how to do this interoperably (at least in this thin slice of the web platform).
