### ISSUE TITLE
comments to be selectively preserved despite minification need string or format

### ISSUE THREAD

**Issue by Nick-Levinson** [w3c/html#294]
Minifying removes comments some of which should, however, stay in place for the benefit of website visitors. Many comments are functional even after delivery to a user agent. We need a comment format that minifiers will recognize for preserving selected comments. Comments that should be preserved are (a) those for parsing by some user agents (comments are often prepared for consumption by selected versions of Microsoft Internet Explorer) and (b) those for human consumption after source code is received and renderable as source code at a user agent (such as clarification of a meta element's meaning or a humanly-parsable legal notice applicable only to source code and not to object code).

HTML5 section 8.1.6 does not limit the purposes of comments, forbid minification, or require absence from source code delivered to a user agent (viz., require minifictation). HTML5 says only that it "may have text". That does not bar text meant for consumption by user agents or text meant for understanding by humans using user agents.

Developers of minifiers, whether standalone or included in some other apps, wanting a way to determine which comments to preserve when a Web author wants selectivity in minification would look to HTML5 for guidance on comment format. HTML5 now lacks guidance on how an author should indicate that some comments should be kept by a minifier when others should be deleted, so recent implementations are inconsistent,  but they are shown here in order of utility for consideration for HTML5:

htmlmin 0.1.6 (thus, by convention, beta): "When set, comments will be removed. They can be kept on an individual basis by starting them with a '!' . . . . The '!' will be removed from the final output. If you want a '!' as the leading character of your comment, put two of them . . . ." https://pypi.python.org/pypi/htmlmin/ & https://github.com/mankyd/htmlmin > "Download ZIP" > htmlmin-master.zip > docs > quickstart.rst > optional arguments > "-c, --remove-comments", both as accessed Aug. 15, 2015.

HTML compressor: Follow the standard comment opening tag by any one user-specified character to preserve that comment (https://htmlcompressor.com/compressor/ > Source > show > Comments, CSS and JavaScript > "Keep . . ." > "(?)", as accessed Aug. 15, 2015), i.e., the Web page author may specify a character and put it immediately after the opening tag to preserve the comment that has the specified character.

html-minifier (by kangax): "If you have chunks of markup you would like preserved, you can wrap them". Inside the comment would appear the string htmlmin:ignore (but unclear where inside the comment). https://github.com/kangax/html-minifier, as accessed July 14, 2015. "[T]here's a slight difference in the way HTML comments are treated inside SCRIPT and STYLE elements. In scripts, comment start delimiter ('<!-<span></span>-') tells parser to ignore everything until newline" http://perfectionkills.com/experimenting-with-html-minifier/, as accessed Jul. 15, 2015.

gulp-minify-html can decline to minify "conditional internet explorer comments". https://www.npmjs.com/package/gulp-minify-html, as accesssed Jul. 24, 2015.

The best format I'd recommend would probably be this opening tag:

<!--!

To begin the comment content itself with an exclamation point and not a space, the author would write a double exclamation point. Whether to separate the opening tag from the content with a space would be unaffected. The closing tag would be unaffected.

Past comments on a like proposal at https://www.w3.org/Bugs/Public/show_bug.cgi?id=28832 include that no one need minify any comments and that minification will delete all comments anyway. This proposal is for selectivity at the author's discretion, a principle at the heart of virtually everything in HTML5. It would be a bad idea to require that there be no comments in source code delivered to a user agent and, in terms of page-loading speed, it would be a bad idea to forbid any minification. The page author is in control and should stay in control. This adding of a comment string or format would leave that control in the author's hands, while removing a need to spend hours minifying by hand to achieve the same selectivity at which computers already excel in seconds.

Developing and adding it probably does not require a lot of development work and testing.

The priority may be low to normal.

**Comment by travisleithead** [comment]
Very interesting. I'm trying to think through what the implication would be on the HTML spec. 
- The HTML parser: no change `<!---` and `-->` still delineate a #comment node which will be created an inserted into the DOM.
  - Hypothetically, we could add parser support to somehow skip comments with some designated flag as a client-side processing step, but this seems pointless as one goal of minification is to minimize the bytes-on-wire, so after-transport removal of certain comments (on the client-side) seems ridiculous.
- #comment nodes (their API, and content model rules, etc., as described in the DOM spec) would not need to change either.

So this leaves authoring guidance, if I understand you correctly. We could add some recommended best practices for describing these types of comments to the spec, but I don't think it would be appropriate to make them normative (required). Thoughts?

**Comment by Nick-Levinson** [comment]
This is only for minification as a step before a file is publicly on a website. Standardizing on a flag would support more preprocessors with consistency.

I don't think minification should be performed by a user agent like a browser at the website visitor's client, as that wouldn't save on transmission time, would delay rendering, and would interfere with a website author's intent if the author intends some comments to be available to a visitor or to be used to affect how rendering is done.

If there's no preprocessing and no user agents delete comments, authors would need no guidance. But I can imagine a Web host offering minification of a client's entire site for a fee as a feature to speed page-loading, since faster speed is a goal recommended by Google. My host doesn't offer that but there are many hosts. This flag or something functionally kindred would preserve an author's control while still supporting speedier page-loading. Thus, it should be normative, especially to guide those who design preprocessors, including hosts.
