### ISSUE TITLE
Clarify definition of field where relevant to scheme

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#299]
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=27795">Bugzilla #27795</a>.

Ping @Nick-Levinson

**Comment by chaals** [comment]
From Bugzilla

> In this one context, the word "field" is confusing: "Use only one scheme per field, or make the scheme declaration part of the value." (This appears under "scheme on meta elements" in section 11.2 (http://www.w3.org/TR/html5/single-page.html#non-conforming-features) and reference may also be made to the spec for HTML 4.01, sec. 7.4.4.2 (http://www.w3.org/TR/html4/struct/global.html#h-7.4.4.2).) Searching the single-page file for the string "field" yields over 100 matches, according to my browser, which includes mentions of form fields and "fieldset". In this context, is "property", "property-value pair", or something else meant? Please clarify this instance of "field".

**Comment by stevefaulkner** [comment]
fixed: https://github.com/w3c/html/commit/8431ccf458769958f9d592ed3d584c69380de2af
