### ISSUE TITLE
Current iframe sandbox doesn't prevent download from sandbox child frame

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#301]
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=29100">Bugzilla #29100</a>.
Ping @travisleithead @arronei @adanilo

**Comment by chaals** [comment]
From Bugzilla

> Current iframe sandbox does not prevent download from sandboxed child frame. This allows malicious ads to force download malicious files which users might think that it is served from trusted parent domain.

**Comment by chaals** [comment]
CSP issue?

**Comment by travisleithead** [comment]
I think CSP offers a variety of controls to fine-tune this experience. For example:
- child-src (http://www.w3.org/TR/CSP/#directive-child-src) - prevent the frame from spawning child browsing contexts
- default-src (http://www.w3.org/TR/CSP/#directive-default-src) - restrict all resource-acquiring elements to specific origins or `'none'` to restrict outright. I believe this is the feature the original bug felt was lacking. 

Given this, I'm going to close this issue as "works for me"
