### ISSUE TITLE
Use active voice, not passive.

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#310]
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=27573">Bugzilla #27573</a>

**Comment by chaals** [comment]
There are probably many places in the spec this should be applied.

**Comment by fititnt** [comment]
An advantage of English over other languages is that it is much easier to find tools to evaluate this type of improvement.

I suggest the following:
- Atom Editor plugin: https://github.com/gepoch/linter-write-good
- Shell: http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/
- Perl: https://github.com/devd/Academic-Writing-Check
- NodeJS: https://www.npmjs.com/package/write-good#passive

## See output:

``` shell
$ write-good semantics-embedded-content.include 

In semantics-embedded-content.include
=============
e in HTML, when there is only a single image resource,
                         ^^^^
"only" can weaken meaning on line 9 at column 43
-------------
  However, there are a number of situations for which the author might wish to u
  ^^^^^^^
"However" is wordy or unneeded on line 21 at column 2
(...)
```

Check https://gist.github.com/fititnt/b34f531ed42470412e6fa371e7e7830a for rest of output

**Comment by chaals** [comment]
This is a general editing practice, not an issue. Will be documented in editorial best practice.
