### ISSUE TITLE
Harmonise alt techniques glossary with ARIA glossary

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#312]
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=27924">Bugzilla #27924</a>

**Comment by LJWatson** [comment]
@halindrome can you shed any light on what's needed here? Thanks

**Comment by stevefaulkner** [comment]
closing this as no actionable explanation of change provided, feel free to re-open if an actionable chnage is provided
