### ISSUE TITLE
Editorial issues in 3.2.1 semantics

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#313]
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=21813">Bugzilla 21813</a>

**Comment by LJWatson** [comment]
Think most of <a href="http://w3c.github.io/html/dom.html#elements-semantics">3.2.1 Semantics</a> could do with rewriting because it's both inaccurate and difficult to read.

Have made a <a href="https://github.com/LJWatson/html/compare/master...LJWatson:Issue313-Semantics">first attempt</a> to rewrite it. Review and feedback welcome.

**Comment by arronei** [comment]
@LJWatson I think these change ideas look like they are headed in the right direction. Go ahead and do a PR and I will do some inline commenting for some little tweaks.

**Comment by LJWatson** [comment]
Thanks @Arronei <a href="https://github.com/w3c/html/pull/339">PR 339</a> assigned to you.

**Comment by LJWatson** [comment]
Closed with PR #339
