### ISSUE TITLE
<img> elements ignoring http status code

### ISSUE THREAD

**Issue by henke37** [w3c/html#322]
The img element appears to have a loophole in the loading algorithm (formally "update the image data") that results in responses with an error status code (such as 404) succeeding to load, if the response body is a valid image.

In other words: an img element pointing at a resource that returns a 404 response that is an image will not fire the error event you'd expect from a 404 response.

**Comment by travisleithead** [comment]
I think that is intentional:

Just below the definition of [fully decodable](http://w3c.github.io/html/single-page.html#fully-decodable)

> Whether the image is fetched successfully or not (e.g., whether the response status was an ok status) must be ignored when determining the image’s type and whether it is a valid image.
> 
> NOTE: This allows servers to return images with error responses, and have them displayed.

Since in this case, the `<img>` would fully load and display its image data, I think it would be more confusing to fire an error event...

**Comment by henke37** [comment]
The intent may have been to display the error response. But it has more consequences than that.

I don't mind the error response being shown. I'm actually positive to that.

The problem is the script viewpoint. For a script that cares about the actual, requested, resource it's a problem. You don't want to proceed under the false assumption that the resource is fine and ready for use. At a minimum the script may want to alert the user that something went wrong.

I think that the img element has a get out of jail card here. It's replaced content. And the spec is awfully loose on how to work with that. As an example, some browsers choose to show an icon in the area for the image if it fails to load.

I say, why not repurpose that semantic and make it standardized? Do some magic that might involve shadow dom to show the result, yet not officially load it at the same time. Some authors would love to be able to specify their own error icon in a stylesheet.

**Comment by chaals** [comment]
This suggestion looks like a proposal for change that would break implementation, assuming that implementation matches the spec.

If developers are relying on this behaviour now, changing it to help other developers isn't obviously a win :S

**Comment by henke37** [comment]
I find that it's unlikely that anyone would depend on the current behavior. Developers generally don't expect error replies to result in success. And it's rather rare to see a server setup to return images for error responses.

**Comment by prlbr** [comment]
> And it's rather rare to see a server setup to return images for error responses.

I’ve actually done that. I think it’s a sensible response for deleted images on remote image hosting services for example.

**Comment by henke37** [comment]
I am afraid that you and me are both in the minority here. It takes effort to do this and most people don't.

**Comment by travisleithead** [comment]
We're going to need implementor feedback on this one--would also love to see how much of the web would be impacted, and what that impact might be...

**Comment by henke37** [comment]
To be specific: what needs measurement is how often image resources get error responses, how often said error responses are valid images and how often scripting checks for image load failure. As well as some samples of applications that do look for failure/success and would behave different than the author intended in this corner situation.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
