### ISSUE TITLE
The current state of HTML input elements

### ISSUE THREAD

**Issue by kevinSuttle** [w3c/html#324]
I wrote up a synopsis of forms and suggestions for baseline HTML form inputs. Hopefully these are useful. 
http://codepen.io/write/the-current-state-of-web-forms

**Comment by stevefaulkner** [comment]
Hi Kevin, I get a 404 on the link you provided

On Friday, 29 April 2016, Kevin Suttle notifications@github.com wrote:

> I wrote up a synopsis of forms and suggestions for baseline HTML form
> inputs. Hopefully these are useful.
> http://codepen.io/write/the-current-state-of-web-forms
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/html/issues/324

## 

## 

Regards

SteveF
Current Standards Work @W3C
http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/

**Comment by kevinSuttle** [comment]
Oh, I posted a link to the editor. Apologies. http://codepen.io/kevinSuttle/post/the-current-state-of-web-forms

**Comment by chaals** [comment]
This set of feature proposals should go through the incubation process at http://discourse.wicg.io to get traction with implementation.

FWIW I think they're generally pretty sound, so I hope that they make some progress there.

**Comment by chaals** [comment]
This is a set of proposals, and each needs incubation. If individual proposals have traction and are ready to migrate into HTML, please open individual issues for them.
