### ISSUE TITLE
Add event handler attributes (e.g. onplaying, etc) to HTMLMediaElement (and likely others)

### ISSUE THREAD

**Issue by wolenetz** [w3c/html#335]
Thanks to @foolip for raising similar issues on [MSE](https://github.com/w3c/media-source/issues/66) and [EME](https://github.com/w3c/encrypted-media/issues/176) specs, and for @domenic and @annevk for their guidance in https://github.com/w3ctag/design-principles/issues/29#issuecomment-215560292, I looked to see if the extended HTMLMediaElement needs these, too. It looks like HTML5.1 media element spec has an inconsistent mixture of objects (which inherit transitively from EventTarget) with and without EventHandler attributes for their events.  (e.g. MediaController has onplaying for 'playing', but HTMLMediaElement just has 'playing' but no onplaying attribute). Per the w3ctag guidance, these missing EventHandler attributes need definition.

**Comment by paulbrucecotton** [comment]
> Per the w3ctag guidance, these missing EventHandler attributes need definition.

@travisleithead: Can you open an HTML 5.1 issue for these attributes?

**Comment by foolip** [comment]
There are all on [`GlobalEventHandlers`](https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers) instead of `HTMLMediaElement`, as is the case for other HTML elements as well.

EME does add an event fired on `HTMLMediaElement`, but I'm not sure what to suggest. Extending `GlobalEventHandlers` would be more consistent with the other events, so I guess that.

**Comment by domenic** [comment]
The reason they're on GlobalEventHandlers is because events bubble, so you want to be able to allow `parentEl.oneventname = ...` to catch the bubbling event. So I guess if it bubbles it belongs there.

**Comment by chaals** [comment]
@travisleithead can you check this milestone, and if necessary bump it please

**Comment by chaals** [comment]
Didn't happen. @travisleithead I've assigned it to the next-but one draft, but feel free to get it done earlier :)

**Comment by zcorpan** [comment]
@domenic event handlers are generally put in GlobalEventHandlers even if the event in question doesn't bubble. I guess it is a simpler model.

**Comment by travisleithead** [comment]
Turns out a previous update added these :) We are in sync.

**Comment by travisleithead** [comment]
(e.g., GlobalEventHandlers is [relatively] in sync)
