### ISSUE TITLE
4.10.1.1. Writing a form’s user interface - misleading/ confusing example & guidance on field/ label containers

### ISSUE THREAD

**Issue by karlgroves** [w3c/html#336]
4.10.1.1 contains the following sentence:  

> Each part of a form is considered a paragraph, and is typically separated from other parts using p elements. 

(For reference, the section on paragraphs is 3.2.4.4. Paragraphs)

Although this guidance fits squarely within the definition of a paragraph (at least as far as HTML is concerned), it _feels_ wrong. More importantly I think the general consensus within modern development practices is that a `<p>` is not the right element for this job - or, at least that there are other elements that can contain phrasing content that may be better, such as `<div>`.  In fact, what surprised me most about this guidance was that I've not seen a `<p>` used this way in a very long time.

There are several code examples within 4.10.x that would need to be modified as well. If desired, I can submit a PR with changes.

**Comment by StommePoes** [comment]
It "feels wrong" because to developers, a paragraph means something. However, we're wrapping label-input pairs for styling reasons, not to mean anything. &lt;div&gt; makes more sense in that case.

**Comment by stevefaulkner** [comment]
> There are several code examples within 4.10.x that would need to be modified as well. If desired, I can submit a PR with changes.

let's see what people have to say about the change, but if no reasoned objections PRs are welcome
