### ISSUE TITLE
Why restrict `header` and `footer` from nesting

### ISSUE THREAD

**Issue by chaals** [w3c/html#34]
The specification says that `header` and `footer` elements cannot contain each other, so cannot be nested.

There is a [longstanding bug](https://www.w3.org/Bugs/Public/show_bug.cgi?id=19054) and some use cases, and it isn't clear what purpose is served by the restriction.

Seems reasonable to me that we drop the restriction. Does anyone know of something that would actually break?

**Comment by AndySky21** [comment]
The long-standing bug linked here has some use cases but as it emerged in the text, the use they make of footer element is too loose (appendices for ebooks, or the container for the _whole_ text of a license agreement).

As it was stated in the messages, I would suggest to drop the suggestion that footers can contain articles or appendices, or at least clarify what kind of appendices might be put inside. Not the whole Appendices section of a book probably.

**Comment by iandevlin** [comment]
Unfortunately the 'longstanding bug' that has been linked to won't open for me (the whole bug tracker appears to be down) so although I cannot think of a specific use case that would warrant nested `header` and `footer` elements, I also don't see why it should be explicitly restricted.

**Comment by stevefaulkner** [comment]
> Seems reasonable to me that we drop the restriction. Does anyone know of something that would actually break?

[`header` is defined](http://w3c.github.io/html/semantics.html#the-header-element) as 

> The header element represents introductory content for its nearest ancestor sectioning content or sectioning root element.

as `header` itself is neither  sectioning content or sectioning root, it makes no sense to allow a `header` as a child of `header`. 
Suggest we add some advice to spec to effect that if there is a circumstance where an author thinks `header` or `footer` needs a nested `footer` or `header` then use a `section` element in place of the outer `header/footer`

**Comment by chaals** [comment]
This issue has been duplicated by #273 - closing here, and I'll put a pointer there
