### ISSUE TITLE
Adding additional attributes to HTMLMediaElement

### ISSUE THREAD

**Issue by Sworddragon** [w3c/html#346]
This ticket was originally posted here ( https://www.w3.org/Bugs/Public/show_bug.cgi?id=29481 ) and got now forwarded to this tracker.

**Comment by paulbrucecotton** [comment]
Note that W3C Media Stream Extensions CR contains a [VideoPlaybackQuality object](http://www.w3.org/TR/media-source/#videoplaybackquality) that may be related to the request for more HTMLMediaElement attributes about a video stream.

**Comment by chaals** [comment]
Fair enough. The other feature requests, as per the [contribution guidelines](https://github.com/w3c/html#contributing-to-this-repository) should be incubated to demonstrate traction before they are likely to be accepted as changes to the HTML specification.

**Comment by Sworddragon** [comment]
Basically the same I have posted in #344. If somebody finds this feature request useful feel free to take over the incubation process.
