### ISSUE TITLE
Correct allowed role info for the dd and dt element

### ISSUE THREAD

**Issue by cpandhi** [w3c/html#352]
The latest Editor’s Draft, 6 May 2016 HTML 5.1 in github spec says 
Allowed ARIA role attribute values:
    Any role value. 
The latest Editor’s Draft, 10 March 2016 Document conformance requirements for use of ARIA attributes in HTML says
The dd and dt elements have no corresponding role (implicit or allowed)
Which document is correct? and so the incorrect document needs the correction.

**Comment by stevefaulkner** [comment]
The ARIA in HTML is the normative specification, the HTML specification content is informative. The HTML spec needs updating, thanks for raising the issue.

**Comment by travisleithead** [comment]
Fixed by #443
