### ISSUE TITLE
Broken links in draft intro

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#36]
This Version: http://www.w3.org/TR/2016/WD-html-5.1-20160113/ - Document not found

Latest version: http://www.w3.org/TR/html/ - This points to HTML5, W3C Recommendation 28 October 2014. Is it correct?

Previous Versions: http://www.w3.org/TR/2014/WD-html51-20140204/ - Is this correct? Shouldn't it be http://www.w3.org/TR/2015/WD-html51-20151008/ (HTML 5.1, W3C Working Draft 08 October 2015)?

~~Issue Tracking: GitHub (https://github.com/MicrosoftEdge/HTML/issues/) - Incorrect link~~

EDIT: the multipage version is appreciated :smile: but unfortunately some links are broken! (all links to `table sorting model` in [semantics.html](https://w3c.github.io/html/semantics.html) lack the `#` and as such they don't work).

**Comment by adrianba** [comment]
Merged as 670f986203f618b614244ae0dda8b2d22cc1454f

Note the broken table sorting links issue is tracked in issue #77.
