### ISSUE TITLE
Consider adding an informative table - Categories of form elements

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#360]
this spreadsheet was created by @simevidas and got a lot of interest on [twitter ](https://twitter.com/simevidas/status/729858190410698753)
Google doc:
https://docs.google.com/spreadsheets/d/1S_5AewU0xanq791jfm0l91T1u-t9G6Ze_GKjrlUEfDY/edit#gid=0

Maybe something we should consider adding to spec.

**Comment by travisleithead** [comment]
Table created based on @simevidas doc. @stevefaulkner and friends, please review PR #406
