### ISSUE TITLE
Document latest version logic for /TR/html(\d)*/

### ISSUE THREAD

**Issue by plehegar** [w3c/html#361]
/TR/html always to latest version of HTML, ie a WD
/TR/html5/ always to HTML 5.0
/TR/html51/ always to HTML 5.1
/TR/html52/ always to HTML 5.2
...

**Comment by plehegar** [comment]
Also document the branching logic. See
 https://www.w3.org/2016/05/10-html-editors-minutes.html#item04

**Comment by plehegar** [comment]
And document on picking issues with editorial for beginners

**Comment by plehegar** [comment]
Also suggest to add name in ack section when making a pull request.

**Comment by travisleithead** [comment]
Doesn't look like PR #400 fully addressed this issue given the above...so keeping it active.

**Comment by plehegar** [comment]
- [ ] document on picking issues with editorial for beginners
- [x] suggest to add name in ack section when making a pull request.

**Comment by siusin** [comment]
Updated --
/TR/html/ should point to HTML 5.2 (done)
/TR/html5/ points to HTML 5.2 (done)

We'll request to obsolete the previous versions in April.

**Comment by chaals** [comment]
@plehegar : 

> document on picking issues with editorial for beginners
 suggest to add name in ack section when making a pull request.
rse
These aren't about this issue. We need to improve our documentation (so does the universe) but that should not keep this issue open.

@siusin, those pointers now update according to what is the latest version, right If so, I think we can close this issue - I'll let you confirm by closing it :)
