### ISSUE TITLE
Review normative references for changes from HTML5

### ISSUE THREAD

**Issue by arronei** [w3c/html#363]
- raise issues of changes
- identify tests

**Comment by plehegar** [comment]
This might be useful as well: https://github.com/whatwg/html/commit/8f038efb9d21b87a73c7e00a68873153f3e060e6

**Comment by arronei** [comment]
DOM, Fetch, URL understand what we are linking too.

**Comment by chaals** [comment]
For 5.1 this is done. For 5.2 let's open a new issue…
