### ISSUE TITLE
Things we don't expect to take into HTML

### ISSUE THREAD

**Issue by adanilo** [w3c/html#365]
https://github.com/whatwg/html/commit/a0005518c8828690805d59c8640af3d0935aea42

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/ccd4d995daab83c93d19db45d5f86928b6c0e39f done

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/264f97c558d16aebffac316697713108c4597f2f

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/05f9f3266d6050b8b299ec365fdc63d5eab5b2b3

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/8c6c3eb4efe8641ec155c13afc77abfe9161eea0

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/948a19de67facb6043fc8f52650e411551c2e1cd

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/6c38a3a0594809a14c1a28056f6bed18d98d7088

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/59b7e2466c2b7c5c408a4963b05b13fd808aa07a done

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/de04d13347a67e616304f66a7c3a71939b8d2992

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/4a0016570040070dff2a26c09430a601611ec57a

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/1490eba4dba5ab476f0981443a86c01acae01311 done

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/392c10a84c9fffc20d05157343d6f92fa55dc71d canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/56ceea878e32d6bc308b46d5f4b33e8b08d3d749

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/0a668271cdef3c0b165ca546f5f3a66eeab78e31

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/1cae7e940b9d7cbfe5fd463fc2895519505310bd

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/3d4f9b12a95fbda87c7358fe545d7475ac004f24

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/99373f9cb9562201a6287929f1fae25716699677

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/5ec3672ab500496bd97148e51f7c874004c33059 we're not hip

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/7f99b089c9f6587e164e65e079be57f4eef3cdad

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/495262aa91d8b525095e0e629e5bcebc8e04bd53

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/18b243aafe328f5cc2095ddfdcdabd585f74b026

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/faec3a50ea181f322ab9819975e285ced34a0308 related to ping

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/6fc8c2eedb650f37f3f6ffdfcf9728e7a8958a8e workers

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/9c45e28f3496100b86eeb5cf866ec664fa61a010

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/ed1c7c24b777c946b4b616349b3ba58ec7f4e964

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/a9d8e7b04f7ed5d0f44612c567d93b06b50d76a3

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/5c3e4ab770c719ff55b439f314817b83f5a8cc96

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/a4b9eef6ff40c394cf6ec9247ce6286795348f3f canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/24a0de0f71ed6041a4feb0ab751c3f3cfb13926e canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/772ba0fdc3b2be1b7253cd895c1cb36ca39dc430

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/49f9e0489bd69fe022e1d3597021f2af9964c9b1 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/ca522a7478bc0db74a1f96f95ae499087b3655ec canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/6170556321e1b0274155c145bea30f08524ccfcd

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/78e6d56a64eb7d8ed7ee29b93ea37789f249b3ef web sockets

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/055f54045075922ad15938f01da24080cb5a3c34

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/3dadbcad063a10b586ef52dd4b427aa339048ee7 web sockets

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/249c29f258c3740cce2e0f5d1edd8621ec66a791

**Comment by adanilo** [comment]
Being checked for 5.1 https://github.com/whatwg/html/commit/740634d0f30a3b76e9da166ac2fa8835fcc073ab canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/6f47a53c915ba001cb9e8f7d106a4dcab2a03f98 server sent events

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/06059a864e93441cb85d10d719cf306985aa1c48 done

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/96be6c02315d677c48ac334a689a48cbd1929c95

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/26f5645b0c161c60903e945adace86165d56c03c web messaging

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/d09b0457aec355d7fbe88f9401fe3f2f0eab566f canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/0b88bf3d79e44382ae264664b15e5b12893b025c canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/78b44df4f67fc82ec564ae9c65d67f6e9993ea4d

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/df16ff393210dde1abf7c22fd7660f0ec70c357e

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/17336ad69be4744dfc17194f2ee51bd730ca4d93 web sockets

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/3d0c45406d4259533c676bf7bd30bb4b918fe8e2

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/929be879dfcad567bfdee14d33263cb13d2b189e web sockets

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/e2bd61d1e4bd356b747e15c4e724a75eadbb25ac web sockets

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/6115ed5f8078656a4f1972ae90d8d99368da9f1b

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/0c029fc38775a6e88d2aee358a3942f157ba8271 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/afab06c9a6f48963f4713eed2c8a75324712a9b5 workers

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/60e5fc361572c8d0ef576dc78542ec4b845aef5b web messaging

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/78806b0a466dd8f1f04fdcd5bc51ca002ccbf31f

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/43ad288bc5dfc567c232afb292d16be1929a51e2 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/fc53707c221ed6a6fd3c754feccabef88c9995f7

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/52ef2b19a2f818a032d12c0bc708c058784b9224 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/50d7221be05f8944d7ee3ad5652401bd6e7bb91d

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/fedaaea0c0ef73eb976cab97c7c94fa0f798af73

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/806874fa426589be159c3c2e8266e00ade80e2e9 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/b0e6f35926508b73dc49478c6fcbe9d1d1d0be73 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/b0244d358611b302c56d503ae7822153dd862b04

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/f5a6059b327506b43dc4e3e4770148b40f68e8e2 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/a4fb976e4cd1865f2d4259f1783866c3add40f66 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/536a96229ced274b80f78ad791c34ecfe11b289b workers

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/4c59797403ca6545ca54ec2808264f5723727e7a canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/f7367217e5c488267204982faec075313cac3c7c editing

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/99f0f1ae017523276ea4dd5784ec63a23a23834d done

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/4081f129ac4667fccd365b4a68de4aff0211b2f1 workers

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/2749fa5eddea79586e58cb5387b713f44b3b035e canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/817da9577b565e808d7af0295e1affc094887418

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/5c44abc734eb483f9a7ec79da5844d2fe63d9c3b done

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/fcb0756dd94d96df9b8355741d82fcd5ca0a6154 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/09f0e7947d7e50685b4c2b769deea4f0e04b8e9c server events

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/09f0e7947d7e50685b4c2b769deea4f0e04b8e9c canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/7c9ba543a60a150e50ce6c10877fe330aabb95cc canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/c2a3b2a2e3db49c14b486a5e99acf7d10cfe8443 done

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/634698e70ea4586d58c989fa7d2cbfcad20d33e6 done

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/c92fee202c1b4076209c127fc2151df1d2f68f98 canvas

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/24ab0606cb83dbad6e9ee627b4d8fc55a9bb5f5a

**Comment by adanilo** [comment]
https://github.com/whatwg/html/commit/6bc91faf94b35b2b21bb40d7b3d6f519bd715676 workers

**Comment by chaals** [comment]
WHATWG-specific aministrivia:
- https://github.com/whatwg/html/commit/4b4c941e58849da433a2e7706642db222476e536 -

**Comment by chaals** [comment]
Editing:
- https://github.com/whatwg/html/commit/8f144e8df1feb00b19070415486b09a70ab41442
- https://github.com/whatwg/html/commit/a5f708cf5cbb909345a0da695fb86b2a6cd9d3a0

**Comment by travisleithead** [comment]
Shared Workers
- https://github.com/whatwg/html/commit/18c891f1a300a336d3df5b76fdae3b1d77b0b468

**Comment by travisleithead** [comment]
This is documentation for historical archives--I see no reason to keep this issue open.
