### ISSUE TITLE
Complete privacy questionnaire

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#366]
The Privacy IG has asked us to complete their <a href="http://gregnorc.github.io/ping-privacy-questions/">privacy questionnaire</a>.

**Comment by chaals** [comment]
Here's a first draft:

1.) Does this specification have a "Privacy Considerations" section?

Yes, there is a [security and privacy considerations](https://w3c.github.io/html/webappapis.html#security-and-privacy) section. There is [another one for media](https://w3c.github.io/html/semantics-embedded-content.html#security-and-privacy-considerations), and yet [another for `registerContentHandler` and `registerProtocolHandler`](https://w3c.github.io/html/webappapis.html#security-and-privacy).

2.) Does this specification collect personally derived data?

Not inherently.

3.) Does this specification generate personally derived data, and if so how will that data be handled?

Not inherently

4.) Does this specification allow an origin direct access to a user’s location, and if so is that information minimized?

No.

5.) How should this specification work in the context of a user agent’s "incognito" mode?

It should work the same.

6.) Is it possible to spoof/fake the data being generated for privacy purposes?

For real form attributes it is, for hidden inputs it has to be done by expecting to find something. This _can_ be done using e.g. browser extensions.

7.) Does the standard utilize data that is personally-derived, i.e. derived from the interaction of a single person, or their device or address?

No

8.) Does the data record contain elements that would enable re-correlation when combined with other datasets through the property of intersection (commonly known as "fingerprinting")?

There are some features that can be used for fingerprinting. These are generally identified.

9.) Is the user likely to know if information is being collected?

The user doesn't know what will actually _get submitted_ by a form - hidden inputs can be added and carried along.

10.) Can the user easily, preferably through an element of the GUI, revoke consent granted to a particular feature?

Don't think HTML has data collection features beyond forms

Hidden form inputs, and what data will actually be sent with a form, could be detected by a browser extension but this is generally not a feature exposed to normal users.

11.) Once consent has been given, is there a mechanism whereby it can be automatically revoked after a reasonable, or user configurable, period?

Not Applicable

12.) Does this standard utilize strong end to end encryption?

HTML does not require the use of end-to-end encryption, and given the enormous deployed legacy it is unlikely to do so in the near future. However it does allow for it in general.

**Comment by chaals** [comment]
I'm going to close this issue, and if there are concrete changes we need to make to our privacy implications section - like having one instead of 3 - they should be opened as individual issues.
