### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/html#371]
"The term empty, when used of an attribute value, Text node, ..."

Should it be "used on an..."
http://www.w3.org/TR/html5/infrastructure.html#terminology-0

**Comment by chaals** [comment]
The original is grammatically correct english. Just not a very simple way to say things.

I think a better way to say this is "When an attribute, Text node, … is described as _empty_ …"

**Comment by travisleithead** [comment]
@LJWatson's PR addresses this, I believe.
