### ISSUE TITLE
Remove non-interoperable bits of autofill

### ISSUE THREAD

**Issue by chaals** [w3c/html#372]
A lot of what is in there is not implemented interoperably

**Comment by travisleithead** [comment]
I think we need to remove `requestAutoComplete` as Chrome is deprecating, and (I think) they were the only ones to implement. See:
- https://developers.google.com/web/fundamentals/design-and-ui/input/forms/use-request-auto-complete

And per: https://codereview.chromium.org/1958543002/ it looks like it may have been removed already.

Interop data from Chrome Status: https://www.chromestatus.com/feature/5092662981951488

A little further info is needed for the autocomplete attribute extensions. They may have much more utility and wide implementation.

**Comment by travisleithead** [comment]
Note: removal of requestAutoComplete() is in PR #446

**Comment by travisleithead** [comment]
Tested support for the extended autocomplete feature set (the "autofill detail tokens").

https://jsfiddle.net/54mbLy9d/1/

Results: 
- Edge and Chrome: the DOM API seems to **reflect** (unqualified) the content attribute. This makes it impossible to tell whether the implementation is processing these extra tokens. Edge doesn't, and my guess is that Chrome doesn't either.
- Firefox does implement the IDL attribute `autocomplete` as reflecting **only known values** for the content attribute. In this way, we can see that they clearly don't support (e.g., process) any values outside of the `on` and `off` value.

Looking for help in testing Safari and validating Chrome.

**Comment by travisleithead** [comment]
I agree with @LJWatson that these "autofill detail tokens" are at-risk from 5.1. Either that, or we can make the IDL attribute simply reflecting the content attribute, taking the test-ability out of the feature :(

**Comment by chaals** [comment]
Safari 9.1 on MacOS X 101.10 gives all the expected values (nothing for the last two…). Not that I took the time to understand the test but I hope it tells you something useful.

**Comment by LJWatson** [comment]
Closed with #537
