### ISSUE TITLE
example of language detection fallback, no mention of pragma

### ISSUE THREAD

**Issue by r12a** [w3c/html#376]
https://www.w3.org/TR/html51/dom.html#the-lang-and-xmllang-attributes
3.2.5.3. The lang and xml:lang attributes, the example starting "For example, if a document is delivered over HTTP"

This example was added in response to https://www.w3.org/Bugs/Public/show_bug.cgi?id=16979

This new issue is just to add a suggestion build on the added text.

The example describes a situation where there is no lang attribute in scope but there is an HTTP header with language information.  It doesn't mention, however, that the HTTP header is only applied if there is no pragma-set default language set. It should probably say something like: 

> ...if a document is delivered over HTTP and the Content-Language HTTP header is specified with a value "en", and there is no pragma-set default language, then for any element in the document that does not itself have a lang attribute nor any ancestor of that element, the fallback language for the element will be English

In a way, i'm a little worried about that though, since i don't want it to seem like we're encouraging the use of the pragma for setting language.  If there's some wording we can weasel in order to avoid that, i'd be happier. Alternatively, if you think this is just splitting hairs, i'd be happy to leave as is, too.

**Comment by LJWatson** [comment]
Closed with #533
