### ISSUE TITLE
Correct allowed role info ofr iframes, the aria in html conformance table does not allow role of presentation for iframes.

### ISSUE THREAD

**Issue by cpandhi** [w3c/html#377]
HTMl5.1 draft states the allowed roles for iFrames areAllowed ARIA role attribute values:
    application, document, img or presentation.
While the aria in html conformance table states the allowed roles are Role: application, document, or img.
It does not allow role of presentation.
https://www.w3.org/TR/html-aria/#docconformance

**Comment by travisleithead** [comment]
Fixed by #443
