### ISSUE TITLE
Fix "exported" links so that they only jump out of the spec in predetermined places

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#378]
Right now, we have quite a few anchors that link to external specs and by clicking a link, you are often jumped out of our spec into the linked spec. These include:
1. Terms defined in `single-page.bs` that use linking text off to external URLs
2. Exported anchors (e.g., `<a spec="url">term</a>`)

In both cases, we should put dfns in place that "capture" all these external links, and allow the user to then link out to the external definition. This will avoid reader-surprise.

(We think there is a way to do this in the updated Bikeshed system by wrapping an anchor in an dfn...)

**Comment by travisleithead** [comment]
Maybe related to: https://github.com/tabatkins/bikeshed/issues/356, but filed https://github.com/tabatkins/bikeshed/issues/723 directly...

**Comment by travisleithead** [comment]
Checked, and found that an auto-linking anchor in a dfn generates an error because the auto-link part must also be defined elsewhere, and this causes two conflicting definitions 😢.

**Comment by chaals** [comment]
@travisleithead is this related to #809 ?

**Comment by travisleithead** [comment]
@chaals no, #809 is about populating the Bikeshed database with exported DFNs automatically. This is more about definition navigation within a spec.

Having said that. There's no action to take yet, so moving to future.

**Comment by chaals** [comment]
Is the action here to provide an internal "definition" of terms that are actually defined elsewhere, and manually link each of those to the source definition?

**Comment by travisleithead** [comment]
@chaals yes. We have a rather large section of the spec ([Dependencies](https://w3c.github.io/html/infrastructure.html#conformance-requirements-dependencies)) that is intended for this purpose:

but these are a mixture of external links and **dfn**s.

We could consider just removing all but the most general dependency notices from that section, and leave the actual specifics to the [Terms defined by reference](https://w3c.github.io/html/fullindex.html#index-defined-elsewhere) which is automatically generated by Bikeshed (which is a more accurate and up-to-date reference of what is actually depended on by the spec's prose).

At this point, I'm not expecting a new Bikeshed feature will appear to help solve our problem. I think our choice here is to either:

1. Leave the spec as is--all links defined outside the spec will just link there directly. If a new Bikeshed feature appears in the future, we could consider using it in the Dependencies section.
2. Clean-up/lighten the Dependencies section to describe high-level dependencies--not ever possible cross-link.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
