### ISSUE TITLE
Obsolete value for type attribute on <menu>

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#38]
Admittedly, this issue refers to an element which has met a terrible fate (hasn't it?) due to lack of implementation.

The allowed keywords for `type` attribute on `<menu>` element have been listed as `popup` and `toolbar` since [May 2013](https://www.w3.org/TR/2013/WD-html51-20130528/interactive-elements.html#the-menu-element) and up until [October 2015](https://www.w3.org/html/wg/drafts/html/master/semantics.html#the-menu-element). Now the current version of the draft has aligned with its original definition, mapping the popup state with the `context` keyword. I think `popup` value should be listed among the obsolete features, in order to make this change more evident.

**Comment by arronei** [comment]
This is document in the changes seciton as being changed from `popup` to `context`. And there is only one implementation that has already implemented as 'context'. I think we are okay not putting anything in the obsolete section.
