### ISSUE TITLE
Clarification onof text on the definition of row and column headers.

### ISSUE THREAD

**Issue by richschwer** [w3c/html#380]
# From  http://w3c.github.io/html/tabular-data.html#header-and-data-cell-semantics

A header cell anchored at the slot with coordinate (x, y) with width width and height height is said to be a column header if any of the following conditions are true:

```
The cell's scope attribute is in the column state, or
The cell's scope attribute is in the auto state, and there are no data cells in any of the cells covering slots with y-coordinates y .. y+height-1.
```

A header cell anchored at the slot with coordinate (x, y) with width width and height height is said to be a row header if any of the following conditions are true:

```
The cell's scope attribute is in the row state, or
The cell's scope attribute is in the auto state, the cell is not a column header, and there are no data cells in any of the cells covering slots with x-coordinates x .. x+width-1.
```
# 

Unless I'm misreading this, it's saying that a cell is a column header if there are no data cells below it and it's a row header if there are no data cells to the right of it. That seems backward. Don't you mean to say y-coordinates 0..y-1 for column header and 0..x-1 for row header.

**Comment by chaals** [comment]
I need to check while I am thinking carefully, but at first glance it looks like you are right.

**Comment by chaals** [comment]
Missed the milestone. Rescheduling
