### ISSUE TITLE
Update all TR links to https

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#399]
See https://github.com/w3c/echidna/issues/282 for the upcoming publishing requirement details.

**Comment by plehegar** [comment]
Not all TR links. Only TR headers and SOTD ones.

**Comment by mikewest** [comment]
Why not TR links? If those documents are available over HTTPS, it seems reasonable to link to them over HTTPS.

**Comment by ZoeBijl** [comment]
Aren't all http links automagically forwarded to https?

**Comment by travisleithead** [comment]
Seems like it would be easier to change all TR links at once for consistency. If the TR site supports HTTPS, then I don't see why not.

**Comment by plehegar** [comment]
Required all links to W3C documents to use https would be a huge burden on editors imho. We're breaking them already on several fronts (respec, bikeshed, old pubrules, new pubrules, etc.) so I worry about adding more and more requirements on them. Now having said that, my comments was only about the required scope of this change. We can certainly use HTTPS for all links in the HTML spec (i've changed a few myself in the past).

**Comment by plehegar** [comment]
A good chunk got addressed in 04c44434aadf7eb0eaad0b7de7fc79562975b412
