### ISSUE TITLE
p end tag omission rules

### ISSUE THREAD

**Issue by prlbr** [w3c/html#4]
I noticed that the list of elements before which a p element’s end tag may be omitted at
(1) http://w3c.github.io/html/#the-p-element
is different from
(2) https://html.spec.whatwg.org/multipage/semantics.html#the-p-element
(3) https://www.w3.org/TR/2015/WD-html51-20151008/semantics.html#the-p-element
Is this intentional? In particular, I’d like to see the figure element included which (1) lacks but which is included in (2) and (3).

**Comment by travisleithead** [comment]
I believe this was a merge problem due to hgroup being in the list of tag omission...

**Comment by travisleithead** [comment]
Fixed by PR #10

**Comment by prlbr** [comment]
Thanks!
