### ISSUE TITLE
image not loading

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#416]
yesterday I added an image https://github.com/w3c/html/blob/master/images/dialog.png
to http://w3c.github.io/html/interactive-elements.html#the-dialog-element, it is not loading any ideas why? @plehegar?

**Comment by plehegar** [comment]
It seems to work now. I see it in https://github.com/w3c/html/blob/gh-pages/images/dialog.png and in the spec.

**Comment by plehegar** [comment]
@stevefaulkner feel free to reopen if you still have the loading issue.
