### ISSUE TITLE
IntersectionObservers

### ISSUE THREAD

**Issue by plehegar** [w3c/html#420]
[[
For each fully active Document in docs, run the update intersection observations steps for that Document, passing in now as the timestamp.
]]
This step should be pushed to HTML.next since intersection observers are still in incubation.

**Comment by plehegar** [comment]
Check https://wicg.github.io/IntersectionObserver/#event-loop before reintegrating it for HTML.next

**Comment by travisleithead** [comment]
Closed by #423
