### ISSUE TITLE
Keygen element removal

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#43]
The `keygen` is stated to be in the process of being removed from the Web platform, probably due to a lack of implementations, and its use is discouraged.

So why isn't it listed as obsolete feature?

**Comment by chaals** [comment]
It has been widely implemented, but I'm not sure how well. There was a pretty lively discussion about its proposed removal, and we should look at the outcome of that before simply dropping it.

**Comment by AndySky21** [comment]
That's much clearer now.

If you are not sure, probably advising authors to check by themselves if it works as expected before using it in production would be better than just stating it should not be used. This way implementers won't feel it's safe to drop support of it, I guess.

Thank you for the answer!

**Comment by chaals** [comment]
It's an open question because it may be the case that it gets dropped from implementations - we'll have to watch and see how this unfolds

**Comment by chaals** [comment]
See also ["The keygen element": The only supported signature algorithm is the outdated and insecure md5WithRSAEncryption. The element should at least have an optional signature algorithm, with the option to use the more secure sha1WithRSAEncryption and sha256WithRS](https://www.w3.org/Bugs/Public/show_bug.cgi?id=13518) in bugzilla

**Comment by bblfish** [comment]
The issue is that something good should be in its place before it gets removed, as it is important in allowing cheap and secure client certificates to be created - indeed ones that don't necessarily need to be created by a CA. ( see http://webid.info/spec/ ) There are many ways to improve what is not good in the current system for sure (as there always is in most elements of browsers). But TLS client certificates are actually the only secure and efficient method of authentication where the user is in control that are available in browsers. 

In any case there is a discussion of these issues in the W3C TAG https://github.com/w3ctag/client-certificates as this touches many elements of the browser from crypt to UI and more.

**Comment by ZoeBijl** [comment]
Before it gets removed, where can we find a replacement for this feature?

**Comment by chaals** [comment]
This is a main topic of discussion in the [current TAG thread](http://www.w3.org/mid/op.yh9rtjsbs7agh9@widsith.local) on this issue. While none of the participants there (except me) are members of Web Platform WG, I'm watching that thread.

**Comment by stevefaulkner** [comment]
+1 to remove, 

> since the only browser that supports <keygen> currently is Mozilla, who plans to deprecate regardless of what the TAG says, then it can also be justified to remove from the standard today as **there is no
> interoperability**.
> https://lists.w3.org/Archives/Public/www-tag/2016May/0013.html

**Comment by ZoeBijl** [comment]
Thank you @chaals. I've talked this through with Léonie and will let people more knowledgeable on the subject decide on this.

**Comment by hillbrad** [comment]
+1 to remove.  It is either not currently supported or slated for removal from all modern browsers, and the certificates that could be generated with the obsolete algorithm specified would not be trusted by all modern browsers. 

If it needs a replacement and what to replace it with is a distinct issue.  We should not propagating this obsolete and unsupported feature into the next stable version of HTML.

**Comment by chaals** [comment]
As far as I can tell from trying it `keygen` works in both Mozilla and Safari. (I believe it also works in presto-based Opera, which is actually in use, although that's only of historical interest).

**Comment by chaals** [comment]
As [resolved by the working group](https://lists.w3.org/Archives/Public/public-html/2016Jun/0001.html) this is at risk for HTML 5.1 and we will (at least provisionally) remove it from HTML 5.2

**Comment by ramoas** [comment]
@stevefaulkner You are in favor of keygen removal based on a quote from Harry Halpin that contains factual errors (e.g., "the only browser that supports <keygen> currently is Mozilla").

@chaals, @hillbrad <keygen> does not generate the certificate.  It generates an RSA key pair, and then sends off a certificate request to the server; this cert request is what is signed with MD5withRSA, not the resulting certificate in the response from the server.  A server can indeed sign the resulting certificate with a more modern algorithm like SHA1withRSA / SHA256withRSA.  This is totally independent of the algorithm used to sign the cert request.  Additionally, any weakness of the MD5 signature on the certificate request can be mitigated by ensuring cert request submission occurs over HTTPS with a modern TLS configuration (key exchange, cipher, etc.).

It's disappointing some of you voting for the deprecation of <keygen> clearly either have never actually used it in one browser -- let alone across different browsers -- or do not seem to understand how it functions completely.

Additionally, we now seem to have fully circular reasoning for deprecating: the browsers are deprecating so the standards should and vice versa.

It's a mistake to remove <keygen> before whatever standard is supposedly going to replace it actually gets finalized, implemented, and deployed to enough of an extent to be an effective and pragmatic replacement.

**Comment by chaals** [comment]
@ramoas, please don't make statements about what you think other people may know or have done, that can't be demonstrated. It is impolite, and inappropriate to the discussion.

We are aware that `keygen` has been implemented in multiple browsers - see my comments above. The fact that it is being removed from browsers is what led to the discussion and subsequent Working Group decision to remove it from the specification - this is not circular.

It is indeed unfortunate if there is no replacement functionality, but the newest HTML specification should not document things that are disappearing from the platform as if they are still current - and `keygen` is documented in HTML 5.0 for anyone who wants to implement it. 

If the decision to remove it from browsers is reversed, the decision should obviously be revisited.

**Comment by ramoas** [comment]
@chaals My previous comments were targeted at specific individuals' prior comments in this discussion that contained factual errors.  Correcting those mis-statements seems highly relevant to the discussion of a feature that is slated for removal.  I was not trying to be impolite - I apologize - I was trying to provide facts.

Is there a standard process / set of conditions for removing something from a spec that was previously implemented by multiple browsers?  Why not push back on the browsers to hold off on removal until a replacement is definitively in place?

**Comment by ghost** [comment]
@ramoas  [Re: removing keygen from HTML](https://lists.w3.org/Archives/Public/www-tag/2016Jun/0006.html)
> &lt;keygen&gt;, as noted is one of the few cross-origin features that manipulates browser state and violates OP, and thus browser vendors are trying to do the right thing in terms of security and privacy by deprecating it. New W3C standards (that the TAG should both know about and support via technical review) such as WebCrypto and Web Authentication allow cryptographic authentication and cryptographic primitives to be used without violating SOP or relying on soon-to-be deprecated parts of HTML.
