### ISSUE TITLE
DOMParser question

### ISSUE THREAD

**Issue by eligrey** [w3c/html#434]
https://w3c.github.io/DOM-Parsing/#methods mentions the steps for `parseFromString`, and I'm having trouble understanding where it says to treat empty XML documents as invalid.

Why do Chrome, Firefox, and Edge all emit `<parsererror>`s when running the following code?

```
var doc = (new DOMParser).parseFromString("", "application/xhtml+xml");
// inspect with (new XMLSerializer).serializeToString(doc)
```

`document.implementation.createDocument("", "", null)`, which also creates an empty XML document, works just fine. This inconsistency puzzles me.

A webapp I'm working on depends on `DOMParser` and `xhr.response` (where `responseType == "document"`) having the same behavior. This bug is making these two interfaces behave inconsistently, and it'd odd that it's present in every browser.

Edit: Nvm, closed. Appears that a root element is required in the XML spec.

**Comment by travisleithead** [comment]
FYI: you can file future bugs on the DOMParser spec, if they are relevant: http://github.com/w3c/DOM-Parsing/issues/new
