### ISSUE TITLE
What to do with multiple thead / tfoot / caption

### ISSUE THREAD

**Issue by chaals** [w3c/html#438]
[Browsers are inconsistent](http://chaals.github.io/testcases/table-section-row-ordering.html) in how they handle multiple `thead`, `tfoot` and `caption` elements.

I haven't checked what happens if you try to navigate through multiple pieces, but there seems to be a bunch of magic applied to forming rows for the table and rendering them.

The parts of the spec affected are at least [rendering](https://w3c.github.io/html/rendering.html#tables), [parsing](https://w3c.github.io/html/syntax.html#the-in-table-insertion-mode), and [forming a table](https://w3c.github.io/html/tabular-data.html#forming-a-table).

**Comment by foolip** [comment]
Per https://www.w3.org/TR/CSS2/tables.html it looks like Firefox is wrong about `caption`, filed https://bugzilla.mozilla.org/show_bug.cgi?id=1276885

Then there's https://www.w3.org/Bugs/Public/show_bug.cgi?id=29018 about the API.

Is there anything else that isn't interoperable here?

**Comment by chaals** [comment]
Those are the ones I've found. There are some other cases I'd like to test, but haven't got there yet.

**Comment by chaals** [comment]
Seems that Blink moved into line with Firefox/IE regarding the multiple `thead` and `tfoot` elements, which conforms to what the spec says, so I think we can close this.
