### ISSUE TITLE
In Rendering chapter, remove references to defunct BECSS spec & binding property

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/html#445]
The rendering chapter [defines the default appearance of HTML elements in terms of "bindings"](https://www.w3.org/TR/html51/rendering.html#bindings) to standard UI objects.  The `binding` property it uses was proposed in the aborted [Behavioral Extensions to CSS](https://www.w3.org/TR/becss/) spec, which is now just a note explaining why it was abandoned.

**Comment by AmeliaBR** [comment]
(I was going to make a separate issue for this, but on second thought it is really the same problem...)

For the elements whose rendering is currently defined in terms of "bindings", the spec will need to clarify which default renderings authors can over-ride with CSS and which are essential.  For the rest of the chapter, this is indicated by `!important` CSS rules.  For elements described by bindings, it is more obscure.  This is most noticeable for the `<button>` element, which appears at first glance to follow the CSS box model, but actually acts as a replaced element (i.e., always forms a block) in current implementations.  

The proposed CSS [`appearance` property](https://drafts.csswg.org/css-ui-4/#appearance-switching) could be referenced, to clarify that these renderings only apply for `auto` appearance.

**Comment by chaals** [comment]
Can you provide a PR to fix this? No milestone assigned yet, since nobody is assigned to the bug yet.
