### ISSUE TITLE
Is input type=datetime implemented?

### ISSUE THREAD

**Issue by chaals** [w3c/html#462]
A quick test which I will clean up and put here suggests not in any of Edge, Safari, Firefox or Yandex.browser. Let's mark it at risk for HTML 5.1

**Comment by jungshik** [comment]
Isn't yandex browser Chromium-based Then? ,if so,  it's odd that it's not working there.

**Comment by chaals** [comment]
Yes. Although it could well be my scratchy test, too. I'll clean it up today I hope.

**Comment by dstorey** [comment]
I'm almost 100% sure this is not implemented anywhere, only datetime-local. Check http://html5test.com/ in Chrome for example.

**Comment by chaals** [comment]
Yeah, I got a couple of implementations for datetime-local but nothing for datetime… and still haven't cleaned up my scratchy test.

I don't have a working install of Chrome, but on Yandex 16-6 datetime is listed as not working there. @dstorey I presume you mean that it isn't working in Chrome either, but it would be helpful if you explicitly said so.

**Comment by dstorey** [comment]
Yes, I meant it isn't supported anywhere.

**Comment by travisleithead** [comment]
OK, removing datetime (at-risk) feature from the html5.1 branch in PR#530

**Comment by LJWatson** [comment]
Closed with #530
