### ISSUE TITLE
Default <details> heading should be localized

### ISSUE THREAD

**Issue by LeaVerou** [w3c/html#470]
> If there is no child summary element, the user agent should provide its own legend (e.g. "Details").
> http://drafts.htmlwg.org/html/master/interactive-elements.html#the-details-element

In practice, UAs have implemented the default title of "Details", which does not seem to change depending on the specified language [[demo]](http://dabblet.com/gist/e0be732fbc828ebb5ea494edef1a5d4f). I think it should be explicitly mentioned that the default title should be localized.

**Comment by chaals** [comment]
Makes a lot of sense to me. This is analogous to `<input type="submit">`.

On the other hand I have an alarm bel in my head about whether providing default content is really such a brilliant idea.

Also, the link you used is way out of date. I don't know who owns htmlwg.org, but the correct link is http://w3c.github.io/html/interactive-elements.html#the-details-element (similar content in regards to this issue). I'll see if I can get a redirect sorted.

**Comment by r12a** [comment]
And we may need to clearly state that the language should be determined from the computed language of the element, rather than from the locale of the browser/system, etc.

**Comment by dstorey** [comment]
Same for Summary in HTML AAM, 5.7.1 step 4 https://w3c.github.io/aria/html-aam/html-aam.html#summary-element

**Comment by stevefaulkner** [comment]
please review

**Comment by r12a** [comment]
Looks good to us. Thanks!
