### ISSUE TITLE
Allow a page to request a given locale (was bug 16965)

### ISSUE THREAD

**Issue by aphillips** [w3c/html#473]
This issue was originally I18N-ISSUE-97 tracked [here](https://www.w3.org/Bugs/Public/show_bug.cgi?id=16965). I [reviewed](https://github.com/w3c/i18n-activity/issues/122) the text submitted there to address this issue and, in our most recent teleconference, I18N WG actioned me to re-forward this issue. To save clicking around, here is my comment from our github issue:
## 

So the bugzilla bug was closed as "already fixed" by Travis. He quoted this text:

>    Browsers are encouraged to use user interfaces that present dates, times, and
>    numbers according to the conventions of either the locale implied by the input
>    element’s language or the user’s preferred locale. Using the page’s locale will
>    ensure consistency with page-provided data.

I'm not entirely cool with this text and think we should discuss it. My criticisms basically are:
1. I would prefer if the text weren't just "encouraging" but normative (the original issue). It doesn't have to say "MUST", but it ought to say "SHOULD", IMO.
2. The text lists dates, times, and numbers, but these should just be exemplery. Other things can be locale affected.
3. There is a missing step linking language and locale. This allows both page-provided locale (@lang) or the user's locale.

I would suggest that this text be altered thusly:

>    Browsers SHOULD provide user interfaces that present locale-affected formats such as dates, times, and numbers according to the conventions of the locale derived from the input element’s language attribute. Using the page’s locale will ensure consistency with page-provided data.

**Comment by aphillips** [comment]
(would you please add the label 'i18n' to this issue?)

**Comment by cynthia** [comment]
@travisleithead I'm not up to date on the history/rationale for the original change - are you fine with the change suggested? It looks fine to me, so if you are fine with it I'll go ahead and change it.
