### ISSUE TITLE
Inconsistency in text around HTMLMediaElement.seekable

### ISSUE THREAD

**Issue by wolenetz** [w3c/html#475]
> The seekable attribute must return a new static normalized TimeRanges object...
> TimeRanges.start() and TimeRanges.end() both return just 'double' (so must be finite).

So far, so good.
But then (**bold mine**) infinite end() appears in a non-normative note:

> If the user agent can seek to anywhere in the media resource, e.g., because it is a simple movie file and the user agent and the server support HTTP Range requests, then the attribute would return an object with one range, whose start is the time of the first frame (the earliest possible position, typically zero), and whose end is the same as the time of the first frame plus the duration attribute’s value (which would equal the time of the last frame, and **might be positive Infinity**).

Should TimeRanges.start() and end() indeed by double, or should they instead be unrestricted double?
If just double, then what should seekable() report for a stream with infinite duration?

See also https://github.com/w3c/media-source/issues/5 that is attempting to provide MediaSource apps better control over seekable on live streams or streams of unknown duration.

**Comment by wolenetz** [comment]
@foolip I just noticed HTML5 and HTML5.1 both have this inconsistency already internally. Please take a look.

**Comment by wolenetz** [comment]
@jdsmith3000 fyi -- I don't think this particular inconsistency impacts our direction for fixing https://github.com/w3c/media-source/issues/5

**Comment by chaals** [comment]
@wolonetz do you propose unrestricted double, or am I misunderstanding? Is there actual implementation yet?

**Comment by wolenetz** [comment]
Chrome implements with double in TimeRanges IDL, though internally it looks like at least non-MSE src= media playback might populate an infinite end time. Edge IIRC implements with unrestricted double in at least one MSE case. @foolip I recall you had some thoughts about this previously. Can you clarify please what the spec should say about this?

**Comment by foolip** [comment]
That is strange indeed, I hadn't noticed that note. I was skeptical about allowing Infinity in https://github.com/w3c/media-source/issues/5#issuecomment-150556828 because it would make the seek algorithm weird when it comes to clamping to seekable ranges, but the spec is inconsistent and needs to change somehow.

@wolenetz, I take it you're going for the `setLiveSeekableRange()` solution for MSE now, so would it be OK to change the note, or what's your preferred outcome?

**Comment by travisleithead** [comment]
Waiting on confirmation from @Wolenetz. I propose the following change to the Note. From:

> If the user agent can seek to anywhere in the media resource, e.g. because it is a simple movie file and the user agent and the server support HTTP Range requests, then the attribute would return an object with one range, whose start is the time of the first frame (the earliest possible position, typically zero), and whose end is the same as the time of the first frame plus the duration attribute's value (which would equal the time of the last frame, and might be positive Infinity).

to:

> If the user agent can seek to anywhere in the media resource, e.g. because it is a simple movie file and the user agent and the server support HTTP Range requests, then the attribute would return an object with one range, whose start is the time of the first frame (the earliest possible position, typically zero), and whose end is the **time of the last frame**.

For this simple example it makes sense and no longer confuses the issue. Thoughts?

**Comment by travisleithead** [comment]
Assuming my suggestion will work. PR opened to make the suggested change.
