### ISSUE TITLE
Define or remove the use of the term Plain Unicode String

### ISSUE THREAD

**Issue by stevenatkin** [w3c/html#476]
5.7.2 The drag data store
http://www.w3.org/TR/html51/editing.html#the-drag-data-store

The drag data store introduces a new term called "Plain Unicode String". It is unclear if this type of string has a restricted set of characters. The spec seems to imply that this is simply text. If this term is equivalent to Unicode text or strings, then we should use either one of those terms rather than introducing a new term. Additionally, what about a binary string that contains a file name as per the drag item kind.

**Comment by edent** [comment]
This appears to be a reference to `text/plain` as defined in [RFC1341](https://tools.ietf.org/html/rfc1341). As seen in https://www.w3.org/TR/input-events-2/#interface-InputEvent-Attributes

Should we update the Drag Data Store with a reference to the RFC, or just remove the word "plain"?

**Comment by chaals** [comment]
We don't seem to have a definition of a plain text string, but I suspect it is reasonable to use it as a normal term - we certainly talk about strings everywhere as if the term is part of normal english...

**Comment by chaals** [comment]
You might want to use charmod's [character string](https://www.w3.org/TR/charmod/#def-character-string) definition - perhaps by reference...
