### ISSUE TITLE
wbr word breaks selectively need hyphenation

### ISSUE THREAD

**Issue by Nick-Levinson** [w3c/html#480]
The wbr element should support hyphenation in some contexts where used, but not everywhere. I propose adding an attribute, hyphen, with a value of yes or no, and allowing an implied value of yes if only the attribute is present. Thus, these would be equivalent and acceptable (assuming angle brackets instead of parentheses here): (wbr hyphen) and (wbr hyphen="yes"). A value of no would be equivalent to not supplying the attribute.

I don't know of two implementations, or even one. I have asked Mozilla to add it to Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1279753).

**Comment by prlbr** [comment]
You can use the soft hyphen entities `&shy;` or `&#173;` or `&#xAD;` for a conditional hyphenated break.

**Comment by ZoeBijl** [comment]
Why would this need to be a HTML attribute? It's already in CSS: [6.1. Hyphenation Control: the ‘hyphens’ property](http://www.w3.org/TR/css-text-3/#hyphens-property).

**Comment by Nick-Levinson** [comment]
I blew it. I think I missed the CSS option because it's only an editor's draft; but, at any rate, it works in Firefox and probably in other browsers. I'm using it now. Thanks.

**Comment by ZoeBijl** [comment]
According to caniuse.com it's [supported in all but Blink based browsers](http://caniuse.com/#search=hyphens).
