### ISSUE TITLE
input type=emoji

### ISSUE THREAD

**Issue by wwwwhiterabbit** [w3c/html#495]
For example, Slack and GitHub emoji reactions can be implemented with this type of input.

Forces emoji keyboard on mobile devices.

![](https://cloud.githubusercontent.com/assets/10136844/16127542/60522096-3416-11e6-852f-539aec89ca4c.png)

Shows emoji popup on desktop.

![](https://cloud.githubusercontent.com/assets/10136844/16126704/bea762a4-3412-11e6-84cc-4e24c640de5c.png)

![2016-06-16 23 20 42](https://cloud.githubusercontent.com/assets/10136844/16128187/12658352-3419-11e6-8d83-4ff4c6a92f02.png)

**Two modes of passing data**
`unicode` and `ascii`. Affects data sent to server.
unicode `🍕`
ascii `:pizza:`

**Multiple select mode**
Browser sends to server unique list of selected emojis. Data sent to server:
unicode `💣🔥`
ascii `:bomb::fire:`

**It should be implemented as a button**

![](https://cloud.githubusercontent.com/assets/10136844/16131367/4f6b4a62-3427-11e6-9343-696c15301c00.png)

![](https://cloud.githubusercontent.com/assets/10136844/16127394/bcae7d18-3415-11e6-8bf4-90d0ee034f1a.png)

I guess emoji reactions are the evolution of likes.

**Comment by chaals** [comment]
Making this a value for input's `type` attribute seems the wrong approach. There's no obvious way in the proposal to determine whether it provides unicode code points or ascii psuedo-codes, and having it as a `type` wouldn't readily allow mixing emoji with other content.

It might work a lot better as a value for [`inputmode`](https://w3c.github.io/html/sec-forms.html#input-modalities-the-inputmode-attribute) …

**Comment by wwwwhiterabbit** [comment]
It should also have attribute with list of allowed or forbidden emojis.

**Comment by ZoeBijl** [comment]
I'm not sure how this works, but could the [`pattern`](http://w3c.github.io/html/sec-forms.html#element-attrdef-input-pattern) attribute be used for that? Maybe give in unicode ranges?

**Comment by LJWatson** [comment]
@vladimirsazhin
This is an interesting idea. It would be good to get a sense of whether it is workable in the browser, and whether there is browser interest in implementing it.

As @Chaals mentioned, the best way to do this is to propose your idea in the Web Incubator CG. You can just post something to the <a href="https://discourse.wicg.io/">WICG Discourse forum</a>.

Pinging a heads up to @yoavweiss @cwilso and @marcos-c

**Comment by vladimirsazhin** [comment]
I can't describe my thoughts very well in english. May someone to force the idea on specific resources to implement this thing? I'm writing polyfill for `input type=emoji` and I shall release it in a few weeks. :space_invader:

**Comment by travisleithead** [comment]
This is already in the incubation process--it's a bit early IMO to integrate this into HTML.

https://discourse.wicg.io/t/invoke-emoji-input/1030

**Comment by LJWatson** [comment]
As @travisleithead mentioned, it's too early to consider this for HTML.
