### ISSUE TITLE
Add labels for specific topics

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/html#5]
It would be helpful to all if issues could be labelled. In the ARIA repo we have some for the different documents, like: APG, ARIA, AAM, etc. We also have some for specific topics, which might be more suited here: accessibility, security, editorial, etc.

**Comment by chaals** [comment]
I've set up a handful of labels, for management of the issues "at a glance".

I think an issue is itself a topic - there shouldn't really be three issues for the same thing (although I realise I am guilty of doing that)...

(Feel free to reopen if you think we should be doing something differently)
