### ISSUE TITLE
Add note about keyboard and Accessibility API

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#500]
> The user agent should allow the user to manually trigger elements that have an activation behavior, for instance using keyboard or voice input, or through mouse clicks.

Specifically, Enter key is the canonical keyboard way to do this, and Accessibility API can also trigger the activation behavior.

**Comment by travisleithead** [comment]
May want to check which elements also respond to Space key (cross browser). (Check on Mac also)

**Comment by chaals** [comment]
> May want to check which elements also respond to Space key (cross browser). (Check on Mac also)

Which is where we fall down the slope.

Things with a _single_ activation behaviour are reasonably straightforward. Beasties like date pickers or audio players aren't :(

**Comment by chaals** [comment]
As Travis said, "enter" is the simple case. We need tests for all the other things.

`<button>` generally responds to space. And the ARIA WG people who are working on [ARIA implementation guide](https://www.w3.org/TR/wai-aria-practices/) have a bunch of information already, so ask them.
