### ISSUE TITLE
are menu / menuitem / contextmenu interoperably implemented?

### ISSUE THREAD

**Issue by chaals** [w3c/html#502]
Are these things implemented sufficiently to keep them in HTML 5.1?

**Comment by SebastianZ** [comment]
I've tested this myself in Firefox 47.0, Chrome 51.0, Opera 38.0, Internet Explorer 11 and Edge 25.

Firefox is currently the only browser that supports them by default. Chrome and Opera have an implementation behind the _Experimental Web Platform features_ flag.
All three implementations only allow to define context menus for elements. Button menus and toolbars are not supported.

[caniuse.com has some compatibility info](http://caniuse.com/#feat=menu) and I've updated the compatibility info for [`<menu>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu#Browser_compatibility) and [`<menuitem>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem#Browser_compatibility) on MDN.

Sebastian

**Comment by stevefaulkner** [comment]
so looks like we have 2 implementations of context menu in browser engines gecko (firefox) and blink (chrome,opera) with blink behind a flag.

**Comment by LJWatson** [comment]
@stevefaulkner asked (offline):
"only context menu/menuitem is implemented in 2 browser engines and is behind flag in one, are we counting features behind flags as acceptable?"

Behind the flag is ok. Do you have tests you can point to?

**Comment by stevefaulkner** [comment]
I have removed references to type=toolbar as its not implemented, leaving the type=contextmenu intact https://github.com/w3c/html/pull/529

**Comment by stevefaulkner** [comment]
@LJWatson  tests used:
- https://thepaciellogroup.github.io/AT-browser-tests/test-files/menu-context.html
- https://thepaciellogroup.github.io/AT-browser-tests/test-files/menuitem.html
- https://thepaciellogroup.github.io/AT-browser-tests/test-files/menu-toolbar.html

**Comment by SebastianZ** [comment]
It looks like the feature got removed from the _Experimental Web Platform features_ in Chromium and is now only [available via the command line option `--enable-blink-features=ContextMenu`](https://chromium.googlesource.com/chromium/src/+/990b0dfe5c98990f3a27e44a2a5e512f5ed3140d). See [bug 412945](https://bugs.chromium.org/p/chromium/issues/detail?id=412945) for more info.

Sebastian
