### ISSUE TITLE
html acknowledgements

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#514]
place to add names that are to be added to acknowledgements. Please add names as comments on this issue and I will ensure they get added to acks in html

**Comment by chaals** [comment]
@stevefaulkner, did you add the people listed as contributing to versions of HTML prior to 5 in the section that says "people who previously contributed to other versions"? Or are they just people who worked on HTML 5.x?

**Comment by chaals** [comment]
Actually, since this is effectively an editorial task, it seems easier to just continue to go through the logs and gather the names - nobody is adding them here anyway. So I'm going to continue doing that, and close this issue.
