### ISSUE TITLE
Sectioning content also defines scope for header elements

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html#519]
[Current spec](http://w3c.github.io/html/dom.html#kinds-of-content-sectioning-content) reads:

> 3.2.4.2.3. Sectioning content
> Sectioning content is content that defines the scope of headings and &lt;footers&gt;.

But sectioning content also defines scope for `header` elements, so that sentence should read something:

> Sectioning content is content that defines the scope of headings, &lt;header&gt; and &lt;footer&gt; elements.

Note need to correct "&lt;footers&gt;" typo: The tag is &lt;footer&gt;.

See related issue #68.

**Comment by unor** [comment]
It also defines the scope for the `bookmark` link type, and in case of `article`, for the `address` element and the `author` link type.

**Comment by stevefaulkner** [comment]
> It also defines the scope for the bookmark link type, and in case of article, for the address element and the author link type.

This is correct, but it is identified in the relevant sections of the spec, I don't think it needs adding here.
