### ISSUE TITLE
Example for 'valid time string' that shows that hours must consist of two digits

### ISSUE THREAD

**Issue by unor** [w3c/html#521]
The example for a valid time string value ([`time` element](https://w3c.github.io/html/textlevel-semantics.html#the-time-element)) is:

> ```
> <time>14:54</time>
> ```

An author that wants to mark up e.g. 09:42 would not necessarily know that it’s supposed to be `09:42` instead of `9:42`. The author would have to visit (and understand) the [definition of _valid time string_](https://w3c.github.io/html/infrastructure.html#valid-time-string) to learn this.

I think an additional example (or a Note) would be helpful here.

**Comment by adanilo** [comment]
How about changing the example to be 09:42 instead of 14:54? Probably worth testing if browsers allow single digit hour, and if so, the definition of hour as 2 ASCII digits could be relaxed.
