### ISSUE TITLE
Port the `WindowOrWorkerGlobalScope` mixin.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#522]
https://html.spec.whatwg.org/#windoworworkerglobalscope-mixin does not exist in W3C's HTML. It would be nice if it did.

**Comment by cynthia** [comment]
If @travisleithead is too busy for this, I'm willing to take this (as part of some other work I'm looking into, more on that later) - question would be if everyone is fine nuking the IDLs in individual following sections and only provide the amalgamated IDL in this new section, like how the upstream spec does this.

Are we fine with doing it like that? (I'd say this reduces the chances of mistakes when maintaining in the future)
