### ISSUE TITLE
Port "creator context security" (once it's defined).

### ISSUE THREAD

**Issue by mikewest** [w3c/html#524]
https://github.com/whatwg/html/pull/1561 defines a new "creator context security" concept, which replaces the "creator `Document`" concept that Secure Contexts relied on back when it existed. It apparently doesn't exist anymore, so.... w3c/webappsec-secure-contexts#37 :)

It would be lovely if y'all would port this change over, assuming that your friends and mine at WHATWG accept it.

**Comment by mikewest** [comment]
https://github.com/whatwg/html/pull/1561 landed, FYI.

**Comment by mikewest** [comment]
FYI: We need this to move Secure Contexts past CR. October 20th is the first day we could ask for that transition.

 /cc @adanilo @hillbrad

**Comment by adanilo** [comment]
@travisleithead will you be looking at this, or do you need me to have a bash?

**Comment by adanilo** [comment]
Ping - I'll look at this tomorrow if Travis doesn't pick it up to get you over the line for the 20th

**Comment by adanilo** [comment]
https://github.com/w3c/html/pull/615 is in flight, currently not building though...

**Comment by travisleithead** [comment]
Closed with PR#772
