### ISSUE TITLE
allow <dfn> ancestor to include <li>

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#539]
For the purpose of scoping a term's definition using the [<dfn>](http://w3c.github.io/html/textlevel-semantics.html#the-dfn-element) element, the current allowed elements are `<p>`, `<dl>` and `<section>` as ancestors of `<dfn>` I can't find any reasons for this choice and it was not defined in HTML4, so I propose to allow `<li>` as an ancestor to provide more flexibility in scoping of defintion(s) for a term.

As mentioned above this provides more flexibility for styling, while retaining a clear relationship between term in <dfn> and its definition. 

**example:** the term 'define' is defined by the text contained within `<li id="define-defined">`
[codepen example](http://codepen.io/stevef/pen/dXZZbW)

```
<ul>
<li id="define-defined"><dfn>define</dfn>:  verb (used with object), defined, defining. 
<ul><li>to state or set forth the meaning of (a word, phrase, etc.): 
They disagreed on how to define “liberal.”.</li>
<li>to explain or identify the nature or essential qualities of; describe:
to define judicial functions.</li>
<li>to fix or lay down clearly and definitely; specify distinctly:
to define one's responsibilities.
Synonyms: state, name, describe, detail, enumerate.</li>
<li>to determine or fix the boundaries or extent of:
to define property with stakes.</li>
<li>to make clear the outline or form of:
The roof was boldly defined against the sky.</li>
</ul>
</li>
</ul>
```

simple example:
instead of having to do this:

```
<dl>
  <dt>aria-disreputed</dt> 
  <dd>does not exist</dd>
  <dt>aria-bedridden</dt>  
  <dd>does not exist</dd>
</dl>
```

you could do this:

```
<ul>
 <li> <dfn>aria-disreputed</dfn> does not exist </li>
 <li> <dfn>aria-bedridden</dfn>  does not exist</li>
</ul>
```

**Comment by aardrian** [comment]
Yes.

Context link for those who want to see [how it is worded in the spec](https://www.w3.org/TR/html5/text-level-semantics.html#the-dfn-element).
