### ISSUE TITLE
The inert attribute

### ISSUE THREAD

**Issue by markcellus** [w3c/html#546]
Hello, forgive me if this is not the right repo for this (there are quite a few related to specific portions of the spec). I am simply interested in knowing the status of the `inert` attribute. I see it [in the spec](https://www.w3.org/TR/html51/editing.html#inert-subtrees), as it's been there for a while. But seems to have been abandoned. Why?

**Comment by adanilo** [comment]
This is consistent with the WHATWG version of HTML, there is no explicit attribute to control inertness. It's a side-effect of other things, like creating a modal dialog. The spec. is supposed to reflect what's implemented in at least 2 browsers, and currently no browser that I know of intends to add an 'inert' attribute.

**Comment by markcellus** [comment]
Hmm, then what is [this](https://github.com/WICG/inert)? Or is that unrelated?

**Comment by adanilo** [comment]
[That](https://github.com/WICG/inert) is a JS polyfill to implement inert behavior which looks like it's being incubated in the WICG. It still isn't implemented natively in 2 browsers which is a requirement to be in the spec. If you read 'Background' in the github repository, you'll see the comment that is was removed. So now it lives in the incubation community group, and if it gets implemented by 2 browsers in the future, it'll make it into the spec.
