### ISSUE TITLE
Upstream `plugin-types` hooks from CSP3.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#547]
It would be lovely if y'all would port https://github.com/whatwg/html/pull/1618 once it lands.

**Comment by mikewest** [comment]
(It landed. And since it explains the existing behavior in Firefox and Chrome, it seems like something y'all could pick up for 5.2 without too much worry.)

**Comment by LJWatson** [comment]
Thanks @mikewest 

Pinging @adanilo @travisleithead @arronei

**Comment by mikewest** [comment]
Ping.

/cc @hillbrad

**Comment by mikewest** [comment]
Ping.

**Comment by arronei** [comment]
This has been corrected using our new merging technique.

**Comment by mikewest** [comment]
Could you point to a commit? It doesn't look like @stevefaulkner's landed?
