### ISSUE TITLE
Navigation should be based on Fetch.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#548]
Compare https://w3c.github.io/html/browsers.html#navigating-across-documents to https://html.spec.whatwg.org/#navigate. The latter calls into Fetch for processing, the former doesn't. This makes it pretty hard to port changes like https://github.com/whatwg/html/issues/1230.

It would be helpful if the W3C version of this document picked up navigation-related changes to ensure that we don't have to write these kinds of hooks twice.

**Comment by mikewest** [comment]
Talking with @estark37 a moment ago, referrer policy is another concrete example of a spec that this is going to block: see the series of patches that landed in WHATWG's HTML to resolve https://github.com/w3c/webappsec-referrer-policy/issues/40.

/cc @wseltzer @hillbrad @dveditz

**Comment by mikewest** [comment]
Note that this is going to block CSP as well, due to the various navigation hooks we need (see https://github.com/whatwg/html/pull/1619).

**Comment by adanilo** [comment]
Thanks, we'll aim to port these changes in. Aiming for part of 5.2 is the most likely target.

**Comment by mikewest** [comment]
Wonderful, thank you @adanilo!

**Comment by mikewest** [comment]
Ping.

**Comment by adanilo** [comment]
Reviewing this now

**Comment by adanilo** [comment]
Current 5.2 WD references fetch.
