### ISSUE TITLE
Allow multiple meta-description elements if they have different lang values?

### ISSUE THREAD

**Issue by unor** [w3c/html#553]
HTML5 ([REC](https://www.w3.org/TR/2014/REC-html5-20141028/document-metadata.html#meta-description)), HTML 5.1 ([CR](https://www.w3.org/TR/2016/CR-html51-20160621/document-metadata.html#description)) and HTML 5.2 ([ED](https://w3c.github.io/html/document-metadata.html#description)) have this restriction for `meta`-`description`:

> There must not be more than one `meta` element with its `name` attribute set to the value `description` per document.

I think it would make sense to allow one `meta`-`description` _per language/language+region_, e.g.:

```
<meta name="description" lang="en" content="This page is great." />
<meta name="description" lang="de" content="Diese Seite ist toll." />
```

```
<meta name="description" lang="en-US" content="You give us dollars, we give you Bitcoin." />
<meta name="description" lang="en-EZ" content="You give us euros, we give you Bitcoin." />
```

**Comment by adanilo** [comment]
Interesting point, seems this is consistent with the WHATWG version of the spec. as well. Seems like this can be used by search engines for indexing, so perhaps multiple description elements could pose a precedence problem - which one is definitive? There can only be one charset as well, this is all likely to be a legacy hangover, since UTF-8 copes with any mix of languages. I'd be curious if other folks would know why this restriction exists.

**Comment by chaals** [comment]
simple [test for two descriptions with different `lang` attributes](https://chaals.github.io/testcases/multiple-meta-description-manual.html).

Tried it in BlueGrfiffon (which uses Firefox to parse) and doesn't complain or change anything.

**Comment by chaals** [comment]
It seems there is nothing in browsers that cares one way or another. The key question is probably who consumes this and whether allowing a second description would break anything - and the one cogent response I got from a small unscientific survey was that it would be helpful to allow it.

I will make a PR, marking the feature "at-risk" and suggest we actively look for people who are consuming the data, and if it is a problem, remove it from the draft.

**Comment by chaals** [comment]
Notes: It seems some big-size consumers include Bing and Naver for search results, and Firefox for bookmarks. Opera used to do so, but no longer.

**Comment by chaals** [comment]
It [also appears](http://yandex.com/clck/jsredir?bu=uniq15162380055661016763&from=yandex.com%3Bsearch%2F%3Bweb%3B%3B&text=&etext=1669.7NB_gZaMTZ_ILbhYeU_P3cIY_QvHLyFC29pobSIAesiT8dbudXgLm73UZvCX0xI8G_6IRY40gpCHr5A4cZi1dg.af20bccaf25dacbd604639f19d49b96ec6e74d84&uuid=&state=PEtFfuTeVD5kpHnK9lio9bb4iM1VPfe4W5x0C0-qwflIRTTifi6VAA,,&&cst=AiuY0DBWFJ5Hyx_fyvalFBp1euPNyrdPMHYiM8nzmfPNbOSEJnQVWkp7mn1elaJ-QDXEcb9Xos22Hdf1yoA1rHJcMBT0xLQ8CFDREjMnNFWHUeG0XfmVsUO1U5KDGeMike5CpIeVtZ-KuGrmgp4cVF1GcwalSyS4lI7FLyTsWh6nDySz4ZS3w5HAv8IsRYk-QtVQ4cxPRyKDyc92eK8VWLTq6Bg2uAVW&data=UlNrNmk5WktYejY4cHFySjRXSWhXS0RXWkxKWmhka0o3ZVpqcUhncU1keFMwekYyaV9EM0lEM0pvTG1PbGdueGdxQjlPNDFJTDZrNWdFNDl6SnBxU1ZIRTFuTXIwTFRlMk5yNXdyS3gyYkc3ckhIZ3BZdGdzS3AtamVfUFZETVoyTVhSQzdtWl9ENjlvdUpiZDJtU3RGVU9FM2x6Y1JiaFRIN2ZLS0RQQW9XZXdBaHBONGllamcsLA,,&sign=248ced6cd4021d9f643ea7f06b01b0c3&keyno=0&b64e=2&ref=orjY4mGPRjkh5N2Mxdt9IijjiAnZEKSkq3IJ1QKHpok1QMEE4oaJAxRWvMPKFS3x8rgVG7y2FnHM-p873S1Ng9lBCrTUKnBzpTPXH0FFgvtb8vKHPgTc6w,,&l10n=en&cts=1516248209111&mc=3.9994581877844015) that e.g. Google doesn't have a **problem** - but selects the first occurrence regardless.
