### ISSUE TITLE
Consider removing table sorting model

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#56]
has been removed in whatwg due to lack of implementer interest
https://github.com/whatwg/html/issues/345

related ARIA thread
https://lists.w3.org/Archives/Public/public-aria/2016Feb/thread.html#msg11

**Comment by chaals** [comment]
A possible approach to doing this sensibly is to move it from HTML to aria - but this looks like explicitly pushing the scope of ARIA beyond accessibility APIs. Which is its own can of worms…

**Comment by stevefaulkner** [comment]
> A possible approach to doing this sensibly is to move it from HTML to aria - but this looks like explicitly > pushing the scope of ARIA beyond accessibility APIs. Which is its own can of worms…

i don't understand what this would achieve as ARIA already provides acc API hooks via aria-sorted.  Why would implementers be any more interested to implement it if it was moved to ARIA? Perhaps it could be separated into a module and see if anybody in the WICG wants to take it up.

**Comment by ZoeBijl** [comment]
Moving things from HTML to ARIA seems backwards to me; it's supposed to work the other way around.

**Comment by LJWatson** [comment]
If there are no current browser implimentations and no sign this will change (which seems likely based on the WHATWG thread), we should just remove this feature.

If there is any reason to think this would be controversial, suggest posting a pointer to this issue on p-webapps@ and inviting wider comment.

**Comment by chaals** [comment]
I think we can just remove this - there seems to be no implementation. I'll write to p-html saying that's the plan, and asking for objections based on implementation...

**Comment by patrickhlauke** [comment]
FWIW, agree this should simply be removed. I suspect that the reality of tabular content (particularly once you start moving down the path of complex, nested, tree-widget style tables) is too complex to be fully covered by a simple sorting algorithm...and that in many cases you'd still have to resort to custom JS to do your complex sorting...and that this is why there was not much momentum behind it for fear of opening up a rat's nest of edge cases?

**Comment by chaals** [comment]
[public-html discussion](https://lists.w3.org/Archives/Public/public-html/2016Apr/0021.html)
