### ISSUE TITLE
Port 'referrerpolicy' integration

### ISSUE THREAD

**Issue by estark37** [w3c/html#560]
There are a few WHATWG HTML PRs that integrated the 'referrerpolicy' content attribute from Referrer Policy:
https://github.com/whatwg/html/pull/1651
https://github.com/whatwg/html/pull/1649
https://github.com/whatwg/html/pull/1641

It would be great to get those ported. They're based on Fetch, though (as mentioned in https://github.com/w3c/html/issues/548).

**Comment by LJWatson** [comment]
Thanks @estark37 for pinging us about these. It's appreciated.

**Comment by chaals** [comment]
Note that Can I Use [*claims*](http://caniuse.com/#search=referrer-policy) there are two good implementations, plus partial implementation in other modern engines

**Comment by adanilo** [comment]
Mostly there, just need to fix some bikeshed link references, will be ready for review shortly.
