### ISSUE TITLE
handling focus() API during sequential focus navigation

### ISSUE THREAD

**Issue by vdua** [w3c/html#564]
While running the focusing steps [0] for a candidate element during sequential focus navigation[1] (on a user request to move to next focussable area), a focus event with the name blur has to be triggered as part of focus update steps [2]. Now if the HTML author decides to use a focus() API on that event listener what should be the behavior ? The specification doesn't clearly states that whether the rest of the focus update steps to be executed or not, i.e. step 3 onwards in focus update steps should be executed or not.

[0] https://w3c.github.io/html/editing.html#focusing-steps
[1] https://w3c.github.io/html/editing.html#sec-sequential-focus-navigation
[2] https://w3c.github.io/html/editing.html#loses-focus

**Comment by adanilo** [comment]
Great question. Seems it'd be possible to create infinite loops of focus event, listener calling etc. if this isn't defined well. I guess some tests need to be written to see what browsers do currently, and clarify the text once we work that out.

**Comment by shwetank** [comment]
http://focusandblurevent.surge.sh/ is a small test i made where I call `blur()` on the focus event listener and `focus()` on the blur event listener. 

Chromium based browsers get a 'Uncaught RangeError: Maximum call stack size exceeded.' error. 
Firefox and Edge seem to not show the error, but of course, the focus is no longer on the input. Safari seems to be a bit similar to chrome where it keeps calling focus and blur untill the call stack maxes out (RangeError) and sometimes it crashes (especially when web inspector is open).

**Comment by shwetank** [comment]
Overall, IMO it shouldn't be the case that we allow a situation where we call `focus()` on the `blur` event listener (and vice versa). At best, it's a usability no-no, and at worst, will cause browser range errors and even crashes. 

However, sometimes developers might want to do some additional checking on form elements and return focus on the input if not validated. However, there doesn't seem to be a use-case (that I can think of) where we allow the user to call `blur()` on the focus event handler.

**Comment by shwetank** [comment]
So on more pondering, it seems to me that even though it would be possible to some questionable things like call `blur` on the focus event listener and then `focus` on the blur event listener causing trouble for the browser - in most cases people won't really do that ... but there are some use cases where calling just one of those (like `focus` on blur event listener) where it would be genuinly be needed by developers. The spec should not enforce developers (or browsers) to choose certain behaviour like this. If devs want to do it, then they should be free to do so, and thus, no change is required in the current spec for this.
