### ISSUE TITLE
In html form input type "number" allows the "e".

### ISSUE THREAD

**Issue by pankitgami** [w3c/html#565]
![screenshot 142](https://cloud.githubusercontent.com/assets/12875933/17802422/d7f7b470-660d-11e6-8030-b63e0006595b.png)

I have mobile number field with type number in my form.
But still, it is allowing character "e". Hereby I have attached a screenshot of this.

I am a web developer with a handful of knowledge. I would like to contribute to HTML development by solving this issue. 

Thanks.

Best Regards
-Pankit Gami

**Comment by SebastianZ** [comment]
The HTML 5.2 specification explicitly [allows the 'e' character as part of a floating-point number in exponential notation](https://w3c.github.io/html/infrastructure.html#valid-floating-point-number) like `1.23e-10`.

For a telephone number you should rather use [`<input type="tel">`](https://w3c.github.io/html/sec-forms.html#telephone-state-typetel), maybe in combination with a custom validation via the `pattern` attribute or the [`setCustomValidity()`](https://w3c.github.io/html/sec-forms.html#dom-htmlinputelement-setcustomvalidity) method.

Sebastian

**Comment by pankitgami** [comment]
Thanks for the information. I didn't know that. 
Surely, I will use custom validation for telephone number.

**Comment by faizan-jivani** [comment]
@SebastianZ Thanks !

**Comment by oalbacha** [comment]
A different approach I took that did the trick for a 4-digit pin code:
`<input type "text" maxlength: 4, size: 4, pattern: '\d{4}'>`
It should restrict all alphabetical and special characters and only allow numbers 😀
