### ISSUE TITLE
What is the simple alternative to <iframe seamless>?

### ISSUE THREAD

**Issue by thx1111** [w3c/html#568]
Looking through the Issues associated with <iframe seamless>, I am not seeing any actual discussion which justifies it removal from the HTML standard.  What justifies removal of <iframe seamless>, other than "laziness" on the part of browser developers?

What is the use case for <iframe seamless>?  Here, in 2016, I still find myself using a terminal emulator to view my notes.  I'd much rather be able to write to a broader palette, given the richness of html and latex, with the help of libraries like mathjax and chemdoodle, and then display the result in my web browser.  But then, to support my preferred style of writing, writing and displaying short notes, and then cutting and pasting these together into larger documents, it becomes prohibitively tedious using scripts or HTML Imports.  <iframe seamless> would have addressed this issue.

And then, what is the proposed simple alternative to <iframe seamless> for my use case?  Searching on "include html in html" will show this is a desirable feature, but without any simple solution.  Again, why?

**Comment by thx1111** [comment]
Hmm - I'm wondering if "iframe" is even the appropriate model for considering inclusion of one html document in another.  My naive assumption is that the body of one document is simply to be pasted into another document.  As I understand, "iframe" is more complicated than that, so maybe not a good starting point?

**Comment by adanilo** [comment]
seamless isn't supported in any modern browser, and so developers can't rely on using it at all. Hence, it's removal from the spec. is to help the spec. reflect reality better.

**Comment by thx1111** [comment]
"seamless isn't supported in any modern browser" - presumably because "seamless" is not part of any current or proposed HTML specification.  Therefore, no modern browser developer is motivated to provide the functionality.  Therefore, "seamless isn't supported in any modern browser".

That is a circular argument.  It does not explain anything - or even say anything.

Or, did you mean to suggest that the W3C just does what Google - who appears to dominate the web browser market - tells them to do?  Actually, I don't know how that is suppose to work.  Either the W3C develops standards and policy directions that are then followed and implemented by browser developers - or, the W3C is responsible for documenting what the dominant browser developers have already done, where Google's motivation is only to support their online search products.

Can someone clarify?

**Comment by adanilo** [comment]
The way W3C specs work, is that to reach Recommendation status (stable), there is a requirement to have 2 working implementations. The specs are not design docs, they document shipping code. For something like 'seamless', it's the kind of thing that can either be part of the incubation community group WICG (https://www.w3.org/community/wicg/) where it can be developed, and if it ends up shipping, transition into the whatever spec. is appropriate. Hope that helps.

**Comment by hax** [comment]
Even WICG is not helpful, because browser vendors refuse to implement it. It's not the first time they refuse to support features which developers need and will not be the last. 😒
