### ISSUE TITLE
Custom Elements in HTML

### ISSUE THREAD

**Issue by chaals** [w3c/html#569]
If Custom Elements is implemented in a second browser, we need to determine how to integrate it into the HTML specification - and how to handle modularisation...

WHATWG has made (Up to June 1) the following changes related to intregrating Custom Elements
- [ ] https://github.com/whatwg/html/commit/db8899be5b0971a3c43b8a2ac926a5df1f5bc2b9 add `customElements.whenDefined()`
- [ ] https://github.com/whatwg/html/commit/1d596a555d3c2f067ae643e447eaa88137b595ac Add customElements.get() to retrieve a constructor
- [ ] https://github.com/whatwg/html/commit/785863622acc5cc9faf1ff392ae17786ee7b3b80 Rename the types of custom elements
- [ ] https://github.com/whatwg/html/commit/6e7eaa4bd2912965fd83766f99f984f249531f3a Integrate custom elements - **big patch**
- [ ] https://github.com/whatwg/html/commit/dee1771d9e3e0bd996521402988fba73372ee33e rename `attachedCallback` -> `connectedCallback`
- [ ] https://github.com/whatwg/html/commit/27aa7bc4fa6f168654a8c858f0773e611f679b39 Formalise custom element reactions
- [ ] https://github.com/whatwg/html/commit/11bdd701e79c8dd6040586b5257eb01f3b620659 Make custom element definition trigger in-document upgrades
- [ ] https://github.com/whatwg/html/commit/28f252fbf714e18209cc1b747f5ee130a50ec649 Fix custom elements `whenDefined()` behaviour
- [ ] https://github.com/whatwg/html/commit/edda04a44c64352387199ba6ed412d27ea305bfb Correctly find upgrade candidates during custom element definition
- [ ] https://github.com/whatwg/html/commit/ea2f021c265bd082415f2775fc7a1c562ec7275a Define contentDocument more clearly
- [ ] https://github.com/whatwg/html/commit/5946d084658ff2f8d5ec3cea3c448175eaa5336e - small editorial
- [ ] https://github.com/whatwg/html/commit/6561250ec3788938a2d64932093b0ea293b97174 - fix / clarify stack-popping

**Comment by arronei** [comment]
This seems like one of the perfect components to create as a new module to HTML. If we can define this using the new module idea then we should be able to define anything as modules.

**Comment by plehegar** [comment]
As a module, isn't that what https://www.w3.org/TR/custom-elements/ currently doing? if not, then we'd need to understand what about be different in that module.

**Comment by chaals** [comment]
Closing this issue - I will open one on whether to integrate custom elements, and if we decide that is the right idea, then we'll open issues as needed for the work...
