### ISSUE TITLE
5.2 Spec version URL

### ISSUE THREAD

**Issue by kevinSuttle** [w3c/html#570]
The latest 5.2 spec links to https://www.w3.org/TR/html51/

Should it be https://www.w3.org/TR/html52/ ?

<img width="468" alt="screen shot 2016-08-30 at 10 45 01 am" src="https://cloud.githubusercontent.com/assets/95672/18093728/dc4f201e-6e9e-11e6-8178-afd2e1b1a295.png">

**Comment by LJWatson** [comment]
Thanks @kevinSuttle 

Pinging @plehegar @siusin and @ylafon for help fixing.
