### ISSUE TITLE
Bad markdown with location.assign(url)

### ISSUE THREAD

**Issue by kciray8** [w3c/html#571]
[https://www.w3.org/TR/html51/browsers.html#location-location](https://www.w3.org/TR/html51/browsers.html#location-location)

![image](https://cloud.githubusercontent.com/assets/5188373/18122169/da33f782-6f70-11e6-8ed3-3e2dc392fc3f.png)

**Comment by stevefaulkner** [comment]
thanks @kciray8, I believe that this has been fixed in 5.2 [http://w3c.github.io/html/browsers.html#location-location](http://w3c.github.io/html/browsers.html#location-location), but the version you have accessed is a Working draft which will not be updated until it is republished.

**Comment by stevefaulkner** [comment]
@kciray8 if you prefer to identified by something other than "Yaroslaw" let me know

**Comment by kciray8** [comment]
@stevefaulkner  okay, "Yaroslaw" is fine
