### ISSUE TITLE
Anyway to get specs for offline?

### ISSUE THREAD

**Issue by corysimmons** [w3c/html#573]
It'd be nice if there was a button to download a zip of html, epub, or pdf somewhere (I know can view single page and cmd+s, or wget).

If this kinda thing already exists, I'm overlooking it.

Would love to have all the specs offline. :)

**Comment by adanilo** [comment]
You could print to PDF using Chrome, Firefox and Safari (not sure about IE/Edge), which should solve your needs.

**Comment by corysimmons** [comment]
Whoa, that's a lot better than Chrome's cmd+s option, but isn't exactly ideal.

Notice how in https://virtualenvwrapper.readthedocs.io/en/latest/ you can expand the bottom left and have a plethora of options for download:

![image](https://cloud.githubusercontent.com/assets/224636/18168289/f1c5fc58-7022-11e6-8f6c-6904aac24f98.png)

They're obviously using a few scripts to auto-generate those downloads.

It'd just be nice if the W3C specs had a similar feature. For instance, I might want to download the HTML spec in epub format and read it on my phone while camping. Or click around to various sections using the html version.

Just wondering if I'm overlooking something or if the W3C might be interested in this feature.

**Comment by plehegar** [comment]
We don't really provide the ability to download the spec offline at the moment. You could always use tools like wget to download a page and all of its sub-pages. There has been some attempts to provide an epub version of the spec. @iherman would know more about that. With the 2016 style version of our specifications (see https://github.com/w3c/tr-design/), this might be easier to do that previously. Also pinging @deniak, the current W3C webmaster, who might have some thoughts.

Honestly, at the moment, our priorities are improving our publication pipeline so that https://www.w3.org/TR/ is up-to-date and improving how we link and reference our publications (given the wide variety of audiences). If we can integrate tools to deliver zip, pdf, Epub along the way, that would be nice but not a must have.

**Comment by corysimmons** [comment]
Yeah I'm not stressing about it or anything -- just thought I might be overlooking it, or it'd be a nice new feature to have.

Is there a better place to file this feature request than w3c/html?

**Comment by deniak** [comment]
Unfortunately, there's no _easy_ way to download a spec from /TR. [Authors _may_ provide alternative formats](https://www.w3.org/pubrules/doc/rules/?profile=WD#altRepresentations) such as zip or pdf but that's not a requirement and few editors are actually doing it.
As @plehegar mentioned, the current priority is to improve the publication workflow for editors but we are also thinking about revamping the /TR page and that will be a good opportunity to do something similar to RTD.

In the meantime, I can only suggest `wget -r --no-parent <spec url>` or the print method @adanilo explained. Note for the html spec, you might want to do it on [the single page version](https://www.w3.org/TR/html51/single-page.html).

**Comment by iherman** [comment]
I did have a script to turn TR documents into EPUB; it is still [on github](https://github.com/iherman/tr2epub), but it has not been actively maintained (in particular, it has not been updated to the latest version of the TR design, and that shows). Instead, the service that is maintained actively is an extension to respec to generate an EPUB for the documents; this is now part of respec (one can choose 'epub' when saving an HTML+respec file) and is also kept up on a [github repo](https://github.com/iherman/respec2epub). But, as @deniak said, it is up to the author to provide that alternative format, there is no obligation. Whether we could do that systematically for all TR document on longer term... that is still to be discussed.

**Comment by corysimmons** [comment]
@deniak wget and such always give me problems. I've got about 100 websites saved that are severely screwed up (missing images, or scripts, etc. etc.) offline. I used a plethora of options and read a lot about it. Same with httrack. One day I might settle down with those man pages and really figure it out and create some CLI to mirror webpages and websites well. This isn't a plea for you to give me the exact command (or suggesting the command you provided already wouldn't work perfectly) -- just whining (aren't you glad you read this paragraph?).

> we are also thinking about revamping the /TR page and that will be a good opportunity to do something similar to RTD.

Sounds great! Hope this feature makes its way in. If the spec layouts get standardized I'd be happy to provide some scripts for this stuff.

@iherman Thanks for the info. 👍

**Comment by plehegar** [comment]
@corysimmons regarding a better place to file this bug, the only place I can think of is to file it under https://github.com/w3c/echidna/issues/ . This repo contains our automatic publication tool and, if we're going to provide offline version, that's a great place to start thinking about it. Once you filed it, feel free to close this issue.
