### ISSUE TITLE
Add `export` attribute to various definitions.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#577]
In order for Bikeshed specs to be able to automagically link to HTML-defined terms, they must be exported. It would be lovely if y'all would port over some patches like https://github.com/whatwg/html/commit/81ee034f316f4366aeb315d16ea21521c83ab427, https://github.com/whatwg/html/commit/b2764ef551e5d7d1a67fe09cf3e561a47ccc78ff, https://github.com/whatwg/html/commit/c050450c8d804228ef827266fbfa1b0369b7930a, https://github.com/whatwg/html/commit/bae9fc59d8e51863f3813fceda7d20b7a5faa8e2, etc.

**Comment by mikewest** [comment]
Note: The list of terms defined by HTML at https://w3c.github.io/webappsec-csp/#index-defined-elsewhere is a nice (if selfishly-motivated!) list of terms to prioritize. :)

**Comment by adanilo** [comment]
Thanks @mikewest we'll add these to the pile:-)

**Comment by chaals** [comment]
Closing this issue, but exporting relevant definitions will probably be something we need to consider as part of editorial practice…
