### ISSUE TITLE
CFC: Publish HTML5.1 as Proposed Recommendation (PR)

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#578]
With thanks to everyone who contributed, and to the HTML editors in particular, this is a Call For Consensus (CFC) to request W3C publish the <a href="https://www.w3.org/WebPlatform/docs/html51-20160902/

">HTML5.1 Editor's Draft (ED)</a> as a PR.

Please respond by end of day on Friday 9th September 2016. Responses maybe given in reply to the <a href="https://lists.w3.org/Archives/Public/public-webapps/2016JulSep/0086.html">CFC email</a>, or on this Github issue. Positive responses are preferred and encouraged, but silence will be taken as consent to the proposal.

Following Candidate Recommendation (CR), several "at risk" features were removed, whilst others were retained. Details can be found in the status section of the ED.

The <a href="http://w3c.github.io/test-results/html51/implementation-report.html
">HTML5.1 Implementation report</a>  references three features with no known native implementations, and three features with one known implementation. In each case the W3C specification aligns with the WHATWG specification.

Of the features with one iplementation, we expect that there will be more implementations in the future. Of those with no implementations:
1. the algorithm steps to support CSP have no impact unless the relevant parts of CSP _are_ supported, in which case they specify the expected interoperable
   behaviour. The chairs expect such CSP support to occur relatively soon. If it appears that this will not be implemented in the future, this change is likely
   to be reverted in HTML 5.2.
2. the algorithm steps to support closing a blob with the FileAPI's close() method likewise have no impact unless the method is supported. Since the future
   of that method is under discussion, this part of the relevant algorithm will be a candidate for removal from HTML 5.2.
3. probablySupportsContext is a convenience function to enhance performance when using canvas. If this does not seem likely to be implemented, it will be
   a candidate for removal from HTML 5.2
   
   The WebPlat chairs recommend supporting this proposal. Although it is not perfect, it represents a substantial improvement over the HTML5 Recommendation, so publishing it would be helpful. Rather than hold up the publication of these improvements, we can continue to improve and iterate the HTML specification as HTML5.2.

**Comment by stevefaulkner** [comment]
_Unsurprisngly_ i support this CFC

**Comment by LJWatson** [comment]
This CFC received several positive responses and no objections, so it passes (recorded in <a href="https://lists.w3.org/Archives/Public/public-webapps/2016JulSep/0100.html">this announcement</a>).
