### ISSUE TITLE
rb and rtc should not be non-conforming in html5.1

### ISSUE THREAD

**Issue by r12a** [w3c/html#579]
11.2. Non-conforming features

https://www.w3.org/TR/html51/obsolete.html#ref-for-elementdef-rb-21

> `<rb>`
> 
> `<rtc>`
> 
> Providing the ruby base directly inside the ruby element or using nested ruby elements is sufficient.

This text has only just come to the attention of the i18n WG. It seems to have been imported automatically from the WhatWG spec.  The i18n WG disagrees that these elements are non-conforming. They were added to HTML in HTML5, and have been implemented by Mozilla. In fact, the CSS folks are counting on them being around in the future for CSS ruby styling features to work.

Please remove that text.

**Comment by chaals** [comment]
This looks like an editorial issue - the elements are in the 5.0, 5.1, and 5.2 specifications.

**Comment by stevefaulkner** [comment]
closing as fixed

**Comment by r12a** [comment]
thanks
