### ISSUE TITLE
References to Web IDL members no longer links.

### ISSUE THREAD

**Issue by ddorwin** [w3c/html#58]
All references to members of HTMLMediaElement, including attributes and constants used to be links to the definition. Now, they are no longer links. Even some attributes are no longer links in the Web IDL itself.

Specific examples (compare to https://www.w3.org/TR/html/embedded-content-0.html#media-elements):
- Member constants, such as `NETWORK_EMPTY` and `HAVE_NOTHING` are links in the [IDL](http://w3c.github.io/html/semantics.html#media-elements) but nowhere else in the document.
- **Some** member attributes, such as `networkState`, are not a link anywhere in the document, including In the [IDL](http://w3c.github.io/html/semantics.html#media-elements).

HTMLObjectElement and other elements have similar issues, so this is not limited to media elements.

**Comment by arronei** [comment]
Waiting on [Update widlparser](https://github.com/tabatkins/bikeshed/issues/613)
