### ISSUE TITLE
WebIDL bugs

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/html#581]
- `DOMElementMap` uses the `creator` keyword, but that is no longer valid in WebIDL
- `HTMLTextAreaElement`, `HTMLInputElement` and `HTMLSelectElement` uses `required` as an attribute name, but since that's a WebIDL keyword, I believe the name must be prefixed with a `_`

**Comment by chaals** [comment]
Gave this a concrete milestone.

**Comment by travisleithead** [comment]
PR ready:

Fixes the DOMElementMap issue by syncing to WHATWG's section which drops support for this interface, and picks up support for the [already legacy] DOMStringList interface and its members.

Adds an underscore to `required` in the IDL blocks for `HTMLInputElement`, `HTMLSelectElement` and `HTMLTextAreaElement` (and links everything up correctly).
