### ISSUE TITLE
Unclear conformance of attributes on <table> element

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#582]
https://w3c.github.io/html/tabular-data.html#the-table-element

This is an editorial issue coming from previous editions, which has not been fixed yet.
The "border" attribute on tables is (controversially) conforming, though with the only allowed values of 1 and the empty string.
This means that the sentences:

> The use of the non-conforming `border` attribute with the non-conforming value 0
> 
> The use of the non-conforming `border` attribute with a value other than 0

in the table about possible indicator for table recognition heuristics should be changed into:
- The use of the `border` attribute with the non-conforming value 0
- The use of the `border` attribute with a value other than 0

For the same reason, the sentence

> The use of the `summary` attribute

should be changed as follows:
- The use of the non-conforming `summary` attribute

These changes could appear unnecessary, but the table also lists `cellpadding` and `cellspacing` as indicators, correctly marking them as non-conforming. Misuse of this expression could lead to wrong conclusions.

**Note:** This table has been changed in HTML 5.1, probably cherry-picking from WHATWG spec, where `border` attribute was effectively non-conforming. I hope the same fix can still be extended to the candidate recommendation.

**Comment by travisleithead** [comment]
These seems like good changes to make as long as they are strictly editorial in nature. With HTML5.1 in PR, we don't want to make any substantive changes... of course, we do hope to continue editing and publishing HTML, so the updates in the 5.2 editor's draft will eventually replace 5.1, so it's not the end of the world if we miss this...

**Comment by travisleithead** [comment]
@chaals what do you think?

**Comment by chaals** [comment]
Assuming @AndySky21 is right, which seems reasonable, the changes proposed could be made in 5.1 without causing a problem, since they are correcting an inconsistency and not changing substantive facts.

And it seems like they **should** be made in the latest draft otherwise.

**Comment by AndySky21** [comment]
Just consider that, per spec, the part referring to **Content attributes** in each element introduction is to be considered normative. So, if an attribute is listed there, no matter how controversial it is, that attribute is allowed. This means that defining it "non-conforming" in other parts of the spec is an editorial mistake. I suppose that a substantive change would be to remove said attribute from the list.

**Comment by chaals** [comment]
Oops. This should have been done :(

Scheduling for this week.

**Comment by chaals** [comment]
:( Didn't get done. New milestone.
