### ISSUE TITLE
HTMLElement.dropzone forwards to DOMTokenList.value, but there's no such attribute in the DOM

### ISSUE THREAD

**Issue by kciray8** [w3c/html#585]
From [HTMLElement ](https://www.w3.org/TR/html51/dom.html#elements-in-the-dom)

`[PutForwards=value] readonly attribute DOMTokenList dropzone;`

But [DOMTokenList](https://www.w3.org/TR/dom/#domtokenlist) doesn't have attribute **value**. Interface DOMSettableTokenList has this attribute, but this's another interface.

**Comment by stevefaulkner** [comment]
@travisleithead ping?

**Comment by travisleithead** [comment]
DOM4 and DOM Living Specification diverged. Since DOM4 is out-of-date (and no new re-publication has been scheduled at W3C), we are using the DOMTokenList defined here for now: https://dom.spec.whatwg.org/#interface-domtokenlist
