### ISSUE TITLE
wbr mechanics

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#586]
From HTML5 to HTML5.1, the suggested rendering of wbr element has been changed from "content" property to "display-outside".
https://www.w3.org/TR/html5/rendering.html#phrasing-content-0
https://www.w3.org/TR/html51/rendering.html#non-replaced-elements-phrasing-content

However, display-outside for both br and wbr elements relies upon values which have been discussed on February 2015 (https://logs.csswg.org/irc.w3.org/css/2015-02-23/) and never implemented nor standardised since then.

As a matter of fact, these two elements still work because the browser knows what to do. This is relevant because there is no apparent way to change the default rendering for these elements.

I reported this issue some time ago when I suggested that wbr, as word break opportunity, could be used for a better soft hyphenation. This would allow authors to break long strings consistently and without having to insert `&shy;` (it tends to behave erratically when it comes to deal with text content in any way). Current suggestion isn't even meant to allow that in the future.

**Comment by stevefaulkner** [comment]
While they are in CSS display module level 3 https://drafts.csswg.org/css-display/#the-display-outside, doesn't look like they have been implemented by any browser as yet. So as far as 5.1 goes it would be better if the advice is based on properties that work, but i think the 5.1 ship has sailed ( @chaals  ? ). Note CSS specced in the rendering section section is a suggestion only, i.e. not normative.

**Comment by AndySky21** [comment]
@stevefaulkner, `display-outside` is defined in the module you cited, the proposed keywords `break-opportunity` and `newline` are not.

> Values are defined as follows:
> 
> `<display-outside>`  = `block` | `inline` | `run-in` ;

HTML spec is suggesting UAs to render two elements by using unspecified values for an unimplemented property.
My aim is not to see the change in 5.1 (it has sailed indeed), but I hope it can be revised altogether for the future. And, as the current suggestion is not viable, maybe the change could be made in the direction I defined above (allowing authors to display `<br>` and `<wbr>` as something different from a _line break_ and a _naked string break_).

**Comment by chaals** [comment]
Hopefully assigning a milestone. But need to assign someone to do this, unless there is a PR...

**Comment by stevefaulkner** [comment]
closing wont fix as this section is not normative and we have parity with WHATWG on the advice.
