### ISSUE TITLE
Global attributes reference

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#591]
Editorial issue (the same problem is present in the HTML 5.1 spec)
https://w3c.github.io/html/dom.html#sec-global-attributes
In the list linked above, several attributes no longer link to the sections detailing them in the spec. This makes it harder to retrieve relevant information.

Is it because said sections have been moved? Can it be fixed?

**Comment by arronei** [comment]
There are many links like this that are broken. When we switched over to a different publishing tool for the specification we had to rewrite all of our linking. Many of these as you can tell were missed and are still broken.

I am in the process of doing a section by section sweep of the linking but it take a considerable amount of time.

**Comment by arronei** [comment]
This is now covered by bikeshed and should be linking using the standard definitions. If not this is a bikeshed issue affecting all specifications.

Other linking is handled by our new merging process.
