### ISSUE TITLE
[Editorial] 5.1 should have summary changes from 5.0 REC

### ISSUE THREAD

**Issue by tantek** [w3c/html#592]
The HTML 5.1 PR changes section lists changes between public working drafts, whereas to most people (outside the WG etc.), a summary changes from the 5.0 REC would be much more useful / readable / understandable, especially in cases (if there are any?) where multiple changes to a feature occurred across multiple public working drafts.

http://www.w3.org/TR/2016/PR-html51-20160915/changes.html#changes-20160822

I'm ok with _keeping_ the specific per working draft changes (this is not a proposal for _replacement_).

Rather, the proposal is to _start_ this section with a summary of changes from 5.0 REC (which I think is all that most readers of this document will care about), and then we can keep the more detailed per WD changelog after that.

This is effectively (or should be!) purely an editorial issue, and yet I think will greatly help broader understanding of 5.1 (in comparison to 5.0) and should be done before 5.1 REC if at all possible.

Since I'm reviewing it anyway, if there's a chance of this issue being accepted, I can try working on a sample summary. Also more than happy to let the editors do that.

**Comment by chaals** [comment]
Yeah, absolutely agreed. I edit the changes section, and I'm happy to do that.

**Comment by chaals** [comment]
Done in #651
