### ISSUE TITLE
Editorial error on SetCustomValidity

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#595]
https://w3c.github.io/html/sec-forms.html#the-constraint-validation-api

Formatting error.

**Comment by stevefaulkner** [comment]
@AndySky21 what is the formatting error?

**Comment by stevefaulkner** [comment]
@AndySky21 i see it now

**Comment by stevefaulkner** [comment]
element . {{HTMLInputElement/setCustomValidity(message)}}

**Comment by AndySky21** [comment]
Unfortunately it's the same in HTML 5.1.
https://www.w3.org/TR/html51/sec-forms.html#the-constraint-validation-api

Editorial fix needed?

**Comment by chaals** [comment]
Was this fixed by #611 - or do you want a better fix?

**Comment by stevefaulkner** [comment]
@ chaals the fix works for 5.2 , its still borked in 5.1, unsure how to flag as errata for 5.1?

**Comment by chaals** [comment]
Raising an issue, and fixing things in 5.2, is how we flag the errata from 5.1. So this can be closed… fixing 5.1 is unlikely to be worth the effort.
