### ISSUE TITLE
Port over changes to `data:` origin handling.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#597]
It would be lovely if y'all could port the changes that resulted from https://github.com/whatwg/html/issues/1753.

/cc @adanilo

**Comment by cynthia** [comment]
I'd be willing to work on this if @adanilo doesn't have time.

**Comment by adanilo** [comment]
Feel free to assign it to yourself if so. I'm planning to help most of get Mike's issues addressed in a more timely fashion;-)

**Comment by cynthia** [comment]
Merged.
