### ISSUE TITLE
Port the `nonce` attribute for `<link>`.

### ISSUE THREAD

**Issue by mikewest** [w3c/html#599]
Please port over the changes from https://github.com/whatwg/html/pull/1820 once it lands (soonish?).

Thanks!

/cc @adanilo

**Comment by mikewest** [comment]
FYI: This landed.

**Comment by chaals** [comment]
What about implementation?

**Comment by mikewest** [comment]
Chrome, Firefox, and WebKit all support nonce mechanisms for stylesheets, which require support for the attribute, and an eventual fix for https://github.com/w3c/html/issues/198: see the nonce section of the implementation report at https://w3c.github.io/webappsec/implementation_reports/CSP2_implementation_report.html.

Edge support should be coming soon when they land CSP2 bits and pieces.

**Comment by adanilo** [comment]
Thanks, @stevefaulkner let me know if you'd like to pass this on to me, happy for you to port of course!

**Comment by stevefaulkner** [comment]
@adanilo @mikewest has reviewed my PR https://github.com/w3c/html/pull/604 and have updated in response. Can you take a look and merge if good, thanks!

**Comment by chaals** [comment]
Oops. Labelling for historical purposes at this stage, I hope.

**Comment by adanilo** [comment]
Closing, PR #604 covered this and it's been merged.
