### ISSUE TITLE
typo in definition of ancestor browsing context

### ISSUE THREAD

**Issue by avrljk** [w3c/html#601]
In http://w3c.github.io/html/browsers.html#sec-nested-browsing-contexts

> A is said to be an ancestor of a browsing context B if there exists a browsing context **A that is a child browsing context of A** and that is itself an ancestor of B, or if the browsing context A is the parent browsing context of B.

(bold added to highlight issue)

The first A in bold above is A' (A-prime) in https://www.w3.org/TR/html5/browsers.html#nested-browsing-contexts

Alternatively (may be clearer):

Instead of A <- A <- B, perhaps that should be A <- C -< B (matches the use of C as the child name in the preceding paragraph of the spec).

Or rename the deepest descendant here to C, with B as the example ancestor between it and A (A <- B <- C).

**Comment by adanilo** [comment]
Ahh, good catch. We'll need to fix this, thanks.

**Comment by cynthia** [comment]
Fixed.
