### ISSUE TITLE
Multiple text input with datalist

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#608]
This is just a suggestion and it could be difficult to implement.

As datalist heavily relies upon UA implementation to be displayed correctly, it is particularly difficult to change it through JS. So I'd like to suggest a feature it maybe lacks.

There is currently no way to display more than one suggestion, meaning that it cannot be used in a "multiple select" fashion. This is right, as it refers to a field which has no "multiple" attribute. It is also true that, as text input is meant for free-form text, browsers cannot predefine a separator (as seen in email fields).

I would implement this feature as an attribute in datalist element, let's say "separator". This would be the model:

``` html
<input name="fruits" list="types" />
<datalist id="types" separator=",">
  <option value="apple" />
  <option value="banana" />
  <option value="orange" />
</datalist>
```

This way, every time user types the separator string (in this case, a comma), the browser shows the datalist again, thus allowing multiple guided inputs.
Of course data are to be sanitised and intepreted server-side, maybe splitting on the same string provided as separator. This is just a matter of user experience.

**Comment by chaals** [comment]
Hi @AndySky21, this seems like the sort of feature that should be incubated in [WICG](https://wicg.io) or demonstrated in JS - which is messy but I think technically feasible, if you actually collect the separator, copy the form value and then delete the real one and paint a fake over it to trigger the datalist - to get some traction among developers and/or browser implementors.

**Comment by AndySky21** [comment]
@chaals, thanks for the suggestion, but I don't think I can gain any
traction, I don't know how to attract implementers' interest other than
opening a topic on Discourse WICG (I did it here:
https://discourse.wicg.io/t/datalist-multiple-suggestion/1739). I'll show
an example later.

**Comment by stevefaulkner** [comment]
Closing here as this needs incubation and has been raised in the WICG refer to https://github.com/w3c/html/issues/608#issuecomment-251683628
