### ISSUE TITLE
Inconsistent description of comma-separated tokens

### ISSUE THREAD

**Issue by An-dz** [w3c/html#613]
https://w3c.github.io/html/infrastructure.html#comma-separated-tokens
The description text of the comma-separated tokens seems inconsistent to me, this might be discussed by the working group. I've opened this here as I was unsure where to post this. The issue, as I believe, is the following:

> A set of comma-separated tokens is a string containing zero or more tokens each separated from the next by a single U+002C COMMA character (,), _where tokens consist of any string of zero or more characters, **neither beginning nor ending with space characters**,_ nor containing any U+002C COMMA characters (,), **and optionally surrounded by space characters**.

The description is inconsistent when it first says that the tokens don't start and/or end with space characters, but ends saying they are optional. Example 23 right below the description confirms that they are indeed optional (at least for whitespaces):

> Leading and trailing whitespace around each token doesn’t count as part of the token

The text preventing space character should be removed to avoid any misinterpretation of the text.

**Comment by AndySky21** [comment]
I suppose it should only be rephrased. Such descriptions usually mean that, when a list is as follows:
`foo, bar , baz`
the spaces are to be considered as part of the separator and not as first/last character of the token itself.

**Comment by stevefaulkner** [comment]
I don't agree that the text is confusing, what I did find was that the example was incorrect and fixed it.
https://github.com/w3c/html/commit/d522354981b70b5b3f64c9ee5759549a94f8be7d
