### ISSUE TITLE
Editorial error on "Date, time and number formats"

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#614]
https://w3c.github.io/html/sec-forms.html#date-time-and-number-formats

> Likewise, in markup and form submission numbers are always written without grouping separators, and a FULL STOP character "." @@ as a decimal separator.

Does the @@ have a meaning?

**Comment by cynthia** [comment]
Looks very much like a temporary placeholder which never got fixed.

**Comment by chaals** [comment]
Should probably use terminology like "A single U+002E FULL STOP character (.)" for consistency

**Comment by stevefaulkner** [comment]
fixed by https://github.com/w3c/html/commit/3534711693c88adb95cd98a1079c9736eb78da38
