### ISSUE TITLE
July 2016 Port 9 - Merge and review <picture> 

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#625]
https://github.com/whatwg/html/issues/52

Validate <picture>; it is already merged in HTML5.2, but re-validate the content to ensure it is up to date:
- Additional clarity around srcset/sizes/media attributes: https://github.com/whatwg/html/commit/de58b9ebf9d06dc846f6fe8cd301ae4c6d66c0c8

**Comment by chaals** [comment]
Doesn't seem to change any conformance requirements.
