### ISSUE TITLE
July 2016 Port 11 - Worker constructors (use current, not incumbant script)

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#627]
Clarity on the mechanics of invoking the constructors. Testable. Tests noted:

> As shown by https://settings-object-worker-client-abibrisfdk.now.sh, all
> browsers use the current settings object for the fetch client, i.e. the
> "outside settings", instead of the incumbent settings object. (Except we
> do not know the result in Edge, since they don't seem to send a Referer
> header for us to inspect.) Part of #1430.
> 
> As shown by
> https://settings-object-worker-client-wellwosyqf.now.sh/entry/entry.html,
> all browsers also use the current settings object for URL resolution,
> instead of the entry settings object. Part of #1431.

https://github.com/whatwg/html/commit/485c76a84611d094839b3b60d13e6e997594800b

**Comment by chaals** [comment]
This is for HTML or for workers?
