### ISSUE TITLE
How to create diff files between different versions of HTML

### ISSUE THREAD

**Issue by fititnt** [w3c/html#634]
Related to #592 and #588

---

How the file https://github.com/w3c/html/blob/master/diff/html5to51diff.html was created?

cc @arronei

**Comment by chaals** [comment]
Probably with http://services.w3.org/htmldiff

**Comment by fititnt** [comment]
Thanks. I will describe here for who is interested.

## How to use for multi part

To see diff of, for example, new changes to HTML 5.2 (https://www.w3.org/TR/html52/textlevel-semantics.html#textlevel-semantics) from Text-level semantics from HTML 5.1
- Go to http://services.w3.org/htmldiff
-  Address of reference document: https://www.w3.org/TR/html51/textlevel-semantics.html#textlevel-semantics
- Address of new document: https://www.w3.org/TR/html52/textlevel-semantics.html
- Press "get Diff"
- New page with diffs will be http://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fhtml51%2Ftextlevel-semantics.html&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2Fhtml52%2Ftextlevel-semantics.html

## How to use for single-page (Does not work at the moment)

Right now does not work, error 500. It's probably a very costly request. URL to test: http://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fhtml51%2Fsingle-page.html&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2Fhtml52%2Fsingle-page.html

---

Get help to generate single page version, even without using the W3C service, is welcome. Or change the W3C server be set to allow larger files.
