### ISSUE TITLE
Add note about proper usage of `tabindex` with skip links

### ISSUE THREAD

**Issue by thierryk** [w3c/html#635]
The warning in section [5.4.3](https://w3c.github.io/html/editing.html#the-tabindex-attribute) by @patrickhlauke is a great addition but I think the following sentence needs to be seriously emphasized:

> However, authors should only make elements focusable if they act as interactive controls or widgets.

or may be followed by something like:

Authors must use `tabindex="-1"` onto elements that need to receive focus but are _not meant to be part of the sequential focus navigation_ (i.e. the target of a skip link).

I think this is important to mention because it seems many people do not make the difference between "being focusable" and "being keyboard accessible"&mdash;assuming that to be focusable, an element has to be part of the tab sequence.

These 2 skip link examples demonstrate the issue:
- [knowbility.org](http://www.knowbility.org/#main) where the main section is not part of the sequential focus navigation
- [simplyaccessible.com](http://simplyaccessible.com/#acc-heading-0) where headings are part of the sequential focus navigation

**Comment by patrickhlauke** [comment]
I was going to say that this may be unnecessary, as it's mentioned explicitly later on in the same section...but then realised that the note about `tabindex="0"` that was originally in that warning boxout is also just reiterating/reinforcing what's said later on too. So yes, might as well add a further paragraph to the warning as well.

**Comment by patrickhlauke** [comment]
I mostly used your excellent initial suggestion there in my proposal, with one major difference: I changed the "must" to "should"

**Comment by thierryk** [comment]
Yeah&mdash;I went back and forth&mdash;"must" is a _big_ word.

As a side note, I think the following may also confuse people:

> The tabIndex IDL attribute must reflect the value of the tabindex content attribute. Its default value is 0 for elements that are focusable and -1 for elements that are not focusable.

I think in people's mind, this translates to:  _`tabindex="-1"` is for elements that are not focusable_

**Comment by patrickhlauke** [comment]
@thierryk good stuff https://github.com/w3c/html/pull/637
