### ISSUE TITLE
dropzone isn't supported

### ISSUE THREAD

**Issue by plehegar** [w3c/html#64]
As far as I can tell, drop zone isn't supported on existing browsers.
Test at:
http://w3c-test.org/html/editing/dnd/dropzone/007.html

**Comment by ZoeBijl** [comment]
What part of the spec is this referring to?

**Comment by stevefaulkner** [comment]
http://w3c.github.io/html/editing.html#the-dropzone-attribute

##

**Comment by plehegar** [comment]
Also appear in http://w3c.github.io/html/dom.html#dom-htmlelement-dropzone

**Comment by rniwa** [comment]
WebKit supports this feature prefixed (webkitdropzone).  Blink might support it too.

**Comment by plehegar** [comment]
@adrianba expressed support for keeping this in the spec.

**Comment by travisleithead** [comment]
Moving milestone to After 5.1 per discussion with the editors.

**Comment by stevefaulkner** [comment]
@travisleithead any update on this?

**Comment by stevefaulkner** [comment]
dropzone dropped in whatwg https://github.com/whatwg/html/pull/2402
