### ISSUE TITLE
July 2016 Port 16 - script fetching integration cleanup

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#640]
https://github.com/whatwg/html/commit/b4f40e72fcca8a13eefa8a2dd06258378e76fcb7

Reduces number of Fetch integration points by consolidating the concepts. Not testable--editorial. (see https://github.com/whatwg/html/issues/1485)

(Note the importScripts consolidation part will not included, as Workers is not in our document. @cynthia ) see https://github.com/whatwg/html/issues/1151.

Includes some external-spec hook entry-points for Service Workers.

**Comment by cynthia** [comment]
I'll take a look at this.
