### ISSUE TITLE
July 2016 Port 25 - Add examples of <hgroup>

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#650]
Editorial (not testable). The linked issue (from the commit) has a good discussion that motivated this change, but we should probably have a second look at this before porting... @stevefaulkner 

https://github.com/whatwg/html/commit/648ae64bb6cf61487bee534df2107c33bbd9dcbe

**Comment by chaals** [comment]
We don't have an `hgroup` element, so this is moot. If we should, that would be a different issue.
