### ISSUE TITLE
July 2016 Port 26 - Couple of editorial cleanup

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#655]
Editorial alignment that improves readability (not testable):

https://github.com/whatwg/html/commit/c9b8b1759bf86ae0ce2bd2bce46e082b1f555d64

Use of various terms consistently: form field -> text control, etc. (not testable):

https://github.com/whatwg/html/commit/f5cf21cbae5a6227221a0eba62688cfbc198256b

**Comment by cynthia** [comment]
Closing due to change in work mode.
