### ISSUE TITLE
July 2016 Port 27 - Remove replace arg to window.open()

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#656]
Alignment to real-world implementations. Tests (http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=4320 ) show this is only supported in IE/Edge. No other implementations are adding it, so time for the feature to go.

https://github.com/whatwg/html/commit/f444d452cb062ba848570c7b69e6cfcf8aac5c62

**Comment by arronei** [comment]
Will occur with new merge process.
