### ISSUE TITLE
Which branch should I check out for translation?

### ISSUE THREAD

**Issue by mulder21c** [w3c/html#660]
Hi, I am a web developer in Korea.
I want to translate the HTML 5.1  specification, so I forked the repository(github.com/w3c/html), and checked out the 5.1  branch, and then I am currently  translating with include files in section directory. (I am editing that files, then exporting with bikeshed and multiple.js)

I noticed that the 5.1 specification changes to the recommendation.
But, it is still described as CR-20160621 version in includes/status.include file.

So  I want to know if it is right that I am looking at that branch, or  which branch to look at, if not.

**Comment by chaals** [comment]
Hi,

First, thank you for the offer to translate. Please also follow the steps outlined in https://www.w3.org/Consortium/Translation/ (mostly, send an email to a mailing list to announce that you are working on a translation)

if you are trying to translate the Recommendation then you should check out the 5.1 branch. You will discover that there are a few small things - perhaps the status, probably some references - that we edited by hand after building, but the rest of the text is the same. @siusin might know in more detail exactly what was edited after building.

**Comment by siusin** [comment]
Hey @mulder21c,

Yep, most of the changes were in the status, the changes section and the refs section IIRC, also a [editorial fix](https://github.com/w3c/html/commit/7a298e2841cc3c60ef7169d0387f58c874e8b8d8) on a bad example.

If it helps, I can create a "published" folder in the 5.1 branch, and upload the stable version of HTML 5.1.

**Comment by adanilo** [comment]
The "published" folder is a good idea, agreed. Closing now.

**Comment by mulder21c** [comment]
Thanks for your replies and advices, @chaals, @siusin .

Your comments are sufficient to know what I should do. :-)

I think it would be helpful if I can easily compare the difference between any files that is in the "published" folder and any files that is published using bikeshed (if that file is "single-page.html" or are splitted files) through git-diff.

**Comment by r12a** [comment]
postscript: chaals, i wonder whether we could use a 'translation' label for things like this, since they aren't really issues of the review comment type, and this didn't really need to be notified to the i18n WG (unless i missed something)?

**Comment by chaals** [comment]
@r12a Good idea. Done.
