### ISSUE TITLE
HTML History: no proposal was "rejected" at a 2004 workshop

### ISSUE THREAD

**Issue by dckc** [w3c/html#664]
After discovering this bit:
> The proposal was rejected on the grounds that the proposal conflicted with the previously chosen direction for the Web’s evolution
-- [history section](https://www.w3.org/TR/2016/REC-html51-20161101/introduction.html#introduction-history)

I reviewed the [summary of the relevant workshop](https://www.w3.org/2004/04/webapps-cdf-ws/summary) looking for such a decision, which would be quite unusual -- I don't think [W3C workshops](https://www.w3.org/2003/08/Workshops/archive) have mandate to make any decisions -- and it's clear that "There were three topics raised for straw poll: ...  the results are not binding."

I suggest:

> The proposal was not pursued; arguments against included ...

p.s. I was going to suggest an edit directly, but I can't find the source of this section. Where is it?

**Comment by stevefaulkner** [comment]
@dckc FYI - it's here https://github.com/w3c/html/blob/html5.1/sections/introduction.include

**Comment by chaals** [comment]
... and we would be very grateful if you do propose the edit directly :)

**Comment by dckc** [comment]
What's next? Do I close this? Let's try it and see...
