### ISSUE TITLE
June 2016 Port 1 - Extract bits out of a javascript URL through serialization

### ISSUE THREAD

**Issue by adanilo** [w3c/html#666]
> The root cause here is a change in the URL parser that allows all
> schemes to have components such as host. Without this change more
> obscure javascript URLs such as javascript://test/%0Aalert(1) would
> fail to function.

https://github.com/whatwg/html/commit/4113965994bb5d0c650bae13f28883d525a34002

**Comment by cynthia** [comment]
Closing due to change in work mode.
