### ISSUE TITLE
June 2016 Port 2 - Editorial: "allowed to show a popup" → "triggered by user activation"

### ISSUE THREAD

**Issue by adanilo** [w3c/html#667]
> The "allowed to show a popup" algorithm can be more generally useful than just in popup blocking. It should get a more general name so that it can be reused more broadly.
> 
> This commit also moves it into the "Activation" section, instead of the "Browsing context names" section, as the former makes a lot more sense.

https://github.com/whatwg/html/commit/797f412eb78fd88bd5d0a1c098d17fbf1736c188

**Comment by cynthia** [comment]
Closing due to change in work mode.
