### ISSUE TITLE
June 2016 Port 5 - Fix and clarify child browsing context name property set definition

### ISSUE THREAD

**Issue by adanilo** [w3c/html#670]
> Follow up to #1312. Make “child browsing context name property set”
> actually return browsing context names and clarify how the omitting
> duplicates process works.

NB: Relies on porting change #1312 from May before applying. https://github.com/whatwg/html/commit/a2bde183aa5eddc3a58c4852ac9f4c3431ea86fa

**Comment by cynthia** [comment]
Closing due to change in work mode.
