### ISSUE TITLE
June 2016 Port 6 - Fix races between tasks resolving/rejecting play promises and them be…

### ISSUE THREAD

**Issue by adanilo** [w3c/html#671]
> For example, if pause() is called, it creates a task to reject all
> promises even if there is none around. If play() is called just after,
> this task would reject the newly created promise.
> 
> This is fixing the issue by creating tasks rejecting/resolving a given
> list of promises, copied for the task.

NB: This requires a lot of other rewording in the media loading section to be applied. https://github.com/whatwg/html/commit/18be384bc7c9c1a7f3201a73e870682844addf3a

**Comment by cynthia** [comment]
Closing due to change in work mode.
