### ISSUE TITLE
header listed under "sections", but is not sectioning content

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#68]
http://w3c.github.io/html/semantics.html#sections
suggest moving to grouping content
http://w3c.github.io/html/semantics.html#grouping-content

**Comment by travisleithead** [comment]
would you limit to...
3.2.4.2.3. Sectioning content

Sectioning content is content that defines the scope of headings and footers.
⇒  article , aside , nav , section 

So... footer would go too?

**Comment by chaals** [comment]
> So... footer would go too?

Makes sense. 

The distinction between what gets into those two sections is a bit of a mystery at first glance (but then, that's true for a lot of the spec today…)

**Comment by travisleithead** [comment]
@stevefaulkner unless you feel strongly about this, I'm inclined to not fix this.
- This grouping of elements in the TOC is somewhat arbitrary--it is not tied directly to content model descriptions
- Fixing this would probably drag not just `<header>`, but also `<footer>`, `<address>` (where would this go?), `<h1>` - `<h6>` (and related section 4.3.10), and finally `<body>` (should that be listed as sectioning content??)

Let me know if you feel strongly about this one, and I can move just `<header>` and `<footer>`.

**Comment by stevefaulkner** [comment]
@travisleithead, not a high priority. 
suggest moving to 5.2.

**Note:** `footer` is actually a sectioning element, while `header` is not (it being the only one in the sectioning content section which is not sectioning content).

**Comment by unor** [comment]
> **Note:** `footer` is actually a sectioning element, while `header` is not […]

How do you mean that, @stevefaulkner? [The spec notes](http://w3c.github.io/html/sections.html#the-footer-element)

> The `footer` element is not sectioning content; it doesn’t introduce a new section.

and its categories are "Flow content. Palpable content.", not "Sectioning content.".

**Comment by stevefaulkner** [comment]
@unor 
you are correct, don't know how i got that in my head :-(

**Comment by stevefaulkner** [comment]
closing this as its a non issue
