### ISSUE TITLE
June 2016 Port 15 - Make :target definition sticky based on last scroll-to-fragment

### ISSUE THREAD

**Issue by adanilo** [w3c/html#681]
> Fixes #190. As discussed there, Gecko, WebKit, and Blink all save the
> last-scrolled-to element as what matches :target.
> 
> Also moves :target's definition to live alongside the rest of the
> pseudo-classes, referencing the target element concept from the
> navigation section.

https://github.com/whatwg/html/commit/1488bb6f765e41558bb221dc247012a35d88527b

**Comment by cynthia** [comment]
Closing due to change in work mode.
