### ISSUE TITLE
June 2016 Port 18 - Cleanup "create a new browsing context"

### ISSUE THREAD

**Issue by adanilo** [w3c/html#684]
> This attempts to make this algorithm as similar to “initialising a new
> Document object” as possible to make it easier to merge parts of them
> going forward:
> 
> * It adds the text “Do not obtain any source texts for scripts or
> modules.” for the InitializeHostDefinedRealm() which appeared to be
> missing.
> * It more explicitly allocates a new browsing context and returns it.
> * It changes the order of some steps to match those of the other
> algorithm.
> * It removes an unused variable allocation in the other algorithm.

https://github.com/whatwg/html/commit/f139279fb116bbde5d5ee3d257d21778cd774144

**Comment by cynthia** [comment]
Closing due to change in work mode.
