### ISSUE TITLE
June 2016 Port 20 - Allow all HTML element constructors to be subclassed

### ISSUE THREAD

**Issue by adanilo** [w3c/html#686]
> Previously, only HTMLElement itself ran the algorithm necessary to allow
> subclassing for the purpose of custom elements. This prevented most
> customized built-in elements from working correctly. Here we introduce
> the [HTMLConstructor] IDL extended attribute, in order to automatically
> install the correct constructor behavior for all HTML element
> constructors.
> 
> Fixes #1289. See also heycam/webidl#125 where
> an alternate solution was discussed and rejected before arriving at the
> solution contained here.

https://github.com/whatwg/html/commit/4742b18559a6968213b680ea0b0521eae17de7e1

NB: This is for custom elements in reality

**Comment by cynthia** [comment]
Closing due to change in work mode.
