### ISSUE TITLE
June 2016 Port 24 - Fix incumbent settings object definition and add examples

### ISSUE THREAD

**Issue by adanilo** [w3c/html#690]
> As discussed in #473, starting especially from around
> #473 (comment), the
> definition of incumbent introduced in #401 falls down in certain
> important cases. In order to fix this, we introduce several new
> concepts, which takes care of these trickier examples. These examples
> are now included in the spec, and spell out exactly how exactly
> incumbent settings object calculation works in increasingly-complex
> scenarios.
> 
> The new algorithms "prepare to run a callback" and "clean up after
> running a callback" will be used by Web IDL, similarly to how it already
> uses "prepare to run script" and "clean up after running script."
> 
> Another notable change is that EnqueueJob now correctly tracks the
> necessary goings-on in order to make the incumbent settings object work
> correctly when promises are used to schedule callbacks. However, we
> noticed that it does not correctly track the entry settings object; the
> previous text, introduced in #1091, incorrectly referred to
> job.[[Realm]], which does not exist. The correct fix is unfortunately
> not obvious. So we add a warning there for now, with #1426 tracking
> further work.

https://github.com/whatwg/html/commit/f97c3e478654114bd4c9cc8587418a5519f9eb09

**Comment by cynthia** [comment]
Closing due to change in work mode.
