### ISSUE TITLE
June 2016 Port 25 - Fix javascript: URL example explanation

### ISSUE THREAD

**Issue by adanilo** [w3c/html#691]
> #1107 updated the algorithm to, per
> the browser majority, give 204s for non-strings instead of only for
> undefined. This updates the example following the normative algorithm
> to account for that change as well.

https://github.com/whatwg/html/commit/cdf82d5def226004bb90479c284c22e329a4edbd

**Comment by chaals** [comment]
Where is the dependent issue for the algorithm update?

**Comment by cynthia** [comment]
Closing due to change in work mode.
