### ISSUE TITLE
June 2016 Port 28 - Allow dashes in comments

### ISSUE THREAD

**Issue by adanilo** [w3c/html#694]
> Make dashes in comments no longer be parse errors
> 
> The spec disallowed dashes in comments in order to have conformance
> checkers point out the problem for pre-2006 Firefox that implemented
> SGML-style comment parsing, and to match the syntax requirements in
> HTML4 and XML. These are no longer relevant and instead people are
> getting unhelpful error messages when validating for markup like:
> 
> </div>
> 
> * A comment that ends with a dash is now allowed: 
> * A comment that contains -- is also allowed: 
> * A comment that contains --! is also allowed: 
> * The following are still parse errors: , <!-- --!>
> 
> Fixes #1351.
> 
> Also remove obsolete comments in the spec's source about rewinding
> when hitting EOF (see #1058).
> 
> This also introduces new states to make "<!--" in a comment a parse
> error, since now that "--" is allowed that needs to be handled
> separately.

This is https://github.com/whatwg/html/commit/518d16fdc672d1023dcfd2847d86f559d13a842f which will need manual review. Some of the content is already in the W3C spec, some not. Edit with care.

**Comment by cynthia** [comment]
Closing due to change in work mode.
