### ISSUE TITLE
June 2016 Port 29 - Define initial about:blank document better

### ISSUE THREAD

**Issue by adanilo** [w3c/html#695]
> * We don’t need to say that the encoding of a new document is UTF-8, that’s the default.
> * We also don’t need to say it’s URL is “about:blank”, that’s the default too.
> * We do need to say its content type is “text/html”, as that’s not the default.
> * We do need to say its mode is “quirks”, as that’s not the default and since initial about:blank isn’t parsed, it won’t be set. (This will require a change to DOM to indicate initial about:blank can also set mode.)
> * We need to create the document before using it.
> 
> This change also merges two steps in the initializing a new document algorithm to become one step. This is an improvement as the steps seemed different, but were actually equivalent.

Port https://github.com/whatwg/html/commit/8edc92d6e42878662c7f9f75a43352bd341ae01d which also appears to be dependent on earlier commits.

**Comment by cynthia** [comment]
Closing due to change in work mode.
