### ISSUE TITLE
June 2016 Port 30 - Use fullscreen logic for initial about:blank documents too

### ISSUE THREAD

**Issue by adanilo** [w3c/html#696]
Related to issue #695 

> Fixes #1385.
> 
> (It seems this was an oversight
> 8359fee resulting from having two
> places to initialize document objects as the result of navigation.
> Cleaning that up is a larger separate task.)

Port https://github.com/whatwg/html/commit/c2a8d605e0115c80d1ccb4b15371ecaa56a33e30

**Comment by cynthia** [comment]
Closing due to change in work mode.
