### ISSUE TITLE
June 2016 Port 31 - Cross-origin objects: do not wrap JavaScript functions

### ISSUE THREAD

**Issue by adanilo** [w3c/html#697]
> Instead, carefully refer to the original algorithm and use that.
> Otherwise we confuse the globals.
> 
> This can become more formalized once IDL generates an abstract
> operation for each member of an object.

Port https://github.com/whatwg/html/commit/db361b608157b5cf9fd0d491d7dc76cdce80380b

**Comment by cynthia** [comment]
Closing due to change in work mode.
