### ISSUE TITLE
June 2016 Port 32 - Add a playsinline attribute to <video>

### ISSUE THREAD

**Issue by adanilo** [w3c/html#698]
> Closes #1237. For most user agents this will be a no-op, but this gives
> a standardized pragma for opting into inline behavior in iOS Safari.

Port https://github.com/whatwg/html/commit/6e17d01489060988451fc6607089ef4e2d00bbfa

**Comment by chaals** [comment]
@grorg Is this implemented in shipping Safari? That seems to be a minimum condition for considering it worthwhile adding. Since it's otherwise a no-op, the alternative is not to have it :)

**Comment by cynthia** [comment]
Closing due to change in work mode.
