### ISSUE TITLE
May 2016 Port 6 - Add allow-presentation to sandbox flags

### ISSUE THREAD

**Issue by cynthia** [w3c/html#717]
https://github.com/whatwg/html/commit/0678e3de01a3ef83c5f6f0c017e7464ede1d8ec1

Add allow-presentation to sandbox flags
Fixes w3c/presentation-api#299.

* Upstream: whatwg/html@0678e3de01a3ef83c5f6f0c017e7464ede1d8ec1

**Comment by chaals** [comment]
Duplicates #437
