### ISSUE TITLE
Incorrect URL to a DTD for the named entity declarations

### ISSUE THREAD

**Issue by komputist** [w3c/html#731]
In the following sentence of section [9.2 of HTML 5.1,](https://www.w3.org/TR/2016/REC-html51-20161101/xhtml.html#parsing-xhtml-documents), the URL of the link in the last part of the sentence, is incorrect:

> This specification provides the following additional information that user agents should use when retrieving an external entity: the public identifiers given in the following list all correspond to <a href="https://www.w3.org/TR/2016/REC-html51-20161101/entities.dtd">the URL given by this link</a>

Currently, that URL points to https://www.w3.org/TR/2016/REC-html51-20161101/entities.dtd - which does not exist. Whereas in HTML 5.0 [section 9.2](https://www.w3.org/TR/html5/the-xhtml-syntax.html#parsing-xhtml-documents) and HTML Living Standard [section 13.2](https://html.spec.whatwg.org/multipage/xhtml.html#parsing-xhtml-documents), then, the URL is (as expected) a data URI containing a DTD which declares the named character references that the spec defines in [section 8.5](https://www.w3.org/TR/2016/REC-html51-20161101/syntax.html#named-character-references).

**Comment by TheEskhaton** [comment]
This sentence from [section 8.5](https://www.w3.org/TR/2016/REC-html51-20161101/syntax.html#named-character-references) after the table also has a link to a JSON file which doesn't exist:

> This data is also available [as a JSON file](https://www.w3.org/TR/2016/REC-html51-20161101/entities.json).

The URL Points to https://www.w3.org/TR/2016/REC-html51-20161101/entities.json which doesn't exist.

**Comment by chaals** [comment]
The relevant entity lists are in the repository, so it seems to be a linking issue that is also currently affecting HTML 5.2 :(

**Comment by tstarling** [comment]
It's not just linking, the file is actually missing, right? Odd, since it is in https://github.com/w3c/html/tree/gh-pages

**Comment by travisleithead** [comment]
This is working fine for me at the editor's draft--is this only an issue with the published REC doc?

Both links now point to: http://w3c.github.io/html/entities.json

If we need to update the REC doc in-place to fix this, then @chaals might be able to handle this.

**Comment by chaals** [comment]
I don't have enough magic to fix a link in the Rec document, but @siusin probably does.

**Comment by komputist** [comment]
@travisleithead The expected fix is a **data URI** - namely the same data URI that HTML 5.0 and Living Standard have. The content of the data URI is a DTD which defines the character entities.

Btw, I already said the very same thing in my initial message:  «Whereas in HTML 5.0 section 9.2 and HTML Living Standard section 13.2, then, the URL is (as expected) a data URI containing a DTD which declares the named character references that the spec defines in section 8.5.»

Thus: The expected fix is **not** a link to a JSON list of the entities. (Hence, the issue has not been fixed in the working draft.)

You find links to the appropriate section of HTML 5.0 and HTML Living Standard in my initial message. Both sections contains the data URI. (I could have posted the data URI here, but is  very long and ugly ... so I spare you.)

**Comment by komputist** [comment]
The missing link to the JSON file that @TheEskhaton mentioned is a **different** issue (even if it might be [sic!] linked). The bug **I** reported is about HTML 5.1 section 9.2. Whereas the bug @TheEskhaton mentions is about HTML 5.1 section 8.5. I suppose @TheEskhaton or someone else should open a separate bug for that JSON problem.

**Comment by siusin** [comment]
The missing files have been uploaded. Hope it helps.
- [https://www.w3.org/TR/2016/REC-html51-20161101/entities.dtd](https://www.w3.org/TR/2016/REC-html51-20161101/entities.dtd)
- [https://www.w3.org/TR/2016/REC-html51-20161101/entities.json](https://www.w3.org/TR/2016/REC-html51-20161101/entities.json)
- [https://www.w3.org/TR/html52/entities.dtd](https://www.w3.org/TR/html52/entities.dtd)
- [https://www.w3.org/TR/html52/entities.json](https://www.w3.org/TR/html52/entities.json)

**Comment by chaals** [comment]
@siusin can we close this?

**Comment by siusin** [comment]
@chaals 
Sure!
