### ISSUE TITLE
Break tag includes closing slash

### ISSUE THREAD

**Issue by ghost** [w3c/html#737]
Example 6 of the address element shows the use of the break tag but includes the closing slash, <br/>.
https://w3c.github.io/html/grouping-content.html#the-address-element

While this is allowed, being a void element, it's an exception to the specification for how to write <br> which says nothing about including the closing slash and does not show any same examples of usage. 
https://w3c.github.io/html/textlevel-semantics.html#the-br-element

In addition, the specification clearly states that the closing slash does nothing and, elsewhere stated, is ignored by browsers.

**Comment by stevefaulkner** [comment]
@RobBelics thanks, will fix
