### ISSUE TITLE
Experiment: get current WHATWG/W3C Section 3

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#738]
Using https://diffofhtmls.herokuapp.com/ Get Section 3 current (or explain the differences).

Following this activity, we should know:
* How long the experiment took (in hours)?
  * **Results: 28.7 hours**
* What are the remaining differences (if any)? 
  * Issue #748 - Continue to define xml:base as [not] for HTML docs? 
  * Issue #751 - Accept WHATWG change to drop restrictions on the Bidi algorithm? 
  * Known Difference: We have a detailed section on ARIA roles, states, and properties (mostly non-normative) 
  * Known Difference: We don't define `accessKeyLabel` of the `HTMLElement` interface
* Why there are remaining differences?

**Comment by travisleithead** [comment]
This means all of dom.include will be clean.

**Comment by travisleithead** [comment]
30 minutes elapsed.

**Comment by travisleithead** [comment]
Non-editorial changes: 
* Added [CEReactions] attributes to the IDL
* Switched some DOMString types to USVString

About 3 hours (got bogged down for a bit with understanding eccentricities of Bikeshed linking format). Midway through "Diff of DOM tree accessors" improving linking as I go.

**Comment by travisleithead** [comment]
Now on "Diff of Loading XML documents"

* Bikeshed-ify overhaul of the dom.include section
* Added lots and lots of [strangely] missing links
* Fixing latest bikeshed spec-linking warnings as I go (see #726) -- down to 10 from 21.

About 3 hours.

**Comment by travisleithead** [comment]
Non-editorial changes:
* Dropped `XMLDocument` interface and its `load()` API. `load` was only implemented in Mozilla, which is why it was dropped from the spec. The `XMLDocument` interface is now defined in the DOM spec, so no need to have even a shell in the W3C version.
* Adds the `innerText` API to the Document object (from whatwg/html commit 132a55eb22d419566650c6f2a38c53e68475e7a3 - Upstream the innerText spec)
* WHATWG still has `accessKeyLabel` but we ripped it out in #99

Other notes:
* 3.2.1. was substantively different, but due to different focus of the examples. I left this un-touched.

1.5 hours.

**Comment by travisleithead** [comment]
Finished "Elements in the DOM" section.
 * Added some content on element construction from interfaces, and referenced W3C custom-elements spec.

Skipping the section on "HTML Element Constructors" as this is merged content from the custom elements spec.

Now on: "Element Definitions"

3 hours elapsed time. (excludes time spent syncing and updating the build system to latest bikeshed).

**Comment by travisleithead** [comment]
* Links to "hidden" were a mess! Sorted these out into the "hidden" attribute, "hidden" track type, and "hidden" input element state.
* Various other linking fixes/improvements
* "class" global attribute section shuffled around, conformance requirements moved to DOM spec.
* New global event handler attributes defined:
  * onauxclick (new)
  * onloadend was missing

Ended just before "the lang and xml:lang attributes"

6.5 hours

**Comment by travisleithead** [comment]
* note that other specs can define translatable attributes (such as aria-label)
* we define xml:base global attribute for HTML-in-XML docs (NO CHANGE)

3 hours

**Comment by stevefaulkner** [comment]
Found and fixed linking error presumable caused by your updates https://github.com/w3c/html/commit/242f84ab693aaa53674e5980f4f776dc5de6ee55

**Comment by travisleithead** [comment]
* Refactoring of the DOMStringMap get/set/delete algorithms; no substantive changes
* Moved DOMStringMap interface and algorithms from section 2 to section 3.

Left before adding innerText API

3 hours

**Comment by travisleithead** [comment]
* `innerText` added. Tests are available at: https://github.com/w3c/web-platform-tests/tree/master/innerText

1 hour

**Comment by travisleithead** [comment]
* Dropped BiDi section, but opened https://github.com/w3c/html/issues/751 to validate this

10 minutes, (+issue filing/whatwg spelunking overhead)

**Comment by travisleithead** [comment]
* Cleaned up and link-ified the ARIA roles/states/properties table. Added missing refs in the dependencies section.

2 hours

**Comment by travisleithead** [comment]
* Some final link checking and `<code>..</code>` removals where appropriate. There exist lots of places to further simplify the source code now that Bikeshed supports a shorthand for attr-value links (see https://github.com/tabatkins/bikeshed/pull/888)

2 hours
