### ISSUE TITLE
some link error while building the spec with bikeshed in HTML5.1 branch 

### ISSUE THREAD

**Issue by mulder21c** [w3c/html#756]
Hi, I tried building the spec with bikeshed in the latest commit of HTML 5.1 branch.

but i met some link errors.

I want to know whether this is a problem or not.

![bikeshed-error](https://cloud.githubusercontent.com/assets/14821565/21292514/6cd61824-c54b-11e6-9df4-62dac72425c0.jpg)

**Comment by cynthia** [comment]
This shouldn't be a problem unless you are producing a canonical version of the document. Does the final output look fine?

**Comment by ghost** [comment]
@cynthia Hi, I think I've got the exact steps, please check it out.

I attach a video of what I have done.

[video(youtube)](https://youtu.be/reqOgA-tJ88)

**Comment by travisleithead** [comment]
While we'd like to fix this, we found it faster to just in-place update the Recommendation with specific errata (vs. try to get this edition building again).

> I want to know whether this is a problem or not.

I guess the answer is no.
