### ISSUE TITLE
HTML WG in the specification

### ISSUE THREAD

**Issue by xfq** [w3c/html#758]
In [§ 1.4](https://github.com/w3c/html/blob/d88159a3dbb518653d99c94f603679678ba5047f/sections/introduction.include#L138-L143):

> Since then, the W3C HTML WG has been cherry picking patches from the WHATWG that resolved bugs registered on the W3C HTML specification or more accurately represented implemented reality in user agents. At time of publication of this document, patches from the WHATWG HTML specification have been merged until January 12, 2016. The W3C HTML editors have also added patches that resulted from discussions and decisions made by the W3C HTML WG as well a bug fixes from bugs not shared by the WHATWG.

This paragraph/section needs to be updated, since the HTML WG is Web Platform WG now.

**Comment by cynthia** [comment]
Thanks for pointing this out, patch is in the PR queue for another editor to r+.
