### ISSUE TITLE
consider allowing multiple main elements in the DOM when only 1 is visible

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#761]
There is a use case that the current conformance requirements does not cover. That is the case where the DOM consists of multiple UI views, but only one is visible/active at a particular time (e.g. single page apps). In this case it makes sense to loosen the restriction to allow mutliple instances of the [`main`](https://w3c.github.io/html/grouping-content.html#the-main-element) element, but only 1 can be visible at any time. The [`hidden`](https://www.w3.org/TR/html52/editing.html#the-hidden-attribute) attribute must be present on all other instances.

Conforming Example

```
<main></main>
<main hidden></main>
<main hidden></main>
```

Non-conforming Example

```
<main></main>
<main hidden></main>
<main></main>
```

**Comment by aardrian** [comment]
+1

**Comment by dylanb** [comment]
Why is this different from the following?

```
<main>
<div >Active content</div>
<div hidden>Other stuff</div>
<div hidden>More other stuff</div>
</main>
```

**Comment by jspellman** [comment]
+1 Steve. It's a common and important use case.

**Comment by stevefaulkner** [comment]
@dylanb there is no difference except the former may provide developers with more choice in regards to how they code their pages.
