### ISSUE TITLE
summary element definition does not reflect implementations

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#764]
In all implementations: blink/webkit/firefox the `summary` element is an interactive element. It receives focus and is operated to open/close the details element. It is also exposed as a control via acc APIs in all implementations.

Suggest the spec should be updated to reflect this.

also filed against whatwg spec: https://github.com/whatwg/html/issues/2246

**Comment by stevefaulkner** [comment]
related https://github.com/whatwg/html/commit/5e0b8e673d09bc6042190335f9e522e9c802d26c

**Comment by chaals** [comment]
This doesn't completely document behaviour. A summary element that is [the last child](http://chaals.github.io/testcases/details-with-summary-last-manual.html) or [a direct child with siblings before and after](http://chaals.github.io/testcases/details-with-summary-middle-and-last-manual.html) doesn't abort the algorithm but instead actually behaves as a valid `summary` that is the first child of the `details` element. A [descendant `summary`](http://chaals.github.io/testcases/details-with-misplaced-summary-manual.html) does not get recognised, but overall it seems the first `summary` that is a direct child of the `details` element is recognised.

(a couple more tests would be handy to confirm really edge cases, but I doubt they are critical priority work)

**Comment by chaals** [comment]
The rendering stuff seems to be OK already. I made a commit to fix the activation algorithm that should have been a PR - except I was tired and missed the button - plus another PR. I think that should get us nearly there - maybe we need to note the interactive nature e.g. in describing what elements have `.tabindex == 0` by default but that's a different issue (#199)…

**Comment by chaals** [comment]
`summary` should also be listed in dom.include at #interactive-content

**Comment by chaals** [comment]
Oh. The rendering section only deals with the case where `summary` is used correctly.

If it isn't the first summary element that is a child of a details element, then it's basically treated like a `span`.

**Comment by LJWatson** [comment]
Closed with #851
