### ISSUE TITLE
Should the reference to Polyglot Markup be removed?

### ISSUE THREAD

**Issue by xfq** [w3c/html#765]
The Polyglot spec is mentioned in [§ 1.11](https://github.com/w3c/html/blob/a2c91fad226e62419aef4c67581cec267df61b5e/sections/introduction.include#L1295-L1306), but [it was retired and published as a WG Note](https://www.w3.org/standards/history/html-polyglot) in 2015.

**Comment by cynthia** [comment]
Yes, I think the reference should be retired.
