### ISSUE TITLE
Standardize <template> variables and event handlers

### ISSUE THREAD

**Issue by Mevrael** [w3c/html#766]
This is a proposal on standardizing `<template>` parser which would allow developers:
1.  put variables,
2. use simple statements
3. and attach event handlers when template Node generated/inserted into DOM

**Current stage: Open Discussion about the HTML syntax and JS API**

### Why?

Templates finally standardized the way of making re-usable parts of HTML, templates for widgets/components, however, they are still weak and one of the most general use cases in templates is to put data into them which, currently, is not possible without using a 3rd party library (template engine) or a custom implementation.

This brings:
1. too much diversity across the Web (everyone is doing the same but in a different way)
2. code works slower because it is not a native code which is implemented by a browser.
3. bundle size increases and in case of huge production apps with many 3rd party components it is often required to import also different template engines or frameworks.

### What is needed to be discussed and standardized?

1. How variables should be included inside a `<template>`.
2. How event handlers should be attached to elements inside a `<template>`.
3. What statements (for example "if") are allowed and how they should be used inside a `<template>`

### 1. Variables inside a `<template>`

I would +1 the most popular solution used across many template engines in many languages - variable name should be put inside a {{ }}. To make life even easier and faster it could be implemented as a simple string.replace. We may force developers to write a variable name without a spaces, i.e. {{ var }} will be invalid and {{var}} will work.

### 2. Attaching event handlers to a `<template>` elements

I would propose here new `handler="method"` attribute which would receive an Node when called.

### Example HTML

```html
<template id="card">
  <card>
    <h2>{{title}}</h2>
    <div>{{description}}</div>
    <a href="/card/{{id}}">Read more</a>
    <button handler="onEdit">Edit</button>
  </card>
</temlate>
```

### Example JavaScript

In JS I would suggest just adding new function

```c
Node parseTemplate(String id, Object data = {}, Object handlers = {})
```

because current syntax and manual clone/importNode is ridiculous. We already have functions parseInt, parseFloat, etc.

```javascript
document.body.appendChild(parseTemplate('card', {
  title: 'Card title',
  description: 'Hello, World',
  id: 42
}, {
 onEdit(btn) {
   btn.addEventListener('click', () => {
      // ...
   });
  }
});
```

Currently I have no opinion on statements, may be, we could allow only simple inline statements like in ES6 template strings.

**Comment by chaals** [comment]
This feels like it might belong in the custom elements work. In any event, I think it needs more incubation before it's ready to be part of HTML...

**Comment by rniwa** [comment]
See https://github.com/whatwg/html/issues/2254

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
