### ISSUE TITLE
Fix broken external links

### ISSUE THREAD

**Issue by adrianba** [w3c/html#77]
The [W3C link checker](http://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2Fhtml%2Fsingle-page.html&hide_redirects=on&hide_type=all&depth=&check=Check) shows several broken links including the _table sorting model_ links reported in issue #36.

**Comment by adrianba** [comment]
Fixed by 8fd90967b036bb97c26013ba8c5c667e7935773e.

**Comment by plehegar** [comment]
Fixes are in #150
