### ISSUE TITLE
Update dialog focusing algorithm 

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#773]
After discussion here: https://github.com/whatwg/html/issues/1929 there is rough consensus to modify the existing dialog focus steps to make the `dialog` element focusable by default unless there is a control within the dialog that has an `autofocus` attribute.
Since i do not have the chops to work out how the spec needs to change to reflect this, would like those who may do to help @travisleithead @adanilo @arronei @cynthia any ideas?

the relevant spec bits:
https://w3c.github.io/html/interactive-elements.html#the-dialog-element
https://w3c.github.io/html/editing.html#focusing-steps

Firefox are in the process of implementing (dialog available behind flag in latest nightly) and I am working with the FF acc implementers to ensure that the implementation has good acc out of the box.

**Comment by travisleithead** [comment]
Summary:
* `<dialog>` focusable but not in document's tab order (e.g., implied `tabindex="-1"`).
* on focus:
   1. check for descendant `autofocus` attribute. If found, focus automatically moves to first occurrence of that element (in document order)
   2. If not found, dialog element itself gets focus
* default rendering for `<dialog>` is to hide the focus rect.

Did I miss anything?

**Comment by stevefaulkner** [comment]
@travisleithead thats correct, there is also the suggestion from @cookiecrook to provide `outline:none` as a UA style for `dialog`, which i think is a good idea as the `dialog` does not need a visible focus ring and will appease designers ;-)

**Comment by shwetank** [comment]
@stevefaulkner Reading the focussing steps, it I'm a bit unclear whether the focus will return to the original element which triggered the dialog to pop up (the old focus target). 

If its not explicitly mentioned, then it might be a good idea to have that included.

**Comment by stevefaulkner** [comment]
@shwetank yes i agree that is an important behaviour to be included as part of the implementation definition.

**Comment by patricia-gallardo** [comment]
@LJWatson added a testcase to the pull request #1331
