### ISSUE TITLE
add support for `allowusermedia`

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/html#778]
The Media Capture and Streams specification relies on having explicit permission granted to third-party origins when they try to invoke the `getUserMedia` API from an embedded context, via a `allowusermedia` attribute currently as currently [defined in the WHATWG HTML LS](https://html.spec.whatwg.org/#attr-iframe-allowusermedia) (see also https://github.com/w3c/mediacapture-main/issues/268 and https://github.com/whatwg/html/pull/1492 ).

It would be great if this could be defined in HTML5.2 as well.

**Comment by chaals** [comment]
@dontcallmedom what's the implementation status? Following the tealeaves there are hints that this works, but I didn't run across e.g. a test that was clearly relevant, nor an implementation report. Can you give a pointer please?

**Comment by dontcallmedom** [comment]
as far as I can tell, this isn't implemented yet; the closest browser bug report I [have found](https://browser-issue-tracker-search.appspot.com/?q=allowusermedia) is in [Chromium's](https://bugs.chromium.org/p/chromium/issues/detail?id=682258).

I have started looking at test cases, but it looks like the best approach would be to start from the [tests built for `allowpaymentrequest`](https://github.com/w3c/web-platform-tests/tree/master/payment-request/allowpaymentrequest) and make it applicable to `getUserMedia`.
