### ISSUE TITLE
events improvement  adding priority

### ISSUE THREAD

**Issue by publicocean0** [w3c/html#781]
i move my suggestion from jquery to native api 

i suggest to add a new feature on bind/on method

like this example

$('body').click(function(){...},{priority:0})

where priority is a number.
Then user clicks in a target .... jquery order all callbacks to be executed for this target, ordering before by priority.
In this way i can decide the order in executing events, i can decide if a event has to to executed always before for specific needs for example.

priority can be added in native listeners in similar way

**Comment by chaals** [comment]
Hi,

this feature should be incubated better. It is missing an explanation of what problem needs to be solved, what approaches might be most effective, and some indication that this will be implemented.

If you don't have a space of your own to develop that material, http://discourse.wicg.io is an incubation space for ideas that may become part of HTML.

**Comment by publicocean0** [comment]
ok thanks for suggestion. It was just a idea when you have different indipendent and decoupled modules using same events but you need to execute one before to another for the correct visualization. Surely they are rare case... but it can happen. 
Anyway  i wrote it also in that site  http://discourse.wicg.io   with other requests more important about service worker.  Anyway discussing with a member i saw is not very prepared tecnically so i think is difficult to filter correctly the proposals there:) :) A person telling to solve using ajax instead websocket for async from server  message uhmmm sincerelly it is better he change job ahahaha if all is possible with ajax for what reason to introduce websocket ... Maybe for him it is better to remove websocket and html3 :):)

**Comment by publicocean0** [comment]
thanks for support . ciao
