### ISSUE TITLE
Minor concerns related to phrasing of text in input type=number

### ISSUE THREAD

**Issue by aphillips** [w3c/html#788]
This is related to issue#343: I'm opening it due to investigating whether I18N WG is satisfied with that issue being closed (which I think we are).

Section 4.10.5.1.13 Number State contains this text:

> This specification does not define what user interface user agents are to use; user agent vendors are encouraged to consider what would best serve their users' needs. For example, a user agent in Persian or Arabic markets might support Persian and Arabic numeric input (converting it to the format required for submission as described above). Similarly, a user agent designed for the French market might display the value with apostrophes between thousands and commas before the decimals, and allow the user to enter a value in that manner, internally converting it to the submission format described above. 

My concern here is that "user agent in XXX market(s)" is confusing. We recommend in [implementation notes](http://w3c.github.io/html/sec-forms.html#implementation-notes) that the implementation follow page language. So instead of the "user agent in markets" phrasing (which is also odd because user agents typically don't have "market specific" versions), I'd prefer text like:

> This specification does not define what user interface user agents are to use; user agent vendors are encouraged to consider what would best serve their users' needs. For example, when displaying a page in the Persian or Arabic languages, a form might support Persian and Arabic style numeric input (converting it to the format required for submission as described above). Similarly, a user agent showing a page in a French locale might display the value with apostrophes between thousands and commas before the decimals, and allow the user to enter a value in that manner, internally converting it to the submission format described above.

**Comment by aphillips** [comment]
(maintainers, please add the i18n tag: I don't have permission)

**Comment by chaals** [comment]
Agree that the current wording about a user agent in a given market - as opposed to working with content in a given language - is confusing. The change looks good to me.

**Comment by cynthia** [comment]
Does this actually reflect what the implementations do? I'm worried that the implementations won't go this far. (and unless there is a strong push+market demand, never will)

**Comment by chaals** [comment]
It isn't normative - although I guess that should be clarified with "may" instead of "might". But yes, I frequently use applications where the forms accept input in local format, and process it themselves to produce the right wire format.

I haven't run across it in a user agent, but it is reasonable behaviour and seems reasonable to note that it may occur.
