### ISSUE TITLE
Ambiguity in passage about when header/footer applies to whole page

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html#790]
The entries for `header` and `footer` each contain the following passage:

> When the nearest ancestor sectioning content or sectioning root element is the body element, then it applies to the whole page, unless they are descendants of the main element.

Presumably the "it" refers to the `header` or `footer` element as applicable.

But it's not clear if "they" is meant to refer to the element's nearest ancestor sectioning content or sectioning root element, or the relevant `header` or `footer` element. Either way, the outcome is the same in terms of whether the `header` or `footer` applies to the whole page. But a specification should be more precise than this.

Recommend rewrite as follows:

> When the nearest ancestor sectioning content or sectioning root element is the `body` element, then the [`header`|`footer`] element applies to the whole page, unless it is a descendant of the `main` element.

**Comment by jasonkiss** [comment]
This may be a little pedantic, but it just occurred to me that the `body` element is a sectioning root, and not sectioning content, so my previously proposed rewrite is also incorrect. Same thing goes for the passages that say "Assistive Technology may convey the semantics of the [`header`|`footer`] to users when the nearest ancestor sectioning content or sectioning root element is the `body` element."

In addition to rewriting these two paragraphs, I'd probably re-order and tweak some of the other paragraphs a bit, too.

See the PR: https://github.com/w3c/html/pull/797  (although it's failed some ipr check...)

**Comment by travisleithead** [comment]
Thank you! Shall I merge PR #797 or do you have more you want to add to it?

**Comment by chaals** [comment]
@jasonkiss ping?

**Comment by jasonkiss** [comment]
Sorry for the delay. Nothing more from me. Can merge #797.

**Comment by cynthia** [comment]
Merged, so closing.
