### ISSUE TITLE
headings and sections examples are inconsistent

### ISSUE THREAD

**Issue by chaals** [w3c/html#802]
Hi, as far as I can tell, Examples 24 and 25 and the text around them in the [headings and sections section](https://w3c.github.io/html/sections.html#headings-and-sections) 4.3.9 are inconsistent.

Stripped down, 24 and the normative text before and after it it says you get

```
<body>
  <h1>level 1 in sectioning root</h1>
  <section>
    <h2>level 2 in explicit section</h2>
      <h3>level 3 in implied section</h3>
  </section>
  <section>
    <h3>level **2** in explicit section</h3>
  </section>
</body>
```

Whereas example 25 suggests that isn't so.

I haven't run them through the algorithm itself yet, but unless I missed something one or other of these examples should be updated whether or not we touch the algorithm - proposed by #794 …

**updated** fixed the missing `/` in the last `section` tag in the second-last line.
**updated** linked to the relevant section

**Comment by chaals** [comment]
I tried to walk through the algorithm on the two examples. I am not certain that I got it right - it is not only complex, but the descriptions of what to do and where to go next are pretty unclear.

**As far as I can tell** example 25 is inconsistent with the algorithm, and as suggested by everything before that in the section, the third heading in the first snippet of the example is level three, but in the second snippet it is level 2. In other words, the example is wrong, because the two snippets are *not* semantically the same.

The first snippet *would* be the same as a snippet like

```
  <section>
    <h2>level 2 in explicit section</h2>
    <section>
      <h3>level 3 in explicit section</h3>
    </section>
    <section>
      <h3>level 3 in explicit section</h3>
    </section>
  </section>
```

**Comment by stevefaulkner** [comment]
@chaals i used the https://validator.w3.org/nu/ to check the outlines (it handily provides a representation for both H1-h6 and the theoretical outline)
You are indeed correct, the second example needs to be changed as per

```
 <section>
    <h2>level 2 in explicit section</h2>
    <section>
      <h3>level 3 in explicit section</h3>
    </section>
    <section>
      <h3>level 3 in explicit section</h3>
    </section>
  </section>
```

will fix.

**Comment by stevefaulkner** [comment]
example outlines for corrected example: https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=http%3A%2F%2Fs.codepen.io%2Fstevef%2Fdebug%2FQdXxLw%2FnqkwvewdgpOA#headingoutline
fixed via https://github.com/w3c/html/commit/ae29e96d2e5594cf081a67c733b3c116fe0a84d7

**Comment by stevefaulkner** [comment]
@chaals if you are satisfied please close.

**Comment by chaals** [comment]
Commented - you got the opening and closing tags reversed.
☕️  ;)

**Comment by stevefaulkner** [comment]
@chaals doh! fixed now, i hope...

**Comment by chaals** [comment]
Fixed in https://github.com/w3c/html/commit/5e022ad6e9b74bf088bb218ce15bb09138ac9ca2
