### ISSUE TITLE
update button element definition to be more descriptive

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#807]
currently the [button element](http://w3c.github.io/html/sec-forms.html#the-button-element) is defined:

>The button element represents a button labeled by its contents

a _button is a button_ sort of sucks.

The ARIA definition of a button role for example is more descriptive

> An input that allows for user-triggered actions when clicked or pressed.
https://www.w3.org/TR/wai-aria-1.1/#button

**Comment by patrickhlauke** [comment]
suggest "interactive control" rather than "button"

**Comment by IanPouncey** [comment]
Using the name of another element, like input, is confusing and "clicked or pressed" is limiting. Suggest “An interactive control, labeled by its contents, that allows for user-triggered actions when activated.”

**Comment by metzessible** [comment]
If the intended result is the outcome of someone conceptualizing using a button when using it, removing the terms "clicked or pressed" will muddle the definition. In my opinion, I would append Ian's suggestion this way:

"An interactive control _simulating_ pressing or clicking, labeled by its contents, that allows for user-triggered actions when activated."

**Comment by handcoding** [comment]
I’d lean toward Ian’s version.

**Comment by LJWatson** [comment]
In these days of click, press, tap and speak, I think @IanPouncey's text is the sane approach.

**Comment by patrickhlauke** [comment]
I'd stay away from the *simulating* aspect...otherwise pretty much anything on a screen is "simulated" to an extent. I'd favor Ian's use of "activation"/"activated"

**Comment by metzessible** [comment]
Yes, everything is simulated on the web. But users tend to misunderstand the connection between the terms used and their real world application. 

Evidence:
http://stackoverflow.com/questions/4201007/what-are-some-of-the-most-frequently-misused-html-tags

Even taking away the word _simulating_, I argue that more people will use elements without making a real-world connection because they don't associate anything with the... well... real world connection.

**Comment by patrickdark** [comment]
"A `button` element represents a form submission control in the submit button state, form reset control in the reset button state, menu disclosure control in the menu button state, or an activation target in the simple button state."
