### ISSUE TITLE
Preserve back-compat for cross-origin Window toString

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#811]
I'd like to preserve the previous behavior of the Object.prototype.toString() call when testing against a cross-origin `Window`, so that it continues to return `[object Window]` rather than the currently speced `[object Object]`.

If other browsers are on board, I think the change is to `CrossOriginGetOwnPropertyHelper ( O, P )`, where the first step is replaced by a step that evaluates `O` and if it is a `Window`, then sets the property descriptor's value to `"Window"`, and conversely `"Location"` for a `Location` instance. Everything else remains the same...

**Comment by travisleithead** [comment]
@Domenic, @annevk

**Comment by domenic** [comment]
This doesn't seem like a good change. This is not "previous behavior"; no browser ever implemented it. And no browser currently does (everyone but Edge follows the current spec; Edge throws).

And arguably, cross-origin windows should not stringify as Windows anyway, since they are so different: e.g. they don't have Window.prototype in their prototype chain.

**Comment by travisleithead** [comment]
Edge's current behavior has broken a few of our tools--throwing has only started happening recently (our shipping release does not yet throw). This only started happening once our Script engine added support for @@ToStringTag :-( Yes, we'll fix the tools...that's the not the point.

The point is that I don't like the current behavior of getting `[object Object]` as if the platform has no idea what this thing is. In nearly every other case, the platform is very clear about object identity... 

I'd be happy with `[object CrossOriginWeirdThing]` if you wanted instead...

**Comment by domenic** [comment]
I just don't see a reason to create churn in all browser engines, possibly introducing their own incompatibilities of the same type, where similar browser-specific tools were assuming that cross-origin windows are `[object Object]`. (Or incompatibilities with non-browser-specific tools that work in 3/4 browsers.)

Object.prototype.toString is not meant to be used as a branding mechanism, especially not cross-origin.

**Comment by annevk** [comment]
I tend to agree with @domenic. It also further encourages what I think is an anti-pattern, determining object types through their string tag.

**Comment by travisleithead** [comment]
I guess this is just another instance of https://github.com/heycam/webidl/issues/129, where folks are relying on `toString` but desperately want a cross-Realm hasInstance or instanceof check to pass.
