### ISSUE TITLE
JavaScript & CSS JS Rendered Blocked

### ISSUE THREAD

**Issue by ghost** [w3c/html#823]
I have JavaScript & CSS JS rendered are blocked. For example :
http://suzukisumberbaru.com/wp-content/plugins/automotive/js/jquery-ui-1.10.3.custom.min.js

How to repair ?

**Comment by ghost** [comment]
This is too :
http://suzukisumberbaru.com/wp-content/plugins/accordions/assets/frontend/css/jquery-ui.min.css

**Comment by chaals** [comment]
Hi, this issue tracker is for issues with the HTML specification https://w3c.gituhb.io/html/

For help with individual questions about how to use jquery, you should try a jquery forum or a general help forum.
