### ISSUE TITLE
idea:document.createElement

### ISSUE THREAD

**Issue by annopnod** [w3c/html#824]
**Exsimple**
CreateElement('div[data-id="1"][data-idd="2"]:html("dd"ss")');
**Output**
&lt;div data-id=&quot;1&quot; data-idd=&quot;2&quot;&gt;&quot;dd&quot;ss&quot;&lt;/div&gt;
**JS Code**
function CreateElement(querystring) {
 var tagname = "";
    var attr = querystring.match(/\[(.*?)\]/g)|| [ ];
    var htmlcode = querystring.match(/:html\((.*?)\)/);
    var matchspecialchars = /[:*?+^${}[\]().|\\]/.exec(querystring);
    if (matchspecialchars) {
        tagname = querystring.substring(0, matchspecialchars.index);
    }
  else{
                tagname=querystring;
            }
    var dom = document.createElement(tagname);
    var attrlist = attr;
    for (var i = 0; i < attrlist.length; i++) {
        var eq = attrlist[i].split("=");
        eq[0] = eq[0].substr(1);
        eq[1] = eq[1].substr(0, eq[1].length - 1);
        if (eq[1].charAt(0) === '"' && eq[1].charAt(eq[1].length - 1) === '"')
        {
            eq[1] = eq[1].substr(1, eq[1].length - 2);
        } else if (eq[1].charAt(0) === "'" && eq[1].charAt(eq[1].length - 1) === "'") {
            eq[1] = eq[1].substr(1, eq[1].length - 2);
        }

        dom.setAttribute(eq[0], eq[1]);
    }

    if (htmlcode) {
        dom.innerHTML = htmlcode[1];
    }
    return dom;
}

**Comment by chaals** [comment]
Hi,

This looks like an interesting utility script, but needs some work before it is ready to raise as an issue. I assume the proposal would be to allow the use of createElement natively as in the example, but it is unclear why this is important enough to implement in a browser.

Proposing it to e.g. [WICG](http://discourse.wicg.io), showing that a library function like this is used widely and demonstrating that there is enough value in making the change to browsers are important before proposing it to the specification.

Also, it is likely that if this gets sufficient support, it should be part of the [DOM](http://github.com/w3c/dom) not HTML …
