### ISSUE TITLE
Hooks for Indexed DB, StructuredSerialize

### ISSUE THREAD

**Issue by inexorabletash** [w3c/html#829]
cc:  @LJWatson  @siusin 

* https://github.com/whatwg/html/commit/915dae1acdf59934d8f7e4820633f727ea33e501 introduces a step which calls into Indexed DB, replacing imprecise spec "monkey patching" with correct behavior across the specs. Context at https://github.com/w3c/IndexedDB/issues/87

* https://github.com/whatwg/html/commit/97d644c97335956610a31e8ad98d1a388c063e84 is a big change (noted as 'breaking') that replaces the StructuredClone hook with StructuredSerialize/StructuredDeserialize. Some commentary at  https://github.com/w3c/IndexedDB/issues/170

It would be good to know what the plan is for syncing with the whatwg doc is for these.

**Comment by chaals** [comment]
Needs more than a 3-minute skim to figure where this is up to in implementation. setting to milestone 7

**Comment by inexorabletash** [comment]
Update: The __StructuredSerializeForStorage()__ hook has landed in [whatwg/html](https://github.com/whatwg/html/commit/b3f8779c76de7718bc970fdbccda18a5164d2f98) and I've picked up use of it in [IndexedDB](https://github.com/w3c/IndexedDB/commit/2aef49f8732d9babbc9ad3188af42943f979178d).

**Comment by LJWatson** [comment]
Ping @adanilo?
