### ISSUE TITLE
Broken & insecure links in spec-data. How to fix?

### ISSUE THREAD

**Issue by edent** [w3c/html#832]
There are several links in `.spec-data` which don't use `https` where available.

I'm not sure what the structure or purpose of the `spec-data` folder is.

Is it OK to just go in an change [links like this](https://github.com/w3c/html/blob/master/.spec-data/biblio/biblio-og.data#L10) to point to `https` sources?  Or do I need to change them in a specific location and regenerate them? Or have I missed the point entirely?

CC @arronei & @adrianba who seem to be the people who last committed to the directory.

**Comment by siusin** [comment]
@edent 

This is very good suggestion, but the `.spec-data ` in our repo is a auto-copy from [Bikeshed](https://github.com/tabatkins/bikeshed) during the [Automatic build process](https://github.com/w3c/html/blob/691eef8940d4da8f44346d321b7d86f11db82f22/docs/editing-documentation.md#automatic-build-process).

Could you please raise an issue or submit a PR to the [Bikeshed tool](https://github.com/tabatkins/bikeshed) repo?  It's said that `.spec-data ` should be [readonly](https://github.com/tabatkins/bikeshed/tree/master/bikeshed/spec-data/readonly), perhaps we shouldn't modify these links here.

**Comment by edent** [comment]
Fixed upstream. https://github.com/tobie/specref/issues/340
