### ISSUE TITLE
contextmenus in pages should not override browser context menus 

### ISSUE THREAD

**Issue by chaals** [w3c/html#853]
The [advice in the section on menus](https://w3c.github.io/html/interactive-elements.html#context-menu-processing-model) to allow user agents to hide the normal context menu, and only present what the author asked for, isn't very helpful.

It allows a phishing-type attack, and may remove important functionality from the browser.

**Comment by gerv** [comment]
Can you explain how it allows a phishing attack? If the attacker has control of the page, they have control of the page, and can just run arbitrary script - they don't need to use a faked-up context menu to do it.

**Comment by chaals** [comment]
I mean that it is possible for the author of the page itself to confuse the user by making the faked-up context menu do something different.

I'm not sure whether that actually opens any **new** security risk... my general rule of thumb is that replacing bits of browser UI isn't good - and then I ask for review from smart people.

**Comment by ZoeBijl** [comment]
FWIW: you can already replace the context menu entirely with JavaScript if you so wish. I’m not sure how these implementations work with keyboard, but they exist nonetheless. I’m not talking about `<menu>`, but rather using divs and buttons or whatever to create menu.

**Comment by chaals** [comment]
This is effectively closed by #882
