### ISSUE TITLE
w3c.github.io and /TR

### ISSUE THREAD

**Issue by xfq** [w3c/html#856]
In [docs/contributing-documentation.md](https://github.com/w3c/html/blob/49073d89a7829dc3dbbfc3802f38bf9845902117/docs/contributing-documentation.md#branches-and-versions):

> The `master` branch is the "work in progress" version of the HTML specification. It is available at https://www.w3.org/TR/html/.

But the link actually contains the HTML 5.1 Recommendation, instead of the latest ED (which is available at https://w3c.github.io/html/).

**Comment by LJWatson** [comment]
With thanks @xfq
