### ISSUE TITLE
Add missing word “characters” in definition of “inter-element whitespace“

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html#863]
See https://github.com/whatwg/html/pull/2501

**Comment by chaals** [comment]
As far as I can tell we already have this: https://w3c.github.io/html/dom.html#inter-element-white-space
@sideshowbarker?

**Comment by sideshowbarker** [comment]
> As far as I can tell we already have this: https://w3c.github.io/html/dom.html#inter-element-white-space
> @sideshowbarker?

Yes—should have checked before I raised this…
