### ISSUE TITLE
(Re)disallow script defer/async attributes w/o src

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html#867]
See https://github.com/whatwg/html/pull/2509

**Comment by chaals** [comment]
@sideshowbarker did you check whether this is relevant to the W3C specification?

**Comment by sideshowbarker** [comment]
> @sideshowbarker did you check whether this is relevant to the W3C specification?

The requirement is not stated in anywhere in https://w3c.github.io/html/ that I could find, so I believe this is relevant yeah

**Comment by chaals** [comment]
The requirement seems to be somewhat arbitrary, since ignoring it would have no measurable effect beyond failing validation, but for that reason it seems harmless too.
