### ISSUE TITLE
CFC: Publish HTML5.1 2nd Edition

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#874]
This Call For Consensus (CFC) is to publish an update to HTML5.1.

An issue has been identified with HTML5.1, whereby the system identifiers in the example doctypes shown in [8.1.1 Doctypes](https://www.w3.org/TR/2016/REC-html51-20161101/syntax.html#the-doctype) are incorrect. They use "https://" instead of "http://".

The original issue and subsequent discussion can be found in #754.

The issue has already been corrected in HTML5.2 and would be easy to backport into HTML5.1 2nd Edition. The administration required to publish HTML5.1 2nd Edition would be trivial.

Please respond to this CFC by end of day on Wednesday 19th April 2017. 

* If you agree with the proposal to publish an update to HTML5.1, post a +1 on this issue
* If you disagree with the proposal to publish an update to HTML5.1, post a -1 to this issue

Alternatively you can send an email with your response to public-webapps@w3.org. Positive responses are encouraged, but silence will be taken as implicit agreement with the proposal.

**Comment by iandevlin** [comment]
+1

**Comment by aardrian** [comment]
+1

**Comment by jasonkiss** [comment]
+1

**Comment by agcolom** [comment]
+1

**Comment by LJWatson** [comment]
Record of the [CFC decision](https://lists.w3.org/Archives/Public/public-webapps/2017AprJun/0046.html)
