### ISSUE TITLE
Colgroup start tag optional or not?

### ISSUE THREAD

**Issue by yatil** [w3c/html#876]
[HTML5.1 does not allow to omit a colgroup start tag](https://www.w3.org/TR/html5/tabular-data.html#the-colgroup-element):

> Tag omission in text/html:
A colgroup element’s end tag may be omitted if the colgroup element is not immediately followed by a space character or a comment.

[WHATWG’s version allows to omit a colgroup start tag](https://html.spec.whatwg.org/multipage/tables.html#the-colgroup-element):

> Tag omission in text/html:
A colgroup element's start tag can be omitted if the first thing inside the colgroup element is a col element, and if the element is not immediately preceded by another colgroup element whose end tag has been omitted. (It can't be omitted if the element is empty.)
A colgroup element's end tag can be omitted if the colgroup element is not immediately followed by ASCII whitespace or a comment.

- - -

It might be good to clarify that, indeed validating the following table (which omits the start colgroup tag) yields no errors:

```html
<!DOCTYPE html>
<html>
<head><title>Test</title></head>
<body>
<table class="numbers">
  <col>
  <colgroup span="2"></colgroup>
  <colgroup span="2"></colgroup>
  <tr>
    <td rowspan="2"></td>
    <th colspan="2" scope="colgroup">Mars</th>
    <th colspan="2" scope="colgroup">Venus</th>
  </tr>
  <tr>
    <th scope="col">Produced</th>
    <th scope="col">Sold</th>
    <th scope="col">Produced</th>
    <th scope="col">Sold</th>
  </tr>
  <tr>
    <th scope="row">Teddy&nbsp;Bears</th>
    <td>50,000</td>
    <td>30,000</td>
    <td>100,000</td>
    <td>80,000</td>
  </tr>
  <tr>
    <th scope="row">Board&nbsp;Games</th>
    <td>10,000</td>
    <td>5,000</td>
    <td>12,000</td>
    <td>9,000</td>
  </tr>
</table>
</body>
</html>
``` 

- - -

Also, if colgroup is mandatory, and as its span value is 1 by default, what is the raison d’être for the col element? (Apart from history…)

- - - 

(Ref: w3c/wai-tutorials#459)

**Comment by stevefaulkner** [comment]
thanks @yatil will fix

**Comment by yatil** [comment]
Thanks @stevefaulkner!
