### ISSUE TITLE
Expand IDL acronym in 1st use

### ISSUE THREAD

**Issue by agcolom** [w3c/html#883]
In https://www.w3.org/TR/2017/WD-html52-20170406/infrastructure.html#reflecting-content-attributes-in-idl-attributes the spec use the IDL for the first time. We should specify what IDL stands for. For example, we could change the first sentence:
Some IDL attributes are defined to reflect a particular content attribute.

to 

Some Interface Definition Language (IDL) attributes are defined to reflect a particular content attribute.

Does this look ok to you? I can make the change immediately once I get thumbs up to go ahead.

**Comment by agcolom** [comment]
Actually, It looks like IDL is used earlier, here: https://www.w3.org/TR/2017/WD-html52-20170406/introduction.html#audience 

Does this look like to right place to expand? Otherwise, we could also do it here: https://www.w3.org/TR/2017/WD-html52-20170406/infrastructure.html#idl-attribute

**Comment by chaals** [comment]
I'm not sure whether we should expand those abbreviations, because I **believe** the common term is in fact the abbreviation not the expansion; much like laser and radar are known terms, but their expansions are not recognisable to most people...

Feel free to be convinced by my argument, or equally free to find that people aren't, and so make the change you propose...

This is not a strongly held opinion and I suspect it boils down to personal preference. Hence the poor level of guidance :S

**Comment by agcolom** [comment]
@chaals Leonie and I had a chat about this today, and we thought we could maybe add a link to the WebIDL Sepc (https://www.w3.org/TR/WebIDL-1/) either as well as or instead of expanding the acronym... I'm still thinking about how to best do this (i.e. where and what). Any views welcome :-)

**Comment by chaals** [comment]
@agcolom my view is that linking a lot is a good idea, but I wouldn't worry about expanding the acronym. As I said earlier, feel free to disagree and propose whatever edits make sense to you…

**Comment by patrickdark** [comment]
Seems appropriate to expand it. Though I think abbreviation clarity issues are generally avoided by liberal use of `abbr` elements with `title` attributes. 

Also, I find it weird that an HTML specification doesn't use `abbr` elements (with/without `title` attributes).

**Comment by siusin** [comment]
According to the [WebIDL](https://www.w3.org/TR/WebIDL-1/#idl) spec,

> This section describes a language, Web IDL, which can be used to define interfaces for APIs in the Web platform.

WebIDL is the name of this specific language, so I don't think it's necessary to use `abbr` or expand the acronym. Does it help to add the definition of WebIDL to the [2.2.2 Dependencies section](https://www.w3.org/TR/html52/infrastructure.html#conformance-requirements-dependencies)?

**Comment by LJWatson** [comment]
@siusin
 thanks for clarifying that WebIDL is the name of the specification. Agree we should not expand the acronym.

+1 to adding WebIDL as a dependency though.

**Comment by chaals** [comment]
WebIDL is in there.
