### ISSUE TITLE
Make readonly work on range?

### ISSUE THREAD

**Issue by chaals** [w3c/html#89]
Some browsers respect a [`readonly` attribute on `input type="range"`](http://chaals.github.io/testcases/readonlyNonAlphaNumericFormControls.html) and there seem to be use cases.

HTML currently says this is wrong. Which should it be?

**Comment by chaals** [comment]
This works in Safari 9.1 and Blink-based browsers like Yandex 16.4

Any appetite for matching it in Edge, or Gecko @hsivonen?

Obvious use cases:
1. Allow for review of a form but not changing it. 
2. As a way to render a `progress` or `meter` element

**Comment by stevefaulkner** [comment]
@travisleithead any plans to implement in edge?

**Comment by stevefaulkner** [comment]
From a reading of this [current related thread](https://github.com/whatwg/html/issues/2311) on whatwg, and lack of responses from vendors, there appears to be no appetite for normalizing this behaviour. Closing this here for now.

**Comment by chaals** [comment]
Except that normalising it so readonly *doesn't* work also doesn't seem to have a whole lot of support yet, unless I missed something.

Until browsers look likely to do something interoperable, maybe we should clarify that this **may** work.

I admit that's a sub-optimal situation, but it is reality.
