### ISSUE TITLE
Identify sections at risk for 5.2

### ISSUE THREAD

**Issue by chaals** [w3c/html#893]
As preparation for the HTML 5.2 Candidate Recommendation, we should identify anything in the specification that does not have interoperable implementation. Roughly, this means at least two working implementations that are **not** marked for deprecation - and ideally, some sense that further implementations are likely. Please list candidate sections in this issue, or open an issue suggesting something be marked at risk and noting why...

**Comment by chaals** [comment]
Proposed: `inputmode`. 

[According to CanIUse](http://caniuse.com/#search=inputmode) it was implemented by Firefox, and it has been implemented repeatedly in the past by mobile browsers, although I do not know of interop testing. Note that "autocapitalize" has been suggested as having implementation: #208

**Comment by chaals** [comment]
Proposed: `menu` and `menuitem`

The only known implementation is Firefox. While I know of claims that Blink implemented this, it appears not to work in any blink-based browser, even with the enabling flag set.

**Comment by chaals** [comment]
proposed: `allow-presentation` as a sandboxing flag for iframes - see #437

**Comment by chaals** [comment]
Proposed: `dialog`
It's implemented in blink. There is an implementation behind a flag in Firefox, but it's pretty flaky. If it got more work, then this feature might be ready to land. Otherwise, I think not yet...

**Comment by chaals** [comment]
Proposed: `input type="datetime"`

Still doesn't seem to be supported, running a [simple test](https://chaals.github.io/testcases/input-datetime-local-manual.html)

**Comment by chaals** [comment]
Proposed: The plugin API

Browsers are consistently tightening the constraints on this, to the point where it seems unlikely to continue being interoperable.

We should examine this and if appropriate remove it.

**Comment by prlbr** [comment]
`<menuitem>` has been removed from Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=87553&desc=2#c66 (via https://github.com/whatwg/html/issues/2730)

**Comment by siusin** [comment]
The [at-risk](https://www.w3.org/TR/2017/WD-html52-20170718/#status) features for HTML5.2 have been announced at the latest WD.

**Comment by chaals** [comment]
@tidoust do you have implementation info for `allow-presentation` ?

**Comment by chaals** [comment]
`<input type="datetime">` [doesn't work](https://chaals.github.io/testcases/input-datetime-local-manual.html) in recent Blink, Edge or Gecko. As far as I know it is not implemented in Webkit either. Suggest removal

`<menuitem>` [works](https://thepaciellogroup.github.io/AT-browser-tests/test-files/menu-context.html) in Firefox but not Edge nor Yandex (Blink). As far as I know it is not supported in Webkit but I didn't test that. Suggest removal.

[CaniUse](http://caniuse.com/#search=inputmode) says inputmode doesn't work and I don't know of any modern implementation still shipping. Suggest removal.

**Comment by chaals** [comment]
The chairs/editors [propose to keep `dialog`](https://lists.w3.org/Archives/Public/public-html/2017Sep/0001.html) given that there are two implementations...

**Comment by chaals** [comment]
The Plugins API has been moved to obsolete, rather than removed entirely.

**Comment by chaals** [comment]
`allowpresentation` as a flag on iframe should be removed from 5.2 (but not 5.3)

**Comment by chaals** [comment]
This is done...

**Comment by csarven** [comment]
@chaals re https://github.com/w3c/html/issues/893#issuecomment-298318286 , on what grounds did `menu` made its way into the spec?

**Comment by LJWatson** [comment]
@csarven it didn't. ```<menu>``` was [pulled from HTML5.2](https://github.com/w3c/html/pull/1043)

**Comment by csarven** [comment]
@LJWatson I'm aware (hence this issue and https://github.com/w3c/html/issues/893#issuecomment-298318286 I'm referring to). It was removed on the grounds that only Firefox supports it. I'm asking on what grounds was it introduced to 5.x to begin with.

**Comment by chaals** [comment]
@csarven I think it seemed like a good idea at the time, to those who were working on it. There were other implementations to the point where we **didn't** pull it from 5.1, and even in the 5.2 timeframe there was "implementor interest". Once upon a time that was considered good enough to put things in an HTML spec, before the world realised that this didn't translate into reality well.

**Comment by LJWatson** [comment]
The background is that ```<menu>``` was redefined in HTML5.0, having been present in HTML since the early days. Looking briefly through the [HTML5.0 test results](https://w3c.github.io/test-results/html/all.html), it seems that all tests relating to menu passed with two (or in some cases more) implementations at the time HTML5 went to Rec.

**Comment by csarven** [comment]
@chaals Are you particularly referring to Web browser implementors as opposed to any?

@LJWatson Thanks for sharing! That's interesting.

Is there a general protocol on addressing potential backwards compatibility issues - whether within the HTML WG or in coordination with the other W3C WGs?

If/how are HTML documents in the wild, non-browser tools, and W3C specs (WAI*) referring to components in HTML - like the concept of an interactive element "menu" - should handle the changes in the HTML spec? Or is that out of scope for the HTML WG?
