### ISSUE TITLE
Discrepancies between HTML and ARIA in HTML specs

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/html#894]
A while back I did an APA review of ARIA in HTML. During this review a bunch of discrepancies between HTML and ARIA in HTML were found, most of these relating to which roles are allowed on which elements.

@stevefaulkner has told me that ARIA in HTML is leading in this instance and asked me to log the issues here.

Changes for HTML:
- `a` without a `href` attribute may have any role
- `address` element allows any role
- `article` element may have a `presentation` role
- `aside` element may have a `region` role
- `base` element doesn’t allow any aria-* attributes or roles
- `button` element allows `checkbox` and `tab` role
- `dd` element has default role of `definition`
- `dt` element has default role of `listitem`
- role computation rules for `footer` element are not in the HTML spec
- `head` element doesn’t allow any aria-* attributes or roles
- role computation rules for `header` element are not in the HTML spec
- `img` element allows any role
- `link` element has a default role of `link` and doesn’t allow any aria-* attributes or roles
- `main` element has a default role of `main` but doesn’t allow any other roles (HTML currently lists `presentation`).
- `map` element doesn’t allow any aria-* attributes or roles
- `section` element has mismatch between roles allowed
- `td` element is missing allowed aria role `heading`

**Comment by cycomachead** [comment]
It seems that `tr` is missing `role=row` as the default.

**Comment by scottaohara** [comment]
Shall we close this issue, since [merging PR 1133](https://github.com/w3c/html/pull/1133) resolved this + more?

**Comment by chaals** [comment]
@scottaohara 

> Shall we close this...

Yes. Thank you...
