### ISSUE TITLE
Too many &amp's in example?

### ISSUE THREAD

**Issue by r12a** [w3c/html#897]
8.2.4.72. Character reference state
Example 13
https://w3c.github.io/html/syntax.html#example-6a85a40d

```
If the markup contains (not in an attribute) the string I'm &amp;notit; I tell you, the character 
reference is parsed as "not", as in, I'm ¬it; I tell you (and this is a parse error). But if the markup was 
I'm &amp;notin; I tell you, the character reference would be parsed as "notin;", resulting in I'm ∉ I tell 
you (and no parse error).
 
However, if the markup contains the string I'm &amp;notit; I tell you in an attribute, no character 
reference is parsed and string remains intact (and there is no parse error).
```

I have to admit that i didn't plow through the algorithm before this example, but the example seems incorrect to me.  Shouldn't `&amp;notin;` be `&notin;` when a content author types it as source code, and therefore when you read this example?  I think the former would just produce `&notin;` when the browser displays the page. (Of course, you'd need to type `&amp;notin;` in the source code _for the HTML spec_ to show `&notin;` in the example.)

**Comment by chaals** [comment]
Looking through the algorithm, if the sequence consumed was `&notit;` then it would behave as described, but `&amp;notit;` should produce the output `&notit;` - assuming my plow through it didn't confuse me.

**Comment by maffe** [comment]
The example (at https://w3c.github.io/html/syntax.html#tokenizer-character-reference-state) still contains `&amp;notit;`/`&amp;notin;` (rendered output in the browser) which I think should be `&notit;`/`&notin;` (HTML source code contains `&amp;amp;` which should be `&amp;`).

**Comment by chaals** [comment]
Thanks for picking this up. I'll make a Pull Request to fix the source
