### ISSUE TITLE
Sync "Safe passing of structured data"

### ISSUE THREAD

**Issue by stefhak** [w3c/html#898]
Whatwg recently updated that section (https://html.spec.whatwg.org/multipage/infrastructure.html#safe-passing-of-structured-data), and that to me looks cleaner.

Could this spec be updated to follow the same pattern?

**Comment by LJWatson** [comment]
Thanks for the suggestion @stefhak

**Comment by scottaohara** [comment]
This issue was actually addressed in July 2017 [as part of PR #963](https://github.com/w3c/html/commit/cbc4af11f7dddf722f699a7ed2788ca5dae31228).

I compared both specifications, today, to verify, and they are identical.
