### ISSUE TITLE
select element definition missing autocomplete attr in list of content attributes

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html#900]
See http://w3c.github.io/html/sec-forms.html#the-select-element

The list of content attributes for the `select` element is missing the `autocomplete` attribute.

**Comment by iandevlin** [comment]
@cynthia I am happy to do this, but am hesitant since you have assigned it to yourself.

**Comment by stevefaulkner** [comment]
@iandevlin please go ahead if you have time, have unassigned @cynthia

**Comment by iandevlin** [comment]
@stevefaulkner On it, thanks!
