### ISSUE TITLE
Allow `readonly` on `input type="color"`?

### ISSUE THREAD

**Issue by chaals** [w3c/html#91]
Doesn't seem to work anywhere, but people have use cases for it.

[testcase](http://chaals.github.io/testcases/readonlyNonAlphaNumericFormControls.html)

**Comment by HolgerJeromin** [comment]
Opera 12 aka Presto supports readonly color input :-)

**Comment by chaals** [comment]
So does Safari 9, by virtue of not implementing anything so it falls back to an input type="text"…

But I'm not sure that counts as a real implementation

**Comment by stevefaulkner** [comment]
Closing this as not currently supported
