### ISSUE TITLE
HTMLMediaElement loop property should have corresponding event 

### ISSUE THREAD

**Issue by benwiley4000** [w3c/html#910]
Many `HTMLMediaElement` properties and methods have corresponding media events, which can be used to monitor changes to the media state and update UI accordingly.

E.g.
* The `ratechange` event for `playbackRate`
* The `volumechange` event for `muted` and `volume`
* The `pause` event after `pause()` is called

However there does not seem to be one in either the [WHATWG](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-media-loop) or [W3C](https://www.w3.org/TR/html5/embedded-content-0.html#mediaevents) standards corresponding to the `loop` property/attribute. This is a serious shame since it's common for media player UIs (especially for audio) to feature the ability to dynamically toggle single-track looping during playback. In fact, this is possible currently, but it is not easy to track that change if the client code is not privy to the operation that triggered the toggle.

I would propose an event, possibly called `loopchange`, which would be fired whenever the `loop` attribute or property is modified.

**Comment by benwiley4000** [comment]
By the way, here's a working polyfill I'm using for my own project while this doesn't exist:
```javascript
const loopchange = new Event('loopchange');

class HTMLAudioElementWithLoopEvent extends HTMLAudioElement {
  get loop () {
    return super.loop;
  }

  set loop (value) {
    super.loop = value;
    this.dispatchEvent(loopchange);
  }
}

document.registerElement('audio-with-loop-event', {
  prototype: HTMLAudioElementWithLoopEvent.prototype,
  extends: 'audio'
});

function createHTMLAudioElementWithLoopEvent () {
  return document.createElement('audio', 'audio-with-loop-event');
}
```

**Comment by iandevlin** [comment]
I think that this is a good idea, even if only for completeness.

**Comment by benwiley4000** [comment]
Here's the relevant discussion in the [whatwg/html repo](https://github.com/whatwg/html/issues/2691). Probably not gonna happen!

**Comment by chaals** [comment]
And closed here too for the same reasons
