### ISSUE TITLE
Duplicated text on id: infrastructure.html#xml-compatible-xml-compatible

### ISSUE THREAD

**Issue by bangseongbeom** [w3c/html#919]
Duplicated "xml-compatible" on id: https://w3c.github.io/html/infrastructure.html#xml-compatible-xml-compatible

**Comment by chaals** [comment]
And the definition is apparently not *used* anywhere in the spec.

**Comment by chaals** [comment]
Thank you @bangseongbeom - I have written a PR that I believe would fix this. But as far as I know, we don't reference the concept in the spec. If anyone external does, we'll break their link - I don't think that's a big risk in practice but I assigned an editor to decide whether to make the change or not...
