### ISSUE TITLE
type attr on area elements listed as obsolete, but still listed in area definition

### ISSUE THREAD

**Issue by jasonkiss** [w3c/html#926]
The `type` attribute on `area` elements is [listed as obsolete and non-conforming](http://w3c.github.io/html/obsolete.html#element-attrdef-area-type), but it's still listed and discussed in the [element definition for `area`](http://w3c.github.io/html/semantics-embedded-content.html#elementdef-area).

Side note: The text associated with `type` on `area` elements in the list of obsolete features could be rewritten to refer to a single attribute (e.g. "This attribute...") instead of many (i.e. "These attributes...").

**Comment by LJWatson** [comment]
@jasonkiss I didn't update the obsolete section because I think "these attributes" correctly refers to the previous two attributes mentioned in that section? Ping if you disagree though.
