### ISSUE TITLE
4.12.4.3 Canvas color spaces and color correction

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#940]
Migrated from [Bugzilla 25309](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25309)

>"Seeking some clarification for this section.

"The canvas APIs must perform color correction at only two points: when rendering images with their own gamma correction and color space information onto a bitmap, to convert the image to the color space used by the bitmaps (... drawImage"

So "a bitmap" ... "the bitmaps" ... is this referring to canvas element's bitmap?

What is "the color space used by "the bitmaps" ?  What color space is that exactly?">

**Comment by LJWatson** [comment]
Pinging @Cabanier, @jatindersman, @techtoons, and @wiltzius for advice.

**Comment by chaals** [comment]
"bitmap" here seems to refer to the (virtual) bitmap that defines the canvas' visible rendering.

"In user agents that support CSS, the color space used by a canvas element must match the color space used for processing any colors for that element in CSS." (in the [same "Color Spaces and Color Correction" section](https://w3c.github.io/html/semantics-scripting.html#color-spaces-and-color-correction))

**Comment by chaals** [comment]
It seems like this would be a lot clearer if the paragraphs in this section were re-ordered.
