### ISSUE TITLE
Clarify the meaning of browsing context familiarity 

### ISSUE THREAD

**Issue by arturjanc** [w3c/html#951]
The [Browsing Context Security](https://www.w3.org/TR/html52/single-page.html#browsing-context-security) section defines the concept of familiarity of two browsing contexts. The definition is fairly non-obvious and doesn't explain the consequences of two browsing contexts being familiar with each other, or the high-level reasons for introducing it.

Since this is not a common term I'd suggest adding a note or example to makes this easier to grok.

**Comment by chaals** [comment]
This term is only used a couple of times, in the chapter where it is defined - on browsing contexts. I suggest adding a note to the definition explaining what the point is...

**Comment by LJWatson** [comment]
Thanks arturjanc. Is there any chance you could suggest some words for this change?

**Comment by siusin** [comment]
Note added by pull #1019 .
