### ISSUE TITLE
Update clickjacking and CSRF protection guidance

### ISSUE THREAD

**Issue by arturjanc** [w3c/html#952]
The [Writing secure applications with HTML](https://www.w3.org/TR/html51/single-page.html#writing-secure-applications-with-html) section has a good overview of the most common web bugs, but the advice could use a couple of tweaks to reflect current best practices:

**Clickjacking**
> To avoid this, sites that do not expect to be used in frames are encouraged to only enable their interface if they detect that they are not in a frame (e.g., by comparing the window object to the value of the top attribute).

JS-based framebusting is not the recommended solution for clickjacking for a variety of reasons, including the possibility of disabling framebusters by abusing XSS filters. Instead, please recommend [`X-Frame-Options`](https://tools.ietf.org/html/rfc7034) or CSP [`frame-ancestors`](https://www.w3.org/TR/CSP2/#directive-frame-ancestors).

**CSRF**
> Sites can prevent such attacks by populating forms with user-specific hidden tokens, or by checking Origin headers on all requests.

Since the Origin header is not always present for legitimate requests, following this advice might lead to breakage (see e.g. http://lenxwei.blogspot.ch/2014/08/how-to-mitigate-csrf-using-origin.html). I'd suggest limiting the advice to recommend unpredistable CSRF tokens as the main solution.

Also, as a minor note, I'd recommend against raising SQLi in the section which talks about escaping/validating data and instead focus on discussing XSS (to avoid conflating the two).

**Comment by LJWatson** [comment]
Thanks @arturjanc. Is there any chance you could suggest some words for these changes?

**Comment by LJWatson** [comment]
@Cynthia can you take a run at this?
