### ISSUE TITLE
form label Example 2 is broken.

### ISSUE THREAD

**Issue by karlcow** [w3c/html#953]
1. Go to https://www.w3.org/TR/html51/sec-forms.html#element-attrdef-label-for
2. head to example 2

![capture d ecran 2017-06-15 a 09 23 55](https://user-images.githubusercontent.com/505230/27160082-76e0cb32-51ac-11e7-9521-d99c6b110c02.png)

It seems one character was not properly escaped.

**Comment by cynthia** [comment]
Good catch, will take a look.

**Comment by chaals** [comment]
Yep. Was fixed in 5.2 already, but since we have a 5.1 2nd ed. in flight we may as well fix it there too. @siusin ?

**Comment by siusin** [comment]
Thanks @karlcow !

We have updated [this piece of code in the editor's draft](https://rawgit.com/w3c/html/html5.1-2/single-page.html#element-attrdef-label-for) of the HTML 5.1 2nd Edition, which will be (hopefully) published as a CR on Monday.
