### ISSUE TITLE
Add quotation marks in figure-element note, to prevent ambiguity

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html#965]
See https://github.com/whatwg/html/pull/2834

**Comment by iandevlin** [comment]
Shouldn't this issue be updated?

**Comment by stevefaulkner** [comment]
please do!

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by iandevlin** [comment]
@stevefaulkner Well I would, but how?

**Comment by stevefaulkner** [comment]
@iandevlin looks like it already been fixed :-)

**Comment by iandevlin** [comment]
@stevefaulkner It is now, thanks to @LJWatson. I didn't have the option to close it by the way, hence I was asking.

**Comment by stevefaulkner** [comment]
@iandevlin ah misunderstood, thought it still needed doing, then saw that it had been edited and merged.

**Comment by iandevlin** [comment]
@stevefaulkner Fair enough!
