### ISSUE TITLE
Minor proposals/issues related to chapter 4.3.9.

### ISSUE THREAD

**Issue by rehierl** [w3c/html#972]
Before I set up a PR that would address the following minor proposals/issues, I would like to know if those changes are accepted or if I simply misunderstood something:

### 1) Relocate the definition of "sectioning roots" from 4.3.9. to 3.2.4.

The definition of the [body element](https://w3c.github.io/html/sections.html#the-body-element) defines it to be a [sectioning root](https://w3c.github.io/html/sections.html#sectioning-roots) element (see the "Categories" property). If you follow the sectioning-root-link, you will be forwarded to chapter [4.3.9. Headings and sections](https://w3c.github.io/html/sections.html#headings-and-sections).

The definition of the [section element](https://w3c.github.io/html/sections.html#the-section-element) defines it to be a [sectioning content](https://w3c.github.io/html/dom.html#sectioning-content-2) element. If you follow the sectioning-content-link, you will be forwarded to chapter [3.2.4. Content models](https://w3c.github.io/html/dom.html#content-models).

What is a little inconsistent is that the definitions of the terms "sectioning root" and "sectioning content" are located in different chapters. In short: The definition of a main category should not be hidden inside a sub-chapter (i.e. 4.3.9.).

So **my proposal here** would be to move the definition of the term "sectioning root" into chapter "3.2.4. Content models" and let it become entry "3.2.4.2.3 Sectioning root". The current entry "3.2.4.2.3 Sectioning content" would then become entry "3.2.4.2.4".

### 2) The term "sectioning content" feels a bit off

Personally, when ignoring the current definition of "sectioning content", I would understand the term to refer to any element that splits up content into different sections (which would include the elements `body`, `section`, etc.) and not refer to a mere subset of these kind of elements (which does not include `body`, etc.).

Take the set of whole numbers (..., -2, -1, 0, 1, 2, ...) for example. The current definition of "sectioning content" feels similar to using the word "integer" to only refer to all non-negative numbers, excluding all negative numbers, although the latter ones should clearly be included.

**Unfortunately I can't think of what to do here.** Let me know if the term "sectioning content" is actually a perfect fit and I am just misreading it.

### 3) Introduce a more general term: e.g. "sectioning element"

In my mind, after having re-read chapter 4.3.9. multiple times, I have started to use the term "sectioning element" as an umbrella term to refer to elements if, in a given context, it does not matter if an element is a "sectioning root" or a "sectioning content" element. Personally I think that this would make it a bit easier to understand chapter 4.3.9. if you read it for the first time.

So **my proposal here** would be to add the definition of a more general umbrella term (e.g. "sectioning element"). The exact term and wording are of course a matter of discussion, but it could be phrased as follows:

_In cases where an element is possibly either a "sectioning root" element, or a "sectioning content" element it can be referred to as "sectioning element"._

If such a definition would exist, then all the occurrences of "sectioning content element or a sectioning root element" could simply be replaced by "sectioning element". The longer or-version appears quite a few times inside chapter 4.3.9., so I wouldn't call such a change negligible.

### 4) Sectioning elements, Sectioning containers

The definition of "[sectioning root](https://w3c.github.io/html/sections.html#sectioning-roots)" states that these elements can have their own outlines. The definition of "[sectioning content](https://w3c.github.io/html/dom.html#sectioning-content-2)" states that each potentially has a heading and an outline. The definition of "[section container](https://w3c.github.io/html/sections.html#section)" states that these are objects that refer to some nodes in the DOM tree and that they are mere conceptual sections which may have a heading.

4.1) The outline algorithm never associates a heading element with a sectioning content element. Heading elements are always associated with a sectioning container. So **my proposal here** would be to either add an explanation what the heading of a sectioning content element is, or drop the "has a heading" part in the definition of "sectioning content". My personal impression is that only the latter would make sense.

(Edit - The first sentence of the 2nd paragraph in chapter 4.3.9. does define the first element of heading content to be the heading of an element of sectioning content.)

4.2) The way the outline algorithm works is that each sectioning element will always have an outline object that will always contain at least one section container object. So **my proposal here** would be to drop the (a bit) confusing conjunctive phrasing (i.e. "potentially has", "can have").

Granted, sectioning elements will only have an outline object associated with them if the outline algorithm has generated these. But this spec should relate to the general properties of these kind of elements and not what happens in practice. The way it is phrased now tempts one to believe that, even in theory, there could be sectioning elements that have no outline. Note that even an empty outline is an outline.

**Comment by stevefaulkner** [comment]
Hi @rehierl this sounds interesting, please do submit a PR and we can review.

**Comment by rehierl** [comment]
While trying to set up a PR I noticed, that there is actually a definition for what the heading of an element of sectioning content is; see the 1st sentence in the 2nd paragraph.

Could it be that the meaning of the `<section>` element has changed over time from a dedicated element (only one heading per `<section>` element) to a "special container" element? Or is that definition the result of confusing the terms "section container" and "sectioning content element"?

**Comment by rehierl** [comment]
@stevefaulkner I consider this PR to be more of a showcase of what the effects of a more general term could be. So if you don't want to merge it, then that'll be fine by me.

**Comment by rehierl** [comment]
For the record: My request to withdraw my PR was accepted. The reason I gave was as follows:

From the current state of this specification, both groups of elements (sectioning roots and sectioning content elements) appear as if they could be treated the same - they both are defined to have an outline (a sequence of sections with one or more entries). That is of course with the exception of the characteristics in which they differ (contributes to a parent outline or not -and- has a definition of a heading or not). With that (limited) point of view, this PR certainly wasn't wrong.

Unfortunately, the whole chapter of "4.3. Headings and sections", including the algorithm's definition, is anything but easy to understand in all its details. In order to head back to a clear and easy to implement vision, it could turn out to make more sense to redefine sectioning content elements to always have a single root section - i.e. allowing these elements to have an outline, and thus possibly multiple sections, might turn out to be a conceptual problem.

If that is the case, then both groups of elements can no longer be treated the same. Hence, merging this PR could turn out to be a step into the wrong direction.
