### ISSUE TITLE
The content model of the map element should not be "just" transparent

### ISSUE THREAD

**Issue by shepard8** [w3c/html#974]
Hello,

Consider the following HTML5 document, adapted from the [specification](https://www.w3.org/TR/html5/embedded-content-0.html#image-maps) (I just added the standard HTML boilerplate so that it is a complete HTML5 document):

    <!doctype html>
    <html>
      <head><title>Hey</title></head>
      <body>
        <p>
         Please select a shape:
         <img src="shapes.png" usemap="#shapes"
              alt="Four shapes are available: a red hollow box, a green circle, a blue triangle, and a yellow four-pointed star.">
         <map name="shapes">
          <area shape=rect coords="50,50,100,100"> 
          <area shape=rect coords="25,25,125,125" href="red.html" alt="Red box.">
          <area shape=circle coords="200,75,50" href="green.html" alt="Green circle.">
          <area shape=poly coords="325,25,262,125,388,125" href="blue.html" alt="Blue triangle.">
          <area shape=poly coords="450,25,435,60,400,75,435,90,450,125,465,90,500,75,465,60"
                href="yellow.html" alt="Yellow star.">
         </map>
        </p>
      </body>
    </html>

As the content model for [map](https://www.w3.org/TR/html5/embedded-content-0.html#the-map-element) is transparent, this document is correct only if the area element is allowed in `HTML > BODY > P`, which is not the case according to the [contexts in which the area element can be used](https://www.w3.org/TR/html5/embedded-content-0.html#the-area-element).

Actually the only way to get a correct document that makes use of the area element, is to surround them with some [template](https://www.w3.org/TR/html5/scripting-1.html#the-template-element) element, which is unrelated to image maps.

I believe the content model of the map element should be something like "Transparent with the addition of the area element". By the way it may be worthy to explain why it is useful for the map element to accept any other element than areas as children.

As a side note, the above HTML5 document is validated by the [Nu Html Checker](https://validator.w3.org/nu/), while it should not according to the specification.

**Comment by shepard8** [comment]
Another hint that something is wrong: In section [3.2.4.1.8](https://www.w3.org/TR/html5/dom.html#palpable-content), map is allowed whereas area is not (the argument is the same: As map is transparent, area should be allowed there).

**Comment by chaals** [comment]
The `map` element is phrasing content, and can be used more or less anywhere.

So although `area` elements require a `map` or `template` ancestor, they can have that within a paragraph or within various phrasing or block elements.

I think that means the validator is correct, and that the content models are OK as is...

I propose closing this issue as I think it is invalid.

Thank you for taking the time to file it.
