### ISSUE TITLE
Desire for a more-easily-parsable HTML

### ISSUE THREAD

**Issue by prototypo** [w3c/html#976]
The Web Platform WG might reasonably support a subset of HTML 5.1 to serve as a long term maintenance recommendation. If you go down that path, please ensure that parsing does not require state keeping during parsing, e.g. by removing the necessity for multi-modal parsing. This might be of benefit to some mobile or computationally-constrained use cases.

A more-easily-parsable HTML 5.1 might include the following limitations:

- Compliance with the XHTML profile, and hence ability to parse into a tree structure with XML parsers;
- Disallowance of inline CSS;
- Disallowance of inline JavaScript.

**Comment by chaals** [comment]
Hi @prototypo 

The first question is about implementation - is there a clear set of implementations that would converge to this? One possible approach is through the suggestion to [standardise something like AMP](https://discourse.wicg.io/t/profiled-html-e-g-amp-friends/1979) - which not only has many of the properties you describe - although it also adds some cutting edge stuff and can evolve - but has a number of independent implementations.

**Comment by prototypo** [comment]
Hi @chaals 

Yes, that approach would satisfy our perceived need. Thanks for the link.

**Comment by chaals** [comment]
Closing this and letting it incubate for now.

**Comment by LJWatson** [comment]
Where is this being incubated?

**Comment by chaals** [comment]
[In WICG](https://discourse.wicg.io/t/profiled-html-e-g-amp-friends/1979/) (and in practice, especially in China at the moment)
