### ISSUE TITLE
Missing links for 'sub' and 'sup' elements

### ISSUE THREAD

**Issue by unor** [w3c/html#985]
https://www.w3.org/TR/2017/CR-html52-20170808/textlevel-semantics.html#the-sub-and-sup-elements

The first and second paragraph link `sup`, but not `sub`:

> The [`sup`](https://www.w3.org/TR/2017/CR-html52-20170808/textlevel-semantics.html#elementdef-sup) element represents a superscript and the `sub` element represents a subscript.

> […] it would be inappropriate for the `sub` and [`sup`](https://www.w3.org/TR/2017/CR-html52-20170808/textlevel-semantics.html#elementdef-sup) elements to […]

(If this can be fixed, it would make sense to define `sub` before `sup` in the first paragraph.)

The last paragraph links neither:

> […] but authors may opt to use `sub` and `sup` if […]

**Comment by LJWatson** [comment]
Thanks @unor
