### ISSUE TITLE
Link types "external" and "prefetch" have no normative definitions

### ISSUE THREAD

**Issue by unor** [w3c/html#987]
https://www.w3.org/TR/2017/CR-html52-20170808/links.html#sec-link-types

In the "Link types" section, it says:

> The following table summarizes the link types that are defined by this specification, by their coresponding keywords. This table is non-normative; the actual definitions for the link types are given in the next few sections.

But there don’t seem to be definitions for `external` and `prefetch` outside of the table.

**Comment by chaals** [comment]
These are pretty straightforward.

`rel="prefetch"` is [covered by WIkipedia](https://en.wikipedia.org/wiki/Link_prefetching) probably reasonably reliably :)

`rel="external"` is [described in the microformats wiki](http://microformats.org/wiki/rel-external), and doesn't require browser behaviour - it is informational...

**Comment by gibson042** [comment]
According to the [IANA Link Relation Types registry](https://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1), `prefetch` is defined by https://www.w3.org/TR/resource-hints/#prefetch . `external` is not registered.

**Comment by edent** [comment]
Should the document also be updated with `dns-prefetch`, `preconnect`, `prerender` which are listed in the resource hints document?

**Comment by brucelawson** [comment]
Adding the relevant info; adding Richard Gibson to acknowledgements.
