### ISSUE TITLE
Missing links to 'link' and 'area' in "Other link types" section

### ISSUE THREAD

**Issue by unor** [w3c/html#988]
https://www.w3.org/TR/2017/CR-html52-20170808/links.html#sec-other-link-types

> Effect on... `link`

> Effect on... [`a`](https://www.w3.org/TR/2017/CR-html52-20170808/textlevel-semantics.html#elementdef-a) and `area`

`a` is linked, while `link` and `area` aren’t.

**Comment by LJWatson** [comment]
With thanks @unor
