### ISSUE TITLE
HTML5.1-2 "Latest version" points to HTML5.1

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#991]
The "latest version" link in the HTML5.1 2nd Edition spec points to the HTML5.1 Rec. Think it should point to the latest published version of 2nd Edition?

**Comment by siusin** [comment]
The /TR design guidance says /TR/html51 wont be changed until HTML5.1-2 moves to REC...

**Comment by LJWatson** [comment]
Is there somewhere I can file an issue against the design guidance? It is very confusing. The latest version of HTML5.2 points to the latest published version (right no that's the CR), so logically the 5.1 2nd Ed latest version should point to the PR.

**Comment by siusin** [comment]
@LJWatson please fire an issue on https://github.com/w3c/tr-design/, perhaps ping plh in that issue.
