### ISSUE TITLE
idea:input search 

### ISSUE THREAD

**Issue by annopnod** [w3c/html#995]
&lt;input type=&quot;search&quot; list=&quot;browsers&quot;  onselectlist=&quot;&quot;&gt;
        &lt;datalist id=&quot;browsers&quot;&gt;
            &lt;option value=&quot;1&quot;&gt;&lt;img src=&quot;ie.png&quot;/&gt;Internet Explorer&lt;/option&gt;
            &lt;option value=&quot;2&quot;&gt;&lt;img src=&quot;ff.png&quot;/&gt;Firefox&lt;/option&gt;
            &lt;option value=&quot;3&quot;&gt;&lt;img src=&quot;co.png&quot;/&gt;Chrome&lt;/option&gt;
        &lt;/datalist&gt;

**onselectlist event**
if click list return value
![ss](https://user-images.githubusercontent.com/6957642/29492276-d90d58de-85a0-11e7-87aa-c5c697feb9bf.png)

**Comment by SebastianZ** [comment]
`<option>` elements currently also only allow text content, so I've created issue #996 asking to extend their support to cover other elements.

Sebastian

**Comment by chaals** [comment]
It's not very clear what this input type would do. And the experience of adding new input types has been pretty mixed.

I suggest clarifying the problem that this solves, and I think it is probably a better idea to start it [in incubation](https://discourse.wicg.io), e.g. developing a polyfill and explaining it ...

**Comment by chaals** [comment]
Another possibility is to mark something up with schema.org as [a searchaction](https://schema.org/SearchAction), e.g.

```
<div vocab="http://schema.org/" typeof="WebSite">
    <meta property="url" href="http://www.example.com/"/>
    <form property="potentialAction" typeof="http://schema.org/SearchAction">
      <meta property="target" content="http://www.example.com/search?q={query}"/>
      <input property="query-input" type="text" name="query">
      <input type="submit">
    </form>
</div>
```

(You would use a separate control here to select the search engine you want, or add keywords like the Github search does if that's a goal. We don't have a type that lets you **add** text to an option in the way you propose for the mockup.)

In any event, I am closing this, at least until something has been demonstrated as having implementer interest, if the above don't meet your needs
